// packages/lumx-vue/src/components/menu-button/MenuItem.tsx
import { defineComponent, ref, type SlotsType } from 'vue';

import type { JSXElement } from '@lumx/core/js/types';
import { ColorPalette } from '@lumx/core/js/constants';
import {
    MenuItem as UI,
    MenuItemProps as UIProps,
    MenuItemPropsToOverride,
    CLASSNAME,
    COMPONENT_NAME,
} from '@lumx/core/js/components/Menu/MenuItem';

import { useClassName } from '../../composables/useClassName';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Icon } from '../icon';
import Text from '../text/Text';

import { useMenuContext } from './context';

export interface MenuItemActionSlotProps {
    /** Props to spread on the custom action element (includes onClick). */
    actionProps: Record<string, any>;
    /** Whether the item is disabled. */
    isDisabled: boolean;
}

/** MenuItem props. */
export type MenuItemProps = VueToJSXProps<UIProps, MenuItemPropsToOverride> & {
    /** MDI icon rendered as `<Icon size="xs" />` prepended to the `before` slot. */
    icon?: string;
    /** MDI icon rendered as `<Icon size="xs" />` appended to the `after` slot. */
    afterIcon?: string;
    /** Foreground color applied to the icon and label text. */
    color?: ColorPalette;
};

/**
 * MenuItem component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const MenuItem = defineComponent(
    (props: MenuItemProps, { slots, emit, attrs }) => {
        const { handle } = useMenuContext();
        const className = useClassName(() => props.class);
        const internalRef = ref<HTMLLIElement | null>(null);

        const onClick = (event: any) => {
            if (props.isDisabled) {
                event.preventDefault();
                return;
            }
            emit('click', event);
            if (!event.defaultPrevented) {
                handle.trigger?.focus();
                handle.setOpen(false);
            }
        };

        return () => {
            // Slots
            const before = slots.before?.();
            const action = slots.action?.({
                actionProps: { onClick },
                isDisabled: props.isDisabled as boolean,
            })?.[0];
            const after = slots.after?.();

            // Prepend menu item icon at the start of the "before" section
            const beforeWithIcon = props.icon ? (
                <>
                    <Icon icon={props.icon} size="xs" color={props.color} />
                    {before}
                </>
            ) : (
                before
            );

            // Append menu item icon at the end of the "after" section
            const afterWithIcon = props.afterIcon ? (
                <>
                    {after}
                    <Icon icon={props.afterIcon} size="xs" color={props.color} />
                </>
            ) : (
                after
            );

            let actionProps: Record<string, any> | undefined;
            let label: JSXElement | undefined;

            // Custom action rendered => merge props
            if (action) {
                actionProps = { ...action.props, onClick, as: action.type };
                label = action.children as JSXElement;
            }

            // Use action slot label or fallback to menu item slots
            label = label ?? (slots.default?.() as JSXElement);

            return UI({
                ...attrs,
                ...props,
                className: className.value,
                ref: internalRef,
                isDisabled: props.isDisabled,
                handleClick: onClick,
                // Slots
                before: beforeWithIcon as JSXElement,
                actionProps,
                after: afterWithIcon as JSXElement,
                children: (
                    <Text as="span" color={props.color}>
                        {label}
                    </Text>
                ) as JSXElement,
            });
        };
    },
    {
        name: 'LumxMenuItem',
        inheritAttrs: false,
        props: keysOf<MenuItemProps>()('icon', 'afterIcon', 'color', 'isDisabled', 'class'),
        emits: ['click'],
        slots: Object as SlotsType<{
            default: void;
            action: MenuItemActionSlotProps;
            before: void;
            after: void;
        }>,
    },
);

export { CLASSNAME, COMPONENT_NAME };
export default MenuItem;

// packages/lumx-react/src/components/menu/MenuItem.tsx
import { ElementType, ReactNode, SyntheticEvent, useRef } from 'react';
import type { ReactElement, Ref } from 'react';

import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { HasPolymorphicAs, HasRequiredLinkHref } from '@lumx/react/utils/type';
import { GenericProps } from '@lumx/core/js/types';
import { ColorPalette } from '@lumx/core/js/constants';
import {
    MenuItem as UI,
    MenuItemProps as UIProps,
    MenuItemPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Menu/MenuItem';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';

import { Icon } from '../icon';
import { Text } from '../text';
import { useMenuContext } from './context/MenuContext';

/** Props forwarded to the inner action element. */
export type MenuItemActionProps<E extends ElementType = 'button'> = HasPolymorphicAs<E> & HasRequiredLinkHref<E>;

/** MenuItem props. */
export interface MenuItemProps<E extends ElementType = 'button'>
    extends GenericProps,
        ReactToJSX<UIProps, MenuItemPropsToOverride> {
    /** Item label content. */
    children?: ReactNode;
    /** Click handler. Calls `event.preventDefault()` to keep the menu open. */
    onClick?(event: SyntheticEvent): void;
    /** MDI icon rendered as `<Icon size="xs" />` prepended to the `before` slot. */
    icon?: string;
    /** Foreground color applied to the icon and label text. */
    color?: ColorPalette;
    /** Content rendered before the label (rendered AFTER `icon` if both are provided). */
    before?: ReactNode;
    /** Content rendered after the label (e.g. a shortcut hint). */
    after?: ReactNode;
    /** Props forwarded to the inner action element (`{ as: 'a', href: '/foo' }`, etc.). */
    actionProps?: MenuItemActionProps<E>;
}

/**
 * MenuItem component.
 *
 * @param  props Component props.
 * @return React element.
 */
export const MenuItem: {
    <E extends ElementType = 'button'>(props: MenuItemProps<E> & { ref?: Ref<HTMLLIElement> }): ReactElement | null;
    readonly $$typeof: symbol;
    displayName: typeof COMPONENT_NAME;
    className: typeof CLASSNAME;
} = forwardRef<MenuItemProps, HTMLLIElement>((props, ref) => {
    const { handle } = useMenuContext();
    const { children, icon, color, before, after, isDisabled, onClick, actionProps, ...rest } = props;

    const internalRef = useRef<HTMLLIElement>(null);
    const actionRef = useRef<HTMLElement>(null);
    const mergedRef = useMergeRefs(ref, internalRef);

    const handleClick = (event: SyntheticEvent) => {
        if (isDisabled) {
            event.preventDefault();
            return;
        }
        onClick?.(event);
        if (!event.defaultPrevented) {
            // Focus the trigger before closing so focus restoration works with
            // closeMode="hide" (items unmount on close, leaving focus on body).
            handle.trigger?.focus();
            handle.setOpen(false);
        }
    };

    // Prepend the optional `icon` to the `before` slot — consumer-supplied `before`
    // (if any) is rendered after the icon to preserve composability.
    const mergedBefore = icon ? (
        <>
            <Icon icon={icon} size="xs" color={color} />
            {before}
        </>
    ) : (
        before
    );

    return UI({
        ...rest,
        ref: mergedRef,
        actionRef,
        before: mergedBefore,
        after,
        children: (
            <Text as="span" color={color}>
                {children}
            </Text>
        ),
        isDisabled,
        actionProps,
        handleClick,
    });
}) as any;

MenuItem.displayName = COMPONENT_NAME;
MenuItem.className = CLASSNAME;
