// packages/site-demo/content/product/components/popover/vue/directed.vue
<template>
    <FlexBox :style="{ padding: '80px', gap: '128px' }" orientation="vertical">
        <FlexBox :fill-space="true" vertical-align="center" horizontal-align="center">
            <Button ref="leftRef" size="s" emphasis="medium">LEFT</Button>
            <Popover :is-open="true" class="lumx-spacing-padding-huge" :anchor-ref="leftElRef" placement="left">
                Popover
            </Popover>
        </FlexBox>
        <FlexBox :fill-space="true" vertical-align="center" horizontal-align="center">
            <Button ref="topRef" size="s" emphasis="medium">TOP</Button>
            <Popover :is-open="true" class="lumx-spacing-padding-huge" :anchor-ref="topElRef" placement="top">
                Popover
            </Popover>
        </FlexBox>
        <FlexBox :fill-space="true" vertical-align="center" horizontal-align="center">
            <Button ref="bottomRef" size="s" emphasis="medium">BOTTOM</Button>
            <Popover :is-open="true" class="lumx-spacing-padding-huge" :anchor-ref="bottomElRef" placement="bottom">
                Popover
            </Popover>
        </FlexBox>
        <FlexBox :fill-space="true" vertical-align="center" horizontal-align="center">
            <Button ref="rightRef" size="s" emphasis="medium">RIGHT</Button>
            <Popover :is-open="true" class="lumx-spacing-padding-huge" :anchor-ref="rightElRef" placement="right">
                Popover
            </Popover>
        </FlexBox>
    </FlexBox>
</template>

<script setup lang="ts">
import { computed, useTemplateRef } from 'vue';
import { Button, FlexBox, Popover } from '@lumx/vue';

const leftRef = useTemplateRef<InstanceType<typeof Button>>('leftRef');
const leftElRef = computed(() => leftRef.value?.$el as HTMLElement | undefined);

const topRef = useTemplateRef<InstanceType<typeof Button>>('topRef');
const topElRef = computed(() => topRef.value?.$el as HTMLElement | undefined);

const bottomRef = useTemplateRef<InstanceType<typeof Button>>('bottomRef');
const bottomElRef = computed(() => bottomRef.value?.$el as HTMLElement | undefined);

const rightRef = useTemplateRef<InstanceType<typeof Button>>('rightRef');
const rightElRef = computed(() => rightRef.value?.$el as HTMLElement | undefined);
</script>

// packages/site-demo/content/product/components/popover/react/directed.tsx
import { useRef, type RefObject } from 'react';
import { classNames } from '@lumx/core/js/utils';
import { Button, FlexBox, Popover, type Placement } from '@lumx/react';

export default () => {
    const popovers: Array<[Placement, RefObject<any>]> = [
        ['left', useRef(null)],
        ['top', useRef(null)],
        ['bottom', useRef(null)],
        ['right', useRef(null)],
    ];
    return (
        <FlexBox style={{ padding: 80, gap: 128 }} orientation="vertical">
            {popovers.map(([placement, ref]) => (
                <FlexBox key={placement} fillSpace vAlign="center" hAlign="center">
                    <Button ref={ref as any} size="s" emphasis="medium">
                        {placement.toUpperCase()}
                    </Button>

                    <Popover isOpen className={classNames.padding('huge')} anchorRef={ref as any} placement={placement}>
                        Popover
                    </Popover>
                </FlexBox>
            ))}
        </FlexBox>
    );
};
