// packages/site-demo/content/product/components/popover/vue/matching-width.vue
<template>
    <div :style="{ marginBottom: '80px' }">
        <TextField
            ref="textFieldRef"
            placeholder="Search"
            :value="searchValue"
            :icon="mdiMagnify"
            @change="searchValue = $event"
        />
    </div>
    <Popover
        :is-open="true"
        class="lumx-spacing-padding-huge"
        :anchor-ref="anchorRef"
        placement="bottom-start"
        :fit-to-anchor-width="true"
    >
        Popover's width matching anchor's
    </Popover>
</template>

<script setup lang="ts">
import { computed, ref, useTemplateRef, type ComponentPublicInstance } from 'vue';
import { mdiMagnify } from '@lumx/icons';
import { Popover, TextField } from '@lumx/vue';

const searchValue = ref('');
const textFieldTemplateRef = useTemplateRef<ComponentPublicInstance>('textFieldRef');
const anchorRef = computed<HTMLElement | undefined>(() => textFieldTemplateRef.value?.$el as HTMLElement | undefined);
</script>

// packages/site-demo/content/product/components/popover/react/matching-width.tsx
import { mdiMagnify } from '@lumx/icons';
import { Placement, Popover, TextField } from '@lumx/react';
import React, { useRef } from 'react';

export const App = ({ theme }: any) => {
    const [searchValue, setSearchValue] = React.useState('');
    const anchorRef = useRef(null);

    return (
        <>
            <div style={{ marginBottom: 80 }}>
                <TextField
                    placeholder="Search"
                    value={searchValue}
                    onChange={setSearchValue}
                    icon={mdiMagnify}
                    theme={theme}
                    textFieldRef={anchorRef}
                />
            </div>
            <Popover
                isOpen
                className="lumx-spacing-padding-huge"
                theme={theme}
                anchorRef={anchorRef}
                placement={Placement.BOTTOM_START}
                fitToAnchorWidth
            >
                Popover's width matching anchor's
            </Popover>
        </>
    );
};
