// packages/site-demo/content/product/components/popover/vue/offset.vue
<template>
    <Button :style="{ marginBottom: '80px' }" ref="anchorRef" size="s" emphasis="medium"> Anchor </Button>

    <Popover
        :is-open="true"
        class="lumx-spacing-padding-huge"
        :anchor-ref="anchorElRef"
        placement="right"
        :offset="{ away: 30, along: 60 }"
    >
        Popover
    </Popover>
</template>

<script setup lang="ts">
import { computed, useTemplateRef } from 'vue';
import { Button, Popover } from '@lumx/vue';

const anchorRef = useTemplateRef<InstanceType<typeof Button>>('anchorRef');
const anchorElRef = computed(() => anchorRef.value?.$el as HTMLElement | undefined);
</script>

// packages/site-demo/content/product/components/popover/react/offset.tsx
import { Chip, Placement, Popover, Size } from '@lumx/react';
import React, { useRef } from 'react';

const App = ({ theme }: any) => {
    const anchorRef = useRef(null);

    return (
        <>
            <Chip style={{ marginBottom: 80 }} chipRef={anchorRef} theme={theme} size={Size.s}>
                Anchor
            </Chip>

            <Popover
                isOpen
                className="lumx-spacing-padding-huge"
                theme={theme}
                anchorRef={anchorRef}
                placement={Placement.RIGHT}
                offset={{
                    away: 30,
                    along: 60,
                }}
            >
                Popover
            </Popover>
        </>
    );
};

export default App;
