// packages/site-demo/content/product/components/thumbnail/vue/demo6.vue
<template>
    <Thumbnail
        is-loading
        image="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAoMBgDTD2qgAAAAASUVORK5CYII="
        alt="loading image"
        aspect-ratio="square"
        size="xl"
        variant="rounded"
        :theme="theme"
    />
</template>

<script setup lang="ts">
import { Thumbnail, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();
</script>

// packages/site-demo/content/product/components/thumbnail/react/demo6.tsx
import { Thumbnail, type Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => (
    <Thumbnail
        isLoading
        image="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAoMBgDTD2qgAAAAASUVORK5CYII="
        alt="loading image"
        aspectRatio="square"
        size="xl"
        variant="rounded"
        theme={theme}
    />
);
