// packages/site-demo/content/product/components/thumbnail/vue/variants.vue
<template>
    <Thumbnail image="https://picsum.photos/id/1/128/128" alt="Squared" size="xl" variant="squared" />
    <Thumbnail image="https://picsum.photos/id/1/128/128" alt="Rounded" size="xl" variant="rounded" />
</template>

<script setup lang="ts">
import { Thumbnail } from '@lumx/vue';
</script>

// packages/site-demo/content/product/components/thumbnail/react/variants.tsx
import { Size, Thumbnail, ThumbnailVariant } from '@lumx/react';
import React from 'react';

const App = () => (
    <>
        <Thumbnail image="https://picsum.photos/150" size={Size.xl} variant={ThumbnailVariant.squared}/>
        <Thumbnail image="https://picsum.photos/150" size={Size.xl} variant={ThumbnailVariant.rounded}/>
    </>
);

export default App;
