// packages/site-demo/content/product/components/chip/react/dismissible.tsx
import { mdiClose, mdiEmail } from '@lumx/icons';
import { Chip, Icon, Size } from '@lumx/react';
import React from 'react';

export const App = ({ theme }: any) => {
    // Initialize a click handler
    const onClick = () => console.log('clicked chip');

    return (
        <>
            <Chip theme={theme} after={<Icon icon={mdiClose} size={Size.xs} />} onClick={onClick}>
                Dismissible
            </Chip>

            <Chip
                theme={theme}
                before={<Icon icon={mdiEmail} size={Size.xs} />}
                after={<Icon icon={mdiClose} size={Size.xs} />}
                onClick={onClick}
            >
                Dismissible rich
            </Chip>
        </>
    );
};

// packages/site-demo/content/product/components/chip/vue/dismissible.vue
<template>
    <Chip :theme="theme" @click="onClick">
        <template #after>
            <Icon :icon="mdiClose" size="xs" />
        </template>
        Dismissible
    </Chip>

    <Chip :theme="theme" @click="onClick">
        <template #before>
            <Icon :icon="mdiEmail" size="xs" />
        </template>
        <template #after>
            <Icon :icon="mdiClose" size="xs" />
        </template>
        Dismissible rich
    </Chip>
</template>

<script setup lang="ts">
import { mdiClose, mdiEmail } from '@lumx/icons';
import { Chip, Icon, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const onClick = () => console.log('clicked chip');
</script>
