// packages/site-demo/content/product/components/chip/react/small.tsx
import { mdiClose, mdiEmail } from '@lumx/icons';
import { Chip, Icon, Size } from '@lumx/react';

export const App = ({ theme }: any) => {
    // Initialize a click handler
    const onClick = () => console.log('clicked chip');

    return (
        <>
            <Chip theme={theme} size={Size.s}>
                Small
            </Chip>

            <Chip theme={theme} size={Size.s} before={<Icon icon={mdiEmail} size={Size.xxs} theme={theme} />}>
                Small rich
            </Chip>

            <Chip
                theme={theme}
                size={Size.s}
                after={<Icon icon={mdiClose} size={Size.xxs} theme={theme} />}
                onClick={onClick}
            >
                Small dismissible
            </Chip>
        </>
    );
};

// packages/site-demo/content/product/components/chip/vue/small.vue
<template>
    <Chip :theme="theme" size="s">Small</Chip>

    <Chip :theme="theme" size="s">
        <template #before>
            <Icon :icon="mdiEmail" size="xxs" />
        </template>
        Small rich
    </Chip>

    <Chip :theme="theme" size="s" @click="onClick">
        <template #after>
            <Icon :icon="mdiClose" size="xxs" />
        </template>
        Small dismissible
    </Chip>
</template>

<script setup lang="ts">
import { mdiClose, mdiEmail } from '@lumx/icons';
import { Chip, Icon, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const onClick = () => console.log('clicked chip');
</script>
