// packages/lumx-react/src/components/toolbar/Toolbar.tsx
import { ReactNode } from 'react';

import { GenericProps } from '@lumx/react/utils/type';
import {
    Toolbar as UI,
    ToolbarProps as UIProps,
    CLASSNAME,
    TOOLBAR_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Toolbar';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

/**
 * Defines the props of the component.
 */
export interface ToolbarProps extends GenericProps, UIProps {
    /** After content (placed after the label). */
    after?: ReactNode;
    /** Before content (placed before the label). */
    before?: ReactNode;
    /** Label content. */
    label?: ReactNode;
}

/**
 * Toolbar component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Toolbar = forwardRef<ToolbarProps, HTMLDivElement>((props, ref) => {
    return UI({
        ref,
        ...props,
    });
});
Toolbar.displayName = TOOLBAR_NAME;
Toolbar.className = CLASSNAME;
Toolbar.defaultProps = DEFAULT_PROPS;

// packages/lumx-vue/src/components/toolbar/Toolbar.tsx
import { defineComponent, useAttrs } from 'vue';
import {
    Toolbar as ToolbarUI,
    type ToolbarProps as UIProps,
    CLASSNAME,
    TOOLBAR_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Toolbar';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import type { JSXElement } from '@lumx/core/js/types';

export type ToolbarProps = VueToJSXProps<UIProps, 'ref' | 'label' | 'after' | 'before'>;

export { CLASSNAME, TOOLBAR_NAME, DEFAULT_PROPS };

const Toolbar = defineComponent(
    (props: ToolbarProps, { slots }) => {
        const attrs = useAttrs();

        return () => {
            return (
                <ToolbarUI
                    {...props}
                    {...attrs}
                    className={props.class}
                    label={slots.default?.() as JSXElement}
                    before={slots.before?.() as JSXElement}
                    after={slots.after?.() as JSXElement}
                />
            );
        };
    },
    {
        name: 'LumxToolbar',
        inheritAttrs: false,
        props: keysOf<ToolbarProps>()('class'),
    },
);

export default Toolbar;
