// packages/lumx-react/src/components/user-block/UserBlock.tsx
import React, { ReactNode } from 'react';

import classNames from 'classnames';
import isEmpty from 'lodash/isEmpty';
import set from 'lodash/set';

import { Avatar, ColorPalette, Link, Orientation, Size, Theme } from '@lumx/react';
import { GenericProps, HasTheme } from '@lumx/react/utils/type';
import { getRootClassName, handleBasicClasses } from '@lumx/react/utils/className';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

import { useTheme } from '@lumx/react/utils/theme/ThemeContext';
import { AvatarProps } from '../avatar/Avatar';

/**
 * User block sizes.
 */
export type UserBlockSize = Extract<Size, 'xs' | 's' | 'm' | 'l'>;

/**
 * Defines the props of the component.
 */
export interface UserBlockProps extends GenericProps, HasTheme {
    /** Props to pass to the avatar. */
    avatarProps?: Omit<AvatarProps, 'alt'>;
    /** Additional fields used to describe the user. */
    fields?: string[];
    /** Props to pass to the link wrapping the avatar thumbnail. */
    linkProps?: React.DetailedHTMLProps<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>;
    /** Custom react component for the link (can be used to inject react router Link). */
    linkAs?: 'a' | any;
    /** Multiple action toolbar content. */
    multipleActions?: ReactNode;
    /** User name. */
    name?: React.ReactNode;
    /** Props to pass to the name block. */
    nameProps?: GenericProps;
    /** Orientation. */
    orientation?: Orientation;
    /** Simple action toolbar content. */
    simpleAction?: ReactNode;
    /** Size variant. */
    size?: UserBlockSize;
    /** On click callback. */
    onClick?(): void;
    /** On mouse enter callback. */
    onMouseEnter?(): void;
    /** On mouse leave callback. */
    onMouseLeave?(): void;
    /** Display additional fields below the original name and fields */
    additionalFields?: React.ReactNode;
    /** Display an additional element after the entire component. (to the right if orientation is horizontal, at the bottom if orientation is vertical) */
    after?: React.ReactNode;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'UserBlock';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * Component default props.
 */
const DEFAULT_PROPS: Partial<UserBlockProps> = {
    orientation: Orientation.horizontal,
    size: Size.m,
};

/**
 * UserBlock component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const UserBlock = forwardRef<UserBlockProps, HTMLDivElement>((props, ref) => {
    const defaultTheme = useTheme() || Theme.light;
    const {
        avatarProps,
        className,
        fields,
        linkProps,
        linkAs,
        multipleActions,
        name,
        nameProps,
        onClick,
        onMouseEnter,
        onMouseLeave,
        orientation = DEFAULT_PROPS.orientation,
        simpleAction,
        size = DEFAULT_PROPS.size,
        theme = defaultTheme,
        children,
        additionalFields,
        after,
        ...forwardedProps
    } = props;
    let componentSize = size;

    // Special case - When using vertical orientation force the size to be Sizes.l.
    if (orientation === Orientation.vertical) {
        componentSize = Size.l;
    }

    const shouldDisplayActions: boolean = orientation === Orientation.vertical;

    const isLink = Boolean(linkProps?.href || linkAs);
    const isClickable = !!onClick || isLink;

    const nameBlock: ReactNode = React.useMemo(() => {
        if (isEmpty(name)) {
            return null;
        }
        let NameComponent: any = 'span';
        const nProps: any = {
            ...nameProps,
            className: classNames(`${CLASSNAME}__name`, linkProps?.className, nameProps?.className),
        };
        if (isClickable) {
            NameComponent = Link;
            Object.assign(nProps, {
                ...linkProps,
                onClick,
                linkAs,
                color: ColorPalette.dark,
            });
        }
        // Disable avatar focus since the name block is the same link / same button.
        if (avatarProps) {
            set(avatarProps, ['thumbnailProps', 'tabIndex'], -1);
        }
        return <NameComponent {...nProps}>{name}</NameComponent>;
    }, [avatarProps, isClickable, linkAs, linkProps, name, nameProps, onClick]);

    const shouldDisplayFields = componentSize !== Size.s && componentSize !== Size.xs;

    const fieldsBlock: ReactNode = fields && shouldDisplayFields && (
        <div className={`${CLASSNAME}__fields`}>
            {fields.map((field: string, idx: number) => (
                <span key={idx} className={`${CLASSNAME}__field`}>
                    {field}
                </span>
            ))}
        </div>
    );

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames(
                className,
                handleBasicClasses({ prefix: CLASSNAME, orientation, size: componentSize, theme, isClickable }),
            )}
            onMouseLeave={onMouseLeave}
            onMouseEnter={onMouseEnter}
        >
            {avatarProps && (
                <Avatar
                    linkAs={linkAs}
                    linkProps={linkProps}
                    alt=""
                    {...(avatarProps as any)}
                    className={classNames(`${CLASSNAME}__avatar`, avatarProps.className)}
                    size={componentSize}
                    onClick={onClick}
                    theme={theme}
                />
            )}
            {(fields || name || children || additionalFields) && (
                <div className={`${CLASSNAME}__wrapper`}>
                    {children || nameBlock}
                    {fieldsBlock}
                    {shouldDisplayFields ? additionalFields : null}
                </div>
            )}
            {shouldDisplayActions && simpleAction && <div className={`${CLASSNAME}__action`}>{simpleAction}</div>}
            {shouldDisplayActions && multipleActions && (
                <div className={`${CLASSNAME}__actions`}>{multipleActions}</div>
            )}
            {after ? <div className={`${CLASSNAME}__after`}>{after}</div> : null}
        </div>
    );
});
UserBlock.displayName = COMPONENT_NAME;
UserBlock.className = CLASSNAME;
UserBlock.defaultProps = DEFAULT_PROPS;

// packages/lumx-vue/src/components/user-block/UserBlock.tsx
import { computed, defineComponent, toRaw, useAttrs, type VNode } from 'vue';

import isEmpty from 'lodash/isEmpty';
import set from 'lodash/set';

import {
    UserBlock as UserBlockUI,
    type UserBlockProps as UIProps,
    UserBlockPropsToOverride,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
    element,
    isUserBlockClickeable,
    type UserBlockSize,
} from '@lumx/core/js/components/UserBlock';
import { ColorPalette } from '@lumx/core/js/constants';
import type { JSXElement } from '@lumx/core/js/types';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { classNames } from '@lumx/core/js/utils';

import { Avatar, type AvatarProps } from '../avatar';
import { Link } from '../link';
import Text from '../text/Text';
import { useHasEventListener } from '@lumx/vue/composables/useHasEventListener';

export type { UserBlockSize };

export type UserBlockProps = VueToJSXProps<
    UIProps,
    | UserBlockPropsToOverride
    | 'handleClick'
    | 'handleMouseEnter'
    | 'handleMouseLeave'
    | 'simpleAction'
    | 'multipleActions'
    | 'additionalFields'
    | 'after'
> & {
    /** Props to pass to the avatar. */
    avatarProps?: Omit<AvatarProps, 'alt'>;
    /** Props to pass to the link wrapping the avatar thumbnail. */
    linkProps?: Record<string, any>;
};

export const emitSchema = {
    click: () => true,
    mouseenter: () => true,
    mouseleave: () => true,
};

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * UserBlock component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const UserBlock = defineComponent(
    (props: UserBlockProps, { emit, slots }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        const handleClick = () => {
            emit('click');
        };

        const handleMouseEnter = () => {
            emit('mouseenter');
        };

        const handleMouseLeave = () => {
            emit('mouseleave');
        };

        const hasOnClick = useHasEventListener('onClick');
        const hasOnMouseEnter = useHasEventListener('onMouseenter');
        const hasOnMouseLeave = useHasEventListener('onMouseleave');

        /**
         * This logic needs to occur on the wrapper level, since core templates cannot manage
         * the render of dynamically determined components. So `NameComponent`, if moved to core,
         * it will return an `undefined`
         */
        const nameBlock = computed((): VNode | null => {
            const name = props.name || slots.name?.();
            if (isEmpty(name)) {
                return null;
            }

            const isClickable = isUserBlockClickeable({
                linkAs: props.linkAs,
                linkProps: props.linkProps,
                handleClick: hasOnClick ? handleClick : undefined,
            });

            let NameComponent: any = 'span';
            const nProps: any = {
                ...props.nameProps,
                class: classNames.join(element('name'), props.linkProps?.class, props.nameProps?.class),
            };

            if (isClickable) {
                NameComponent = Link;
                Object.assign(nProps, {
                    ...props.linkProps,
                    color: ColorPalette.dark,
                });
            }

            return (
                <NameComponent {...nProps} onClick={handleClick}>
                    <Text as="span">{name}</Text>
                </NameComponent>
            ) as VNode;
        });

        // Create modified avatarProps with tabIndex if clickable
        const computedAvatarProps = computed(() => {
            if (!props.avatarProps) return undefined;

            const isClickable = isUserBlockClickeable({
                linkAs: props.linkAs,
                linkProps: props.linkProps,
                handleClick,
            });

            if (isClickable) {
                // Disable avatar focus since the name block is the same link / same button.
                const modifiedProps = { ...props.avatarProps };
                set(modifiedProps, ['thumbnailProps', 'tabIndex'], -1);
                return modifiedProps;
            }

            return props.avatarProps;
        });

        return () => {
            const { linkAs, fields, ...restProps } = props;
            const childrenContent = slots.default?.() || nameBlock.value;

            return (
                <UserBlockUI
                    {...restProps}
                    {...attrs}
                    linkAs={toRaw(linkAs)}
                    className={props.class}
                    theme={props.theme || defaultTheme.value}
                    handleClick={hasOnClick ? handleClick : undefined}
                    handleMouseEnter={hasOnMouseEnter ? handleMouseEnter : undefined}
                    handleMouseLeave={hasOnMouseLeave ? handleMouseLeave : undefined}
                    avatarProps={computedAvatarProps.value}
                    fields={(fields || slots.fields?.()) as any}
                    simpleAction={(slots['simple-action']?.() || slots.simpleAction?.()) as JSXElement}
                    multipleActions={(slots['multiple-actions']?.() || slots.multipleActions?.()) as JSXElement}
                    additionalFields={(slots['additional-fields']?.() || slots.additionalFields?.()) as JSXElement}
                    after={slots.after?.() as JSXElement}
                    Avatar={(avProps) => {
                        const { badge, ...restAvatarProps } = avProps;
                        return (
                            <Avatar {...restAvatarProps} class={avProps.className}>
                                {{
                                    badge: badge ? () => badge : undefined,
                                }}
                            </Avatar>
                        );
                    }}
                    Text={Text as unknown as UIProps['Text']}
                    children={childrenContent as JSXElement}
                    mouseEnterProp="onMouseenter"
                    mouseLeaveProp="onMouseleave"
                />
            );
        };
    },
    {
        name: 'LumxUserBlock',
        inheritAttrs: false,
        props: keysOf<UserBlockProps>()(
            'avatarProps',
            'class',
            'fields',
            'linkAs',
            'linkProps',
            'name',
            'nameProps',
            'orientation',
            'size',
            'theme',
        ),
        emits: emitSchema,
    },
);

export default UserBlock;
