// packages/site-demo/src/components/content/HashNavLink/index.vue
<!-- Demo "hash" nav link displaying a <a> with aria-current -->
<template>
    <a v-bind="attrs" :href="hash" :aria-current="isActive ? 'page' : undefined">
        <slot />
    </a>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, useAttrs } from 'vue';

defineOptions({ inheritAttrs: false });
const { hash } = defineProps<{ hash: string }>();
const attrs = useAttrs();

const matchesHash = () => (window.location.hash || '#') === hash;
const isActive = ref(matchesHash());
const onHashChange = () => isActive.value = matchesHash();

onMounted(() => window.addEventListener('hashchange', onHashChange));
onUnmounted(() => window.removeEventListener('hashchange', onHashChange));
</script>

// packages/site-demo/src/components/content/HashNavLink/index.tsx
import { WINDOW } from '@lumx/core/js/constants/browser';
import { useSyncExternalStore } from 'react';

// Demo "hash" nav link displaying a <a> with aria-current
export const HashNavLink = ({ className, hash, children }: any) => {
    const getSnapshot = () => (WINDOW?.location.hash || '#') === hash;
    const isActive = useSyncExternalStore(
        (listener) => {
            WINDOW?.addEventListener('hashchange', listener);
            return () => WINDOW?.removeEventListener('hashchange', listener);
        },
        getSnapshot,
        getSnapshot,
    );
    return (
        <a className={className} href={hash} aria-current={isActive ? 'page' : undefined}>
            {children}
        </a>
    );
};
