// packages/site-demo/content/product/components/mosaic/react/two-images.tsx
import { Mosaic, ThumbnailProps } from '@lumx/react';
import React from 'react';

const IMAGES: ThumbnailProps[] = [
    { image: '/demo-assets/portrait1.jpg', alt: 'Portrait 1' },
    { image: '/demo-assets/portrait2.jpg', alt: 'Portrait 2' },
];

export const App = () => {
    return (
        <div style={{ width: 250 }}>
            <Mosaic thumbnails={IMAGES} />
        </div>
    );
};

// packages/site-demo/content/product/components/mosaic/vue/two-images.vue
<template>
    <div style="width: 250px">
        <Mosaic
            :thumbnails="[
                { image: 'https://picsum.photos/id/653/275/500', alt: 'Portrait 1' },
                { image: 'https://picsum.photos/id/670/350/500', alt: 'Portrait 2' },
            ]"
        />
    </div>
</template>

<script setup lang="ts">
import { Mosaic } from '@lumx/vue';
</script>
