// packages/site-demo/content/product/components/uploader/vue/avatar.vue
<template>
    <Uploader :icon="mdiImagePlus" label="Add photo" :theme="theme" :variant="UploaderVariant.circle" />
</template>

<script setup lang="ts">
import { mdiImagePlus } from '@lumx/icons';
import { Uploader, UploaderVariant, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();
</script>

// packages/site-demo/content/product/components/uploader/react/avatar.tsx
import React from 'react';

import { mdiImagePlus } from '@lumx/icons';
import { Uploader, UploaderVariant } from '@lumx/react';

const App = ({ theme }: any) => (
    <div className="demo-grid">
        <Uploader icon={mdiImagePlus} label="Add photo" theme={theme} variant={UploaderVariant.circle} />
    </div>
);

export default App;
