// packages/lumx-core/src/js/components/GenericBlock/index.tsx
import type { CommonRef, JSXElement, LumxClassName } from '../../types';
import { classNames } from '../../utils';
import { Orientation, Size } from '../../constants';

import { GenericBlockGapSize } from './constants';
import { FlexBoxProps } from '../FlexBox';

export interface GenericBlockProps extends FlexBoxProps {
    /**
     * Component to use as visual element.
     */
    figure?: JSXElement;
    /**
     * Main content.
     */
    content?: JSXElement;
    /**
     * Actions to set after the main content.
     */
    actions?: JSXElement;
    /**
     * Orientation of the 3 sections
     */
    orientation?: FlexBoxProps['orientation'];
    /**
     * Horizontal alignment.
     */
    horizontalAlign?: FlexBoxProps['hAlign'];
    /**
     * Vertical alignment.
     */
    verticalAlign?: FlexBoxProps['vAlign'];
    /**
     * The props to forward to the content.
     * By default, the content will have the same alignment as wrapper.
     */
    contentProps?: Omit<FlexBoxProps, 'children'>;
    /**
     * props to forward to the actions element.
     */
    actionsProps?: Omit<FlexBoxProps, 'children'>;
    /**
     * props to forward to the figure element.
     */
    figureProps?: Omit<FlexBoxProps, 'children'>;
    /**
     * FlexBox component
     */
    FlexBox: (props: FlexBoxProps) => any;
    /**
     * Gap space between sections.
     */
    gap?: GenericBlockGapSize;
    /**
     * reference to the root element
     */
    ref?: CommonRef;
}

export interface GenericBlockSectionProps extends FlexBoxProps {
    /**
     * Gap space between items.
     */
    gap?: GenericBlockGapSize;
}

export type GenericBlockPropsToOverride = 'FlexBox' | 'content';

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'GenericBlock';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-generic-block';
const { block, element } = classNames.bem(CLASSNAME);

/**
 * Component default props.
 */
export const DEFAULT_PROPS: Partial<GenericBlockProps> = {
    gap: Size.big,
    orientation: Orientation.horizontal,
};

/**
 * The GenericBlock is a layout component made of 3 sections that can be
 * displayed either horizontally of vertically with the same gap between each section.
 *
 * The sections are:
 * - `Figure` => A visual element to display before the main content.
 * - `Content` => The main content displayed
 * - `Actions` => One or more actions to set after the element.
 *
 * @see https://www.figma.com/file/lzzrQmsfaXRaOyRfoEogPZ/DS%3A-playground?node-id=1%3A4076
 */
export const GenericBlock = (props: GenericBlockProps) => {
    const {
        className,
        figure,
        figureProps,
        children,
        actions,
        actionsProps,
        gap = DEFAULT_PROPS.gap,
        ref,
        content,
        orientation = DEFAULT_PROPS.orientation,
        contentProps,
        FlexBox,
        ...forwardedProps
    } = props;

    return (
        <FlexBox
            ref={ref}
            className={classNames.join(className, block())}
            gap={gap}
            orientation={orientation}
            {...forwardedProps}
        >
            {figure && (
                <FlexBox {...figureProps} className={classNames.join(figureProps?.className, element('figure'))}>
                    {figure}
                </FlexBox>
            )}

            {content && (
                <FlexBox
                    orientation={Orientation.vertical}
                    fillSpace
                    {...contentProps}
                    className={classNames.join(contentProps?.className, element('content'))}
                >
                    {content}
                </FlexBox>
            )}

            {actions && (
                <FlexBox {...actionsProps} className={classNames.join(actionsProps?.className, element('actions'))}>
                    {actions}
                </FlexBox>
            )}
        </FlexBox>
    );
};

// packages/lumx-vue/src/components/generic-block/GenericBlock.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    GenericBlock as GenericBlockUI,
    type GenericBlockProps as UIProps,
    GenericBlockPropsToOverride,
} from '@lumx/core/js/components/GenericBlock';
import type { JSXElement } from '@lumx/core/js/types';

import { FlexBox as FlexBoxVue, FlexBoxProps } from '../flex-box';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

// Follow Vue FlexBox convention: expose verticalAlign/horizontalAlign instead of vAlign/hAlign.
// figure, actions and content are handled via named slots only (not as VNode props).
export type GenericBlockProps = VueToJSXProps<
    UIProps,
    | GenericBlockPropsToOverride
    | 'figure'
    | 'actions'
    | 'vAlign'
    | 'hAlign'
    | 'actionsProps'
    | 'contentProps'
    | 'figureProps'
> & {
    /** Customize the root element tag. */
    as?: string;
    /** Vertical alignment (maps to core's vAlign). */
    verticalAlign?: UIProps['vAlign'];
    /** Horizontal alignment (maps to core's hAlign). */
    horizontalAlign?: UIProps['hAlign'];
    /**
     * The props to forward to the content.
     * By default, the content will have the same alignment as wrapper.
     */
    contentProps?: FlexBoxProps;
    /**
     * props to forward to the actions element.
     */
    actionsProps?: FlexBoxProps;
    /**
     * props to forward to the figure element.
     */
    figureProps?: FlexBoxProps;
};

/**
 * The GenericBlock is a layout component made of 3 sections that can be
 * displayed either horizontally or vertically with the same gap between each section.
 *
 * The sections are provided via named slots:
 * - `figure` slot => A visual element to display before the main content.
 * - default slot => The main content displayed.
 * - `actions` slot => One or more actions to set after the element.
 */
const GenericBlock = defineComponent(
    (props: GenericBlockProps, { slots }) => {
        const attrs = useAttrs();

        return () => {
            const figure = slots.figure?.() as JSXElement;
            const content = slots.default?.() as JSXElement;
            const actions = slots.actions?.() as JSXElement;

            // Forward alignment to sub-sections (like the React wrapper does with alignProps).
            // verticalAlign/horizontalAlign are in {…props} spread, and FlexBoxVue declares them,
            // so they propagate correctly through forwardedProps → injected FlexBoxVue.
            const alignProps = {
                verticalAlign: props.verticalAlign,
                horizontalAlign: props.horizontalAlign,
            };

            // Destructure `class` out of props so it isn't forwarded as-is to GenericBlockUI
            // (which would reach FlexBoxVue as both `class` and `className`, causing FlexBoxVue
            // to prefer `class` over the merged `className` that includes the BEM block class).
            const { class: _, ...restProps } = props;

            return (
                <GenericBlockUI
                    {...restProps}
                    {...attrs}
                    className={props.class as string}
                    FlexBox={FlexBoxVue as any}
                    figure={figure}
                    content={content}
                    actions={actions}
                    figureProps={{ ...alignProps, ...(props.figureProps as any) }}
                    contentProps={{ ...alignProps, ...(props.contentProps as any) }}
                    actionsProps={{ ...alignProps, ...(props.actionsProps as any) }}
                />
            );
        };
    },
    {
        name: 'LumxGenericBlock',
        inheritAttrs: false,
        props: keysOf<GenericBlockProps>()(
            'as',
            'orientation',
            'verticalAlign',
            'horizontalAlign',
            'gap',
            'fillSpace',
            'wrap',
            'marginAuto',
            'noShrink',
            'figureProps',
            'contentProps',
            'actionsProps',
            'class',
        ),
    },
);

export default GenericBlock;
