// packages/lumx-vue/src/components/list/ListSection.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    ListSection as ListSectionUI,
    type ListSectionProps as UIProps,
    COMPONENT_NAME,
} from '@lumx/core/js/components/List/ListSection';
import type { JSXElement } from '@lumx/core/js/types';

import { useId } from '../../composables/useId';
import { useClassName } from '../../composables/useClassName';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Text } from '../text';

export type ListSectionProps = VueToJSXProps<UIProps, 'id' | 'Text'>;

/**
 * ListSection component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const ListSection = defineComponent(
    (props: ListSectionProps, { slots }) => {
        const attrs = useAttrs();
        const id = useId();
        const className = useClassName(() => props.class);

        return () => (
            <ListSectionUI
                {...props}
                {...attrs}
                className={className.value}
                id={id}
                Text={Text as unknown as UIProps['Text']}
                children={slots.default?.() as JSXElement}
            />
        );
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<ListSectionProps>()('label', 'icon', 'itemsWrapperProps', 'class'),
    },
);

export default ListSection;

// packages/lumx-react/src/components/list/ListSection.tsx
import { ReactNode } from 'react';

import { GenericProps } from '@lumx/react/utils/type';
import {
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
    ListSection as UI,
    ListSectionProps as UIProps,
} from '@lumx/core/js/components/List/ListSection';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useId } from '@lumx/react/hooks/useId';

import { Text } from '../text';

/**
 * Defines the props of the component.
 */
export interface ListSectionProps extends GenericProps, ReactToJSX<UIProps, 'children' | 'id' | 'Text'> {
    /** Section content */
    children: ReactNode;
}

/**
 * ListSection component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const ListSection = forwardRef<ListSectionProps, HTMLLIElement>((props, ref) => {
    const id = useId();
    return UI({ ...props, ref, id, Text });
});

ListSection.displayName = COMPONENT_NAME;
ListSection.className = CLASSNAME;
ListSection.defaultProps = DEFAULT_PROPS;
