// packages/site-demo/content/product/components/inline-list/vue/color-and-typography.vue
<template>
    <InlineList typography="body1" color="dark-L2">
        <Text as="span">Some text</Text>
        <Link href="#">Some link</Link>
        <Icon :icon="mdiEarth" />
    </InlineList>
</template>

<script setup lang="ts">
import { mdiEarth } from '@lumx/icons';
import { Icon, InlineList, Link, Text } from '@lumx/vue';
</script>

// packages/site-demo/content/product/components/inline-list/react/color-and-typography.tsx
import { Icon, InlineList, Link, Text } from '@lumx/react';
import { mdiEarth } from '@lumx/icons';

export default () => (
    <InlineList typography="body1" color="dark-L2">
        <Text as="span">Some text</Text>
        <Link href="#">Some link</Link>
        <Icon icon={mdiEarth} />
    </InlineList>
);
