// packages/lumx-react/src/components/uploader/Uploader.tsx
import React, { MouseEventHandler } from 'react';

import { AspectRatio, Icon, Size, Theme } from '@lumx/react';
import { GenericProps, HasTheme, ValueOf } from '@lumx/react/utils/type';
import { useClassnames } from '@lumx/react/utils';
import type { LumxClassName } from '@lumx/core/js/types';
import { classNames } from '@lumx/core/js/utils';
import { useBooleanState } from '@lumx/react/hooks/useBooleanState';
import { useId } from '@lumx/react/hooks/useId';
import { useTheme } from '@lumx/react/utils/theme/ThemeContext';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { HasAriaDisabled } from '@lumx/react/utils/type/HasAriaDisabled';
import { useDisableStateProps } from '@lumx/react/utils/disabled';

/**
 * Uploader variants.
 */
export const UploaderVariant = {
    square: 'square',
    rounded: 'rounded',
    circle: 'circle',
} as const;
export type UploaderVariant = ValueOf<typeof UploaderVariant>;

/**
 * Uploader sizes.
 */
export type UploaderSize = Extract<Size, 'xl' | 'xxl'>;

/**
 * Extend native HTML input props with specialized `onChange` providing the a `File` array.
 */
interface FileInputProps extends Omit<React.ComponentProps<'input'>, 'onChange'> {
    onChange(files: File[], evt: React.ChangeEvent<HTMLInputElement>): void;
}

/**
 * Defines the props of the component.
 */
export interface UploaderProps extends GenericProps, HasTheme, HasAriaDisabled {
    /** Image aspect ratio. */
    aspectRatio?: AspectRatio;
    /** Icon (SVG path). */
    icon?: string;
    /** Disabled state */
    isDisabled?: boolean;
    /** Label text. */
    label?: string;
    /** Size variant. */
    size?: UploaderSize;
    /** Variant. */
    variant?: UploaderVariant;
    /** On click callback. */
    onClick?: MouseEventHandler;
    /** Handle file selection with a native input file. */
    fileInputProps?: FileInputProps;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'Uploader';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-uploader';

/**
 * Component default props.
 */
const DEFAULT_PROPS: Partial<UploaderProps> = {
    aspectRatio: AspectRatio.horizontal,
    size: Size.xl,
    variant: UploaderVariant.square,
};

/**
 * Uploader component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Uploader = forwardRef<UploaderProps>((props, ref) => {
    const { block, element } = useClassnames(CLASSNAME);
    const { disabledStateProps, otherProps, isAnyDisabled } = useDisableStateProps(props);
    const defaultTheme = useTheme() || Theme.light;
    const {
        aspectRatio = DEFAULT_PROPS.aspectRatio,
        className,
        label,
        icon,
        size = DEFAULT_PROPS.size,
        theme = defaultTheme,
        variant = DEFAULT_PROPS.variant,
        fileInputProps,
        onClick,
        ...forwardedProps
    } = otherProps;
    // Adjust to square aspect ratio when using circle variants.
    const adjustedAspectRatio = variant === UploaderVariant.circle ? AspectRatio.square : aspectRatio;

    const handleClick: React.MouseEventHandler = React.useCallback(
        (evt) => {
            if (isAnyDisabled) {
                evt.preventDefault();
            } else {
                onClick?.(evt);
            }
        },
        [isAnyDisabled, onClick],
    );

    const generatedInputId = useId();
    const inputId = fileInputProps?.id || generatedInputId;
    const [isDragHovering, unsetDragHovering, setDragHovering] = useBooleanState(false);
    const wrapper = fileInputProps
        ? ({ Component: 'label', props: { htmlFor: inputId } } as const)
        : ({ Component: 'button', props: { type: 'button', ...disabledStateProps } } as const);

    const onChange = React.useMemo(() => {
        if (isAnyDisabled || !fileInputProps?.onChange) return undefined;
        return (evt: React.ChangeEvent<HTMLInputElement>) => {
            const fileList = evt.target.files;
            const files = fileList ? Array.from(fileList) : [];
            fileInputProps.onChange(files, evt);
        };
    }, [isAnyDisabled, fileInputProps]);

    return (
        <wrapper.Component
            ref={ref as any}
            {...wrapper.props}
            {...forwardedProps}
            onClick={handleClick}
            className={block(
                {
                    [`aspect-ratio-${adjustedAspectRatio}`]: Boolean(adjustedAspectRatio),
                    [`size-${size}`]: Boolean(size),
                    [`theme-${theme}`]: Boolean(theme),
                    [`variant-${variant}`]: Boolean(variant),
                    'is-drag-hovering': isDragHovering,
                    'is-disabled': isAnyDisabled,
                },
                className,
            )}
        >
            <span className={element('background')} />

            <span className={element('wrapper')}>
                {icon && <Icon className={element('icon')} icon={icon} size={Size.s} />}

                {label && <span className={element('label')}>{label}</span>}
            </span>

            {fileInputProps && (
                <input
                    type="file"
                    id={inputId}
                    className={element('input', [classNames.visuallyHidden()])}
                    {...disabledStateProps}
                    {...fileInputProps}
                    readOnly={isAnyDisabled}
                    onChange={onChange}
                    onDragEnter={setDragHovering}
                    onDragLeave={unsetDragHovering}
                    onDrop={unsetDragHovering}
                />
            )}
        </wrapper.Component>
    );
});
Uploader.displayName = COMPONENT_NAME;
Uploader.className = CLASSNAME;
Uploader.defaultProps = DEFAULT_PROPS;

// packages/lumx-vue/src/components/uploader/Uploader.tsx
import { computed, defineComponent, ref, useAttrs } from 'vue';

import {
    Uploader as UploaderUI,
    UploaderVariant,
    DEFAULT_PROPS,
    CLASSNAME,
    COMPONENT_NAME,
} from '@lumx/core/js/components/Uploader';
import type { UploaderProps as UIProps, UploaderPropsToOverride } from '@lumx/core/js/components/Uploader';
import type { UploaderSize } from '@lumx/core/js/components/Uploader';

import { useTheme } from '../../composables/useTheme';
import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { useId } from '../../composables/useId';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

type VueFileInputProps = {
    /** Accepted file types. */
    accept?: string;
    /** Whether multiple files can be selected. */
    multiple?: boolean;
    /** Camera capture mode. */
    capture?: boolean | 'user' | 'environment';
    /** Native input id (generated if not provided). */
    id?: string;
};

export type UploaderProps = VueToJSXProps<UIProps, UploaderPropsToOverride> & {
    /** Handle file selection with a native input file. */
    fileInputProps?: VueFileInputProps;
};

export const emitSchema = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    change: (_files: File[], _event?: Event) => true,
};

export type { UploaderSize };
export { UploaderVariant, DEFAULT_PROPS, CLASSNAME, COMPONENT_NAME };

/**
 * Uploader component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const Uploader = defineComponent(
    (props: UploaderProps, { emit }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();
        const generatedInputId = useId();
        const inputId = computed(() => props.fileInputProps?.id || generatedInputId);
        const isDragHovering = ref(false);

        const { isAnyDisabled, disabledStateProps, otherProps } = useDisableStateProps(
            computed(() => ({ ...props, ...attrs })),
        );

        const handleClick = (event: MouseEvent) => {
            if (isAnyDisabled.value) {
                event.preventDefault();
                return;
            }
            event.stopImmediatePropagation();
            (attrs as any).onClick?.(event);
        };

        const handleChange = (event: Event) => {
            if (isAnyDisabled.value) return;
            event.stopImmediatePropagation();
            const input = event.target as HTMLInputElement;
            const files = input.files ? Array.from(input.files) : [];
            emit('change', files, event);
        };

        return () => {
            const hasFileInput = Boolean(props.fileInputProps);
            const {
                onClick: _onClick,
                fileInputProps: _fp,
                class: _class,
                theme: _theme,
                ...restProps
            } = otherProps.value as any;

            return (
                <UploaderUI
                    {...restProps}
                    className={props.class}
                    theme={props.theme || defaultTheme.value}
                    inputId={inputId.value}
                    isAnyDisabled={isAnyDisabled.value}
                    isDragHovering={isDragHovering.value}
                    handleClick={handleClick}
                    handleChange={handleChange}
                    Component={hasFileInput ? 'label' : 'button'}
                    fileInputProps={{
                        ...props.fileInputProps,
                        ...disabledStateProps.value,
                        readonly: isAnyDisabled.value,
                        onDrop: () => {
                            isDragHovering.value = false;
                        },
                        onDragleave: () => {
                            isDragHovering.value = false;
                        },
                        onDragenter: () => {
                            isDragHovering.value = true;
                        },
                    }}
                    {...(hasFileInput ? { htmlFor: inputId.value } : { type: 'button', ...disabledStateProps.value })}
                />
            );
        };
    },
    {
        name: 'LumxUploader',
        inheritAttrs: false,
        props: keysOf<UploaderProps>()(
            'class',
            'theme',
            'aspectRatio',
            'icon',
            'label',
            'size',
            'variant',
            'isDisabled',
            'disabled',
            'aria-disabled',
            'fileInputProps',
        ),
        emits: emitSchema,
    },
);

export default Uploader;
