// packages/lumx-core/src/js/components/Uploader/index.tsx
import { AspectRatio, Size } from '../../constants';
import type {
    HasClassName,
    HasDisabled,
    LumxClassName,
    HasTheme,
    ValueOf,
    HasAriaDisabled,
    CommonRef,
} from '../../types';
import { classNames } from '../../utils';
import { Icon } from '../Icon';

/**
 * Uploader variants.
 */
export const UploaderVariant = {
    square: 'square',
    rounded: 'rounded',
    circle: 'circle',
} as const;
export type UploaderVariant = ValueOf<typeof UploaderVariant>;

/**
 * Uploader sizes.
 */
export type UploaderSize = Extract<Size, 'xl' | 'xxl'>;

/**
 * Extend native HTML input props with specialized `onChange` providing the a `File` array.
 */
interface FileInputProps extends Omit<React.ComponentProps<'input'>, 'onChange'> {
    onChange(files: File[], evt: React.ChangeEvent<HTMLInputElement>): void;
}

/**
 * Defines the props of the component.
 */
export interface UploaderProps extends HasClassName, HasDisabled, HasTheme, HasAriaDisabled {
    /** Image aspect ratio. */
    aspectRatio?: AspectRatio;
    /** Icon (SVG path). */
    icon?: string;
    /** Label text. */
    label?: string;
    /** Size variant. */
    size?: UploaderSize;
    /** Variant. */
    variant?: UploaderVariant;
    /** On click callback. */
    handleClick?: (event: any) => void;
    /** Handle file selection with a native input file. */
    fileInputProps?: FileInputProps;
    /** Forwarded ref to the root element. */
    ref?: CommonRef;
    /** Whether the component is disabled (computed from `isDisabled` and `aria-disabled`). */
    isAnyDisabled?: boolean;
    /** Id of the hidden file input (used to link the label `for` attribute). */
    inputId: string;
    /** Whether a file is currently being dragged over the input. */
    isDragHovering?: boolean;
    /** Callback fired when a dragged file leaves the drop zone. */
    handleDragLeave: () => void;
    /** Callback fired when a file is dragged over the drop zone. */
    handleDragEnter: () => void;
    /** Callback fired when the file input value changes. */
    handleChange?: (event: any) => void;
    /** Root element tag or component (e.g. `'button'` or `'label'`). */
    Component: 'button' | 'label';
}

export type UploaderPropsToOverride =
    | 'isAnyDisabled'
    | 'inputId'
    | 'isDragHovering'
    | 'handleDragLeave'
    | 'handleDragEnter'
    | 'Component';

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'Uploader';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-uploader';
export const { block, element } = classNames.bem(CLASSNAME);

/**
 * Component default props.
 */
export const DEFAULT_PROPS: Partial<UploaderProps> = {
    aspectRatio: AspectRatio.horizontal,
    size: Size.xl,
    variant: UploaderVariant.square,
};

/**
 * Uploader component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Uploader = (props: UploaderProps) => {
    const {
        aspectRatio = DEFAULT_PROPS.aspectRatio,
        className,
        label,
        icon,
        size = DEFAULT_PROPS.size,
        theme,
        variant = DEFAULT_PROPS.variant,
        isAnyDisabled,
        fileInputProps,
        inputId,
        isDragHovering,
        handleDragLeave,
        handleDragEnter,
        handleClick,
        handleChange,
        Component = 'label',
        ref,
        ...forwardedProps
    } = props;
    // Adjust to square aspect ratio when using circle variants.
    const adjustedAspectRatio = variant === UploaderVariant.circle ? AspectRatio.square : aspectRatio;

    return (
        <Component
            ref={ref as any}
            {...forwardedProps}
            onClick={handleClick}
            className={classNames.join(
                className,
                block({
                    [`aspect-ratio-${adjustedAspectRatio}`]: Boolean(adjustedAspectRatio),
                    [`size-${size}`]: Boolean(size),
                    [`theme-${theme}`]: Boolean(theme),
                    [`variant-${variant}`]: Boolean(variant),
                    'is-drag-hovering': isDragHovering,
                    'is-disabled': isAnyDisabled,
                }),
            )}
        >
            <span className={element('background')} />

            <span className={element('wrapper')}>
                {icon && Icon({ className: element('icon'), icon, size: Size.s })}

                {label && <span className={element('label')}>{label}</span>}
            </span>

            {fileInputProps && (
                <input
                    type="file"
                    id={inputId}
                    className={classNames.join(element('input'), classNames.visuallyHidden())}
                    {...fileInputProps}
                    readOnly={isAnyDisabled}
                    onChange={handleChange}
                    onDragEnter={handleDragEnter}
                    onDragLeave={handleDragLeave}
                    onDrop={handleDragLeave}
                />
            )}
        </Component>
    );
};

// packages/lumx-vue/src/components/uploader/Uploader.tsx
import { computed, defineComponent, ref, useAttrs } from 'vue';

import {
    Uploader as UploaderUI,
    UploaderVariant,
    DEFAULT_PROPS,
    CLASSNAME,
    COMPONENT_NAME,
} from '@lumx/core/js/components/Uploader';
import type { UploaderProps as UIProps, UploaderPropsToOverride } from '@lumx/core/js/components/Uploader';
import type { UploaderSize } from '@lumx/core/js/components/Uploader';

import { useTheme } from '../../composables/useTheme';
import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { useId } from '../../composables/useId';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

type VueFileInputProps = {
    /** Accepted file types. */
    accept?: string;
    /** Whether multiple files can be selected. */
    multiple?: boolean;
    /** Camera capture mode. */
    capture?: boolean | 'user' | 'environment';
    /** Native input id (generated if not provided). */
    id?: string;
};

export type UploaderProps = VueToJSXProps<UIProps, UploaderPropsToOverride> & {
    /** Handle file selection with a native input file. */
    fileInputProps?: VueFileInputProps;
};

export const emitSchema = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    change: (_files: File[], _event?: Event) => true,
};

export type { UploaderSize };
export { UploaderVariant, DEFAULT_PROPS, CLASSNAME, COMPONENT_NAME };

/**
 * Uploader component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const Uploader = defineComponent(
    (props: UploaderProps, { emit }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();
        const generatedInputId = useId();
        const inputId = computed(() => props.fileInputProps?.id || generatedInputId);
        const isDragHovering = ref(false);

        const { isAnyDisabled, disabledStateProps, otherProps } = useDisableStateProps(
            computed(() => ({ ...props, ...attrs })),
        );

        const handleClick = (event: MouseEvent) => {
            if (isAnyDisabled.value) {
                event.preventDefault();
                return;
            }
            event.stopImmediatePropagation();
            (attrs as any).onClick?.(event);
        };

        const handleChange = (event: Event) => {
            if (isAnyDisabled.value) return;
            event.stopImmediatePropagation();
            const input = event.target as HTMLInputElement;
            const files = input.files ? Array.from(input.files) : [];
            emit('change', files, event);
        };

        return () => {
            const hasFileInput = Boolean(props.fileInputProps);
            const {
                onClick: _onClick,
                fileInputProps: _fp,
                class: _class,
                theme: _theme,
                ...restProps
            } = otherProps.value as any;

            return (
                <UploaderUI
                    {...restProps}
                    className={props.class}
                    theme={props.theme || defaultTheme.value}
                    inputId={inputId.value}
                    isAnyDisabled={isAnyDisabled.value}
                    isDragHovering={isDragHovering.value}
                    handleClick={handleClick}
                    handleChange={handleChange}
                    Component={hasFileInput ? 'label' : 'button'}
                    fileInputProps={{
                        ...props.fileInputProps,
                        ...disabledStateProps.value,
                        readonly: isAnyDisabled.value,
                        onDrop: () => {
                            isDragHovering.value = false;
                        },
                        onDragleave: () => {
                            isDragHovering.value = false;
                        },
                        onDragenter: () => {
                            isDragHovering.value = true;
                        },
                    }}
                    {...(hasFileInput ? { htmlFor: inputId.value } : { type: 'button', ...disabledStateProps.value })}
                />
            );
        };
    },
    {
        name: 'LumxUploader',
        inheritAttrs: false,
        props: keysOf<UploaderProps>()(
            'class',
            'theme',
            'aspectRatio',
            'icon',
            'label',
            'size',
            'variant',
            'isDisabled',
            'disabled',
            'aria-disabled',
            'fileInputProps',
        ),
        emits: emitSchema,
    },
);

export default Uploader;
