// packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.tsx
import React, { createContext, RefObject, useContext, useEffect, useMemo, useRef } from 'react';
import { ClickAwayParameters, useClickAway } from '@lumx/react/hooks/useClickAway';

interface ContextValue {
    childrenRefs: Array<RefObject<HTMLElement>>;
    addRefs(...newChildrenRefs: Array<RefObject<HTMLElement>>): void;
}

const ClickAwayAncestorContext = createContext<ContextValue | null>(null);

interface ClickAwayProviderProps extends ClickAwayParameters {
    /**
     * (Optional) Element that should be considered as part of the parent
     */
    parentRef?: RefObject<HTMLElement>;
}

/**
 * Component combining the `useClickAway` hook with a React context to hook into the React component tree and make sure
 * we take into account both the DOM tree and the React tree to detect click away.
 *
 * @return the react component.
 */
export const ClickAwayProvider: React.FC<ClickAwayProviderProps> = ({
    children,
    callback,
    childrenRefs,
    parentRef,
}) => {
    const parentContext = useContext(ClickAwayAncestorContext);
    const currentContext = useMemo(() => {
        const context: ContextValue = {
            childrenRefs: [],
            /**
             * Add element refs to the current context and propagate to the parent context.
             */
            addRefs(...newChildrenRefs) {
                // Add element refs that should be considered as inside the click away context.
                context.childrenRefs.push(...newChildrenRefs);

                if (parentContext) {
                    // Also add then to the parent context
                    parentContext.addRefs(...newChildrenRefs);
                    if (parentRef) {
                        // The parent element is also considered as inside the parent click away context but not inside the current context
                        parentContext.addRefs(parentRef);
                    }
                }
            },
        };
        return context;
    }, [parentContext, parentRef]);

    useEffect(() => {
        const { current: currentRefs } = childrenRefs;
        if (!currentRefs) {
            return;
        }
        currentContext.addRefs(...currentRefs);
    }, [currentContext, childrenRefs]);

    useClickAway({ callback, childrenRefs: useRef(currentContext.childrenRefs) });
    return <ClickAwayAncestorContext.Provider value={currentContext}>{children}</ClickAwayAncestorContext.Provider>;
};
ClickAwayProvider.displayName = 'ClickAwayProvider';

// packages/lumx-vue/src/utils/ClickAway/ClickAwayProvider.tsx
import {
    defineComponent,
    inject,
    onBeforeUnmount,
    onMounted,
    provide,
    type InjectionKey,
    type PropType,
    type Ref,
} from 'vue';
import { setupClickAway, type ClickAwayCallback } from '@lumx/core/js/utils/ClickAway';

interface ContextValue {
    childrenRefs: HTMLElement[];
    addRefs(...newChildrenRefs: Array<Ref<HTMLElement | undefined>>): void;
}

export const CLICK_AWAY_KEY: InjectionKey<ContextValue> = Symbol('LumxClickAway');

/**
 * Component combining click away detection with Vue's provide/inject to hook into the component tree
 * and take into account both the DOM tree and the component tree to detect click away.
 */
export const ClickAwayProvider = defineComponent(
    (
        props: {
            callback: ClickAwayCallback;
            childrenRefs: Ref<Array<Ref<HTMLElement | undefined>>>;
            parentRef?: Ref<HTMLElement | undefined>;
        },
        { slots },
    ) => {
        const parentContext = inject(CLICK_AWAY_KEY, null);

        const contextChildrenRefs: HTMLElement[] = [];

        const currentContext: ContextValue = {
            childrenRefs: contextChildrenRefs,
            addRefs(...newChildrenRefs) {
                for (const newRef of newChildrenRefs) {
                    const el = newRef.value;
                    if (el) {
                        contextChildrenRefs.push(el);
                    }
                }
                if (parentContext) {
                    parentContext.addRefs(...newChildrenRefs);
                    if (props.parentRef) {
                        parentContext.addRefs(props.parentRef);
                    }
                }
            },
        };

        provide(CLICK_AWAY_KEY, currentContext);

        let teardown: (() => void) | undefined;

        onMounted(() => {
            const refs = props.childrenRefs.value;
            if (refs) {
                currentContext.addRefs(...refs);
            }

            // Setup click away using the context's collected refs directly
            teardown = setupClickAway(() => contextChildrenRefs, props.callback);
        });

        onBeforeUnmount(() => {
            teardown?.();
        });

        return () => slots.default?.();
    },
    {
        name: 'LumxClickAwayProvider',
        props: {
            callback: {
                type: [Function, Boolean, undefined] as PropType<ClickAwayCallback>,
                default: undefined,
            },
            childrenRefs: {
                type: Object as PropType<Ref<Array<Ref<HTMLElement | undefined>>>>,
                required: true,
            },
            parentRef: {
                type: Object as PropType<Ref<HTMLElement | undefined>>,
                default: undefined,
            },
        },
    },
);
