// packages/lumx-vue/src/components/chip/SelectionChipGroup.tsx
import { type ComponentPublicInstance, computed, defineComponent, ref, useAttrs, watchEffect } from 'vue';

import {
    SelectionChipGroup as UI,
    type SelectionChipGroupProps as UIProps,
} from '@lumx/core/js/components/Chip/SelectionChipGroup';
import { CLASSNAME as CHIP_CLASSNAME } from '@lumx/core/js/components/Chip';
import { setupSelectionChipGroupEvents } from '@lumx/core/js/components/Chip/setupSelectionChipGroupEvents';

import { useClassName } from '../../composables/useClassName';
import { useTheme } from '../../composables/useTheme';
import { useRovingTabIndexContainer } from '../../composables/useRovingTabIndexContainer';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { isComponentType } from '../../utils/isComponentType';
import { Icon } from '../icon';
import { Tooltip } from '../tooltip';
import { Text } from '../text';

import Chip from './Chip';
import ChipGroup from './ChipGroup';

/**
 * Props omit 'ref' (handled internally).
 * inputRef is added here for Vue (ref to an associated input element for backspace focus handling).
 */
export type SelectionChipGroupProps = VueToJSXProps<UIProps<any>> & {
    /** Ref to the associated input element (for focus restoration on backspace) */
    inputRef?: HTMLInputElement | null;
};

export const emitSchema = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    change: (_newValue?: any[]) => true,
};

/**
 * SelectionChipGroup component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const SelectionChipGroup = defineComponent(
    (props: SelectionChipGroupProps, { emit, slots }) => {
        const attrs = useAttrs();
        const className = useClassName(() => props.class);
        const defaultTheme = useTheme();
        const containerRef = ref<ComponentPublicInstance | null>(null);

        // Unwrap Vue component instance to the root DOM element
        const getContainer = (): HTMLElement | null => containerRef.value?.$el ?? containerRef.value ?? null;

        // Attach event listeners
        watchEffect((onCleanup) => {
            const cleanup = setupSelectionChipGroupEvents({
                getContainer,
                getInput: () => props.inputRef,
                onChange: (newValue) => emit('change', newValue),
                getValue: () => props.value,
                getOptionId: props.getOptionId,
            });
            onCleanup(cleanup);
        });

        const containerUnwrapped = computed(getContainer);
        useRovingTabIndexContainer({
            containerRef: containerUnwrapped,
            itemSelector: `.${CHIP_CLASSNAME}`,
            itemDisabledSelector: `.${CHIP_CLASSNAME}[aria-disabled="true"]`,
        });

        return () => {
            // Merge getChipProps and chip slot: getChipProps provides base props, slot overrides them,
            // and the core JSX template props take final priority (applied in the core component).
            const getChipProps = (option: any) => {
                const chipProps = props.getChipProps?.(option) || {};
                let slotProps: Record<string, any> = {};
                if (slots.chip) {
                    const vnodes = slots.chip({ option });
                    const customChip = vnodes?.find(isComponentType(Chip));
                    slotProps = customChip?.props || {};
                    // Handle the before slot
                    const beforeSlot = (customChip?.children as any)?.before;
                    if (beforeSlot) slotProps.before = beforeSlot();
                }
                // Filter out undefined values from slotProps so they don't override chipProps
                const definedSlotProps = Object.fromEntries(
                    Object.entries(slotProps).filter(([, v]) => v !== undefined),
                );
                return { ...chipProps, ...definedSlotProps };
            };

            const { class: _class, ...restProps } = props;

            return UI(
                {
                    ...attrs,
                    ...restProps,
                    className: className.value,
                    theme: props.theme || defaultTheme.value,
                    getChipProps,
                    ref: containerRef,
                },
                { Chip, ChipGroup, Icon, Tooltip, Text },
            );
        };
    },
    {
        name: 'LumxSelectionChipGroup',
        inheritAttrs: false,
        props: keysOf<SelectionChipGroupProps>()(
            'getChipProps',
            'getOptionId',
            'getOptionName',
            'value',
            'label',
            'chipRemoveLabel',
            'isDisabled',
            'theme',
            'class',
            'inputRef',
        ),
        emits: emitSchema,
    },
);

export default SelectionChipGroup;

// packages/lumx-react/src/components/chip/SelectionChipGroup.tsx
import React from 'react';

import { CLASSNAME as CHIP_CLASSNAME } from '@lumx/core/js/components/Chip';
import {
    SelectionChipGroup as UI,
    CLASSNAME,
    COMPONENT_NAME,
    type SelectionChipGroupProps as UIProps,
} from '@lumx/core/js/components/Chip/SelectionChipGroup';
import { setupSelectionChipGroupEvents } from '@lumx/core/js/components/Chip/setupSelectionChipGroupEvents';
import { GenericProps } from '@lumx/react/utils/type';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';

import { Chip } from './Chip';
import { ChipGroup } from './ChipGroup';
import { Icon } from '../icon';
import { Text } from '../text';
import { Tooltip } from '../tooltip';
import { isComponentType } from '../../utils/type/isComponentType';
import { useRovingTabIndexContainer } from '../../hooks/useRovingTabIndexContainer';

/**
 * Defines the props of the component.
 */
export interface SelectionChipGroupProps<O> extends GenericProps, ReactToJSX<UIProps<O>> {
    /** Callback on option array selected */
    onChange?(newValue?: O[]): void;
    /** Input ref to restore focus */
    inputRef?: React.RefObject<HTMLInputElement>;
    /** Customize how chips should render (return a <Chip> element to override chip props) */
    renderChip?: (option: O) => React.ReactNode;
}

/**
 * SelectionChipGroup component.
 *
 * @param  props Component props.
 * @return React element.
 */
export const SelectionChipGroup = <O,>({
    onChange,
    value,
    getOptionId,
    getOptionName,
    inputRef,
    renderChip,
    getChipProps: getChipPropsProp,
    theme,
    isDisabled,
    label,
    chipRemoveLabel,
    ...forwardedProps
}: SelectionChipGroupProps<O>) => {
    const containerRef = React.useRef<HTMLDivElement>(null);

    // Store latest values in refs so the event handlers always access current state.
    const valueRef = React.useRef(value);
    valueRef.current = value;
    const onChangeRef = React.useRef(onChange);
    onChangeRef.current = onChange;

    // Attach event listeners
    React.useEffect(() => {
        return setupSelectionChipGroupEvents({
            getContainer: () => containerRef.current,
            getInput: () => inputRef?.current,
            onChange: (newValue) => onChangeRef.current?.(newValue),
            getValue: () => valueRef.current,
            getOptionId,
        });
    }, [inputRef, getOptionId]);

    useRovingTabIndexContainer({
        containerRef,
        itemSelector: `.${CHIP_CLASSNAME}`,
        itemDisabledSelector: `.${CHIP_CLASSNAME}[aria-disabled="true"]`,
    });

    // Merge getChipProps and renderChip: getChipProps provides base props, renderChip overrides them,
    // and the core JSX template props take final priority (applied in the core component).
    const getChipProps = (option: O) => {
        const chipProps = getChipPropsProp?.(option) || {};
        let renderChipProps: Record<string, any> = {};
        if (renderChip) {
            const customChip = renderChip(option);
            if (isComponentType(Chip)(customChip)) {
                renderChipProps = customChip.props || {};
            }
        }
        // Filter out undefined values from renderChipProps so they don't override chipProps
        const definedRenderChipProps = Object.fromEntries(
            Object.entries(renderChipProps).filter(([, v]) => v !== undefined),
        );
        return { ...chipProps, ...definedRenderChipProps };
    };

    return UI(
        {
            ...forwardedProps,
            value,
            getOptionId,
            getOptionName,
            theme,
            isDisabled,
            label,
            chipRemoveLabel,
            getChipProps,
            ref: containerRef,
        },
        { Chip, ChipGroup, Icon, Text, Tooltip },
    );
};
SelectionChipGroup.displayName = COMPONENT_NAME;
SelectionChipGroup.className = CLASSNAME;
