// packages/lumx-vue/src/components/popover/Popover.tsx
import { computed, defineComponent, type Ref, unref, toRef } from 'vue';

import {
    Popover as PopoverUI,
    type PopoverProps as CorePopoverProps,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Popover';
import { type Placement, POPOVER_ZINDEX } from '@lumx/core/js/components/Popover/constants';
import type { PopoverSizes } from '@lumx/core/js/components/Popover/types';
import type { JSXElement } from '@lumx/core/js/types';

import { ThemeProvider } from '../../utils/theme/ThemeProvider';
import { useCallbackOnEscape } from '../../composables/useCallbackOnEscape';
import { useClassName } from '../../composables/useClassName';
import { Portal } from '../../utils/Portal/Portal';
import { ClickAwayProvider } from '../../utils/ClickAway/ClickAwayProvider';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';

import { usePopoverStyle } from './usePopoverStyle';
import { useFocusTrap } from '../../composables/useFocusTrap';
import { useFocus } from '../../composables/useFocus';
import { useRestoreFocusOnClose } from '../../composables/useRestoreFocusOnClose';

/**
 * Vue Popover props derived from core PopoverProps.
 * Omits framework-specific props and narrows element ref types to raw HTMLElement.
 * `isOpen` is made optional (defaults to false at runtime via keysOf).
 */
export type PopoverProps = VueToJSXProps<
    CorePopoverProps,
    'anchorRef' | 'boundaryRef' | 'focusElement' | 'parentElement' | 'focusTrapZoneElement' | 'isOpen'
> &
    PopoverSizes & {
        /** Reference to the DOM element used to set the position of the popover. Accepts a Vue Ref for reactive positioning. */
        anchorRef?: Ref<HTMLElement | undefined> | HTMLElement;
        /** Element which will act as boundary when opening the popover. Accepts a Vue Ref for reactive positioning. */
        boundaryRef?: Ref<HTMLElement | undefined> | HTMLElement;
        /** Element to focus when opening the popover. */
        focusElement?: HTMLElement;
        /** Whether the popover is open or not. */
        isOpen?: boolean;
        /** Reference to the parent element that triggered the popover. */
        parentElement?: HTMLElement;
        /** The element in which the focus trap should be set. Default to popover. */
        focusTrapZoneElement?: HTMLElement;
    };

export const emitSchema = {
    close: () => true,
};

const Popover = defineComponent(
    (props: PopoverProps, { emit, slots, attrs }) => {
        const className = useClassName(() => props.class);
        // Unwrap anchorRef (accepts both Vue Ref and raw HTMLElement) — reused across composables
        const anchorRef = computed(() => unref(props.anchorRef));
        // Reused across useFocus and useFocusTrap
        const focusElementRef = toRef(props, 'focusElement');

        // Positioning
        const { styles, isPositioned, position, floatingRef, arrowRef } = usePopoverStyle({
            anchorRef: anchorRef as Ref<HTMLElement | undefined>,
            boundaryRef: computed(() => unref(props.boundaryRef)) as Ref<HTMLElement | undefined>,
            offset: toRef(props, 'offset'),
            hasArrow: toRef(props, 'hasArrow'),
            fitToAnchorWidth: toRef(props, 'fitToAnchorWidth'),
            fitWithinViewportHeight: toRef(props, 'fitWithinViewportHeight'),
            width: toRef(props, 'width'),
            minWidth: toRef(props, 'minWidth'),
            maxWidth: toRef(props, 'maxWidth'),
            height: toRef(props, 'height'),
            minHeight: toRef(props, 'minHeight'),
            maxHeight: toRef(props, 'maxHeight'),
            placement: computed(() => props.placement || (DEFAULT_PROPS.placement as Placement)),
            style: computed(() => undefined),
            zIndex: computed(() => props.zIndex ?? POPOVER_ZINDEX),
        });

        // Focus restore on close
        useRestoreFocusOnClose(
            computed(() => props.focusAnchorOnClose ?? true),
            anchorRef as Ref<HTMLElement | undefined>,
            computed(() => props.parentElement) as Ref<HTMLElement | undefined>,
            floatingRef,
            computed(() => Boolean(props.isOpen)),
        );

        // Close handler using emit
        const handleClose = () => {
            emit('close');
        };

        // Escape key handling
        useCallbackOnEscape(
            computed(() => handleClose),
            computed(() => Boolean(props.isOpen && props.closeOnEscape)),
        );

        // Focus management
        const shouldFocus = computed(() => !props.withFocusTrap && Boolean(props.isOpen) && isPositioned.value);
        useFocus(focusElementRef, shouldFocus);

        // Focus trap
        const focusZoneElement = computed(() => {
            if (!props.withFocusTrap || !props.isOpen) return false as const;
            return props.focusTrapZoneElement || floatingRef.value || false;
        });
        useFocusTrap(focusZoneElement, focusElementRef);

        // Click-away refs: popover ref + anchor ref
        const clickAwayRefs = computed(() => [floatingRef, anchorRef]) as Ref<Array<Ref<HTMLElement | undefined>>>;

        return () =>
            PopoverUI(
                {
                    ...attrs,
                    as: props.as,
                    closeMode: props.closeMode,
                    elevation: props.elevation,
                    hasArrow: props.hasArrow,
                    usePortal: props.usePortal,
                    children: slots.default?.() as JSXElement,
                    className: className.value,
                    isOpen: Boolean(props.isOpen),
                    position: position.value,
                    popoverStyle: styles.popover.value,
                    arrowStyle: styles.arrow.value,
                    theme: props.theme,
                    ref: floatingRef,
                    arrowRef,
                    clickAwayCallback: props.closeOnClickAway ? handleClose : undefined,
                    clickAwayRefs,
                },
                { Portal, ClickAwayProvider, ThemeProvider },
            );
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<PopoverProps>()(
            'anchorRef',
            'as',
            'boundaryRef',
            'closeMode',
            'closeOnClickAway',
            'closeOnEscape',
            'elevation',
            'fitToAnchorWidth',
            'fitWithinViewportHeight',
            'focusElement',
            'width',
            'minWidth',
            'maxWidth',
            'height',
            'minHeight',
            'maxHeight',
            'focusAnchorOnClose',
            'hasArrow',
            'isOpen',
            'offset',
            'parentElement',
            'placement',
            'usePortal',
            'focusTrapZoneElement',
            'zIndex',
            'withFocusTrap',
            'theme',
            'class',
        ),
        emits: emitSchema,
    },
);

export default Popover;

// packages/lumx-react/src/components/popover/Popover.tsx
import React, { ReactNode, RefObject, useRef } from 'react';
import { createPortal } from 'react-dom';

import classNames from 'classnames';

import { useCallbackOnEscape } from '@lumx/react/hooks/useCallbackOnEscape';
import { useFocus } from '@lumx/react/hooks/useFocus';
import { ClickAwayProvider } from '@lumx/react/utils/ClickAwayProvider';
import { DOCUMENT, VISUALLY_HIDDEN } from '@lumx/react/constants';
import { Comp, GenericProps, HasTheme } from '@lumx/react/utils/type';
import { getRootClassName, handleBasicClasses } from '@lumx/react/utils/className';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { useFocusTrap } from '@lumx/react/hooks/useFocusTrap';
import { skipRender } from '@lumx/react/utils/react/skipRender';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

import { ThemeProvider } from '@lumx/react/utils/theme/ThemeContext';
import { useRestoreFocusOnClose } from './useRestoreFocusOnClose';
import { usePopoverStyle } from './usePopoverStyle';
import { Elevation, FitAnchorWidth, Offset, Placement, POPOVER_ZINDEX } from './constants';

/**
 * Defines the props of the component.
 */
export interface PopoverProps extends GenericProps, HasTheme {
    /** Reference to the DOM element used to set the position of the popover. */
    anchorRef: React.RefObject<HTMLElement>;
    /** Customize the root element. (Must accept ref forwarding and props forwarding!). */
    as?: React.ElementType;
    /** Element which will act as boundary when opening the popover. */
    boundaryRef?: RefObject<HTMLElement>;
    /** Content. */
    children: ReactNode;
    /** Whether a click anywhere out of the popover would close it. */
    closeOnClickAway?: boolean;
    /** Whether an escape key press would close the popover. */
    closeOnEscape?: boolean;
    /** Shadow elevation. */
    elevation?: Elevation;
    /**
     * Manage popover width:
     *   - `maxWidth`: popover not bigger than anchor
     *   - `minWidth` or `true`: popover not smaller than anchor
     *   - `width`: popover equal to the anchor.
     */
    fitToAnchorWidth?: FitAnchorWidth | boolean;
    /** Shrink popover if even after flipping there is not enough space. */
    fitWithinViewportHeight?: boolean;
    /** Element to focus when opening the popover. */
    focusElement?: RefObject<HTMLElement>;
    /** Whether the focus should go back on the anchor when popover closes and focus is within. */
    focusAnchorOnClose?: boolean;
    /** Whether we put an arrow or not. */
    hasArrow?: boolean;
    /** Whether the popover is open or not. */
    isOpen: boolean;
    /** Offset placement relative to anchor. */
    offset?: Offset;
    /** Reference to the parent element that triggered the popover (will get back focus on close or else fallback on the anchor element). */
    parentElement?: RefObject<HTMLElement>;
    /** Placement relative to anchor. */
    placement?: Placement;
    /** Whether the popover should be rendered into a DOM node that exists outside the DOM hierarchy of the parent component. */
    usePortal?: boolean;
    /** The element in which the focus trap should be set. Default to popover. */
    focusTrapZoneElement?: RefObject<HTMLElement>;
    /** Z-axis position. */
    zIndex?: number;
    /** On close callback (on click away or Escape pressed). */
    onClose?(): void;
    /** Whether the popover should trap the focus within itself. Default to false. */
    withFocusTrap?: boolean;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'Popover';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * Component default props.
 */
const DEFAULT_PROPS: Partial<PopoverProps> = {
    elevation: 3,
    placement: Placement.AUTO,
    focusAnchorOnClose: true,
    usePortal: true,
    zIndex: POPOVER_ZINDEX,
};

/** Method to render the popover inside a portal if usePortal is true */
const renderPopover = (children: ReactNode, usePortal?: boolean): any => {
    return usePortal ? createPortal(children, document.body) : children;
};

// Inner component (must be wrapped before export)
const _InnerPopover = forwardRef<PopoverProps, HTMLDivElement>((props, ref) => {
    const {
        anchorRef,
        as: Component = 'div',
        children,
        className,
        closeOnClickAway,
        closeOnEscape,
        elevation,
        focusElement,
        hasArrow,
        isOpen,
        onClose,
        parentElement,
        usePortal,
        focusAnchorOnClose,
        withFocusTrap,
        boundaryRef,
        fitToAnchorWidth,
        fitWithinViewportHeight,
        focusTrapZoneElement,
        offset,
        placement,
        style,
        theme,
        zIndex,
        ...forwardedProps
    } = props;
    const popoverRef = useRef<HTMLDivElement>(null);

    const { styles, attributes, isPositioned, position, setArrowElement, setPopperElement, popperElement } =
        usePopoverStyle({
            offset,
            hasArrow,
            fitToAnchorWidth,
            fitWithinViewportHeight,
            boundaryRef,
            anchorRef,
            placement,
            style,
            zIndex,
        });

    const unmountSentinel = useRestoreFocusOnClose({ focusAnchorOnClose, anchorRef, parentElement }, popperElement);
    const focusZoneElement = focusTrapZoneElement?.current || popoverRef?.current;

    useCallbackOnEscape(onClose, isOpen && closeOnEscape);

    /** Only set focus within if the focus trap is disabled as they interfere with one another. */
    useFocus(focusElement?.current, !withFocusTrap && isOpen && isPositioned);
    useFocusTrap(withFocusTrap && isOpen && focusZoneElement, focusElement?.current);

    const clickAwayRefs = useRef([popoverRef, anchorRef]);
    const mergedRefs = useMergeRefs<HTMLDivElement>(setPopperElement, ref, popoverRef);

    return isOpen
        ? renderPopover(
              <Component
                  {...forwardedProps}
                  ref={mergedRefs}
                  className={classNames(
                      className,
                      handleBasicClasses({
                          prefix: CLASSNAME,
                          theme,
                          elevation: Math.min(elevation || 0, 5),
                          position,
                      }),
                      // Do not show the popover while it's not properly placed
                      !styles.popover?.transform ? VISUALLY_HIDDEN : undefined,
                  )}
                  style={styles.popover}
                  {...attributes.popper}
              >
                  {unmountSentinel}
                  <ClickAwayProvider callback={closeOnClickAway && onClose} childrenRefs={clickAwayRefs}>
                      {hasArrow && (
                          <div ref={setArrowElement} className={`${CLASSNAME}__arrow`} style={styles.arrow}>
                              <svg viewBox="0 0 14 14" aria-hidden>
                                  <path d="M8 3.49C7.62 2.82 6.66 2.82 6.27 3.48L.04 14 14.04 14 8 3.49Z" />
                              </svg>
                          </div>
                      )}
                      <ThemeProvider value={theme}>{children}</ThemeProvider>
                  </ClickAwayProvider>
              </Component>,
              usePortal,
          )
        : null;
});
_InnerPopover.displayName = COMPONENT_NAME;

/**
 * Popover component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Popover: Comp<PopoverProps, HTMLDivElement> = skipRender(
    // Skip render in SSR
    () => Boolean(DOCUMENT),
    _InnerPopover,
);
Popover.displayName = COMPONENT_NAME;
Popover.className = CLASSNAME;
Popover.defaultProps = DEFAULT_PROPS;
