// packages/site-demo/content/product/components/chip/vue/filter.vue
<template>
    <Chip
        :theme="theme"
        :is-selected="isSelected"
        @click="onClick"
        @after-click="onAfterClick"
    >
        <template #after>
            <Icon v-if="isSelected" :icon="mdiCloseCircle" size="xs" />
            <Icon v-else :icon="mdiMenuDown" size="xs" />
        </template>
        Filter
    </Chip>

    <Chip
        :theme="theme"
        :is-selected="isSelected"
        @click="onClick"
        @after-click="onAfterClick"
    >
        <template #before>
            <Icon :icon="mdiFilterVariant" size="xs" />
        </template>
        <template #after>
            <Icon v-if="isSelected" :icon="mdiCloseCircle" size="xs" />
            <Icon v-else :icon="mdiMenuDown" size="xs" />
        </template>
        Filter rich
    </Chip>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { mdiCloseCircle, mdiFilterVariant, mdiMenuDown } from '@lumx/icons';
import { Chip, Icon, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const isSelected = ref(false);
const onClick = () => {
    if (!isSelected.value) {
        isSelected.value = true;
    }
};
const onAfterClick = () => {
    isSelected.value = !isSelected.value;
};
</script>

// packages/site-demo/content/product/components/chip/react/filter.tsx
import { mdiCloseCircle, mdiFilterVariant, mdiMenuDown } from '@lumx/icons';
import { Chip, Icon, Size } from '@lumx/react';
import React, { useState } from 'react';

export const App = ({ theme }: any) => {
    const [isSelected, setSelected] = useState(false);
    const onClick = () => !isSelected && setSelected(true);
    const onAfterClick = () => setSelected(!isSelected);

    return (
        <>
            <Chip
                theme={theme}
                after={<Icon icon={isSelected ? mdiCloseCircle : mdiMenuDown} size={Size.xs} />}
                isSelected={isSelected}
                onClick={onClick}
                onAfterClick={onAfterClick}
            >
                Filter
            </Chip>

            <Chip
                theme={theme}
                before={<Icon icon={mdiFilterVariant} size={Size.xs} />}
                after={<Icon icon={isSelected ? mdiCloseCircle : mdiMenuDown} size={Size.xs} />}
                isSelected={isSelected}
                onClick={onClick}
                onAfterClick={onAfterClick}
            >
                Filter rich
            </Chip>
        </>
    );
};
