// packages/lumx-vue/src/stories/utils/CustomLink.vue
<template>
    <a ref="linkRef" :href="to" data-custom-link v-bind="$attrs">
        <slot />
    </a>
</template>

<script setup lang="ts">
import { ref } from 'vue';

/**
 * Example custom link that can be used in linkAs props.
 */
defineProps<{
    to?: string;
}>();

defineOptions({
    inheritAttrs: false,
});

const linkRef = ref<HTMLAnchorElement>();

defineExpose({
    linkRef,
});
</script>

// packages/lumx-react/src/stories/utils/CustomLink.tsx
import React from 'react';

/**
 * Example custom link that can be used in linkAs props.
 */
export const CustomLink = React.forwardRef<HTMLAnchorElement, { to: string; children?: React.ReactNode }>(
    ({ to = '#', children, ...props }, ref) => (
        <a ref={ref} href={to} data-custom-link {...props}>
            {children}
        </a>
    ),
);
CustomLink.displayName = 'CustomLink';
