// packages/site-demo/content/product/components/skeleton/react/animation-and-style.tsx
import { GenericBlock, SkeletonCircle, SkeletonTypography, type Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => (
    <GenericBlock orientation="horizontal" gap="big" style={{ width: 200 }}>
        <GenericBlock.Figure>
            <SkeletonCircle theme={theme} size="m" />
        </GenericBlock.Figure>

        <GenericBlock.Content>
            <SkeletonTypography theme={theme} typography="body1" />
            <SkeletonTypography theme={theme} typography="caption" width="60%" />
        </GenericBlock.Content>
    </GenericBlock>
);

// packages/site-demo/content/product/components/skeleton/vue/animation-and-style.vue
<template>
    <FlexBox orientation="horizontal" gap="big" :style="{ width: '200px' }">
        <SkeletonCircle :theme="theme" size="m" style="flex-shrink: 0" />

        <div :style="{ width: '100%' }">
            <SkeletonTypography :theme="theme" typography="body1" />
            <SkeletonTypography :theme="theme" typography="caption" width="60%" />
        </div>
    </FlexBox>
</template>

<script setup lang="ts">
import { FlexBox, SkeletonCircle, SkeletonTypography, type Theme } from '@lumx/vue';
defineProps<{ theme?: Theme }>();
</script>
