// packages/lumx-vue/src/components/radio-button/RadioButton.tsx
import { computed, defineComponent, useAttrs } from 'vue';

import {
    RadioButton as RadioButtonUI,
    type RadioButtonProps as UIProps,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/RadioButton';

import { useTheme } from '../../composables/useTheme';
import { useClassName } from '../../composables/useClassName';
import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useId } from '../../composables/useId';

export type RadioButtonProps = VueToJSXProps<UIProps, 'inputId' | 'inputRef'>;

export const emitSchema = {
    change: (value?: string, name?: string, event?: Event) => event instanceof Event,
};

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * RadioButton component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const RadioButton = defineComponent(
    (props: RadioButtonProps, { emit }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();
        const className = useClassName(() => props.class);
        const generatedInputId = useId();
        const inputId = computed(() => props.id || generatedInputId);

        const { isAnyDisabled, disabledStateProps, otherProps } = useDisableStateProps(
            computed(() => ({ ...props, ...attrs })),
        );

        const handleChange = (value?: string, name?: string, event?: any) => {
            if (isAnyDisabled.value) {
                return;
            }

            emit('change', value, name, event);
        };

        return () => {
            return (
                <RadioButtonUI
                    {...otherProps.value}
                    className={className.value}
                    theme={props.theme || defaultTheme.value}
                    inputId={inputId.value}
                    isDisabled={isAnyDisabled.value}
                    handleChange={handleChange}
                    label={props.label}
                    inputProps={{
                        ...props.inputProps,
                        ...disabledStateProps.value,
                        readOnly: disabledStateProps.value['aria-disabled'],
                    }}
                />
            );
        };
    },
    {
        name: 'RadioButton',
        inheritAttrs: false,
        // Redefine properties so that they come in as `props` on the `defineComponent` function
        props: keysOf<RadioButtonProps>()(
            'checked',
            'class',
            'disabled',
            'helper',
            'id',
            'inputProps',
            'isChecked',
            'isDisabled',
            'label',
            'name',
            'theme',
            'value',
            'aria-disabled',
        ),
        emits: emitSchema,
    },
);

export default RadioButton;

// packages/lumx-core/src/js/components/RadioButton/index.tsx
import type {
    JSXElement,
    LumxClassName,
    HasTheme,
    HasAriaDisabled,
    HasDisabled,
    HasClassName,
    HasChecked,
    CommonRef,
} from '../../types';
import { classNames } from '../../utils';
import { InputLabel } from '../InputLabel';
import { InputHelper } from '../InputHelper';

/**
 * Defines the props of the component.
 */
export interface RadioButtonProps extends HasTheme, HasClassName, HasAriaDisabled, HasDisabled, HasChecked {
    /** Helper text. */
    helper?: string;
    /** Native input id property. */
    id?: string;
    /** Label content. */
    label?: JSXElement;
    /** Native input name property. */
    name?: string;
    /** Native input value property. */
    value?: string;
    /** optional props for input */
    inputProps?: Record<string, any>;
    /** Native input ref. */
    inputRef?: CommonRef;
    /** Native input id. */
    inputId: string;
    /** On change callback. */
    onChange?(value?: string, name?: string, event?: any): void;
    /** reference to the root element */
    ref?: CommonRef;
}

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'RadioButton';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-radio-button';
const { block, element } = classNames.bem(CLASSNAME);

/**
 * Component default props.
 */
export const DEFAULT_PROPS: Partial<RadioButtonProps> = {};

/**
 * RadioButton component.
 *
 * @param  props Component props.
 * @return JSX element.
 */
export const RadioButton = (props: RadioButtonProps) => {
    const {
        checked,
        className,
        helper,
        id,
        inputRef,
        isChecked = checked,
        label,
        name,
        ref,
        onChange,
        theme,
        value,
        inputProps = {},
        isDisabled,
        inputId,
        ...forwardedProps
    } = props;

    const handleChange = (event: any) => {
        if (onChange) {
            onChange(value, name, event);
        }
    };

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames.join(
                className,
                block({
                    'is-checked': isChecked,
                    'is-disabled': isDisabled,
                    'is-unchecked': !isChecked,
                    [`theme-${theme}`]: Boolean(theme),
                }),
            )}
        >
            <div className={element('input-wrapper')}>
                <input
                    ref={inputRef}
                    className={element('input-native')}
                    id={inputId}
                    type="radio"
                    name={name}
                    value={value}
                    checked={isChecked}
                    onChange={handleChange}
                    aria-describedby={helper ? `${inputId}-helper` : undefined}
                    {...(inputProps?.readOnly ? { readOnly: inputProps.readOnly } : {})}
                    {...inputProps}
                />

                <div className={element('input-placeholder')}>
                    <div className={element('input-background')} />
                    <div className={element('input-indicator')} />
                </div>
            </div>

            <div className={element('content')}>
                {label && InputLabel({ htmlFor: inputId, className: element('label'), theme, children: label })}
                {helper &&
                    InputHelper({ id: `${inputId}-helper`, className: element('helper'), theme, children: helper })}
            </div>
        </div>
    );
};
