// packages/lumx-vue/src/components/badge/BadgeWrapper.tsx
import { defineComponent, useAttrs } from 'vue';
import {
    BadgeWrapper as BadgeWrapperUI,
    type BadgeWrapperProps as UIProps,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Badge/BadgeWrapper';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import type { JSXElement } from '@lumx/core/js/types';

export type BadgeWrapperProps = VueToJSXProps<UIProps>;

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

const BadgeWrapper = defineComponent(
    (props: BadgeWrapperProps, { slots }) => {
        const attrs = useAttrs();

        return () => {
            return (
                <BadgeWrapperUI
                    {...props}
                    {...attrs}
                    className={props.class}
                    badge={(props.badge || slots.badge?.()) as JSXElement}
                    children={slots.default?.() as JSXElement}
                />
            );
        };
    },
    {
        name: 'LumxBadgeWrapper',
        inheritAttrs: false,
        props: keysOf<BadgeWrapperProps>()('badge', 'class'),
    },
);

export default BadgeWrapper;

// packages/lumx-core/src/js/components/Badge/BadgeWrapper.tsx
import type { CommonRef, HasClassName, JSXElement, LumxClassName } from '../../types';
import { classNames } from '../../utils';

export interface BadgeWrapperProps extends HasClassName {
    /** Badge element to display */
    badge?: JSXElement;
    /** Content to wrap with badge */
    children?: JSXElement;
    /** Ref forwarding */
    ref?: CommonRef;
}

export const COMPONENT_NAME = 'BadgeWrapper';
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-badge-wrapper';
export const DEFAULT_PROPS: Partial<BadgeWrapperProps> = {};

const { block, element } = classNames.bem(CLASSNAME);

export const BadgeWrapper = (props: BadgeWrapperProps) => {
    const { badge, children, className, ref, ...forwardedProps } = props;

    return (
        <div ref={ref} {...forwardedProps} className={classNames.join(className, block())}>
            {children}
            {badge && <div className={element('badge')}>{badge}</div>}
        </div>
    );
};
