// packages/site-demo/content/product/components/generic-block/vue/figure-section.vue
<template>
    <GenericBlock as="article" orientation="vertical" vertical-align="center">
        <template #figure>
            <Avatar image="https://i.pravatar.cc/128?img=32" alt="Emmitt O Lum. Profile Photo" size="l" />
        </template>
        <template #default>
            <Placeholder name="2" :height="52" :width="104" />
        </template>
        <template #actions>
            <Placeholder name="3" :width="80" />
        </template>
    </GenericBlock>

    <GenericBlock as="article" orientation="vertical" vertical-align="center">
        <template #figure>
            <Thumbnail image="https://picsum.photos/id/24/640/480" alt="Book" variant="rounded" size="xl" />
        </template>
        <template #default>
            <Placeholder name="2" :height="52" :width="104" />
        </template>
        <template #actions>
            <Placeholder name="3" :width="80" />
        </template>
    </GenericBlock>

    <GenericBlock as="article" orientation="vertical" vertical-align="center">
        <template #figure>
            <Icon :icon="mdiPlus" size="l" :has-shape="true" />
        </template>
        <template #default>
            <Placeholder name="2" :height="52" :width="104" />
        </template>
        <template #actions>
            <Placeholder name="3" :width="80" />
        </template>
    </GenericBlock>
</template>

<script setup lang="ts">
import { mdiPlus } from '@lumx/icons';
import { Avatar, GenericBlock, Icon, Thumbnail } from '@lumx/vue';
import Placeholder from '@lumx/demo/components/content/Placeholder/index.vue';
</script>

// packages/site-demo/content/product/components/generic-block/react/figure-section.tsx
import { Avatar, GenericBlock, Icon, Thumbnail } from '@lumx/react';
import { mdiPlus } from '@lumx/icons';
import { Placeholder } from '@lumx/demo/components/content/Placeholder';

export default () => (
    <>
        <GenericBlock as="article" orientation="vertical" vAlign="center">
            <GenericBlock.Figure>
                <Avatar image="https://i.pravatar.cc/128?img=32" alt="Emmitt O Lum. Profile Photo" size="l" />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Placeholder name="2" height={52} width={104} />
            </GenericBlock.Content>
            <GenericBlock.Actions>
                <Placeholder name="3" width={80} />
            </GenericBlock.Actions>
        </GenericBlock>

        <GenericBlock as="article" orientation="vertical" vAlign="center">
            <GenericBlock.Figure>
                <Thumbnail image="https://picsum.photos/id/24/640/480" alt="Book" variant="rounded" size="xl" />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Placeholder name="2" height={52} width={104} />
            </GenericBlock.Content>
            <GenericBlock.Actions>
                <Placeholder name="3" width={80} />
            </GenericBlock.Actions>
        </GenericBlock>

        <GenericBlock as="article" orientation="vertical" vAlign="center">
            <GenericBlock.Figure>
                <Icon icon={mdiPlus} size="l" hasShape />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Placeholder name="2" height={52} width={104} />
            </GenericBlock.Content>
            <GenericBlock.Actions>
                <Placeholder name="3" width={80} />
            </GenericBlock.Actions>
        </GenericBlock>
    </>
);
