// packages/lumx-vue/src/components/menu-button/MenuList.tsx
import { defineComponent, nextTick, onMounted, onUnmounted, ref, useSlots, watch } from 'vue';

import type { JSXElement } from '@lumx/core/js/types';
import {
    MenuList as UI,
    MenuListProps as UIProps,
    CLASSNAME,
    COMPONENT_NAME,
} from '@lumx/core/js/components/Menu/MenuList';

import { useClassName } from '../../composables/useClassName';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

import { useMenuContext } from './context';
import { useMenuOpen } from './useMenuOpen';

/** MenuList props. */
export type MenuListProps = VueToJSXProps<UIProps, 'id' | 'aria-labelledby'>;

/**
 * MenuList component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const MenuList = defineComponent(
    (props: MenuListProps) => {
        const slots = useSlots();
        const { menuId, triggerId, handle } = useMenuContext();
        const [isOpen] = useMenuOpen();
        const className = useClassName(() => props.class);
        const internalRef = ref<HTMLElement | null>(null);

        onMounted(() => {
            const el = internalRef.value;
            if (!el) return;
            const cleanup = handle.registerMenu(el);
            onUnmounted(() => cleanup?.());
        });

        watch(isOpen, (open) => {
            if (open) nextTick(() => handle.flushPendingNavigation());
        });

        return () =>
            UI({
                className: className.value,
                id: menuId,
                'aria-labelledby': triggerId,
                ref: internalRef,
                children: isOpen.value ? (slots.default?.() as JSXElement) : null,
            });
    },
    {
        name: 'LumxMenuList',
        inheritAttrs: false,
        props: keysOf<MenuListProps>()('class'),
    },
);

export { CLASSNAME, COMPONENT_NAME };
export default MenuList;

// packages/lumx-react/src/components/menu-button/MenuList.tsx
import { useLayoutEffect, useRef } from 'react';

import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import {
    MenuList as UI,
    MenuListProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Menu/MenuList';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';

import { useMenuContext } from './context/MenuContext';
import { useMenuOpen } from './context/useMenuOpen';

export type MenuProps = Omit<ReactToJSX<UIProps>, 'id' | 'aria-labelledby'>;

/**
 * MenuList component.
 *
 * @param  props Component props.
 * @return React element.
 */
export const MenuList = forwardRef<MenuProps, HTMLElement>((props, ref) => {
    const { menuId, triggerId, handle } = useMenuContext();
    const internalRef = useRef<HTMLElement>(null);
    const mergedRef = useMergeRefs(ref, internalRef);
    const { children, ...forwardedProps } = props;
    const [isOpen] = useMenuOpen();

    // Register menu in context
    useLayoutEffect(() => {
        const menu = internalRef.current;
        if (!menu) return undefined;
        return handle.registerMenu(menu);
    }, [handle]);

    // Flush pending navigation (that could not be done when the menu was closed)
    useLayoutEffect(() => {
        if (isOpen) handle.flushPendingNavigation();
    }, [handle, isOpen]);

    return UI({
        ...forwardedProps,
        id: menuId,
        'aria-labelledby': triggerId,
        ref: mergedRef,
        children: isOpen ? children : null,
    });
});

MenuList.displayName = COMPONENT_NAME;
MenuList.className = CLASSNAME;
