// packages/lumx-vue/src/components/button/ButtonGroup.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    ButtonGroup as ButtonGroupUI,
    type ButtonGroupProps as UIProps,
    COMPONENT_NAME,
} from '@lumx/core/js/components/Button/ButtonGroup';
import type { JSXElement } from '@lumx/core/js/types';

import { useClassName } from '../../composables/useClassName';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';

export type ButtonGroupProps = VueToJSXProps<UIProps>;

/**
 * ButtonGroup component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const ButtonGroup = defineComponent(
    (props: ButtonGroupProps, { slots }) => {
        const attrs = useAttrs();
        const className = useClassName(() => props.class);

        return () => (
            <ButtonGroupUI
                {...props}
                {...attrs}
                className={className.value}
                children={slots.default?.() as JSXElement}
            />
        );
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        // Redefine properties so that they come in as `props` on the `defineComponent` function
        props: keysOf<ButtonGroupProps>()('class'),
    },
);

export default ButtonGroup;

// packages/lumx-core/src/js/components/Button/ButtonGroup.tsx
import { classNames } from '../../utils';
import type { LumxClassName, GenericProps, JSXElement } from '../../types';

/**
 * Defines the props of the component
 */
export interface ButtonGroupProps extends GenericProps {
    /**
     * Children
     */
    children?: JSXElement;
}

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'ButtonGroup';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-button-group';

/**
 * Component default props.
 */
export const DEFAULT_PROPS: Partial<ButtonGroupProps> = {};

/**
 * ButtonGroup component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const ButtonGroup = (props: ButtonGroupProps) => {
    const { children, className, ref, ...forwardedProps } = props;

    return (
        <div ref={ref} {...forwardedProps} className={classNames.join(className, CLASSNAME)}>
            {children}
        </div>
    );
};

ButtonGroup.displayName = COMPONENT_NAME;
ButtonGroup.className = CLASSNAME;
ButtonGroup.defaultProps = DEFAULT_PROPS;
