// packages/site-demo/content/product/components/toolbar/vue/media-picker-toolbar.vue
<template>
    <Toolbar>
        <template #default>
            <FlexBox orientation="horizontal" horizontal-align="center" gap="big">
                <Heading typography="title">Toolbar title</Heading>

                <TextField :value="value" :icon="mdiMagnify" @change="value = $event" />
            </FlexBox>
        </template>
        <template #after>
            <FlexBox orientation="horizontal" horizontal-align="center" gap="regular">
                <IconButton label="Grid" emphasis="low" :icon="mdiViewGrid" />
                <Button>Action</Button>
            </FlexBox>
        </template>
    </Toolbar>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { mdiMagnify, mdiViewGrid } from '@lumx/icons';
import { Button, FlexBox, IconButton, TextField, Toolbar, Heading } from '@lumx/vue';

const value = ref('');
</script>

// packages/site-demo/content/product/components/toolbar/react/media-picker-toolbar.tsx
import { useState } from 'react';
import { mdiMagnify, mdiViewGrid } from '@lumx/icons';
import { Button, FlexBox, IconButton, TextField, Toolbar, Heading } from '@lumx/react';

export default () => {
    const [value, setValue] = useState('');
    return (
        <Toolbar
            label={
                <FlexBox orientation="horizontal" hAlign="center" gap="big">
                    <Heading typography="title">Toolbar title</Heading>

                    <TextField value={value} onChange={setValue} icon={mdiMagnify} />
                </FlexBox>
            }
            after={
                <FlexBox orientation="horizontal" hAlign="center" gap="regular">
                    <IconButton label="Grid" emphasis="low" icon={mdiViewGrid} />

                    <Button>Action</Button>
                </FlexBox>
            }
        />
    );
};
