// packages/site-demo/content/product/components/card/react/elevation.tsx
import { Card, FlexBox, Text } from '@lumx/react';

const ELEVATIONS = [1, 2, 3, 4, 5] as const;

export default () => (
    <FlexBox orientation="horizontal" gap="big" wrap>
        {ELEVATIONS.map((elevation) => (
            <Card key={elevation} elevation={elevation}>
                <Text as="span">Elevation {elevation}</Text>
            </Card>
        ))}
    </FlexBox>
);

// packages/site-demo/content/product/components/card/vue/elevation.vue
<template>
    <FlexBox orientation="horizontal" gap="big" :wrap="true">
        <Card v-for="elevation in ELEVATIONS" :key="elevation" :elevation="elevation">
            <Text as="span">Elevation {{ elevation }}</Text>
        </Card>
    </FlexBox>
</template>

<script setup lang="ts">
import { Card, FlexBox, Text } from '@lumx/vue';

const ELEVATIONS = [1, 2, 3, 4, 5] as const;
</script>
