// packages/lumx-vue/src/components/drag-handle/DragHandle.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    DragHandle as DragHandleUI,
    type DragHandleProps as UIProps,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/DragHandle';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

export type DragHandleProps = VueToJSXProps<UIProps>;

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * DragHandle component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const DragHandle = defineComponent(
    (props: DragHandleProps) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme({ defaultTheme: undefined });

        return () => {
            return (
                <DragHandleUI {...attrs} {...props} className={props.class} theme={props.theme || defaultTheme.value} />
            );
        };
    },
    {
        name: 'LumxDragHandle',
        inheritAttrs: false,
        props: keysOf<DragHandleProps>()('class', 'theme'),
    },
);

export default DragHandle;

// packages/lumx-react/src/components/drag-handle/DragHandle.tsx
import classNames from 'classnames';

import { mdiDragVertical } from '@lumx/icons/esm/drag-vertical';
import { ColorPalette, Icon, Size, Theme } from '@lumx/react';
import { GenericProps, HasTheme } from '@lumx/react/utils/type';
import { getRootClassName, handleBasicClasses } from '@lumx/core/js/utils/className';
import { useTheme } from '@lumx/react/utils/theme/ThemeContext';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

/**
 * Defines the props of the component.
 */
export interface DragHandleProps extends GenericProps, HasTheme {}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'DragHandle';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * DragHandle component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const DragHandle = forwardRef<DragHandleProps, HTMLDivElement>((props, ref) => {
    const defaultTheme = useTheme();
    const { className, theme = defaultTheme, ...forwardedProps } = props;

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames(className, handleBasicClasses({ prefix: CLASSNAME, theme }))}
        >
            <Icon
                icon={mdiDragVertical}
                color={theme === Theme.dark ? ColorPalette.light : ColorPalette.dark}
                size={Size.xs}
            />
        </div>
    );
});
DragHandle.displayName = COMPONENT_NAME;
DragHandle.className = CLASSNAME;
