// packages/lumx-vue/src/components/skeleton/SkeletonTypography.tsx
import { computed, defineComponent, useAttrs } from 'vue';

import {
    SkeletonTypography as SkeletonTypographyUI,
    type SkeletonTypographyProps as UIProps,
    SKELETON_TYPOGRAPHY_CLASSNAME as CLASSNAME,
    SKELETON_TYPOGRAPHY_COMPONENT_NAME as COMPONENT_NAME,
    SKELETON_TYPOGRAPHY_DEFAULT_PROPS as DEFAULT_PROPS,
} from '@lumx/core/js/components/Skeleton';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

export type SkeletonTypographyProps = VueToJSXProps<UIProps>;

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * SkeletonTypography component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const SkeletonTypography = defineComponent(
    (props: SkeletonTypographyProps) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        return () => {
            return (
                <SkeletonTypographyUI
                    {...props}
                    {...attrs}
                    className={props.class}
                    theme={props.theme || defaultTheme}
                />
            );
        };
    },
    {
        name: 'LumxSkeletonTypography',
        inheritAttrs: false,
        props: keysOf<SkeletonTypographyProps>()('class', 'typography', 'width', 'color', 'theme'),
    },
);

export default SkeletonTypography;

// packages/lumx-react/src/components/skeleton/SkeletonTypography.tsx
import { CSSProperties } from 'react';

import classNames from 'classnames';

import { Theme, TypographyInterface, ColorPalette } from '@lumx/react';
import { GenericProps, HasTheme } from '@lumx/react/utils/type';
import { getRootClassName, handleBasicClasses } from '@lumx/core/js/utils/className';
import { useTheme } from '@lumx/react/utils/theme/ThemeContext';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

/**
 * Defines the props of the component.
 */
export interface SkeletonTypographyProps extends GenericProps, HasTheme {
    /** Typography variant. */
    typography: TypographyInterface;
    /** Width CSS property. */
    width?: CSSProperties['width'];
    /** The color of the skeleton. */
    color?: ColorPalette;
}

const DEFAULT_PROPS: Partial<SkeletonTypographyProps> = {};

/**
 * Component display name.
 */
const COMPONENT_NAME = 'SkeletonTypography';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * SkeletonTypography component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const SkeletonTypography = forwardRef<SkeletonTypographyProps, HTMLDivElement>((props, ref) => {
    const defaultTheme = useTheme() || Theme.light;
    const { className, theme = defaultTheme, typography, width, color, ...forwardedProps } = props;

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames(className, handleBasicClasses({ prefix: CLASSNAME, theme, typography, color }))}
            style={{ ...forwardedProps.style, width }}
        >
            <div className={`${CLASSNAME}__inner`} />
        </div>
    );
});
SkeletonTypography.displayName = COMPONENT_NAME;
SkeletonTypography.defaultProps = DEFAULT_PROPS;
SkeletonTypography.className = CLASSNAME;
