// packages/lumx-vue/src/components/skeleton/SkeletonRectangle.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    SkeletonRectangle as SkeletonRectangleUI,
    type SkeletonRectangleProps as UIProps,
    SkeletonRectangleVariant,
    SKELETON_RECTANGLE_CLASSNAME as CLASSNAME,
    SKELETON_RECTANGLE_COMPONENT_NAME as COMPONENT_NAME,
    SKELETON_RECTANGLE_DEFAULT_PROPS as DEFAULT_PROPS,
} from '@lumx/core/js/components/Skeleton';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

export type SkeletonRectangleProps = VueToJSXProps<UIProps>;

export { SkeletonRectangleVariant, CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * SkeletonRectangle component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const SkeletonRectangle = defineComponent(
    (props: SkeletonRectangleProps) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        return () => {
            return (
                <SkeletonRectangleUI
                    {...props}
                    {...attrs}
                    className={props.class}
                    theme={props.theme || defaultTheme}
                />
            );
        };
    },
    {
        name: 'SkeletonRectangle',
        inheritAttrs: false,
        props: keysOf<SkeletonRectangleProps>()('class', 'aspectRatio', 'height', 'variant', 'width', 'color', 'theme'),
    },
);

export default SkeletonRectangle;

// packages/lumx-react/src/components/skeleton/SkeletonRectangle.tsx
import React from 'react';

import classNames from 'classnames';

import { AspectRatio, GlobalSize, Theme, ColorPalette } from '@lumx/react';
import { GenericProps, HasTheme, ValueOf } from '@lumx/react/utils/type';
import { getRootClassName, handleBasicClasses } from '@lumx/react/utils/className';
import { forwardRef } from '@lumx/react/utils/forwardRef';

/**
 * Skeleton variants.
 */
export const SkeletonRectangleVariant = { squared: 'squared', rounded: 'rounded', pill: 'pill' } as const;
export type SkeletonRectangleVariant = ValueOf<typeof SkeletonRectangleVariant>;

/**
 * Defines the props of the component.
 */
export interface SkeletonRectangleProps extends GenericProps, HasTheme {
    /** Aspect ratio (use with width and not height). */
    aspectRatio?: Extract<AspectRatio, 'square' | 'horizontal' | 'vertical' | 'wide'>;
    /** Height size. */
    height?: GlobalSize;
    /** Border variant. */
    variant?: SkeletonRectangleVariant;
    /** Width size. */
    width?: GlobalSize;
    /** The color of the skeleton. */
    color?: ColorPalette;
}

const DEFAULT_PROPS: Partial<SkeletonRectangleProps> = {
    theme: Theme.light,
    variant: SkeletonRectangleVariant.squared,
};

/**
 * Component display name.
 */
const COMPONENT_NAME = 'SkeletonRectangle';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * SkeletonRectangle component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const SkeletonRectangle = forwardRef<SkeletonRectangleProps, HTMLDivElement>((props, ref) => {
    const { aspectRatio, className, height, theme, variant, width, color, ...forwardedProps } = props;

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames(
                className,
                handleBasicClasses({
                    prefix: CLASSNAME,
                    aspectRatio,
                    height: aspectRatio ? undefined : height,
                    theme,
                    variant,
                    width,
                    color,
                }),
            )}
        >
            <div className={`${CLASSNAME}__inner`} />
        </div>
    );
});
SkeletonRectangle.displayName = COMPONENT_NAME;
SkeletonRectangle.className = CLASSNAME;
SkeletonRectangle.defaultProps = DEFAULT_PROPS;
