// packages/lumx-vue/src/components/listbox/ListboxSection.tsx
import { defineComponent, reactive, ref } from 'vue';

import { useClassName } from '../../composables/useClassName';

import {
    ListboxSection as UI,
    type ListboxSectionProps as UIProps,
    type ListboxSectionPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Listbox/ListboxSection';
import type { JSXElement } from '@lumx/core/js/types';

import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useWatchDisposable } from '../../composables/useWatchDisposable';
import { ListSection } from '../list';
import { useListboxContext } from './context/ListboxContext';

export type ListboxSectionProps = VueToJSXProps<UIProps, ListboxSectionPropsToOverride | 'hidden' | 'aria-hidden'>;

/**
 * Combobox.Section component - groups Combobox.Option items under a labelled section.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ListboxSection = defineComponent(
    (props: ListboxSectionProps, { slots }) => {
        const className = useClassName(() => props.class);
        const { list } = useListboxContext();
        const sectionRef = ref<HTMLElement | null>(null);
        const sectionState = reactive({ hidden: false, 'aria-hidden': false });

        // Register with the combobox handle for section state notifications.
        // Watch both handle and sectionRef so registration fires as soon as both are available.
        useWatchDisposable([list, sectionRef], ([h, element]) => {
            if (h && element) {
                return h.registerSection(element, (state) => {
                    sectionState.hidden = state.hidden;
                    sectionState['aria-hidden'] = state['aria-hidden'];
                });
            }
        });

        const setSectionRef = (el: any) => {
            // When ListSection is used directly (no adapter), `el` is the component instance.
            // Unwrap `$el` to get the root DOM element.
            sectionRef.value = (el?.$el ?? el) as HTMLElement | null;
        };

        return () => {
            const children = slots.default?.();
            // Return null when children is empty so the section header is not rendered as an orphan
            if (!children || children.length === 0) return null;

            // Use the label slot content as JSX when no label prop is provided.
            const label = (props.label ?? slots.label?.()) as string | JSXElement | undefined;

            return UI(
                {
                    label,
                    icon: props.icon,
                    className: className.value,
                    hidden: sectionState.hidden,
                    'aria-hidden': sectionState['aria-hidden'] || undefined,
                    ref: setSectionRef as any,
                    children: children as JSXElement,
                },
                { ListSection },
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<ListboxSectionProps>()('label', 'icon', 'class'),
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ListboxSection;

// packages/lumx-react/src/components/listbox/ListboxSection.tsx
import { Children, ReactNode, useEffect, useRef, useState } from 'react';

import {
    ListboxSection as UI,
    ListboxSectionProps as UIProps,
    ListboxSectionPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Listbox/ListboxSection';
import { GenericProps } from '@lumx/core/js/types';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { ListSection } from '../list/ListSection';
import { useListboxContext } from './context/ListboxContext';

/**
 * Props for Combobox.Section component.
 */
export interface ListboxSectionProps extends GenericProps, ReactToJSX<UIProps, ListboxSectionPropsToOverride> {
    /** Section content (should be Combobox.Option elements). */
    children: ReactNode;
}

/**
 * Combobox.Section component - groups Combobox.Option items under a labelled section.
 * Delegates rendering to the core ListboxSection template, injecting the React ListSection.
 *
 * Returns null when children is empty so the section header is not rendered as an orphan.
 *
 * When filter="auto" is active, the section registers itself with the combobox handle.
 * The handle monitors registered options within this section and notifies when all
 * are filtered out. When hidden, the core template renders a bare `<li hidden>` wrapper
 * so children (options) stay mounted and registered.
 *
 * @param props Component props.
 * @param ref   Component ref.
 * @return React element.
 */
export const ListboxSection = forwardRef<ListboxSectionProps, HTMLLIElement>((props, ref) => {
    const { list } = useListboxContext();
    const internalRef = useRef<HTMLLIElement>(null);
    const mergedRef = useMergeRefs(ref, internalRef);
    const [sectionState, setSectionState] = useState({ hidden: false, 'aria-hidden': false });

    // Register with the combobox handle for section state notifications.
    useEffect(() => {
        const element = internalRef.current;
        if (!element || !list) return undefined;
        return list.registerSection(element, setSectionState);
    }, [list]);

    if (Children.count(props.children) === 0) return null;

    return UI(
        {
            ...props,
            ref: mergedRef,
            hidden: sectionState.hidden,
            'aria-hidden': sectionState['aria-hidden'] || undefined,
        },
        { ListSection },
    );
});

ListboxSection.displayName = COMPONENT_NAME;
ListboxSection.className = CLASSNAME;
