// packages/site-demo/content/product/components/generic-block/react/action-section-vertical.tsx
import { Button, Checkbox, GenericBlock } from '@lumx/react';
import { mdiClose, mdiMenuDown } from '@lumx/icons';
import { Placeholder } from '@lumx/demo/components/content/Placeholder';

export default () => (
    <>
        <GenericBlock as="article" orientation="horizontal" style={{ maxWidth: 517 }} gap="medium">
            <GenericBlock.Figure>
                <Placeholder name="1" />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Placeholder name="2" textAlign="left" width={244} />
            </GenericBlock.Content>
            <GenericBlock.Actions hAlign="center" gap="tiny">
                <Button emphasis="medium" size="m" rightIcon={mdiMenuDown}>
                    Role
                </Button>
                <Button emphasis="medium" size="m" leftIcon={mdiClose}>
                    Medium
                </Button>
            </GenericBlock.Actions>
        </GenericBlock>

        <GenericBlock as="article" orientation="horizontal" style={{ maxWidth: 424, width: '100%' }} gap="medium">
            <GenericBlock.Figure>
                <Placeholder name="1" height={64} width={64} />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Placeholder name="2" textAlign="left" height={64} width="100%" />
            </GenericBlock.Content>
            <GenericBlock.Actions hAlign="center">
                <Checkbox isDisabled inputProps={{ 'aria-label': 'Select row' }} />
            </GenericBlock.Actions>
        </GenericBlock>
    </>
);

// packages/site-demo/content/product/components/generic-block/vue/action-section-vertical.vue
<template>
    <GenericBlock
        as="article"
        orientation="horizontal"
        :style="{ maxWidth: '517px' }"
        gap="medium"
        :actions-props="{ gap: 'tiny', horizontalAlign: 'center' }"
    >
        <template #figure>
            <Placeholder name="1" />
        </template>
        <template #default>
            <Placeholder name="2" text-align="left" :width="244" />
        </template>
        <template #actions>
            <Button emphasis="medium" size="m" :right-icon="mdiMenuDown">Role</Button>
            <Button emphasis="medium" size="m" :left-icon="mdiClose">Medium</Button>
        </template>
    </GenericBlock>

    <GenericBlock
        as="article"
        orientation="horizontal"
        :style="{ maxWidth: '424px', width: '100%' }"
        gap="medium"
        :actions-props="{ horizontalAlign: 'center' }"
    >
        <template #figure>
            <Placeholder name="1" :height="64" :width="64" />
        </template>
        <template #default>
            <Placeholder name="2" text-align="left" :height="64" width="100%" />
        </template>
        <template #actions>
            <Checkbox :is-disabled="true" :input-props="{ 'aria-label': 'Select row' }" />
        </template>
    </GenericBlock>
</template>

<script setup lang="ts">
import { mdiClose, mdiMenuDown } from '@lumx/icons';
import { Button, Checkbox, GenericBlock } from '@lumx/vue';
import Placeholder from '@lumx/demo/components/content/Placeholder/index.vue';
</script>
