// packages/site-demo/content/product/components/generic-block/react/anatomy.tsx
import { GenericBlock } from '@lumx/react';
import { Placeholder } from '@lumx/demo/components/content/Placeholder';

export default () => (
    <>
        <GenericBlock orientation="vertical" vAlign="center">
            <GenericBlock.Figure>
                <Placeholder name="1" height={64} width={64} />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Placeholder name="2" height={52} width={104} />
            </GenericBlock.Content>
            <GenericBlock.Actions>
                <Placeholder name="3" width={80} />
            </GenericBlock.Actions>
        </GenericBlock>

        <GenericBlock orientation="horizontal">
            <GenericBlock.Figure>
                <Placeholder name="1" />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Placeholder name="2" width={122} />
            </GenericBlock.Content>
            <GenericBlock.Actions>
                <Placeholder name="3" width={80} textAlign="right" />
            </GenericBlock.Actions>
        </GenericBlock>
    </>
);

// packages/site-demo/content/product/components/generic-block/vue/anatomy.vue
<template>
    <GenericBlock orientation="vertical" vertical-align="center">
        <template #figure>
            <Placeholder name="1" :height="64" :width="64" />
        </template>
        <template #default>
            <Placeholder name="2" :height="52" :width="104" />
        </template>
        <template #actions>
            <Placeholder name="3" :width="80" />
        </template>
    </GenericBlock>

    <GenericBlock orientation="horizontal">
        <template #figure>
            <Placeholder name="1" />
        </template>
        <template #default>
            <Placeholder name="2" :width="122" />
        </template>
        <template #actions>
            <Placeholder name="3" :width="80" text-align="right" />
        </template>
    </GenericBlock>
</template>

<script setup lang="ts">
import { GenericBlock } from '@lumx/vue';
import Placeholder from '@lumx/demo/components/content/Placeholder/index.vue';
</script>
