// packages/site-demo/content/product/components/generic-block/react/content-section-horizontal.tsx
import { classNames } from '@lumx/core/js/utils';
import { GenericBlock, Heading, Text, UserBlock } from '@lumx/react';
import { Placeholder } from '@lumx/demo/components/content/Placeholder';

export default () => (
    <>
        <GenericBlock as="article" orientation="vertical" vAlign="center" gap="big" style={{ maxWidth: 216 }}>
            <GenericBlock.Figure>
                <Placeholder name="2" height={154} width={216} />
            </GenericBlock.Figure>
            <GenericBlock.Content className={classNames.padding('horizontal', 'big')} vAlign="left" gap="tiny">
                <UserBlock name="Emmitt O. Lum" avatarProps={{ image: 'https://i.pravatar.cc/128?img=32' }} size="s" />
                <Heading as="h2" typography="subtitle2">
                    Fiscal Year Results and Conference
                </Heading>
                <Text as="p" typography="body1" color="dark-L2">
                    Our company will release its Fiscal Year Results next…
                </Text>
            </GenericBlock.Content>
        </GenericBlock>

        <GenericBlock as="article" orientation="vertical" vAlign="center" style={{ maxWidth: 184 }}>
            <GenericBlock.Figure>
                <Placeholder name="1" height={64} width={64} />
            </GenericBlock.Figure>
            <GenericBlock.Content>
                <Heading as="h2" typography="subtitle2">
                    Slack
                </Heading>
                <Text as="p" typography="body1" color="dark-L2">
                    A communication platform including chat rooms…
                </Text>
            </GenericBlock.Content>
            <GenericBlock.Actions>
                <Placeholder name="3" width={80} />
            </GenericBlock.Actions>
        </GenericBlock>
    </>
);

// packages/site-demo/content/product/components/generic-block/vue/content-section-horizontal.vue
<template>
    <GenericBlock
        as="article"
        orientation="vertical"
        vertical-align="center"
        gap="big"
        :style="{ maxWidth: '216px' }"
        :content-props="{ verticalAlign: 'left', gap: 'tiny', class: classNames.padding('horizontal', 'big') }"
    >
        <template #figure>
            <Placeholder name="2" :height="154" :width="216" />
        </template>
        <template #default>
            <FlexBox orientation="horizontal" horizontal-align="center" gap="regular">
                <Avatar image="https://i.pravatar.cc/128?img=32" alt="Emmitt O. Lum" size="s" />
                <Text as="span" typography="subtitle1">Emmitt O. Lum</Text>
            </FlexBox>
            <Heading as="h2" typography="subtitle2">Fiscal Year Results and Conference</Heading>
            <Text as="p" typography="body1" color="dark-L2">
                Our company will release its Fiscal Year Results next…
            </Text>
        </template>
    </GenericBlock>

    <GenericBlock as="article" orientation="vertical" vertical-align="center" :style="{ maxWidth: '184px' }">
        <template #figure>
            <Placeholder name="1" :height="64" :width="64" />
        </template>
        <template #default>
            <Heading as="h2" typography="subtitle2">Slack</Heading>
            <Text as="p" typography="body1" color="dark-L2">A communication platform including chat rooms…</Text>
        </template>
        <template #actions>
            <Placeholder name="3" :width="80" />
        </template>
    </GenericBlock>
</template>

<script setup lang="ts">
import { classNames } from '@lumx/core/js/utils';
import { Avatar, FlexBox, GenericBlock, Heading, Text } from '@lumx/vue';
import Placeholder from '@lumx/demo/components/content/Placeholder/index.vue';
</script>
