// packages/lumx-react/src/components/input/RawInputTextarea.tsx
import React, { SyntheticEvent, useRef } from 'react';

import classNames from 'classnames';

import { Theme, useTheme } from '@lumx/react';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import type { HasClassName, HasTheme } from '@lumx/core/js/types';
import { handleBasicClasses, getRootClassName } from '@lumx/core/js/utils';

import { useFitRowsToContent } from './useFitRowsToContent';

type NativeTextareaProps = React.ComponentProps<'textarea'>;

/**
 * Defines the props of the component.
 */
export interface RawInputTextareaProps extends Omit<NativeTextareaProps, 'value' | 'onChange'>, HasTheme, HasClassName {
    minimumRows?: number;
    value?: string;
    onChange?: (value: string, name?: string, event?: SyntheticEvent) => void;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'RawInputTextarea';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * Component default props.
 */
export const DEFAULT_PROPS: Partial<RawInputTextareaProps> = {
    minimumRows: 2,
};

/**
 * Raw input text area component
 * (textarea element without any decoration)
 */
export const RawInputTextarea = forwardRef<Omit<RawInputTextareaProps, 'type'>, HTMLTextAreaElement>((props, ref) => {
    const defaultTheme = useTheme() || Theme.light;
    const {
        className,
        theme = defaultTheme,
        minimumRows = DEFAULT_PROPS.minimumRows as number,
        value,
        onChange,
        ...forwardedProps
    } = props;
    const textareaRef = useRef<HTMLTextAreaElement>(null);

    const rows = useFitRowsToContent(minimumRows, textareaRef, value);

    const handleChange: React.ChangeEventHandler<HTMLTextAreaElement> = React.useCallback(
        (evt) => {
            onChange?.(evt.target.value, evt.target.name, evt);
        },
        [onChange],
    );

    return (
        <textarea
            className={classNames(className, handleBasicClasses({ prefix: CLASSNAME, theme }))}
            ref={useMergeRefs(ref, textareaRef)}
            {...forwardedProps}
            onChange={handleChange}
            value={value}
            rows={rows}
        />
    );
});

// packages/lumx-vue/src/components/text-field/RawInputTextarea.tsx
import { computed, defineComponent, ref, useAttrs } from 'vue';

import {
    RawInputTextarea as RawInputTextareaUI,
    type RawInputTextareaProps as UIProps,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/TextField/RawInputTextarea';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useFitRowsToContent } from './useFitRowsToContent';

export type RawInputTextareaProps = VueToJSXProps<UIProps>;

export const emitSchema = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    change: (value: string, _name?: string, _event?: Event) => typeof value === 'string',
};

/**
 * Raw input textarea component.
 * (textarea element without any decoration)
 *
 * @param  props Component props.
 * @return Vue element.
 */
const RawInputTextarea = defineComponent(
    (props: RawInputTextareaProps, { emit }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        const textareaRef = ref<HTMLTextAreaElement | null>(null);
        const rows = useFitRowsToContent(
            computed(() => props.rows ?? (DEFAULT_PROPS.rows as number)),
            textareaRef,
            computed(() => props.value),
        );

        const handleChange = (value: string, name?: string, event?: any) => {
            event?.stopImmediatePropagation();
            emit('change', value, name, event);
        };

        return () => {
            return (
                <RawInputTextareaUI
                    {...(attrs as UIProps)}
                    ref={textareaRef}
                    value={props.value}
                    rows={rows.value}
                    name={props.name}
                    className={props.class}
                    theme={props.theme || defaultTheme.value}
                    handleChange={handleChange}
                />
            );
        };
    },
    {
        name: 'LumxRawInputTextarea',
        inheritAttrs: false,
        props: keysOf<RawInputTextareaProps>()('class', 'theme', 'value', 'rows', 'name'),
        emits: emitSchema,
    },
);

export default RawInputTextarea;
