// packages/lumx-core/src/js/components/TextField/TextField.tsx
import { mdiAlertCircle, mdiCheckCircle, mdiCloseCircle } from '@lumx/icons';
import { HasTheme, HasAriaDisabled, HasClassName, JSXElement, CommonRef, GenericProps, HasDisabled } from '../../types';
import { classNames } from '../../utils';

import { CLASSNAME } from './constants';
import { InputLabel, InputLabelProps } from '../InputLabel';
import { Emphasis, Kind, Size, Theme } from '../../constants';
import { Icon } from '../Icon';
import { InputHelper } from '../InputHelper';

const { block, element } = classNames.bem(CLASSNAME);

/**
 * Defines the props of the component.
 */
export interface TextFieldProps extends HasClassName, HasTheme, HasAriaDisabled, HasDisabled {
    /** Chip Group to be rendered before the main text input. */
    chips?: JSXElement;
    /** Props to pass to the clear button (minus those already set by the TextField props). If not specified, the button won't be displayed. */
    clearButtonProps?: GenericProps;
    /** Error message. */
    error?: string | JSXElement;
    /** Whether we force the focus style or not. */
    forceFocusStyle?: boolean;
    /** Whether the text field is displayed with error style or not. */
    hasError?: boolean;
    /** Additional element to put at the end of the text field. */
    afterElement?: JSXElement;
    /** Helper text. */
    helper?: string | JSXElement;
    /** Icon (SVG path). */
    icon?: string;
    /** Native input id property (generated if not provided to link the label element). */
    id?: string;
    /** Generated helper id for accessibility attributes. */
    helperId?: string;
    /** Generated error id for accessibility attributes. */
    errorId?: string;
    /** Generated label id for accessibility attributes (used to link the clear button to the field label). */
    labelId?: string;
    /** Whether the component is required or not. */
    isRequired?: boolean;
    /** Whether the text field is displayed with valid style or not. */
    isValid?: boolean;
    /** Label text. */
    label?: string;
    /** Additional label props. */
    labelProps?: InputLabelProps;
    /** Max string length the input accepts (constrains the input and displays a character counter). */
    maxLength?: number;
    /** Character counter message formatter. Receives remaining character count, returns accessible label (e.g. \"{n} characters remaining\"). */
    charCounterMessage?: (charCount: number) => string | JSXElement;
    /** Whether the text field is a textarea or an input. */
    multiline?: boolean;
    /** Placeholder text. */
    placeholder?: string;
    /** Reference to the wrapper. */
    textFieldRef?: CommonRef;
    /** Value. */
    value?: string;
    /** Whether any part is disabled. */
    isAnyDisabled?: boolean;
    /** The input element (input or textarea). */
    input: JSXElement;
    /** Whether the input is focused. */
    isFocus?: boolean;
    /** IconButton component. */
    IconButton: (props: Record<string, any>) => any;
    /** Ref to the component root. */
    ref?: CommonRef;
}

export type TextFieldPropsToOverride =
    | 'input'
    | 'IconButton'
    | 'labelProps'
    | 'textFieldRef'
    | 'clearButtonProps'
    | 'charCounterMessage'
    | 'helperId'
    | 'errorId'
    | 'labelId'
    | 'isAnyDisabled'
    | 'isFocus';

/**
 * Generate unique accessibility IDs for helper and error texts.
 * Combines them with any existing aria-describedby in priority order (error > helper > existing).
 *
 * @param helper Helper text content
 * @param error Error text content
 * @param generatedId Unique ID for this text field instance
 * @param existingAriaDescribedBy Existing aria-describedby value to merge
 * @return Object containing helperId, errorId, and combined describedById
 */
export function generateAccessibilityIds(
    helper: TextFieldProps['helper'],
    error: TextFieldProps['error'],
    generatedId: string,
    existingAriaDescribedBy?: string,
    label?: TextFieldProps['label'],
): { helperId?: string; errorId?: string; describedById?: string; labelId?: string } {
    const helperId = helper ? `text-field-helper-${generatedId}` : undefined;
    const errorId = error ? `text-field-error-${generatedId}` : undefined;
    const labelId = label ? `text-field-label-${generatedId}` : undefined;
    const describedByIds = [errorId, helperId, existingAriaDescribedBy].filter(Boolean);
    const describedById = describedByIds.length === 0 ? undefined : describedByIds.join(' ');

    return { helperId, errorId, describedById, labelId };
}

/**
 * TextField component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const TextField = (props: TextFieldProps) => {
    const {
        chips,
        className,
        clearButtonProps,
        error,
        forceFocusStyle,
        hasError,
        helper,
        icon,
        id: textFieldId,
        isRequired,
        isValid,
        label,
        labelProps,
        isAnyDisabled,
        maxLength,
        multiline,
        placeholder,
        textFieldRef,
        charCounterMessage,
        helperId,
        errorId,
        labelId,
        theme,
        value,
        afterElement,
        input,
        isFocus,
        IconButton,
        ref,
    } = props;

    const valueLength = (value || '').length;
    const isNotEmpty = valueLength > 0;
    const remaining = maxLength ? maxLength - valueLength : 0;
    const charCounter = maxLength ? (
        <span className={element('char-counter')} role="status">
            {charCounterMessage ? charCounterMessage(remaining) : remaining}
            {remaining === 0 && Icon({ icon: mdiAlertCircle, size: Size.xxs })}
        </span>
    ) : undefined;

    return (
        <div
            ref={ref}
            className={classNames.join(
                className,
                block({
                    'has-chips': Boolean(chips),
                    'has-error': !isValid && hasError,
                    'has-icon': Boolean(icon),
                    'has-input': !multiline,
                    'has-input-clear': Boolean(clearButtonProps && isNotEmpty),
                    'has-label': Boolean(label),
                    'has-placeholder': Boolean(placeholder),
                    'has-textarea': multiline,
                    'has-value': Boolean(value),
                    'is-disabled': isAnyDisabled,
                    'is-focus': isFocus || forceFocusStyle,
                    'is-valid': isValid,
                    [`theme-${theme}`]: Boolean(theme),
                }),
            )}
        >
            {(label || maxLength) && (
                <div className={element('header')}>
                    {InputLabel({
                        ...labelProps,
                        id: labelId,
                        htmlFor: textFieldId as string,
                        className: classNames.join(labelProps?.className, element('label')),
                        isRequired,
                        theme,
                        children: [label, charCounter] as any,
                    })}
                </div>
            )}

            <div className={element('wrapper')} ref={textFieldRef}>
                {icon &&
                    Icon({
                        className: element('input-icon'),
                        color: theme === Theme.dark ? 'light' : undefined,
                        icon,
                        size: Size.xs,
                    })}

                {chips ? (
                    <div className={element('chips')}>
                        {chips}

                        {input}
                    </div>
                ) : (
                    <div className={element('input-wrapper')}>{input}</div>
                )}

                {(isValid || hasError) &&
                    Icon({
                        className: element('input-validity'),
                        color: theme === Theme.dark ? 'light' : undefined,
                        icon: isValid ? mdiCheckCircle : mdiAlertCircle,
                        size: Size.xxs,
                    })}

                {clearButtonProps && isNotEmpty && !isAnyDisabled && (
                    <IconButton
                        aria-describedby={labelId}
                        {...clearButtonProps}
                        className={element('input-clear')}
                        icon={mdiCloseCircle}
                        emphasis={Emphasis.low}
                        size={Size.s}
                        theme={theme}
                        type="button"
                    />
                )}

                {afterElement && <div className={element('after-element')}>{afterElement}</div>}
            </div>

            {hasError &&
                error &&
                InputHelper({ children: error, className: element('helper'), kind: Kind.error, theme, id: errorId })}

            {helper && InputHelper({ className: element('helper'), theme, id: helperId, children: helper })}
        </div>
    );
};

// packages/lumx-vue/src/components/text-field/TextField.tsx
import { computed, defineComponent, type ComponentPublicInstance, ref, useAttrs, watch, type VNode } from 'vue';

import {
    TextField as TextFieldUI,
    type TextFieldProps as UIProps,
    type TextFieldPropsToOverride,
    generateAccessibilityIds,
} from '@lumx/core/js/components/TextField/TextField';
import { type InputLabelProps } from '@lumx/core/js/components/InputLabel';
import { CLASSNAME, COMPONENT_NAME } from '@lumx/core/js/components/TextField/constants';

import { useTheme } from '../../composables/useTheme';
import { useClassName } from '../../composables/useClassName';
import { useId } from '../../composables/useId';
import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { useSlot } from '../../composables/useSlot';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { IconButton } from '../button';
import RawInputText from './RawInputText';
import RawInputTextarea from './RawInputTextarea';

export type TextFieldProps = VueToJSXProps<UIProps, TextFieldPropsToOverride | 'chips'> & {
    /** Character counter message formatter. Receives remaining character count, returns accessible label (e.g. \"{n} characters remaining\"). */
    charCounterMessage?: (charCount: number) => string | VNode;
    /** Native input id property (generated if not provided). */
    id?: string;
    /** Props to pass to the clear button. If not specified, the button won't be displayed. */
    clearButtonProps?: { label: string; [key: string]: any };
    /** Native input name property. */
    name?: string;
    /** Native input type (only when multiline is disabled). */
    type?: string;
    /** Minimum rows for textarea (only when multiline is enabled). */
    minimumRows?: number;
    /** Additional label props. */
    labelProps?: InputLabelProps;
    /** Ref callback for the native input element. */
    inputRef?: (el: HTMLInputElement | HTMLTextAreaElement | null) => void;
    /** Ref callback for the text field wrapper element. */
    textFieldRef?: (el: HTMLElement | null) => void;
};

export const emitSchema = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    change: (value: string, _name?: string, _event?: Event) => typeof value === 'string',
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    input: (value: string, _name?: string, _event?: Event) => typeof value === 'string',
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    focus: (_event?: FocusEvent) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    blur: (_event?: FocusEvent) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    clear: (_event?: MouseEvent) => true,
};

export { CLASSNAME, COMPONENT_NAME };

/**
 * TextField component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const TextField = defineComponent(
    (props: TextFieldProps, { emit }) => {
        const attrs = useAttrs();
        const getChipsSlot = useSlot('chips');
        const defaultTheme = useTheme();
        const className = useClassName(() => props.class);
        const generatedId = useId();
        const textFieldId = computed(() => props.id || generatedId);
        const isFocus = ref(false);

        const { isAnyDisabled, disabledStateProps } = useDisableStateProps(computed(() => ({ ...props, ...attrs })));

        // Track the native input element for inputRef forwarding.
        const rawInputInstance = ref<ComponentPublicInstance | null>(null);
        watch(
            rawInputInstance,
            (instance) => {
                const inputElement: HTMLInputElement | HTMLTextAreaElement | null = instance?.$el ?? instance ?? null;
                props.inputRef?.(inputElement);
            },
            { flush: 'sync' },
        );

        const accessibilityIds = computed(() =>
            generateAccessibilityIds(
                props.helper,
                props.error,
                generatedId,
                (attrs['aria-describedby'] as string) || undefined,
                props.label,
            ),
        );

        const handleChange = (value: string, name?: string, event?: any) => {
            emit('change', value, name, event);
        };

        const handleInput = (value: string, name?: string, event?: any) => {
            emit('input', value, name, event);
        };

        const handleFocus = (event?: any) => {
            isFocus.value = true;
            emit('focus', event);
        };

        const handleBlur = (event?: any) => {
            isFocus.value = false;
            emit('blur', event);
        };

        const handleClear = (event?: any) => {
            event?.stopImmediatePropagation();
            emit('change', '');
            emit('clear', event);
        };

        return () => {
            const theme = props.theme || defaultTheme.value;
            const { helperId, errorId, describedById, labelId } = accessibilityIds.value;

            // Filter out attrs handled explicitly so that unknown attrs (e.g. data-*, aria-*)
            // are forwarded to the native input element.
            const {
                class: _class,
                className: _cn,
                'aria-describedby': _ab,
                disabled: _d,
                isDisabled: _id,
                'aria-disabled': _aad,
                ariaDisabled: _ad,
                onChange: _oc,
                onInput: _oi,
                onFocus: _of,
                onBlur: _ob,
                chips: chipsAttr,
                ...inputAttrs
            } = attrs as any;

            const inputCommonProps = {
                ...inputAttrs,
                id: textFieldId.value,
                value: props.value,
                name: props.name,
                placeholder: props.placeholder,
                theme,
                'aria-invalid': props.hasError || undefined,
                'aria-describedby': describedById,
                ...disabledStateProps.value,
                readOnly: !!(inputAttrs as any).readOnly || !!disabledStateProps.value['aria-disabled'],
                onChange: handleChange,
                onInput: handleInput,
                onFocus: handleFocus,
                onBlur: handleBlur,
            };

            const input = (
                props.multiline ? (
                    <RawInputTextarea ref={rawInputInstance} {...inputCommonProps} rows={props.minimumRows} />
                ) : (
                    <RawInputText ref={rawInputInstance} {...inputCommonProps} type={props.type || 'text'} />
                )
            ) as any;

            return (
                <TextFieldUI
                    chips={(getChipsSlot() ?? chipsAttr) || undefined}
                    error={props.error}
                    forceFocusStyle={props.forceFocusStyle}
                    hasError={props.hasError}
                    afterElement={props.afterElement}
                    helper={props.helper}
                    icon={props.icon}
                    isRequired={props.isRequired}
                    isValid={props.isValid}
                    label={props.label}
                    labelProps={props.labelProps}
                    maxLength={props.maxLength}
                    charCounterMessage={props.charCounterMessage as any}
                    multiline={props.multiline}
                    placeholder={props.placeholder}
                    value={props.value}
                    className={className.value}
                    theme={theme}
                    id={textFieldId.value}
                    isAnyDisabled={isAnyDisabled.value}
                    helperId={helperId}
                    labelId={labelId}
                    errorId={errorId}
                    isFocus={isFocus.value}
                    input={input}
                    textFieldRef={props.textFieldRef}
                    IconButton={IconButton as any}
                    clearButtonProps={
                        props.clearButtonProps ? { ...props.clearButtonProps, onClick: handleClear } : undefined
                    }
                />
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<TextFieldProps>()(
            'class',
            'theme',
            'value',
            'error',
            'forceFocusStyle',
            'hasError',
            'afterElement',
            'helper',
            'icon',
            'isRequired',
            'isValid',
            'label',
            'labelProps',
            'maxLength',
            'charCounterMessage',
            'isDisabled',
            'disabled',
            'multiline',
            'placeholder',
            'aria-disabled',
            'id',
            'clearButtonProps',
            'name',
            'type',
            'minimumRows',
            'inputRef',
            'textFieldRef',
        ),
        emits: emitSchema,
    },
);

export default TextField;
