// packages/lumx-core/src/js/components/Dialog/index.tsx
import type { CommonRef, HasClassName, JSXElement, LumxClassName, GenericProps } from '../../types';
import { classNames } from '../../utils';
import { Size } from '../../constants';

export interface BaseDialogProps {
    /** Footer content. */
    footer?: JSXElement;
    /** Whether the divider between the dialog content and the footer is always displayed (instead of showing it on scroll). */
    forceFooterDivider?: boolean;
    /** Header content. */
    header?: JSXElement;
    /** Whether the divider between the dialog content and the header is always displayed (instead of showing it on scroll). */
    forceHeaderDivider?: boolean;
    /** Whether the indefinite progress indicator over the dialog content is displayed or not. */
    isLoading?: boolean;
    /** Whether the component is open or not. */
    isOpen?: boolean;
}

/**
 * Defines the props of the component.
 */
export interface DialogProps extends HasClassName, BaseDialogProps {
    /** Reference to the root element. */
    ref?: CommonRef;
    /** Whether the component is still visible (e.g. during close animation). */
    isVisible?: boolean;
    /** Reference to the dialog content element. */
    contentRef?: CommonRef;
    /** Size variant. */
    size?: DialogSizes;
    /** Z-axis position. */
    zIndex?: number;
    /** Additional props for the dialog container element. */
    dialogProps?: GenericProps;
    /** On close callback. */
    handleClose?(): void;
    /** Whether to prevent closing on click away. */
    shouldPreventCloseOnClickAway?: boolean;
    /** Refs used for click-away detection. */
    clickAwayRefs?: any;
    /** Ref for the root wrapper element. */
    rootRef?: CommonRef;
    /** Ref for the inner section element. */
    wrapperRef?: CommonRef;
    /** Whether the header sentinel is out of view (controls header divider). */
    hasTopIntersection: boolean | null;
    /** Whether the footer sentinel is out of view (controls footer divider). */
    hasBottomIntersection: boolean | null;
    /** Props forwarded from a child <header> element. */
    headerChildProps?: GenericProps;
    /** Content extracted from a child <header> element. */
    headerChildContent?: JSXElement;
    /** Props forwarded from a child <footer> element. */
    footerChildProps?: GenericProps;
    /** Content extracted from a child <footer> element. */
    footerChildContent?: JSXElement;
    /** Dialog body content. */
    content?: JSXElement;
    /** Ref setter for the top scroll sentinel element. */
    setSentinelTop?: any;
    /** Ref setter for the bottom scroll sentinel element. */
    setSentinelBottom?: any;
    /** Portal component for rendering outside the DOM hierarchy. */
    Portal: any;
    /** HeadingLevelProvider component. */
    HeadingLevelProvider: any;
    /** ThemeProvider component. */
    ThemeProvider: any;
    /** ClickAwayProvider component. */
    ClickAwayProvider: any;
    /** ProgressCircular component */
    ProgressCircular: any;
}

export type DialogSizes = Extract<Size, 'tiny' | 'regular' | 'big' | 'huge'>;

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'Dialog';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-dialog';
export const { block, element } = classNames.bem(CLASSNAME);

/**
 * Component default props.
 */
export const DEFAULT_PROPS: Partial<DialogProps> = {
    size: Size.big,
};

/**
 * Dialog component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Dialog = (props: DialogProps) => {
    const {
        className,
        ref,
        header,
        forceFooterDivider,
        forceHeaderDivider,
        footer,
        isLoading,
        isOpen,
        handleClose,
        contentRef,
        size = DEFAULT_PROPS.size,
        zIndex,
        dialogProps,
        headerChildContent,
        isVisible,
        Portal,
        HeadingLevelProvider,
        ThemeProvider,
        ClickAwayProvider,
        shouldPreventCloseOnClickAway,
        clickAwayRefs,
        rootRef,
        wrapperRef,
        hasTopIntersection,
        headerChildProps,
        setSentinelTop,
        content,
        setSentinelBottom,
        footerChildContent,
        footerChildProps,
        ProgressCircular,
        hasBottomIntersection,
        ...forwardedProps
    } = props;

    return (
        <Portal>
            <div
                ref={ref}
                {...forwardedProps}
                className={classNames.join(
                    className,
                    block({
                        'is-hidden': !isOpen,
                        'is-loading': isLoading,
                        'is-shown': isOpen || isVisible,
                        [`size-${size}`]: Boolean(size),
                    }),
                )}
                style={{ zIndex }}
            >
                <div className={element('overlay')} />

                <HeadingLevelProvider level={2}>
                    <ThemeProvider value={undefined}>
                        <div className={element('container')} role="dialog" aria-modal="true" {...dialogProps}>
                            <ClickAwayProvider
                                callback={!shouldPreventCloseOnClickAway && handleClose}
                                childrenRefs={clickAwayRefs}
                                parentRef={rootRef}
                            >
                                <section className={element('wrapper')} ref={wrapperRef}>
                                    {(header || headerChildContent) && (
                                        <header
                                            {...headerChildProps}
                                            className={classNames.join(
                                                element('header', {
                                                    'has-divider': Boolean(forceHeaderDivider || hasTopIntersection),
                                                }),
                                                headerChildProps?.className,
                                            )}
                                        >
                                            {header}
                                            {headerChildContent}
                                        </header>
                                    )}

                                    <div ref={contentRef} className={element('content')}>
                                        <div className={element('sentinel', { top: true })} ref={setSentinelTop} />

                                        {content}

                                        <div
                                            className={element('sentinel', { bottom: true })}
                                            ref={setSentinelBottom}
                                        />
                                    </div>

                                    {(footer || footerChildContent) && (
                                        <footer
                                            {...footerChildProps}
                                            className={classNames.join(
                                                element('footer', {
                                                    'has-divider': Boolean(forceFooterDivider || hasBottomIntersection),
                                                }),
                                                footerChildProps?.className,
                                            )}
                                        >
                                            {footer}
                                            {footerChildContent}
                                        </footer>
                                    )}

                                    {isLoading && (
                                        <div className={element('progress-overlay')}>
                                            <ProgressCircular />
                                        </div>
                                    )}
                                </section>
                            </ClickAwayProvider>
                        </div>
                    </ThemeProvider>
                </HeadingLevelProvider>
            </div>
        </Portal>
    );
};

// packages/lumx-vue/src/components/dialog/Dialog.tsx
import { computed, defineComponent, ref, type Ref } from 'vue';
import { useIntersectionObserver } from '@vueuse/core';

import { Dialog as UI, type BaseDialogProps, type DialogSizes, DEFAULT_PROPS } from '@lumx/core/js/components/Dialog';
import { DIALOG_TRANSITION_DURATION } from '@lumx/core/js/constants';
import type { GenericProps, HasCloseMode, JSXElement } from '@lumx/core/js/types';

import { Portal } from '../../utils/Portal/Portal';
import { ClickAwayProvider } from '../../utils/ClickAway/ClickAwayProvider';
import { ThemeProvider } from '../../utils/theme/ThemeProvider';
import HeadingLevelProvider from '../heading/HeadingLevelProvider';
import ProgressCircular from '../progress/ProgressCircular';

import { useCallbackOnEscape } from '../../composables/useCallbackOnEscape';
import { useClassName } from '../../composables/useClassName';
import { useFocusTrap } from '../../composables/useFocusTrap';
import { useRestoreFocusOnClose } from '../../composables/useRestoreFocusOnClose';
import { useTransitionVisibility } from '../../composables/useTransitionVisibility';
import { useDisableBodyScroll } from '../../composables/useDisableBodyScroll';
import { keysOf } from '../../utils/VueToJSX';

export type DialogProps = Pick<BaseDialogProps, 'forceFooterDivider' | 'forceHeaderDivider' | 'isLoading'> &
    HasCloseMode & {
        /** Additional class name. */
        class?: string;
        /** Whether the dialog is open. */
        isOpen?: boolean;
        /** Size variant. */
        size?: DialogSizes;
        /** Z-axis position. */
        zIndex?: number;
        /** Additional props for the dialog container element. */
        dialogProps?: GenericProps;
        /** Reference to the parent element that triggered modal opening (gets focus back on close). */
        parentElement?: HTMLElement;
        /** Element that should receive focus when the dialog opens. By default the first focusable child. */
        focusElement?: HTMLElement;
        /** Reference to the dialog content element. */
        contentRef?: Ref<HTMLDivElement>;
        /** Whether to keep the dialog open on clickaway or escape press. */
        preventAutoClose?: boolean;
        /** Whether to keep the dialog open on escape press. */
        preventCloseOnEscape?: boolean;
        /** Whether to keep the dialog open on clickaway. */
        preventCloseOnClick?: boolean;
        /** Whether to disable body scroll when the dialog is open. */
        disableBodyScroll?: boolean;
    };

export const emitSchema = {
    close: () => true,
    visibilityChange: (isVisible: boolean) => typeof isVisible === 'boolean',
};

const Dialog = defineComponent(
    (props: DialogProps, { emit, slots, attrs }) => {
        const className = useClassName(() => props.class);

        const rootRef = ref<HTMLDivElement | null>(null);
        const wrapperRef = ref<HTMLDivElement | null>(null);
        const localContentRef = ref<HTMLDivElement | null>(null);

        // Sentinel refs for scroll divider detection — passed as callback refs to core JSX
        const sentinelTopRef = ref<HTMLElement | null>(null);
        const sentinelBottomRef = ref<HTMLElement | null>(null);
        const setSentinelTop = (el: HTMLElement | null) => {
            sentinelTopRef.value = el;
        };
        const setSentinelBottom = (el: HTMLElement | null) => {
            sentinelBottomRef.value = el;
        };

        // Intersection observer for scroll-triggered header/footer dividers
        const hasTopIntersection = ref<boolean | null>(null);
        const hasBottomIntersection = ref<boolean | null>(null);
        useIntersectionObserver(sentinelTopRef, (entries) => {
            const entry = entries[0];
            hasTopIntersection.value = entry ? !entry.isIntersecting : null;
        });
        useIntersectionObserver(sentinelBottomRef, (entries) => {
            const entry = entries[0];
            hasBottomIntersection.value = entry ? !entry.isIntersecting : null;
        });

        // Escape key
        const shouldPreventCloseOnEscape = computed(() => props.preventAutoClose || props.preventCloseOnEscape);
        const handleClose = () => emit('close');
        useCallbackOnEscape(
            handleClose,
            computed(() => Boolean(props.isOpen && !shouldPreventCloseOnEscape.value)),
        );

        // Focus trap inside the dialog wrapper
        const focusZoneElement = computed(() => {
            if (!props.isOpen) return false as const;
            return wrapperRef.value || false;
        });
        useFocusTrap(
            focusZoneElement,
            computed(() => props.focusElement),
        );

        // Restore focus to parentElement when dialog closes
        useRestoreFocusOnClose(
            computed(() => true),
            computed(() => undefined) as Ref<HTMLElement | undefined>,
            computed(() => props.parentElement) as Ref<HTMLElement | undefined>,
            wrapperRef as Ref<HTMLElement | undefined>,
            computed(() => Boolean(props.isOpen)),
        );

        // Disable body scroll when dialog is open
        useDisableBodyScroll(computed(() => props.disableBodyScroll !== false && Boolean(props.isOpen)));

        // Track animation state: keeps dialog mounted during close animation
        const isVisible = useTransitionVisibility(
            computed(() => Boolean(props.isOpen)),
            DIALOG_TRANSITION_DURATION,
            computed(() => (v: boolean) => emit('visibilityChange', v)),
        );

        // Mount guard: keep mounted during open, animation, or hide mode
        const isMounted = computed(() => props.isOpen || isVisible.value || props.closeMode === 'hide');

        // Click-away: only the wrapper section is allowed to be clicked inside
        const clickAwayRefs = computed(() => [wrapperRef]) as Ref<Array<Ref<HTMLElement | undefined>>>;
        const shouldPreventCloseOnClickAway = computed(() => props.preventAutoClose || props.preventCloseOnClick);

        // Merge external contentRef with internal one via callback ref
        const contentRefCallback = (el: HTMLDivElement | null) => {
            localContentRef.value = el;
            if (props.contentRef) {
                (props.contentRef as Ref<HTMLDivElement | null>).value = el;
            }
        };

        return () => {
            if (!isMounted.value) return null;

            return UI({
                ...attrs,
                ClickAwayProvider,
                HeadingLevelProvider,
                Portal,
                ThemeProvider,
                ProgressCircular,
                className: className.value,
                clickAwayRefs,
                content: slots.default?.() as JSXElement,
                contentRef: contentRefCallback,
                dialogProps: props.dialogProps,
                footer: undefined,
                footerChildContent: slots.footer?.() as JSXElement | undefined,
                footerChildProps: undefined,
                forceFooterDivider: props.forceFooterDivider,
                forceHeaderDivider: props.forceHeaderDivider,
                handleClose,
                hasBottomIntersection: hasBottomIntersection.value,
                hasTopIntersection: hasTopIntersection.value,
                header: undefined,
                headerChildContent: slots.header?.() as JSXElement | undefined,
                headerChildProps: undefined,
                isLoading: props.isLoading,
                isOpen: props.isOpen,
                isVisible: isVisible.value,
                ref: rootRef,
                rootRef: rootRef as Ref<HTMLElement | undefined>,
                setSentinelBottom,
                setSentinelTop,
                shouldPreventCloseOnClickAway: shouldPreventCloseOnClickAway.value,
                size: props.size ?? DEFAULT_PROPS.size,
                wrapperRef: wrapperRef as Ref<HTMLElement | undefined>,
                zIndex: props.zIndex,
            });
        };
    },
    {
        name: 'LumxDialog',
        inheritAttrs: false,
        props: keysOf<DialogProps>()(
            'class',
            'closeMode',
            'contentRef',
            'dialogProps',
            'disableBodyScroll',
            'focusElement',
            'forceFooterDivider',
            'forceHeaderDivider',
            'isLoading',
            'isOpen',
            'parentElement',
            'preventAutoClose',
            'preventCloseOnClick',
            'preventCloseOnEscape',
            'size',
            'zIndex',
        ),
        emits: emitSchema,
    },
);

export default Dialog;
