// packages/lumx-react/src/components/dialog/Dialog.tsx
import React, { Children, ReactElement, Ref, RefObject, useMemo, useRef, useState } from 'react';

import { HeadingLevelProvider, ProgressCircular, Size } from '@lumx/react';

import { DIALOG_TRANSITION_DURATION, DOCUMENT } from '@lumx/react/constants';
import { useCallbackOnEscape } from '@lumx/react/hooks/useCallbackOnEscape';
import { useFocusTrap } from '@lumx/react/hooks/useFocusTrap';
import { useIntersectionObserver } from '@lumx/react/hooks/useIntersectionObserver';

import { GenericProps, HasCloseMode, isComponent } from '@lumx/react/utils/type';
import { partitionMulti } from '@lumx/react/utils/partitionMulti';
import { ClickAwayProvider } from '@lumx/react/utils/ClickAwayProvider';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { mergeRefs } from '@lumx/react/utils/react/mergeRefs';

import { useDisableBodyScroll } from '@lumx/react/hooks/useDisableBodyScroll';
import { useTransitionVisibility } from '@lumx/react/hooks/useTransitionVisibility';
import { ThemeProvider } from '@lumx/react/utils/theme/ThemeContext';

import { Portal } from '@lumx/react/utils';
import {
    Dialog as UI,
    CLASSNAME,
    COMPONENT_NAME,
    DialogSizes,
    BaseDialogProps as UIProps,
} from '@lumx/core/js/components/Dialog';

/**
 * Defines the props of the component.
 */
export interface DialogProps extends GenericProps, HasCloseMode, UIProps {
    /** Reference to the parent element that triggered modal opening (will get back focus on close). */
    parentElement?: RefObject<HTMLElement>;
    /** Reference to the dialog content element. */
    contentRef?: Ref<HTMLDivElement>;
    /** Reference to the of the element that should get the focus when the dialogs opens. By default, the first child will take focus. */
    focusElement?: RefObject<HTMLElement>;
    /** Whether to keep the dialog open on clickaway or escape press. */
    preventAutoClose?: boolean;
    /** Whether to keep the dialog open on escape press. */
    preventCloseOnEscape?: boolean;
    /** Whether to keep the dialog open on clickaway. */
    preventCloseOnClick?: boolean;
    /** Size variant. */
    size?: DialogSizes;
    /** Z-axis position. */
    zIndex?: number;
    /** Z-axis position. */
    dialogProps?: GenericProps;
    /** On close callback. */
    onClose?(): void;
    /** Callback called when the open animation starts and the close animation finishes. */
    onVisibilityChange?(isVisible: boolean): void;
    /** whether to disable the scroll on the body or not */
    disableBodyScroll?: boolean;
    /** Children */
    children?: React.ReactNode;
}

const isHeader = isComponent('header');
const isFooter = isComponent('footer');

/**
 * Component default props.
 */
const DEFAULT_PROPS: Partial<DialogProps> = {
    closeMode: 'unmount',
    size: Size.big,
    disableBodyScroll: true,
};

export { type DialogSizes };

/**
 * Dialog component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Dialog = forwardRef<DialogProps, HTMLDivElement>((props, ref) => {
    if (!DOCUMENT) {
        // Can't render in SSR.
        return null;
    }

    const {
        children,
        className,
        closeMode = DEFAULT_PROPS.closeMode,
        header,
        focusElement,
        forceFooterDivider,
        forceHeaderDivider,
        footer,
        isLoading,
        isOpen,
        onClose,
        parentElement,
        contentRef,
        preventAutoClose,
        size = DEFAULT_PROPS.size,
        zIndex,
        dialogProps,
        onVisibilityChange,
        disableBodyScroll = DEFAULT_PROPS.disableBodyScroll,
        preventCloseOnClick,
        preventCloseOnEscape,
        ...forwardedProps
    } = props;

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const previousOpen = React.useRef(isOpen);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    React.useEffect(() => {
        if (isOpen !== previousOpen.current) {
            previousOpen.current = isOpen;

            // Focus the parent element on close.
            if (!isOpen && parentElement && parentElement.current) {
                parentElement.current.focus();
            }
        }
    }, [isOpen, parentElement]);

    const shouldPreventCloseOnEscape = preventAutoClose || preventCloseOnEscape;

    // eslint-disable-next-line react-hooks/rules-of-hooks
    useCallbackOnEscape(onClose, isOpen && !shouldPreventCloseOnEscape);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const wrapperRef = useRef<HTMLDivElement>(null);
    /**
     * Since the `contentRef` comes from the parent and is optional,
     * we need to create a stable contentRef that will always be available.
     */
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const localContentRef = useRef<HTMLDivElement>(null);
    // Handle focus trap.
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useFocusTrap(isOpen && wrapperRef.current, focusElement?.current);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    useDisableBodyScroll(disableBodyScroll && isOpen && localContentRef.current);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [sentinelTop, setSentinelTop] = useState<Element | null>(null);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [sentinelBottom, setSentinelBottom] = useState<Element | null>(null);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const intersections = useIntersectionObserver([sentinelTop, sentinelBottom], {
        threshold: [0, 1],
    });

    const hasTopIntersection = sentinelTop && !(intersections.get(sentinelTop)?.isIntersecting ?? true);
    const hasBottomIntersection = sentinelBottom && !(intersections.get(sentinelBottom)?.isIntersecting ?? true);

    // Separate header, footer and dialog content from children.
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [[headerChild], [footerChild], content] = useMemo(
        () => partitionMulti(Children.toArray(children), [isHeader, isFooter]),
        [children],
    );
    const headerChildProps = (headerChild as ReactElement)?.props;
    const headerChildContent = headerChildProps?.children;
    const footerChildProps = (footerChild as ReactElement)?.props;
    const footerChildContent = footerChildProps?.children;

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const clickAwayRefs = useRef([wrapperRef]);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const rootRef = useRef<HTMLDivElement>(null);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const isVisible = useTransitionVisibility(rootRef, Boolean(isOpen), DIALOG_TRANSITION_DURATION, onVisibilityChange);

    const shouldPreventCloseOnClickAway = preventAutoClose || preventCloseOnClick;

    const isMounted = isOpen || isVisible || closeMode === 'hide';

    return isMounted
        ? UI({
              ClickAwayProvider,
              HeadingLevelProvider,
              Portal,
              ThemeProvider,
              className,
              clickAwayRefs,
              content,
              contentRef: mergeRefs(localContentRef, contentRef),
              dialogProps,
              footer,
              footerChildContent,
              footerChildProps,
              forceFooterDivider,
              forceHeaderDivider,
              handleClose: onClose,
              hasBottomIntersection,
              hasTopIntersection,
              header,
              headerChildContent,
              ProgressCircular,
              headerChildProps,
              isLoading,
              isOpen,
              isVisible,
              ref: mergeRefs(rootRef, ref),
              rootRef,
              setSentinelBottom,
              setSentinelTop,
              shouldPreventCloseOnClickAway,
              size,
              wrapperRef,
              zIndex,
              ...forwardedProps,
          })
        : null;
});
Dialog.displayName = COMPONENT_NAME;
Dialog.className = CLASSNAME;
Dialog.defaultProps = DEFAULT_PROPS;

// packages/lumx-vue/src/components/dialog/Dialog.tsx
import { computed, defineComponent, ref, type Ref } from 'vue';
import { useIntersectionObserver } from '@vueuse/core';

import { Dialog as UI, type BaseDialogProps, type DialogSizes, DEFAULT_PROPS } from '@lumx/core/js/components/Dialog';
import { DIALOG_TRANSITION_DURATION } from '@lumx/core/js/constants';
import type { GenericProps, HasCloseMode, JSXElement } from '@lumx/core/js/types';

import { Portal } from '../../utils/Portal/Portal';
import { ClickAwayProvider } from '../../utils/ClickAway/ClickAwayProvider';
import { ThemeProvider } from '../../utils/theme/ThemeProvider';
import HeadingLevelProvider from '../heading/HeadingLevelProvider';
import ProgressCircular from '../progress/ProgressCircular';

import { useCallbackOnEscape } from '../../composables/useCallbackOnEscape';
import { useClassName } from '../../composables/useClassName';
import { useFocusTrap } from '../../composables/useFocusTrap';
import { useRestoreFocusOnClose } from '../../composables/useRestoreFocusOnClose';
import { useTransitionVisibility } from '../../composables/useTransitionVisibility';
import { useDisableBodyScroll } from '../../composables/useDisableBodyScroll';
import { keysOf } from '../../utils/VueToJSX';

export type DialogProps = Pick<BaseDialogProps, 'forceFooterDivider' | 'forceHeaderDivider' | 'isLoading'> &
    HasCloseMode & {
        /** Additional class name. */
        class?: string;
        /** Whether the dialog is open. */
        isOpen?: boolean;
        /** Size variant. */
        size?: DialogSizes;
        /** Z-axis position. */
        zIndex?: number;
        /** Additional props for the dialog container element. */
        dialogProps?: GenericProps;
        /** Reference to the parent element that triggered modal opening (gets focus back on close). */
        parentElement?: HTMLElement;
        /** Element that should receive focus when the dialog opens. By default the first focusable child. */
        focusElement?: HTMLElement;
        /** Reference to the dialog content element. */
        contentRef?: Ref<HTMLDivElement>;
        /** Whether to keep the dialog open on clickaway or escape press. */
        preventAutoClose?: boolean;
        /** Whether to keep the dialog open on escape press. */
        preventCloseOnEscape?: boolean;
        /** Whether to keep the dialog open on clickaway. */
        preventCloseOnClick?: boolean;
        /** Whether to disable body scroll when the dialog is open. */
        disableBodyScroll?: boolean;
    };

export const emitSchema = {
    close: () => true,
    visibilityChange: (isVisible: boolean) => typeof isVisible === 'boolean',
};

const Dialog = defineComponent(
    (props: DialogProps, { emit, slots, attrs }) => {
        const className = useClassName(() => props.class);

        const rootRef = ref<HTMLDivElement | null>(null);
        const wrapperRef = ref<HTMLDivElement | null>(null);
        const localContentRef = ref<HTMLDivElement | null>(null);

        // Sentinel refs for scroll divider detection — passed as callback refs to core JSX
        const sentinelTopRef = ref<HTMLElement | null>(null);
        const sentinelBottomRef = ref<HTMLElement | null>(null);
        const setSentinelTop = (el: HTMLElement | null) => {
            sentinelTopRef.value = el;
        };
        const setSentinelBottom = (el: HTMLElement | null) => {
            sentinelBottomRef.value = el;
        };

        // Intersection observer for scroll-triggered header/footer dividers
        const hasTopIntersection = ref<boolean | null>(null);
        const hasBottomIntersection = ref<boolean | null>(null);
        useIntersectionObserver(sentinelTopRef, (entries) => {
            const entry = entries[0];
            hasTopIntersection.value = entry ? !entry.isIntersecting : null;
        });
        useIntersectionObserver(sentinelBottomRef, (entries) => {
            const entry = entries[0];
            hasBottomIntersection.value = entry ? !entry.isIntersecting : null;
        });

        // Escape key
        const shouldPreventCloseOnEscape = computed(() => props.preventAutoClose || props.preventCloseOnEscape);
        const handleClose = () => emit('close');
        useCallbackOnEscape(
            handleClose,
            computed(() => Boolean(props.isOpen && !shouldPreventCloseOnEscape.value)),
        );

        // Focus trap inside the dialog wrapper
        const focusZoneElement = computed(() => {
            if (!props.isOpen) return false as const;
            return wrapperRef.value || false;
        });
        useFocusTrap(
            focusZoneElement,
            computed(() => props.focusElement),
        );

        // Restore focus to parentElement when dialog closes
        useRestoreFocusOnClose(
            computed(() => true),
            computed(() => undefined) as Ref<HTMLElement | undefined>,
            computed(() => props.parentElement) as Ref<HTMLElement | undefined>,
            wrapperRef as Ref<HTMLElement | undefined>,
            computed(() => Boolean(props.isOpen)),
        );

        // Disable body scroll when dialog is open
        useDisableBodyScroll(computed(() => props.disableBodyScroll !== false && Boolean(props.isOpen)));

        // Track animation state: keeps dialog mounted during close animation
        const isVisible = useTransitionVisibility(
            computed(() => Boolean(props.isOpen)),
            DIALOG_TRANSITION_DURATION,
            computed(() => (v: boolean) => emit('visibilityChange', v)),
        );

        // Mount guard: keep mounted during open, animation, or hide mode
        const isMounted = computed(() => props.isOpen || isVisible.value || props.closeMode === 'hide');

        // Click-away: only the wrapper section is allowed to be clicked inside
        const clickAwayRefs = computed(() => [wrapperRef]) as Ref<Array<Ref<HTMLElement | undefined>>>;
        const shouldPreventCloseOnClickAway = computed(() => props.preventAutoClose || props.preventCloseOnClick);

        // Merge external contentRef with internal one via callback ref
        const contentRefCallback = (el: HTMLDivElement | null) => {
            localContentRef.value = el;
            if (props.contentRef) {
                (props.contentRef as Ref<HTMLDivElement | null>).value = el;
            }
        };

        return () => {
            if (!isMounted.value) return null;

            return UI({
                ...attrs,
                ClickAwayProvider,
                HeadingLevelProvider,
                Portal,
                ThemeProvider,
                ProgressCircular,
                className: className.value,
                clickAwayRefs,
                content: slots.default?.() as JSXElement,
                contentRef: contentRefCallback,
                dialogProps: props.dialogProps,
                footer: undefined,
                footerChildContent: slots.footer?.() as JSXElement | undefined,
                footerChildProps: undefined,
                forceFooterDivider: props.forceFooterDivider,
                forceHeaderDivider: props.forceHeaderDivider,
                handleClose,
                hasBottomIntersection: hasBottomIntersection.value,
                hasTopIntersection: hasTopIntersection.value,
                header: undefined,
                headerChildContent: slots.header?.() as JSXElement | undefined,
                headerChildProps: undefined,
                isLoading: props.isLoading,
                isOpen: props.isOpen,
                isVisible: isVisible.value,
                ref: rootRef,
                rootRef: rootRef as Ref<HTMLElement | undefined>,
                setSentinelBottom,
                setSentinelTop,
                shouldPreventCloseOnClickAway: shouldPreventCloseOnClickAway.value,
                size: props.size ?? DEFAULT_PROPS.size,
                wrapperRef: wrapperRef as Ref<HTMLElement | undefined>,
                zIndex: props.zIndex,
            });
        };
    },
    {
        name: 'LumxDialog',
        inheritAttrs: false,
        props: keysOf<DialogProps>()(
            'class',
            'closeMode',
            'contentRef',
            'dialogProps',
            'disableBodyScroll',
            'focusElement',
            'forceFooterDivider',
            'forceHeaderDivider',
            'isLoading',
            'isOpen',
            'parentElement',
            'preventAutoClose',
            'preventCloseOnClick',
            'preventCloseOnEscape',
            'size',
            'zIndex',
        ),
        emits: emitSchema,
    },
);

export default Dialog;
