// packages/lumx-react/src/components/lightbox/Lightbox.tsx
import React, { RefObject, useRef, useEffect, AriaAttributes } from 'react';

import classNames from 'classnames';

import { mdiClose } from '@lumx/icons';
import { HeadingLevelProvider, IconButton, IconButtonProps } from '@lumx/react';
import { DIALOG_TRANSITION_DURATION, DOCUMENT } from '@lumx/react/constants';
import { GenericProps, HasTheme } from '@lumx/react/utils/type';
import { getRootClassName, handleBasicClasses } from '@lumx/react/utils/className';

import { useFocusTrap } from '@lumx/react/hooks/useFocusTrap';
import { useDisableBodyScroll } from '@lumx/react/hooks/useDisableBodyScroll';
import { ClickAwayProvider } from '@lumx/react/utils/ClickAwayProvider';
import { mergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { useCallbackOnEscape } from '@lumx/react/hooks/useCallbackOnEscape';
import { useTransitionVisibility } from '@lumx/react/hooks/useTransitionVisibility';
import { ThemeProvider } from '@lumx/react/utils/theme/ThemeContext';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

import { Portal } from '@lumx/react/utils';

/**
 * Defines the props of the component.
 */
export interface LightboxProps extends GenericProps, HasTheme, Pick<AriaAttributes, 'aria-label' | 'aria-labelledby'> {
    /** Props to pass to the close button (minus those already set by the Lightbox props). */
    closeButtonProps?: Pick<IconButtonProps, 'label'> &
        Omit<IconButtonProps, 'label' | 'onClick' | 'icon' | 'emphasis' | 'color'>;
    /** Whether the component is open or not. */
    isOpen?: boolean;
    /** Reference to the element that triggered modal opening to set focus on. */
    parentElement: RefObject<any>;
    /** Reference to the element that should get the focus when the lightbox opens. By default, the close button or the lightbox itself will take focus. */
    focusElement?: RefObject<HTMLElement>;
    /** Whether to keep the dialog open on clickaway or escape press. */
    preventAutoClose?: boolean;
    /** Z-axis position. */
    zIndex?: number;
    /** On close callback. */
    onClose?(): void;
    /** Children */
    children?: React.ReactNode;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'Lightbox';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * Lightbox component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Lightbox = forwardRef<LightboxProps, HTMLDivElement>((props, ref) => {
    const {
        'aria-labelledby': propAriaLabelledBy,
        ariaLabelledBy = propAriaLabelledBy,
        'aria-label': propAriaLabel,
        ariaLabel = propAriaLabel,
        children,
        className,
        closeButtonProps,
        isOpen,
        onClose,
        parentElement,
        focusElement,
        preventAutoClose,
        theme,
        zIndex,
        ...forwardedProps
    } = props;
    if (!DOCUMENT) {
        // Can't render in SSR.
        return null;
    }

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const childrenRef = useRef<any>(null);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const wrapperRef = useRef<HTMLDivElement>(null);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const closeButtonRef = useRef<HTMLButtonElement>(null);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    useDisableBodyScroll(isOpen && wrapperRef.current);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const isVisible = useTransitionVisibility(wrapperRef, !!isOpen, DIALOG_TRANSITION_DURATION);

    // Handle focus trap.
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useFocusTrap(
        // Focus trap zone
        isOpen && wrapperRef.current,
        // Focus element (fallback on close button and then on the dialog)
        focusElement?.current || closeButtonRef.current || wrapperRef.current,
    );

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const previousOpen = useRef(isOpen);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
        if (isOpen !== previousOpen.current) {
            previousOpen.current = isOpen;

            // Focus the parent element on close.
            if (!isOpen && parentElement && parentElement.current) {
                parentElement.current.focus();
            }
        }
    }, [isOpen, parentElement]);

    // Close lightbox on escape key pressed.
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useCallbackOnEscape(onClose);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const clickAwayRefs = useRef([wrapperRef]);

    if (!isOpen && !isVisible) return null;

    return (
        <Portal>
            <div
                ref={mergeRefs(ref, wrapperRef)}
                {...forwardedProps}
                aria-label={ariaLabel}
                aria-labelledby={ariaLabelledBy}
                aria-modal="true"
                role="dialog"
                tabIndex={-1}
                className={classNames(
                    className,
                    handleBasicClasses({
                        prefix: CLASSNAME,
                        isHidden: !isOpen,
                        isShown: isOpen || isVisible,
                        theme,
                    }),
                )}
                style={{ zIndex }}
            >
                {closeButtonProps && (
                    <div className={`${CLASSNAME}__close`}>
                        <IconButton
                            {...closeButtonProps}
                            ref={closeButtonRef}
                            emphasis="low"
                            hasBackground
                            icon={mdiClose}
                            theme="dark"
                            type="button"
                            onClick={onClose}
                        />
                    </div>
                )}
                <HeadingLevelProvider level={2}>
                    <ThemeProvider value={undefined}>
                        <ClickAwayProvider callback={!preventAutoClose && onClose} childrenRefs={clickAwayRefs}>
                            <div ref={childrenRef} className={`${CLASSNAME}__wrapper`} role="presentation">
                                {children}
                            </div>
                        </ClickAwayProvider>
                    </ThemeProvider>
                </HeadingLevelProvider>
            </div>
        </Portal>
    );
});
Lightbox.displayName = COMPONENT_NAME;
Lightbox.className = CLASSNAME;

// packages/lumx-vue/src/components/lightbox/Lightbox.tsx
import { computed, defineComponent, ref, type Ref } from 'vue';

import { Lightbox as UI, type BaseLightboxProps, COMPONENT_NAME } from '@lumx/core/js/components/Lightbox';
import { DIALOG_TRANSITION_DURATION } from '@lumx/core/js/constants';
import type { JSXElement } from '@lumx/core/js/types';

import { Portal } from '../../utils/Portal/Portal';
import { ClickAwayProvider } from '../../utils/ClickAway/ClickAwayProvider';
import { ThemeProvider } from '../../utils/theme/ThemeProvider';
import HeadingLevelProvider from '../heading/HeadingLevelProvider';
import IconButton from '../button/IconButton';

import { useCallbackOnEscape } from '../../composables/useCallbackOnEscape';
import { useClassName } from '../../composables/useClassName';
import { useFocusTrap } from '../../composables/useFocusTrap';
import { useRestoreFocusOnClose } from '../../composables/useRestoreFocusOnClose';
import { useTransitionVisibility } from '../../composables/useTransitionVisibility';
import { useDisableBodyScroll } from '../../composables/useDisableBodyScroll';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';

export type LightboxProps = VueToJSXProps<BaseLightboxProps, 'theme' | 'aria-label' | 'aria-labelledby'> & {
    /** Reference to the element that triggered lightbox opening (gets focus back on close). */
    parentElement?: HTMLElement;
    /** Element that should receive focus when the lightbox opens. By default the first focusable child. */
    focusElement?: HTMLElement;
    /** Props to pass to the close button. */
    closeButtonProps?: any;
};
// theme, aria-label, aria-labelledby pass through via attrs

export const emitSchema = {
    close: () => true,
};

const Lightbox = defineComponent(
    (props: LightboxProps, { emit, slots, attrs }) => {
        const className = useClassName(() => props.class);

        // Root div ref — used as focus zone and click-away zone
        const wrapperRef = ref<HTMLDivElement | null>(null);
        // Close button ref (passed to core; only mounted when closeButtonProps is provided)
        const closeButtonRef = ref<HTMLButtonElement | null>(null);

        const handleClose = () => emit('close');

        // Escape key closes the lightbox
        useCallbackOnEscape(
            handleClose,
            computed(() => Boolean(props.isOpen && !props.preventAutoClose)),
        );

        // Focus trap inside the lightbox root
        const focusZoneElement = computed(() => {
            if (!props.isOpen) return false as const;
            return wrapperRef.value || false;
        });

        useFocusTrap(
            focusZoneElement,
            computed(() => {
                // closeButtonRef holds a Vue component instance; unwrap to the underlying DOM element via $el
                const closeButtonEl = (closeButtonRef.value as any)?.$el ?? closeButtonRef.value;
                return props.focusElement || closeButtonEl || wrapperRef.value;
            }),
        );

        // Restore focus to parentElement when lightbox closes
        useRestoreFocusOnClose(
            computed(() => true),
            computed(() => undefined) as Ref<HTMLElement | undefined>,
            computed(() => props.parentElement) as Ref<HTMLElement | undefined>,
            wrapperRef as Ref<HTMLElement | undefined>,
            computed(() => Boolean(props.isOpen)),
        );

        // Disable body scroll when lightbox is open
        useDisableBodyScroll(computed(() => Boolean(props.isOpen)));

        // Track animation state: keeps lightbox mounted during close animation
        const isVisible = useTransitionVisibility(
            computed(() => Boolean(props.isOpen)),
            DIALOG_TRANSITION_DURATION,
        );

        // Mount guard: keep mounted while open or animating closed
        const isMounted = computed(() => props.isOpen || isVisible.value);

        // Click-away: treat the full root div as the "inside" zone
        const clickAwayRefs = computed(() => [wrapperRef]) as Ref<Array<Ref<HTMLElement | undefined>>>;

        return () => {
            if (!isMounted.value) return null;

            return UI({
                ...attrs,
                ClickAwayProvider,
                HeadingLevelProvider,
                IconButton,
                Portal,
                ThemeProvider,
                className: className.value,
                clickAwayRefs,
                closeButtonProps: props.closeButtonProps,
                closeButtonRef,
                isOpen: props.isOpen,
                isVisible: isVisible.value,
                handleClose,
                preventAutoClose: props.preventAutoClose,
                ref: wrapperRef,
                zIndex: props.zIndex,
                children: slots.default?.() as JSXElement,
            });
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<LightboxProps>()(
            'class',
            'closeButtonProps',
            'focusElement',
            'isOpen',
            'parentElement',
            'preventAutoClose',
            'zIndex',
        ),
        emits: emitSchema,
    },
);

export default Lightbox;
