// packages/lumx-react/src/components/lightbox/LightboxContent.tsx
import { RefObject, useRef, useEffect } from 'react';

import { HeadingLevelProvider, IconButton, IconButtonProps } from '@lumx/react';
import { DIALOG_TRANSITION_DURATION } from '@lumx/react/constants';
import { GenericProps } from '@lumx/react/utils/type';

import { useFocusTrap } from '@lumx/react/hooks/useFocusTrap';
import { useDisableBodyScroll } from '@lumx/react/hooks/useDisableBodyScroll';
import { ClickAwayProvider } from '@lumx/react/utils/ClickAwayProvider';
import { mergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { useCallbackOnEscape } from '@lumx/react/hooks/useCallbackOnEscape';
import { useTransitionVisibility } from '@lumx/react/hooks/useTransitionVisibility';
import { ThemeProvider } from '@lumx/react/utils/theme/ThemeContext';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

import { Portal } from '@lumx/react/utils';

import { Lightbox as UI, BaseLightboxProps as UIProps } from '@lumx/core/js/components/Lightbox';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';

import { DIALOG_LABEL_KEY } from '@lumx/core/js/components/Dialog/constants';
import { useRegisteredId } from '@lumx/react/utils/IdsRegistryContext';

/**
 * Defines the props of the component.
 */
export interface LightboxProps extends GenericProps, ReactToJSX<UIProps> {
    /** Props to pass to the close button (minus those already set by the Lightbox props). */
    closeButtonProps?: Pick<IconButtonProps, 'label'> &
        Omit<IconButtonProps, 'label' | 'onClick' | 'icon' | 'emphasis' | 'color'>;
    /** Reference to the element that triggered modal opening to set focus on. */
    parentElement: RefObject<any>;
    /** Reference to the element that should get the focus when the lightbox opens. By default, the close button or the lightbox itself will take focus. */
    focusElement?: RefObject<HTMLElement>;
    /** On close callback. */
    onClose?(): void;
    /** Children */
    children?: React.ReactNode;
}

/**
 * Renders the core Lightbox UI, resolving its `aria-labelledby` from the ids registry.
 *
 * Must render as a descendant of the `IdsRegistryProvider` set up by `Lightbox` (which is why it is
 * its own component: the subscription hook needs to run below the provider). Internal to the
 * lightbox family - not exported from the package barrel.
 */
export const LightboxContent = forwardRef<LightboxProps, HTMLDivElement>((props, ref) => {
    const {
        children,
        className,
        closeButtonProps,
        isOpen,
        onClose,
        parentElement,
        focusElement,
        preventAutoClose,
        theme,
        zIndex,
        ...forwardedProps
    } = props;

    const childrenRef = useRef<any>(null);
    const wrapperRef = useRef<HTMLDivElement>(null);
    const closeButtonRef = useRef<HTMLButtonElement>(null);

    useDisableBodyScroll(isOpen && wrapperRef.current);

    const isVisible = useTransitionVisibility(wrapperRef, !!isOpen, DIALOG_TRANSITION_DURATION);

    // Handle focus trap.
    useFocusTrap(
        // Focus trap zone
        isOpen && wrapperRef.current,
        // Focus element (fallback on close button and then on the dialog)
        focusElement?.current || closeButtonRef.current || wrapperRef.current,
    );

    const previousOpen = useRef(isOpen);

    useEffect(() => {
        if (isOpen !== previousOpen.current) {
            previousOpen.current = isOpen;

            // Focus the parent element on close.
            if (!isOpen && parentElement && parentElement.current) {
                parentElement.current.focus();
            }
        }
    }, [isOpen, parentElement]);

    // Close lightbox on escape key pressed.
    useCallbackOnEscape(onClose);

    const clickAwayRefs = useRef([wrapperRef]);

    const labelId = useRegisteredId(DIALOG_LABEL_KEY);

    if (!isOpen && !isVisible) return null;

    return UI({
        ClickAwayProvider,
        HeadingLevelProvider,
        IconButton,
        parentElement,
        Portal,
        ThemeProvider,
        children,
        childrenRef,
        className,
        clickAwayRefs,
        closeButtonProps,
        closeButtonRef,
        focusElement,
        isOpen,
        isVisible,
        labelId,
        ref: mergeRefs(ref, wrapperRef),
        theme,
        zIndex,
        preventAutoClose,
        handleClose: onClose,
        ...forwardedProps,
    });
});

// packages/lumx-vue/src/components/lightbox/LightboxContent.tsx
import { computed, defineComponent, ref, type Ref } from 'vue';

import { Lightbox as UI } from '@lumx/core/js/components/Lightbox';
import { DIALOG_TRANSITION_DURATION } from '@lumx/core/js/constants';
import type { JSXElement } from '@lumx/core/js/types';
import { DIALOG_LABEL_KEY } from '@lumx/core/js/components/Dialog/constants';

import { Portal } from '../../utils/Portal/Portal';
import { ClickAwayProvider } from '../../utils/ClickAway/ClickAwayProvider';
import { ThemeProvider } from '../../utils/theme/ThemeProvider';
import HeadingLevelProvider from '../heading/HeadingLevelProvider';
import IconButton from '../button/IconButton';

import { useCallbackOnEscape } from '../../composables/useCallbackOnEscape';
import { useClassName } from '../../composables/useClassName';
import { useFocusTrap } from '../../composables/useFocusTrap';
import { useRegisteredId } from '../../utils/IdsRegistryContext';
import { getName } from '../../utils/VueToJSX';
import { useRestoreFocusOnClose } from '../../composables/useRestoreFocusOnClose';
import { useTransitionVisibility } from '../../composables/useTransitionVisibility';
import { useDisableBodyScroll } from '../../composables/useDisableBodyScroll';

import { emitSchema, LIGHTBOX_PROP_KEYS } from './constants';
import type { LightboxProps } from './types';

/**
 * Renders the core Lightbox UI, resolving its `aria-labelledby` from the ids registry.
 *
 * Owns the lightbox logic (focus trap, escape, transition, body scroll) and must render as a
 * descendant of the `IdsRegistryProvider` set up by `Lightbox` - the subscription composable needs
 * to run below the provider. Internal to the lightbox family - not exported from the package barrel.
 */
const LightboxContent = defineComponent(
    (props: LightboxProps, { emit, slots, attrs }) => {
        const className = useClassName(() => props.class);

        // Root div ref — used as focus zone and click-away zone
        const wrapperRef = ref<HTMLDivElement | null>(null);
        // Close button ref (passed to core; only mounted when closeButtonProps is provided)
        const closeButtonRef = ref<HTMLButtonElement | null>(null);

        const handleClose = () => emit('close');

        // Escape key closes the lightbox
        useCallbackOnEscape(
            handleClose,
            computed(() => Boolean(props.isOpen && !props.preventAutoClose)),
        );

        // Focus trap inside the lightbox root
        const focusZoneElement = computed(() => {
            if (!props.isOpen) return false as const;
            return wrapperRef.value || false;
        });

        useFocusTrap(
            focusZoneElement,
            computed(() => {
                // closeButtonRef holds a Vue component instance; unwrap to the underlying DOM element via $el
                const closeButtonEl = (closeButtonRef.value as any)?.$el ?? closeButtonRef.value;
                return props.focusElement || closeButtonEl || wrapperRef.value;
            }),
        );

        // Restore focus to parentElement when lightbox closes
        useRestoreFocusOnClose(
            computed(() => true),
            computed(() => undefined) as Ref<HTMLElement | undefined>,
            computed(() => props.parentElement) as Ref<HTMLElement | undefined>,
            wrapperRef as Ref<HTMLElement | undefined>,
            computed(() => Boolean(props.isOpen)),
        );

        // Disable body scroll when lightbox is open
        useDisableBodyScroll(computed(() => Boolean(props.isOpen)));

        // Track animation state: keeps lightbox mounted during close animation
        const isVisible = useTransitionVisibility(
            computed(() => Boolean(props.isOpen)),
            DIALOG_TRANSITION_DURATION,
        );

        // Mount guard: keep rendered while open or animating closed
        const isMounted = computed(() => props.isOpen || isVisible.value);

        // Click-away: treat the full root div as the "inside" zone
        const clickAwayRefs = computed(() => [wrapperRef]) as Ref<Array<Ref<HTMLElement | undefined>>>;

        const labelId = useRegisteredId(DIALOG_LABEL_KEY);

        return () => {
            if (!isMounted.value) return null;

            return UI({
                ...attrs,
                ClickAwayProvider,
                HeadingLevelProvider,
                IconButton,
                Portal,
                ThemeProvider,
                className: className.value,
                clickAwayRefs,
                closeButtonProps: props.closeButtonProps,
                closeButtonRef,
                isOpen: props.isOpen,
                isVisible: isVisible.value,
                labelId: labelId.value,
                handleClose,
                preventAutoClose: props.preventAutoClose,
                ref: wrapperRef,
                zIndex: props.zIndex,
                children: slots.default?.() as JSXElement,
            });
        };
    },
    {
        name: getName('LightboxContent'),
        inheritAttrs: false,
        props: LIGHTBOX_PROP_KEYS,
        emits: emitSchema,
    },
);

export default LightboxContent;
