// packages/lumx-vue/src/components/image-block/ImageCaption.tsx
import { defineComponent } from 'vue';

import { ImageCaption as UI } from '@lumx/core/js/components/ImageBlock/ImageCaption';
import { type HorizontalAlignment, type Theme } from '@lumx/core/js/constants';

import { useTheme } from '../../composables/useTheme';
import { keysOf } from '../../utils/VueToJSX';
import { FlexBox } from '../flex-box';
import { Text } from '../text';

type ImageCaptionProps = {
    as?: 'div' | 'figcaption';
    align?: HorizontalAlignment;
    baseClassName?: string;
    captionStyle?: Record<string, any>;
    class?: string;
    description?: any;
    descriptionProps?: Record<string, any>;
    tags?: any;
    theme?: Theme;
    title?: string;
    titleProps?: Record<string, any>;
    truncate?: boolean;
};

/** Internal component used to render image captions */
const ImageCaption = defineComponent(
    (props: ImageCaptionProps) => {
        const defaultTheme = useTheme();

        return () => {
            const { class: _class, theme, ...restProps } = props as any;
            return <UI {...(restProps as any)} theme={theme || defaultTheme.value} FlexBox={FlexBox} Text={Text} />;
        };
    },
    {
        name: 'LumxImageCaption',
        inheritAttrs: false,
        props: keysOf<ImageCaptionProps>()(
            'align',
            'as',
            'baseClassName',
            'captionStyle',
            'class',
            'description',
            'descriptionProps',
            'tags',
            'theme',
            'title',
            'titleProps',
            'truncate',
        ),
    },
);

export default ImageCaption;

// packages/lumx-react/src/components/image-block/ImageCaption.tsx
import { CSSProperties } from 'react';

import { FlexBox, Text, TextProps, useTheme } from '@lumx/react';
import {
    As,
    ImageCaptionPropsToOverride,
    ImageCaption as UI,
    ImageCaptionProps as UIProps,
    ImageCaptionMetadata as UIMetadataProps,
} from '@lumx/core/js/components/ImageBlock/ImageCaption';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';

type ForwardedTextProps = Omit<TextProps, 'as' | 'typography' | 'color' | 'colorVariant'>;

export type ImageCaptionMetadata = Omit<UIMetadataProps, ImageCaptionPropsToOverride> & {
    /** Props to pass to the title. */
    titleProps?: ForwardedTextProps;
    /** Props to pass to the title. */
    descriptionProps?: ForwardedTextProps;
    /** Caption custom CSS style. */
    captionStyle?: CSSProperties;
};

export type ImageCaptionProps<AS extends As = 'figcaption'> = ReactToJSX<UIProps<AS>, ImageCaptionPropsToOverride> &
    ImageCaptionMetadata & {
        /** Truncate text on title & description (no line wrapping). */
        truncate?: TextProps['truncate'];
    };

/** Internal component used to render image captions */
export const ImageCaption = <AS extends As>(props: ImageCaptionProps<AS>) => {
    const defaultTheme = useTheme();
    const { theme = defaultTheme, ...forwardedProps } = props;

    return UI({
        FlexBox,
        Text,
        theme,
        ...forwardedProps,
    });
};
