// packages/site-demo/content/product/components/inline-list/react/text-wrap-and-overflow.tsx
import { Icon, InlineList, Text } from '@lumx/react';
import { mdiEarth } from '@lumx/icons';

export default () => (
    <InlineList typography="body1" color="dark-L2" style={{ maxWidth: 275 }}>
        <Text as="span" noWrap>
            <Icon icon={mdiEarth} />
            Some text
        </Text>
        <Text as="span" truncate>
            Very very very very very long text
        </Text>
    </InlineList>
);

// packages/site-demo/content/product/components/inline-list/vue/text-wrap-and-overflow.vue
<template>
    <InlineList typography="body1" color="dark-L2" :style="{ maxWidth: '275px' }">
        <Text as="span" :no-wrap="true">
            <Icon :icon="mdiEarth" />
            Some text
        </Text>
        <Text as="span" :truncate="true">Very very very very very long text</Text>
    </InlineList>
</template>

<script setup lang="ts">
import { mdiEarth } from '@lumx/icons';
import { Icon, InlineList, Text } from '@lumx/vue';
</script>
