// packages/site-demo/content/product/components/user-block/vue/small.vue
<template>
    <UserBlock
        :theme="theme"
        name="Emmitt O. Lum"
        :name-props="{ 'aria-label': 'Emmitt O. Lum - open user profile' }"
        :fields="['Creative developer', 'Denpasar']"
        :avatar-props="{ image: 'https://i.pravatar.cc/128?img=32' }"
        size="s"
        @click="console.log"
    />
</template>

<script setup lang="ts">
import { UserBlock, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();
</script>

// packages/site-demo/content/product/components/user-block/react/small.tsx
import { UserBlock, type Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => (
    <UserBlock
        theme={theme}
        name="Emmitt O. Lum"
        nameProps={{ 'aria-label': 'Emmitt O. Lum - open user profile' }}
        fields={['Creative developer', 'Denpasar']}
        avatarProps={{ image: 'https://i.pravatar.cc/128?img=32' }}
        size="s"
        onClick={console.log}
    />
);
