// packages/site-demo/content/product/components/user-block/vue/vertical.vue
<template>
    <UserBlock
        :theme="theme"
        name="Emmitt O. Lum"
        :name-props="{ 'aria-label': 'Emmitt O. Lum - open user profile' }"
        :fields="['Creative developer', 'Denpasar']"
        :avatar-props="{ image: 'https://i.pravatar.cc/128?img=32' }"
        size="l"
        orientation="vertical"
        @click="console.log"
    />
</template>

<script setup lang="ts">
import { UserBlock, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();
</script>

// packages/site-demo/content/product/components/user-block/react/vertical.tsx
import { Orientation, Size, UserBlock } from '@lumx/react';

export const App = ({ theme }: any) => (
    <UserBlock
        theme={theme}
        name="Emmitt O. Lum"
        nameProps={{ 'aria-label': 'Emmitt O. Lum - open user profile' }}
        fields={['Creative developer', 'Denpasar']}
        avatarProps={{ image: '/demo-assets/persona.png' }}
        size={Size.l}
        orientation={Orientation.vertical}
        onClick={console.log}
    />
);
