// packages/lumx-react/src/components/table/TableRow.tsx
import React from 'react';

import classNames from 'classnames';

import { COMPONENT_PREFIX } from '@lumx/react/constants';
import { GenericProps, getRootClassName, handleBasicClasses } from '@lumx/react/utils';

/**
 * Defines the props of the component.
 */
interface TableRowProps extends GenericProps {
    /** Whether the component is clickable or not. */
    isClickable?: boolean;
    /** Whether the component is disabled or not. */
    isDisabled?: boolean;
    /** Whether the component is selected or not. */
    isSelected?: boolean;
}

/**
 * The display name of the component.
 */
const COMPONENT_NAME = `${COMPONENT_PREFIX}TableRow`;

/**
 * The default class name and classes prefix for this component.
 */
const CLASSNAME: string = getRootClassName(COMPONENT_NAME, true);

const TableRow: React.FC<TableRowProps> = ({
    children,
    className,
    disabled,
    isClickable,
    isDisabled = disabled,
    isSelected,
    ...forwardedProps
}) => (
    <tr
        {...forwardedProps}
        className={classNames(
            className,
            handleBasicClasses({
                isClickable: isClickable && !isDisabled,
                isDisabled,
                isSelected: isSelected && !isDisabled,
                prefix: CLASSNAME,
            }),
        )}
        tabIndex={isClickable && !isDisabled ? 0 : -1}
        aria-disabled={isDisabled}
    >
        {children}
    </tr>
);

TableRow.displayName = COMPONENT_NAME;

export { CLASSNAME, TableRow, TableRowProps };

// packages/lumx-vue/src/components/table/TableRow.tsx
import { computed, defineComponent, useAttrs } from 'vue';
import { TableRow as UI, type TableRowProps as UIProps, COMPONENT_NAME } from '@lumx/core/js/components/Table/TableRow';
import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { useClassName } from '../../composables/useClassName';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { JSXElement } from '@lumx/core/js/types';

export type TableRowProps = VueToJSXProps<UIProps, 'tabIndex' | 'aria-disabled'> & {
    /** Whether the component is disabled or not. */
    isDisabled?: boolean;
};

const TableRow = defineComponent(
    (props: TableRowProps, { slots }) => {
        const attrs = useAttrs();
        const className = useClassName(() => props.class);

        const { isAnyDisabled, otherProps } = useDisableStateProps(computed(() => ({ ...props, ...attrs })));

        return () => {
            return (
                <UI
                    {...otherProps.value}
                    className={className.value}
                    tabIndex={props.isClickable && !isAnyDisabled.value ? 0 : -1}
                    aria-disabled={isAnyDisabled.value}
                    children={slots.default?.() as JSXElement}
                />
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<TableRowProps>()('class', 'isClickable', 'isDisabled', 'isSelected'),
    },
);

export default TableRow;
