// packages/lumx-react/src/components/select-button/SelectButton.tsx
import React, { ElementType, type ForwardedRef, useCallback, useState } from 'react';

import { mdiMenuDown } from '@lumx/icons';
import { toggleSelection } from '@lumx/core/js/utils/select/toggleSelection';
import type { GenericProps, NamedProps } from '@lumx/core/js/types';
import {
    SelectButton as UI,
    type SelectButtonProps as UIProps,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/SelectButton';
import { type ComboboxButtonLabelDisplayMode } from '@lumx/core/js/components/Combobox/ComboboxButton';
import { CLASSNAME as COMBOBOX_POPOVER_CLASSNAME } from '@lumx/core/js/components/Combobox/ComboboxPopover';
import { type SelectButtonTranslations, type SelectListStatus } from '@lumx/core/js/utils/select/types';
import { ComponentRef } from '@lumx/react/utils/type';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { Button, type ButtonProps } from '../button';
import { Combobox, type ComboboxPopoverProps } from '../combobox';
import { wrapRenderOption } from '../combobox/wrapRenderOption';
import { InfiniteScroll } from '../../utils/InfiniteScroll';

/** Default trigger: LumX `Button` with the dropdown chevron pre-applied. */
const DefaultButton = forwardRef<ButtonProps, HTMLButtonElement>((props, ref) => (
    <Button rightIcon={mdiMenuDown} {...props} ref={ref} />
));

/** Keys managed internally — never forwarded to the trigger element. */
type OmittedKeys =
    | 'value'
    | 'children'
    | 'role'
    | 'aria-controls'
    | 'aria-haspopup'
    | 'aria-expanded'
    | 'aria-activedescendant'
    | 'ref';

/** Select-specific props common to both single and multi modes. */
interface SelectButtonSelectProps<O>
    extends ReactToJSX<
        UIProps<O>,
        'renderOption' | 'buttonProps' | 'value' | 'handleSelect' | 'listProps' | 'infiniteScrollOptions'
    > {
    /** Called to load more options (infinite scroll). */
    onLoadMore?: () => void;
    /** Called when the dropdown opens or closes. */
    onOpen?: (isOpen: boolean) => void;
    /**
     * Custom option renderer. It should return a `<SelectButton.Option>`.
     * Props `value`, `isSelected`, `description` and `key` are merged in automatically.
     */
    renderOption?: (option: O, index: number) => React.ReactNode;
}

/**
 * Forwarded trigger props for a given element `E`, minus the keys that the
 * component manages internally.
 */
type TriggerProps<E extends ElementType> = Omit<NamedProps<React.ComponentProps<E>>, OmittedKeys>;

/**
 * Common base — Select-specific props plus the ARIA / label / popover layer.
 * `as`, `ref`, `selectionType`, `value`, `onChange` are intentionally hoisted
 * to the top-level `SelectButtonProps` shape (below) so that TS can infer
 * `O`, `E`, and `S` directly from those JSX attributes.
 */
type CommonSelectButtonProps<O> = SelectButtonSelectProps<O> &
    GenericProps & {
        /** Button label, used for ARIA and as fallback when no option is selected. */
        label: string;
        /** Props forwarded to the popover. */
        popoverProps?: ComboboxPopoverProps;
        /** How the selected option is shown in the trigger. */
        labelDisplayMode?: ComboboxButtonLabelDisplayMode;
        /**
         * Status of the dropdown list (loading, error, etc.).
         * @default 'idle'
         */
        listStatus?: SelectListStatus;
        /** Screen-reader translations (loading/empty/error/option count). */
        translations?: SelectButtonTranslations;
    };

/**
 * Props for `SelectButton`.
 *
 * Polymorphic — pass `as` to render the trigger as a different component
 * (e.g. `as={IconButton}`, `as={Chip}`, `as={Link}`). With no `as`, the trigger
 * is the LumX `Button` with the dropdown chevron, so LumX `ButtonProps`
 * (`emphasis`, `size`, `leftIcon`…) are accepted. With `as`, the trigger is
 * fully replaced and only props valid for that component apply.
 *
 * Discriminated on `selectionType`:
 * - default / `'single'` → `value?: O`, `onChange?: (newValue: O) => void`.
 * - `'multiple'`         → `value?: O[]`, `onChange?: (newValue: O[]) => void`.
 *
 * `as` and `selectionType` are top-level on this type (rather than buried in
 * an intersection or union member) so that TS can infer `E` from `as` and
 * `S` from `selectionType` without explicit generic annotations at the call site.
 *
 * @typeParam O - Option object type, inferred from `options` / `getOptionId`.
 * @typeParam E - Trigger element type, inferred from `as`. Defaults to the LumX `Button`.
 * @typeParam S - Selection mode, inferred from `selectionType`. Defaults to `'single'`.
 */
export type SelectButtonProps<
    O,
    E extends ElementType = typeof DefaultButton,
    S extends 'single' | 'multiple' = 'single',
> = CommonSelectButtonProps<O> &
    TriggerProps<E> & {
        /** Customize the rendered trigger component. Inference site for `E`. */
        as?: E;
        /** Ref for the trigger element. Type follows `as`. */
        ref?: ComponentRef<E>;
        /**
         * Selection mode discriminator. Inference site for `S`.
         * Optional — defaults to `'single'`. Set to `'multiple'` to opt into
         * multi-select; this also switches `value` / `onChange` to array form.
         */
        selectionType?: S;
        /** Selected option(s). Shape depends on `selectionType`. */
        value?: S extends 'multiple' ? O[] : O;
        /** Called when the selection changes. Shape depends on `selectionType`. */
        onChange?: S extends 'multiple' ? (newValue: O[]) => void : (newValue: O) => void;
    };

/**
 * Single-selection props (`selectionType` defaults to `'single'`).
 */
export type SingleSelectButtonProps<O, E extends ElementType = typeof DefaultButton> = NamedProps<
    SelectButtonProps<O, E, 'single'>
>;

/**
 * Multi-selection props (`selectionType: 'multiple'` is required to opt in).
 */
export type MultipleSelectButtonProps<O, E extends ElementType = typeof DefaultButton> = NamedProps<
    SelectButtonProps<O, E, 'multiple'>
>;

/**
 * `React.forwardRef` re-typed to preserve our polymorphic generics
 * `<O, E, S>` (which the stock `React.forwardRef` would erase).
 */
type ForwardRefSelectButton = (
    render: (
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        props: any,
        ref: ForwardedRef<unknown>,
    ) => React.ReactNode,
) => {
    <O, E extends ElementType = typeof DefaultButton, S extends 'single' | 'multiple' = 'single'>(
        props: SelectButtonProps<O, E, S>,
    ): React.ReactNode;
    displayName?: string;
};

/**
 * A button trigger with a dropdown to select an option (single mode) or
 * options (multi mode) from a list. Polymorphic — pass `as` to customize the trigger element.
 */
export const SelectButton = (React.forwardRef as ForwardRefSelectButton)((props, ref) => {
    const {
        options,
        getOptionId,
        getOptionName,
        getOptionDescription,
        renderOption,
        getSectionId,
        renderSectionTitle,
        selectionType = DEFAULT_PROPS.selectionType,
        value,
        onChange,
        onLoadMore,
        onOpen,
        label,
        popoverProps,
        labelDisplayMode,
        listStatus,
        translations,
        as,
        ...buttonProps
    } = props;
    // The list itself doesn't scroll — its ancestor `__scroll` wrapper does. The
    // IntersectionObserver root must be the actual scrolling/clipping element, or the
    // sentinel is trivially always "intersecting" its non-clipping `<ul>` parent.
    const [scrollContainer, setScrollContainer] = useState<HTMLElement | null>(null);
    const setListElement = useCallback((listElement: HTMLElement | null) => {
        setScrollContainer(listElement?.closest<HTMLElement>(`.${COMBOBOX_POPOVER_CLASSNAME}__scroll`) ?? null);
    }, []);

    const isMultiple = selectionType === 'multiple';

    // Inject core-computed props into the consumer's renderOption result.
    const wrappedRenderOption = wrapRenderOption(renderOption);

    // Map the core's option-id selection back to the option object(s).
    const handleSelect = useCallback(
        (selectedOption: { value: string }) => {
            const next = toggleSelection(options, getOptionId, value, selectedOption?.value, isMultiple);
            onChange?.(next);
        },
        [getOptionId, isMultiple, onChange, options, value],
    );

    // If as is defined and not the Button, render as, else render DefaultButton (with mdiMenuDown right icon)
    const buttonAs = as && as !== Button ? as : DefaultButton;

    return UI(
        {
            options,
            getOptionId,
            getOptionName,
            getOptionDescription,
            renderOption: wrappedRenderOption,
            getSectionId,
            renderSectionTitle,
            value,
            selectionType,
            label,
            labelDisplayMode,
            buttonProps: { ...buttonProps, as: buttonAs, ref },
            popoverProps,
            listProps: { ref: setListElement },
            handleSelect,
            listStatus,
            onOpen,
            translations,
            onLoadMore,
            infiniteScrollOptions: { root: scrollContainer, rootMargin: '100px' },
        },
        { Combobox, InfiniteScroll },
    );
});

SelectButton.displayName = 'SelectButton';

// packages/lumx-vue/src/components/select-button/SelectButton.tsx
import {
    type ComponentPublicInstance,
    type EmitFn,
    type EmitsToProps,
    type PublicProps,
    type SlotsType,
    computed,
    defineComponent,
    ref,
} from 'vue';

import { mdiMenuDown } from '@lumx/icons';
import { type BaseSelectButtonWrapperProps } from '@lumx/core/js/utils/select/types';
import { toggleSelection } from '@lumx/core/js/utils/select/toggleSelection';
import {
    DEFAULT_PROPS,
    CLASSNAME,
    SelectButton as UI,
    type SelectButtonProps as UIProps,
} from '@lumx/core/js/components/SelectButton';
import type { ComboboxButtonProps } from '@lumx/core/js/components/Combobox/ComboboxButton';
import { CLASSNAME as COMBOBOX_POPOVER_CLASSNAME } from '@lumx/core/js/components/Combobox/ComboboxPopover';
import { InfiniteScroll } from '@lumx/vue/utils/InfiniteScroll';
import { JSXElement } from '@lumx/core/js/types';

import { keysOf, type EmitsOf } from '../../utils/VueToJSX';
import { Combobox } from '../combobox';
import { Button } from '../button';
import { useWrappedRenderOptionSlot } from '../combobox/useWrappedRenderOptionSlot';
import { useWrappedRenderSectionTitleSlot } from '../combobox/useWrappedRenderSectionTitleSlot';
import { useHasEventListener } from '../../composables/useHasEventListener';
import { useClassName } from '../../composables/useClassName';
import { useDisableStateProps } from '../../composables/useDisableStateProps';

/**
 * Props exposed to the `#button` scoped slot of `<SelectButton>`.
 *
 * `buttonProps` **must** be spread on the slot root element so that the combobox ARIA
 * attributes (`role="combobox"`, `aria-controls`, `aria-haspopup`, `aria-expanded`,
 * `aria-activedescendant`) and the internal `ref` callback reach the underlying DOM node.
 *
 * The `<Tooltip label={label}>` wrapper is always rendered around the slot root, keeping
 * accessibility semantics consistent regardless of the element returned by the slot.
 *
 * @example
 * ```html
 * <!-- IconButton trigger (no text children — use labelDisplayMode="show-tooltip") -->
 * <SelectButton label="More" label-display-mode="show-tooltip" ...>
 *   <template #button="{ buttonProps, label }">
 *     <IconButton v-bind="buttonProps" :icon="mdiDotsVertical" :label="label" :hide-tooltip="true" />
 *   </template>
 * </SelectButton>
 *
 * <!-- Chip trigger -->
 * <SelectButton label="Status" ...>
 *   <template #button="{ buttonProps, children }">
 *     <Chip v-bind="buttonProps" is-clickable>{{ children }}</Chip>
 *   </template>
 * </SelectButton>
 * ```
 */
export interface SelectButtonButtonSlotProps {
    /**
     * Merged props that **must** be spread on the slot root element.
     *
     * Contains: `role="combobox"`, `aria-controls`, `aria-haspopup="listbox"`,
     * `aria-expanded`, `aria-activedescendant=""`, the internal `ref` callback,
     * `className`, and any caller-provided button attrs.
     */
    buttonProps: Record<string, any>;
    /**
     * The configured label (always defined).
     * Useful for setting the `label` prop of `<IconButton>` or `<Tooltip>`.
     */
    label: string;
    /**
     * Resolved button children computed from `labelDisplayMode`:
     * - `'show-selection'` — selected option name, falls back to the label when nothing is selected.
     * - `'show-label'` — always the label.
     * - `'show-tooltip'` — `null` (label is surfaced only via the Tooltip; ignore this in the slot).
     */
    children: string | null;
}

/** Common props shared by single and multi modes. */
interface BaseSelectButtonProps<O = any> extends BaseSelectButtonWrapperProps<O> {
    /** Controls how the label/value is displayed in the button. */
    labelDisplayMode?: UIProps<O>['labelDisplayMode'];
    /** Props forwarded to the Combobox.Popover. */
    popoverProps?: Record<string, any>;
    /** CSS class. */
    class?: string;
}

/**
 * Single-selection props (`selectionType` defaults to `'single'`).
 * Backwards-compatible — existing consumers do not need to set `selectionType`.
 */
export interface SingleSelectButtonProps<O = any> extends BaseSelectButtonProps<O> {
    /** Selection type. Optional — defaults to `'single'`. */
    selectionType?: 'single';
    /** Selected option (or `undefined` when nothing is selected). */
    value?: O;
}

/** Multi-selection props (`selectionType: 'multiple'` is required to opt in). */
export interface MultipleSelectButtonProps<O = any> extends BaseSelectButtonProps<O> {
    /** Selection type. */
    selectionType: 'multiple';
    /** Selected options. */
    value?: O[];
}

/**
 * SelectButton props — supports both single and multi selection.
 * Discriminated on `selectionType`: when `'multiple'`, `value` is `O[]`.
 */
export type SelectButtonProps<O = any> = SingleSelectButtonProps<O> | MultipleSelectButtonProps<O>;

/**
 * SelectButton events schema
 */
/* eslint-disable @typescript-eslint/no-unused-vars */
export const emitSchema = {
    /**
     * Selection change. Payload type depends on `selectionType`:
     * - default / `'single'` → `O` (selected option).
     * - `'multiple'`         → `O[]` (toggled array).
     *
     * The runtime validator uses `unknown` since the typed payload can't be expressed
     * without the component generic. The typed payload is restored via `SelectButtonEmits`.
     */
    change: (_newValue: unknown) => true,
    /** Bottom of the options list reached — consumer should fetch the next page. */
    'load-more': () => true,
    /** Dropdown opened or closed. */
    open: (_isOpen: boolean) => true,
};
/* eslint-enable @typescript-eslint/no-unused-vars */

/**
 * SelectButton emits typed over the option type O and the selection type S.
 */
type SelectButtonEmits<O, S extends 'single' | 'multiple'> = Omit<EmitsOf<typeof emitSchema>, 'change'> & {
    change: (newValue: S extends 'multiple' ? O[] : O) => void;
};

type SingleSelectButtonPublicProps<O> = SingleSelectButtonProps<O> & EmitsToProps<SelectButtonEmits<O, 'single'>>;
type MultipleSelectButtonPublicProps<O> = MultipleSelectButtonProps<O> & EmitsToProps<SelectButtonEmits<O, 'multiple'>>;

/**
 * SelectButton component constructor with generic type attached to props.
 *
 * Vue's `defineComponent` setup-fn overload cannot carry an unbound generic from the setup
 * signature to the resulting component constructor, so the generic is layered on via cast.
 *
 * Two `new` overloads provide per-branch emit narrowing matching `SelectTextField`.
 */
export interface SelectButtonConstructor {
    new <O = any>(
        props: SingleSelectButtonPublicProps<O> & PublicProps,
    ): {
        $props: SingleSelectButtonPublicProps<O>;
        $emit: EmitFn<SelectButtonEmits<O, 'single'>>;
    };
    new <O = any>(
        props: MultipleSelectButtonPublicProps<O> & PublicProps,
    ): {
        $props: MultipleSelectButtonPublicProps<O>;
        $emit: EmitFn<SelectButtonEmits<O, 'multiple'>>;
    };
}

/**
 * A Button with a select dropdown to choose between a list of options.
 *
 * Scoped slots:
 * - `button({ buttonProps, label, content })` — replaces the default `<Button rightIcon={mdiMenuDown}>` trigger.
 *   `buttonProps` **must** be spread on the slot root so that the combobox ARIA attributes and `ref`
 *   reach the DOM node. The `<Tooltip>` wrapper is always rendered. See `SelectButtonButtonSlotProps`.
 * - `option({ option, index })` — custom option rendering inside a `<Combobox.Option>`.
 * - `sectionTitle({ sectionId, options })` — custom section header rendering.
 */
const SelectButton = defineComponent(
    (props: SelectButtonProps, { emit, slots, attrs }) => {
        // ComboboxList is a Vue component, so the ref resolves to its instance — Vue 3 auto-sets
        // `$el` to the root DOM node (the `<ul>`).
        const listRef = ref<ComponentPublicInstance | null>(null);
        // The list itself doesn't scroll — its ancestor `__scroll` wrapper does. The
        // IntersectionObserver root must be the actual scrolling/clipping element, or the
        // sentinel is trivially always "intersecting" its non-clipping `<ul>` parent.
        const scrollContainer = computed<HTMLElement | null>(
            () => listRef.value?.$el?.closest(`.${COMBOBOX_POPOVER_CLASSNAME}__scroll`) ?? null,
        );

        // Merge `class` prop with `className` attr (React-style attr from core JSX).
        const className = useClassName(() => props.class);

        /*
         * Resolve disabled state from props and any React-named attrs (`ariaDisabled`,
         * `aria-disabled`) forwarded by the core JSX layer.
         */
        const { disabledStateProps } = useDisableStateProps(
            computed(() => ({ ...props, ...attrs }) as Record<string, unknown>),
        );

        /** Adapt the 'option' scoped slots to the core JSX renderOption. */
        const renderOption = useWrappedRenderOptionSlot(slots.option);

        /** Adapt the 'sectionTitle' scoped slots to the core JSX renderSectionTitle. */
        const renderSectionTitle = useWrappedRenderSectionTitleSlot(slots.sectionTitle);

        /** Render button (default Button or custom one) */
        const renderButton = computed(
            (): ComboboxButtonProps['renderButton'] =>
                ({ className: buttonClass, children, ref: triggerRef, ...otherProps }) => {
                    const buttonProps = { class: buttonClass, ref: triggerRef, ...otherProps };

                    // Default button render
                    if (!slots.button) {
                        return (
                            <Button rightIcon={mdiMenuDown} {...buttonProps}>
                                {children}
                            </Button>
                        ) as JSXElement;
                    }

                    // Custom button render
                    return slots.button({ buttonProps, label: props.label, children }) as JSXElement;
                },
        );

        const handleSelect = (selectedOption: { value: string }) => {
            const next = toggleSelection(
                props.options,
                props.getOptionId,
                props.value,
                selectedOption?.value,
                props.selectionType === 'multiple',
            );
            emit('change', next);
        };

        /*
         * Check if a 'load-more' listener is registered on this component
         * (EmitsToProps mapping for the 'load-more' event produces 'onLoad-more').
         */
        const hasLoadMoreListener = useHasEventListener('onLoadMore') || useHasEventListener('onLoad-more');
        const onLoadMore = () => emit('load-more');

        return () => {
            const listStatus = props.listStatus ?? 'idle';

            return UI(
                {
                    options: props.options,
                    getOptionId: props.getOptionId as any,
                    getOptionName: props.getOptionName as any,
                    getOptionDescription: props.getOptionDescription as any,
                    renderOption: renderOption.value as any,
                    getSectionId: props.getSectionId as any,
                    renderSectionTitle: renderSectionTitle.value as any,
                    value: props.value,
                    selectionType: props.selectionType,
                    label: props.label,
                    labelDisplayMode: props.labelDisplayMode,
                    buttonProps: {
                        ...attrs,
                        ...disabledStateProps.value,
                        className: className.value,
                        renderButton: renderButton.value,
                    },
                    popoverProps: props.popoverProps,
                    listProps: { ref: listRef },
                    handleSelect,
                    listStatus,
                    onOpen: (isOpen: boolean) => emit('open', isOpen),
                    translations: props.translations,
                    onLoadMore: hasLoadMoreListener ? onLoadMore : undefined,
                    infiniteScrollOptions: { root: scrollContainer.value, rootMargin: '100px' },
                },
                { Combobox, InfiniteScroll },
            );
        };
    },
    {
        name: 'LumxSelectButton',
        inheritAttrs: false,
        slots: Object as SlotsType<{
            /**
             * Replaces the default `<Button rightIcon={mdiMenuDown}>` trigger.
             * `buttonProps` must be spread on the root element of the slot.
             */
            button: SelectButtonButtonSlotProps;
            /** Custom option rendering inside a `<SelectButtonOption>`. */
            option: { option: unknown; index: number };
            /** Custom section header rendering. */
            sectionTitle: { sectionId: string | undefined; options: unknown[] };
        }>,
        props: keysOf<SelectButtonProps<unknown>>()(
            'options',
            'getOptionId',
            'getOptionName',
            'getOptionDescription',
            'getSectionId',
            'selectionType',
            'value',
            'label',
            'labelDisplayMode',
            'popoverProps',
            'listStatus',
            'translations',
            'class',
        ),
        emits: emitSchema,
    },
);

export default SelectButton as unknown as SelectButtonConstructor & typeof SelectButton;
export { DEFAULT_PROPS, CLASSNAME };
