// packages/lumx-vue/src/components/time-picker-field/TimePickerField.tsx
import { computed, defineComponent, ref, watch } from 'vue';

import {
    TimePickerField as UI,
    type TimePickerFieldProps as UIProps,
    type TimePickerFieldWrapperProps,
    type TimePickerFieldOwnedSelectProps,
    DEFAULT_PROPS,
    COMPONENT_NAME,
} from '@lumx/core/js/components/TimePickerField';
import {
    buildTimeList,
    formatTime,
    getDateAtTime,
    isDateOnTime,
    parseTimeInput,
    snapTimeToBounds,
} from '@lumx/core/js/utils/time';
import { getCurrentLocale } from '@lumx/core/js/utils/locale/getCurrentLocale';

import { getName, keysOf, type ClassValue } from '../../utils/VueToJSX';
import { useClassName } from '../../composables/useClassName';
import { SelectTextField, SelectTextFieldOption } from '../select-text-field';

import type { SingleSelectTextFieldProps } from '../select-text-field/SelectTextField';

/**
 * Inherited SelectTextField props (less the parts owned by TimePickerField).
 */
type InheritedSelectTextFieldProps = Omit<SingleSelectTextFieldProps<any>, TimePickerFieldOwnedSelectProps | 'class'>;

/**
 * `TimePickerField` props.
 */
export interface TimePickerFieldProps extends InheritedSelectTextFieldProps, TimePickerFieldWrapperProps {
    /** CSS class. */
    class?: ClassValue;
}

/**
 * TimePickerField events schema.
 */
export const emitSchema = {
    /**
     * Selection change. Payload is the new `Date` whose date part is inherited
     * from the previous `value` (or today, if none) and whose time-of-day
     * matches the user selection. May be `undefined` when the field is cleared.
     */
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    change: (_newValue?: Date) => true,
};

/**
 * A select-style picker for choosing a time of day. Wraps `SelectTextField`
 * with a generated list of times built from `step`, `minTime`, and `maxTime`.
 *
 * Out-of-range options (strictly before `minTime` or after `maxTime`) remain
 * visible in the dropdown but are rendered as disabled.
 *
 * Free-form typed input (e.g. `"10:30 PM"`, `"14"`, `"930"`) is parsed on blur.
 */
const TimePickerField = defineComponent(
    (props: TimePickerFieldProps, { emit }) => {
        const className = useClassName(() => props.class);
        const locale = computed(() => props.locale ?? getCurrentLocale());
        const step = computed(() => props.step ?? DEFAULT_PROPS.step ?? 30);
        const boundsMode = computed(() => props.boundsMode ?? DEFAULT_PROPS.boundsMode);

        // Build the option list — re-computed only when bounds/step/locale change.
        const timeList = computed(() =>
            buildTimeList({
                step: step.value,
                minTime: props.minTime,
                maxTime: props.maxTime,
                locale: locale.value,
            }),
        );

        // Track the user's last non-empty typed input.
        const committedSearch = ref<string>('');

        // Resolve the option that matches the current value (by time-of-day).
        const selectedOption = computed(() => {
            const { value } = props;
            if (!value) return undefined;
            return {
                hour: value.getHours(),
                minute: value.getMinutes(),
                name: formatTime(value, locale.value),
            };
        });

        // Clamp the current value to bounds whenever enforce mode is set and value/bounds change.
        watch(
            () => [boundsMode.value, props.value, step.value, props.minTime, props.maxTime],
            () => {
                if (boundsMode.value !== 'enforce' || !props.value) return;

                const timeOfDay = {
                    hour: props.value.getHours(),
                    minute: props.value.getMinutes(),
                };
                const clamped = snapTimeToBounds(timeOfDay, step.value, props.minTime, props.maxTime);

                if (clamped.hour !== props.value.getHours() || clamped.minute !== props.value.getMinutes()) {
                    emit('change', getDateAtTime(clamped, props.value));
                }
            },
            { immediate: true },
        );

        const handleChange: UIProps['handleChange'] = (next) => {
            const date = next ? getDateAtTime(next, props.value) : undefined;
            emit('change', date);
        };

        const handleSearch: UIProps['handleSearch'] = (typed) => {
            if (typed) committedSearch.value = typed;
        };

        const handleBlur: UIProps['handleBlur'] = () => {
            const typed = committedSearch.value;
            // Reset our local typed-value tracking; SelectTextField clears its own internal copy.
            committedSearch.value = '';
            if (!typed) return;
            const parsed = parseTimeInput(typed);
            if (!parsed) return;

            // Snap to bounds if needed, then dedup against the current value.
            const time = snapTimeToBounds(parsed, step.value, props.minTime, props.maxTime);
            if (props.value && isDateOnTime(props.value, time)) return;

            emit('change', getDateAtTime(time, props.value));
        };

        return () => {
            const searchInputValue = props.value ? formatTime(props.value, locale.value) : undefined;

            const {
                value: _value,
                locale: _locale,
                step: _step,
                minTime: _minTime,
                maxTime: _maxTime,
                translations,
                class: _class,
                getOptionProps,
                ...forwardedProps
            } = props;

            return UI(
                {
                    ...(forwardedProps as any),
                    value: selectedOption.value,
                    options: timeList.value,
                    translations,
                    className: className.value,
                    handleChange,
                    handleSearch,
                    handleBlur,
                    searchInputValue,
                    getOptionProps,
                },
                { SelectTextField, Option: SelectTextFieldOption },
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<TimePickerFieldProps>()(
            'value',
            'locale',
            'step',
            'minTime',
            'maxTime',
            'boundsMode',
            'translations',
            'getOptionProps',
            'class',
            // Inherited SelectTextField props
            'label',
            'placeholder',
            'icon',
            'isDisabled',
            'aria-disabled',
            'isRequired',
            'hasError',
            'error',
            'helper',
            'id',
            'name',
            'isValid',
            'ariaLabel',
            'inputProps',
            'theme',
            'hasClearButton',
        ),
        emits: emitSchema,
    },
);

export default TimePickerField;

// packages/lumx-react/src/components/time-picker-field/TimePickerField.tsx
import React, { type SyntheticEvent, useCallback, useEffect, useMemo, useState } from 'react';

import type { HasClassName, HasTheme } from '@lumx/core/js/types';
import {
    TimePickerField as UI,
    type TimePickerFieldProps as UIProps,
    type TimePickerFieldWrapperProps,
    type TimePickerFieldOwnedSelectProps,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/TimePickerField';
import { getCurrentLocale } from '@lumx/react/utils/locale/getCurrentLocale';
import {
    buildTimeList,
    formatTime,
    getDateAtTime,
    isDateOnTime,
    parseTimeInput,
    snapTimeToBounds,
    type TimeOfDay,
} from '@lumx/core/js/utils/time';

import { SelectTextField, SingleSelectTextFieldProps } from '../select-text-field';

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * Inherited SelectTextField props (less the parts owned by TimePickerField).
 */
type InheritedSelectTextFieldProps = Omit<
    SingleSelectTextFieldProps<TimeOfDay>,
    TimePickerFieldOwnedSelectProps | 'onChange'
>;

/**
 * `TimePickerField` props.
 */
export interface TimePickerFieldProps
    extends HasClassName,
        HasTheme,
        InheritedSelectTextFieldProps,
        TimePickerFieldWrapperProps {
    /**
     * Change handler. Called with a new `Date` whose date part is inherited from
     * the previous `value` (or today, if none) and whose time-of-day matches the
     * user selection. May also be called with `undefined` when the field is
     * cleared.
     */
    onChange(value: Date | undefined, name?: string, event?: SyntheticEvent): void;
}

/**
 * A select-style picker for choosing a time of day. Wraps `SelectTextField`
 * with a generated list of times built from `step`, `minTime`, and `maxTime`.
 *
 * Out-of-range options (strictly before `minTime` or after `maxTime`) remain
 * visible in the dropdown but are rendered as disabled.
 *
 * Free-form typed input (e.g. `"10:30 PM"`, `"14"`, `"930"`) is parsed on blur.
 *
 * @param props Component props.
 * @return React element.
 */
export const TimePickerField: React.FC<TimePickerFieldProps> = (props) => {
    const {
        value,
        onChange,
        locale = getCurrentLocale(),
        step = DEFAULT_PROPS.step,
        minTime,
        maxTime,
        boundsMode = DEFAULT_PROPS.boundsMode,
        className,
        theme,
        translations,
        name,
        getOptionProps,
        ...forwardedProps
    } = props;

    // Build the option list — re-computed only when bounds/step/locale change.
    const timeList = useMemo(() => buildTimeList({ step, minTime, maxTime, locale }), [step, minTime, maxTime, locale]);

    // Track the user's typed input separately from the SelectTextField's internal search state,
    // so blur can convert it to a Date.
    const [searchValue, handleSearch] = useState<string>('');

    // Resolve the option that matches the current value (by time-of-day).
    const selectedOption = useMemo(() => {
        if (!value) return undefined;
        return { hour: value.getHours(), minute: value.getMinutes(), name: formatTime(value, locale) };
    }, [value, locale]);

    // Clamp the current value to bounds whenever enforce mode is set and value/bounds change.
    useEffect(() => {
        if (boundsMode !== 'enforce' || !value) return;

        const timeOfDay = {
            hour: value.getHours(),
            minute: value.getMinutes(),
        };
        const clamped = snapTimeToBounds(timeOfDay, minTime, maxTime, step);

        if (clamped.hour !== value.getHours() || clamped.minute !== value.getMinutes()) {
            onChange(getDateAtTime(clamped, value), name);
        }
    }, [boundsMode, value, step, minTime, maxTime, onChange, name]);

    const handleChange: UIProps['handleChange'] = useCallback(
        (next) => {
            const date = next ? getDateAtTime(next, value) : undefined;
            onChange(date, name);
        },
        [name, onChange, value],
    );

    const handleBlur: UIProps['handleBlur'] = useCallback(() => {
        if (!searchValue) return;
        const parsed = parseTimeInput(searchValue);
        // Reset our local typed-value tracking; SelectTextField clears its own internal copy.
        handleSearch('');
        if (!parsed) return;

        // Snap to bounds if needed, then dedup against the current value.
        const time = snapTimeToBounds(parsed, minTime, maxTime, step);
        if (value && isDateOnTime(value, time)) return;

        onChange(getDateAtTime(time, value), name);
    }, [maxTime, minTime, name, onChange, searchValue, step, value]);

    const searchInputValue = value ? formatTime(value, locale) : undefined;

    return UI(
        {
            ...forwardedProps,
            value: selectedOption,
            options: timeList,
            translations,
            className,
            theme,
            handleChange,
            handleSearch,
            handleBlur,
            searchInputValue,
            getOptionProps,
        },
        { SelectTextField, Option: SelectTextField.Option },
    );
};

TimePickerField.displayName = COMPONENT_NAME;
