// packages/site-demo/content/product/components/text-field/react/helper.tsx
import { TextField } from '@lumx/react';
import React, { useState } from 'react';

const App = ({ theme }: any) => {
    const [value, setValue] = useState('');

    return (
        <TextField label="Text field label" value={value} onChange={setValue} helper={'Helper text'} theme={theme}/>
    );
};

export default App;

// packages/site-demo/content/product/components/text-field/vue/helper.vue
<template>
    <TextField label="Text field label" :value="value" helper="Helper text" :theme="theme" @change="value = $event" />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { TextField, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const value = ref('');
</script>
