// packages/site-demo/content/product/components/text-field/react/max-length.tsx
import { useState } from 'react';
import { TextField, type Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => {
    const [value, setValue] = useState('');
    return (
        <TextField
            label="Text field label"
            value={value}
            onChange={setValue}
            maxLength={50}
            theme={theme}
            charCounterMessage={(n) => `${n} characters remaining`}
        />
    );

};

// packages/site-demo/content/product/components/text-field/vue/max-length.vue
<template>
    <TextField
        label="Text field label"
        :value="value"
        :max-length="50"
        :theme="theme"
        :char-counter-message="charCounterMessage"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { TextField, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const value = ref('');

const charCounterMessage = (n: number) => `${n} characters remaining`;
</script>
