// packages/lumx-react/src/components/badge/BadgeWrapper.tsx
import React, { ReactElement, ReactNode } from 'react';

import classNames from 'classnames';

import { getRootClassName } from '@lumx/react/utils/className';
import { DEFAULT_PROPS } from '@lumx/react/components/select/WithSelectContext';
import { GenericProps } from '@lumx/react/utils/type';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

export interface BadgeWrapperProps extends GenericProps {
    /** Badge. */
    badge: ReactElement;
    /** Node to display the badge on */
    children: ReactNode;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'BadgeWrapper';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

export const BadgeWrapper = forwardRef<BadgeWrapperProps, HTMLDivElement>((props, ref) => {
    const { badge, children, className, ...forwardedProps } = props;

    return (
        <div ref={ref} {...forwardedProps} className={classNames(className, CLASSNAME)}>
            {children}
            {badge && <div className={`${CLASSNAME}__badge`}>{badge}</div>}
        </div>
    );
});
BadgeWrapper.displayName = 'BadgeWrapper';
BadgeWrapper.className = CLASSNAME;
BadgeWrapper.defaultProps = DEFAULT_PROPS;

// packages/lumx-vue/src/components/badge/BadgeWrapper.tsx
import { defineComponent, useAttrs } from 'vue';
import {
    BadgeWrapper as BadgeWrapperUI,
    type BadgeWrapperProps as UIProps,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Badge/BadgeWrapper';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import type { JSXElement } from '@lumx/core/js/types';

export type BadgeWrapperProps = VueToJSXProps<UIProps>;

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

const BadgeWrapper = defineComponent(
    (props: BadgeWrapperProps, { slots }) => {
        const attrs = useAttrs();

        return () => {
            return (
                <BadgeWrapperUI
                    {...props}
                    {...attrs}
                    className={props.class}
                    badge={(props.badge || slots.badge?.()) as JSXElement}
                    children={slots.default?.() as JSXElement}
                />
            );
        };
    },
    {
        name: 'LumxBadgeWrapper',
        inheritAttrs: false,
        props: keysOf<BadgeWrapperProps>()('badge', 'class'),
    },
);

export default BadgeWrapper;
