// packages/lumx-react/src/components/badge/Badge.tsx
import { ReactNode } from 'react';

import { Badge as UI, BadgeProps as UIProps } from '@lumx/core/js/components/Badge';
import { GenericProps } from '@lumx/react/utils/type';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

/**
 * Defines the props of the component.
 */
export interface BadgeProps extends Omit<UIProps, 'children'>, GenericProps {
    /** Badge content. */
    children?: ReactNode;
}

/**
 * Badge component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Badge = forwardRef<BadgeProps, HTMLDivElement>((props, ref) => {
    return UI({ ...props, ref });
});

Badge.displayName = UI.displayName;
Badge.className = UI.className;
Badge.defaultProps = UI.defaultProps;

// packages/lumx-vue/src/components/badge/Badge.tsx
import { defineComponent, useAttrs } from 'vue';

import { Badge as BadgeUI, type BadgeProps as UIProps } from '@lumx/core/js/components/Badge';
import { type JSXElement } from '@lumx/core/js/types';

import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

export type BadgeProps = VueToJSXProps<UIProps>;

/**
 * Badge component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const Badge = defineComponent(
    (props: BadgeProps, { slots }) => {
        const attrs = useAttrs();

        return () => (
            <BadgeUI {...props} {...attrs} className={props.class} children={slots.default?.() as JSXElement} />
        );
    },
    {
        name: 'LumxBadge',
        inheritAttrs: false,
        // Redefine properties so that they come in as `props` on the `defineComponent` function
        props: keysOf<BadgeProps>()('color', 'class'),
    },
);

export default Badge;
