// packages/site-demo/content/product/components/select-text-field/react/list-error.tsx
import { useState } from 'react';
import { SelectTextField } from '@lumx/react';

const TRANSLATIONS = {
    clearLabel: 'Clear',
    showSuggestionsLabel: 'Show suggestions',
    errorMessage: 'Failed to load options',
    errorTryReloadMessage: 'Please try again later',
};

export default () => {
    const [value, onChange] = useState<{ id: string; name: string } | undefined>();
    return (
        <SelectTextField
            selectionType="single"
            label="Select a fruit"
            placeholder="Search fruits..."
            options={[]}
            filter="auto"
            getOptionId="id"
            getOptionName="name"
            value={value}
            onChange={onChange}
            listStatus="error"
            translations={TRANSLATIONS}
        />
    );
};

// packages/site-demo/content/product/components/select-text-field/vue/list-error.vue
<template>
    <SelectTextField
        selection-type="single"
        label="Select a fruit"
        placeholder="Search fruits..."
        :options="[]"
        filter="auto"
        get-option-id="id"
        get-option-name="name"
        :value="value"
        list-status="error"
        :translations="TRANSLATIONS"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { SelectTextField } from '@lumx/vue';

const TRANSLATIONS = {
    clearLabel: 'Clear',
    showSuggestionsLabel: 'Show suggestions',
    errorMessage: 'Failed to load options',
    errorTryReloadMessage: 'Please try again later',
};

const value = ref<{ id: string; name: string } | undefined>();
</script>
