// packages/site-demo/content/product/components/select-text-field/react/loading-more.tsx
import { useState } from 'react';
import { SelectTextField } from '@lumx/react';

const FRUITS = [
    { id: 'apple', name: 'Apple' },
    { id: 'banana', name: 'Banana' },
    { id: 'cherry', name: 'Cherry' },
];

const TRANSLATIONS = {
    clearLabel: 'Clear',
    showSuggestionsLabel: 'Show suggestions',
    loadingMessage: 'Loading more options...',
};

export default () => {
    const [value, onChange] = useState<(typeof FRUITS)[number] | undefined>();
    return (
        <SelectTextField
            selectionType="single"
            label="Select a fruit"
            placeholder="Search fruits..."
            options={FRUITS}
            filter="auto"
            getOptionId="id"
            getOptionName="name"
            value={value}
            onChange={onChange}
            listStatus="loadingMore"
            translations={TRANSLATIONS}
        />
    );
};

// packages/site-demo/content/product/components/select-text-field/vue/loading-more.vue
<template>
    <SelectTextField
        selection-type="single"
        label="Select a fruit"
        placeholder="Search fruits..."
        :options="FRUITS"
        filter="auto"
        get-option-id="id"
        get-option-name="name"
        :value="value"
        list-status="loadingMore"
        :translations="TRANSLATIONS"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { SelectTextField } from '@lumx/vue';

const FRUITS = [
    { id: 'apple', name: 'Apple' },
    { id: 'banana', name: 'Banana' },
    { id: 'cherry', name: 'Cherry' },
];

const TRANSLATIONS = {
    clearLabel: 'Clear',
    showSuggestionsLabel: 'Show suggestions',
    loadingMessage: 'Loading more options...',
};

const value = ref<(typeof FRUITS)[number] | undefined>();
</script>
