// packages/lumx-vue/src/components/avatar/Avatar.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    Avatar as AvatarUI,
    type AvatarProps as UIProps,
    DEFAULT_PROPS,
    element,
    type AvatarSize,
} from '@lumx/core/js/components/Avatar';
import { AspectRatio } from '@lumx/core/js/constants';
import type { GenericProps, JSXElement } from '@lumx/core/js/types';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Thumbnail, type ThumbnailProps } from '../thumbnail';

export type { AvatarSize };

export type AvatarProps = VueToJSXProps<UIProps, 'image' | 'actions' | 'badge'> & {
    /** Image URL. */
    image: string;
    /** Image alternative text. */
    alt: string;
    /** Props to pass to the link wrapping the thumbnail. */
    linkProps?: GenericProps;
    /** Custom component for the link (can be used to inject vue-router RouterLink). */
    linkAs?: 'a' | any;
    /** Props to pass to the thumbnail (minus those already set by the Avatar props). */
    thumbnailProps?: Omit<ThumbnailProps, 'image' | 'alt' | 'size' | 'theme' | 'aspectRatio'>;
};

const Avatar = defineComponent(
    (props: AvatarProps, { slots }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        return () => {
            const {
                image,
                alt,
                size = DEFAULT_PROPS.size,
                theme,
                linkProps,
                linkAs,
                thumbnailProps,
                class: className,
            } = props;
            const resolvedTheme = theme || defaultTheme.value;

            // Extract event handlers from attrs to forward to Thumbnail (not to root div)
            const { onClick, onKeyPress, ...restAttrs } = { ...attrs } as any;

            const actionsContent = slots.actions?.() as JSXElement;
            const badgeContent = slots.badge?.() as JSXElement;

            return (
                <AvatarUI
                    {...restAttrs}
                    className={className}
                    theme={resolvedTheme}
                    size={size}
                    actions={actionsContent}
                    badge={badgeContent}
                    image={
                        <Thumbnail
                            linkProps={linkProps}
                            linkAs={linkAs}
                            class={element('thumbnail')}
                            onClick={onClick}
                            onKeyPress={onKeyPress}
                            {...thumbnailProps}
                            aspectRatio={AspectRatio.square}
                            size={size}
                            image={image}
                            alt={alt}
                            theme={resolvedTheme}
                        />
                    }
                />
            );
        };
    },
    {
        name: 'LumxAvatar',
        inheritAttrs: false,
        props: keysOf<AvatarProps>()('image', 'alt', 'size', 'theme', 'linkProps', 'linkAs', 'thumbnailProps', 'class'),
    },
);

export default Avatar;

// packages/lumx-react/src/components/avatar/Avatar.tsx
import { KeyboardEventHandler, MouseEventHandler, ReactNode } from 'react';

import { AspectRatio, Theme, Thumbnail, ThumbnailProps } from '@lumx/react';

import { GenericProps } from '@lumx/react/utils/type';
import {
    Avatar as UI,
    AvatarProps as UIProps,
    AvatarSize,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
    element,
} from '@lumx/core/js/components/Avatar';
import { useTheme } from '@lumx/react/utils/theme/ThemeContext';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';

/**
 * Avatar sizes.
 */
export type { AvatarSize };

/**
 * Defines the props of the component.
 */
export interface AvatarProps extends GenericProps, ReactToJSX<UIProps, 'actions' | 'badge' | 'image'> {
    /** Action toolbar content. */
    actions?: ReactNode;
    /** Props to pass to the link wrapping the thumbnail. */
    linkProps?: React.DetailedHTMLProps<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>;
    /** Custom react component for the link (can be used to inject react router Link). */
    linkAs?: 'a' | any;
    /** On click callback. */
    onClick?: MouseEventHandler<HTMLDivElement>;
    /** On key press callback. */
    onKeyPress?: KeyboardEventHandler<HTMLDivElement>;
    /** Image alternative text. */
    alt: string;
    /** Props to pass to the thumbnail (minus those already set by the Avatar props). */
    thumbnailProps?: Omit<
        ThumbnailProps,
        'image' | 'alt' | 'size' | 'theme' | 'align' | 'fillHeight' | 'variant' | 'aspectRatio'
    >;
}

/**
 * Avatar component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Avatar = forwardRef<AvatarProps, HTMLDivElement>((props, ref) => {
    const defaultTheme = useTheme() || Theme.light;
    const {
        actions,
        alt,
        badge,
        className,
        image,
        linkProps,
        linkAs,
        onClick,
        onKeyPress,
        size = DEFAULT_PROPS.size,
        theme = defaultTheme,
        thumbnailProps,
        ...forwardedProps
    } = props;

    return UI({
        ...forwardedProps,
        className,
        theme,
        ref,
        actions,
        badge,
        size,
        image: (
            <Thumbnail
                linkProps={linkProps}
                linkAs={linkAs}
                className={element('thumbnail')}
                onClick={onClick}
                onKeyPress={onKeyPress}
                {...thumbnailProps}
                aspectRatio={AspectRatio.square}
                size={size}
                image={image}
                alt={alt}
                theme={theme}
            />
        ),
    });
});

Avatar.displayName = COMPONENT_NAME;
Avatar.className = CLASSNAME;
Avatar.defaultProps = DEFAULT_PROPS;
