// packages/site-demo/content/product/components/text-field/vue/is-clearable.vue
<template>
    <TextField
        label="Text field label"
        :value="value"
        :clear-button-props="{ label: 'Clear' }"
        :theme="theme"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { TextField, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const value = ref('Clearable value');
</script>

// packages/site-demo/content/product/components/text-field/react/is-clearable.tsx
import { useState } from 'react';
import { TextField, type Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => {
    const [value, setValue] = useState('Clearable value');
    return (
        <TextField
            label="Text field label"
            clearButtonProps={{ label: 'Clear' }}
            value={value}
            onChange={setValue}
            theme={theme}
        />
    );
};
