// packages/site-demo/content/product/components/text-field/vue/placeholder.vue
<template>
    <TextField
        label="Text field label"
        :value="value"
        placeholder="Placeholder text"
        :theme="theme"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { TextField, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const value = ref('');
</script>

// packages/site-demo/content/product/components/text-field/react/placeholder.tsx
import { TextField } from '@lumx/react';
import React, { useState } from 'react';

export const App = ({ theme }: any) => {
    const [value, setValue] = useState('');

    return (
        <TextField
            label="Text field label"
            value={value}
            onChange={setValue}
            placeholder="Placeholder text"
            theme={theme}
        />
    );
};
