// packages/site-demo/content/product/components/text-field/vue/textarea-valid.vue
<template>
    <TextField
        label="Text area label"
        :value="value"
        :multiline="true"
        :is-valid="true"
        :theme="theme"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { TextField, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const value = ref('Valid value');
</script>

// packages/site-demo/content/product/components/text-field/react/text-area-valid.tsx
import { TextField } from '@lumx/react';
import React, { useState } from 'react';

const App = ({ theme }: any) => {
    const [value, setValue] = useState('Valid value');

    return <TextField label="Text area label" value={value} onChange={setValue} isValid theme={theme} multiline/>;
};

export default App;
