// packages/site-demo/content/product/components/text-field/vue/textarea-invalid.vue
<template>
    <TextField
        label="Text area label"
        :value="value"
        :multiline="true"
        :has-error="true"
        :theme="theme"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { TextField, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const value = ref('Invalid value');
</script>

// packages/site-demo/content/product/components/text-field/react/text-area-invalid.tsx
import { TextField } from '@lumx/react';
import React, { useState } from 'react';

export const App = ({ theme }: any) => {
    const [value, setValue] = useState('Invalid value');

    return <TextField label="Text area label" value={value} onChange={setValue} hasError theme={theme} multiline />;
};
