// packages/lumx-vue/src/components/text-field/Stories/WithChips.vue
<template>
    <TextField v-bind="$attrs">
        <template #chips>
            <Chip size="s">Chip 1</Chip>
            <Chip size="s">Chip 2</Chip>
        </template>
    </TextField>
</template>

<script setup lang="ts">
import { Chip, TextField } from '@lumx/vue';

defineOptions({ inheritAttrs: false });
</script>

// packages/site-demo/content/product/components/text-field/react/with-chips.tsx
import { Chip, ChipGroup, Size, TextField } from '@lumx/react';
import React, { useState } from 'react';

export const App = ({ theme }: any) => {
    const [value, setValue] = useState('');

    return (
        <TextField
            value={value}
            onChange={setValue}
            theme={theme}
            chips={
                <ChipGroup>
                    <Chip size={Size.s}>First</Chip>
                    <Chip size={Size.s}>Second</Chip>
                    <Chip size={Size.s}>Third</Chip>
                </ChipGroup>
            }
        />
    );
};
