// packages/lumx-vue/src/components/avatar/Avatar.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    Avatar as AvatarUI,
    type AvatarProps as UIProps,
    DEFAULT_PROPS,
    element,
    type AvatarSize,
} from '@lumx/core/js/components/Avatar';
import { AspectRatio } from '@lumx/core/js/constants';
import type { GenericProps, JSXElement } from '@lumx/core/js/types';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Thumbnail, type ThumbnailProps } from '../thumbnail';

export type { AvatarSize };

export type AvatarProps = VueToJSXProps<UIProps, 'image' | 'actions' | 'badge'> & {
    /** Image URL. */
    image: string;
    /** Image alternative text. */
    alt: string;
    /** Props to pass to the link wrapping the thumbnail. */
    linkProps?: GenericProps;
    /** Custom component for the link (can be used to inject vue-router RouterLink). */
    linkAs?: 'a' | any;
    /** Props to pass to the thumbnail (minus those already set by the Avatar props). */
    thumbnailProps?: Omit<ThumbnailProps, 'image' | 'alt' | 'size' | 'theme' | 'aspectRatio'>;
};

const Avatar = defineComponent(
    (props: AvatarProps, { slots }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        return () => {
            const {
                image,
                alt,
                size = DEFAULT_PROPS.size,
                theme,
                linkProps,
                linkAs,
                thumbnailProps,
                class: className,
            } = props;
            const resolvedTheme = theme || defaultTheme.value;

            // Extract event handlers from attrs to forward to Thumbnail (not to root div)
            const { onClick, onKeyPress, ...restAttrs } = { ...attrs } as any;

            const actionsContent = slots.actions?.() as JSXElement;
            const badgeContent = slots.badge?.() as JSXElement;

            return (
                <AvatarUI
                    {...restAttrs}
                    className={className}
                    theme={resolvedTheme}
                    size={size}
                    actions={actionsContent}
                    badge={badgeContent}
                    image={
                        <Thumbnail
                            linkProps={linkProps}
                            linkAs={linkAs}
                            class={element('thumbnail')}
                            onClick={onClick}
                            onKeyPress={onKeyPress}
                            {...thumbnailProps}
                            aspectRatio={AspectRatio.square}
                            size={size}
                            image={image}
                            alt={alt}
                            theme={resolvedTheme}
                        />
                    }
                />
            );
        };
    },
    {
        name: 'LumxAvatar',
        inheritAttrs: false,
        props: keysOf<AvatarProps>()('image', 'alt', 'size', 'theme', 'linkProps', 'linkAs', 'thumbnailProps', 'class'),
    },
);

export default Avatar;

// packages/lumx-core/src/js/components/Avatar/index.tsx
import type { HasClassName, JSXElement, LumxClassName, HasTheme, CommonRef } from '../../types';
import { classNames } from '../../utils';
import { Size } from '../../constants';

/**
 * Avatar sizes.
 */
export type AvatarSize = Extract<Size, 'xxs' | 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl'>;

/**
 * Defines the props of the component.
 */
export interface AvatarProps extends HasTheme, HasClassName {
    /** Action toolbar content. */
    actions?: JSXElement;
    /** Badge. */
    badge?: JSXElement;
    /** Image URL. */
    image: JSXElement;
    /** Size variant. */
    size?: AvatarSize;
    /** Props to pass to the thumbnail (minus those already set by the Avatar props). */
    ref?: CommonRef;
}

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'Avatar';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-avatar';
export const { block, element } = classNames.bem(CLASSNAME);

/**
 * Component default props.
 */
export const DEFAULT_PROPS = {
    size: Size.m,
} as const;

/**
 * Avatar component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Avatar = (props: AvatarProps) => {
    const { actions, badge, className, image, size = DEFAULT_PROPS.size, theme, ref, ...forwardedProps } = props;

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames.join(
                className,
                block({
                    [`size-${size}`]: Boolean(size),
                    [`theme-${theme}`]: Boolean(theme),
                }),
            )}
        >
            {image}
            {actions && <div className={element('actions')}>{actions}</div>}
            {badge && <div className={element('badge')}>{badge}</div>}
        </div>
    );
};
