// packages/site-demo/content/product/components/button/react/demo6.tsx
import { Button, FlexBox, type Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => (
    <div style={{ display: 'flex', width: '100%', flexDirection: 'column', gap: 16 }}>
        <FlexBox fillSpace gap="big" orientation="horizontal">
            <Button fullWidth emphasis="high" theme={theme}>
                Single full width button
            </Button>
        </FlexBox>

        <FlexBox fillSpace gap="big" orientation="horizontal">
            <Button fullWidth emphasis="medium" theme={theme}>
                Two full width buttons
            </Button>
            <Button fullWidth emphasis="medium" theme={theme}>
                Two full width buttons
            </Button>
        </FlexBox>

        <FlexBox fillSpace gap="big" orientation="horizontal">
            <Button fullWidth emphasis="medium" theme={theme}>
                Single full width button
            </Button>
            <Button emphasis="medium" theme={theme}>
                Button
            </Button>
        </FlexBox>
    </div>
);

// packages/site-demo/content/product/components/button/vue/demo6.vue
<template>
    <div :style="{ display: 'flex', width: '100%', flexDirection: 'column', gap: '16px' }">
        <FlexBox :fill-space="true" gap="big" orientation="horizontal">
            <Button :full-width="true" emphasis="high" :theme="theme">Single full width button</Button>
        </FlexBox>

        <FlexBox :fill-space="true" gap="big" orientation="horizontal">
            <Button :full-width="true" emphasis="medium" :theme="theme">Two full width buttons</Button>
            <Button :full-width="true" emphasis="medium" :theme="theme">Two full width buttons</Button>
        </FlexBox>

        <FlexBox :fill-space="true" gap="big" orientation="horizontal">
            <Button :full-width="true" emphasis="medium" :theme="theme">Single full width button</Button>
            <Button emphasis="medium" :theme="theme">Button</Button>
        </FlexBox>
    </div>
</template>

<script setup lang="ts">
import { Button, FlexBox, type Theme } from '@lumx/vue';
defineProps<{ theme?: Theme }>();
</script>
