// packages/site-demo/content/product/components/button/react/demo4.tsx
import { mdiMenuDown, mdiPencil, mdiPlus } from '@lumx/icons';
import { Button, IconButton, type Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => (
    <>
        <Button emphasis="low" theme={theme}>
            Default
        </Button>

        <Button isDisabled emphasis="low" theme={theme}>
            Disabled
        </Button>

        <Button leftIcon={mdiPencil} emphasis="low" theme={theme}>
            With Icon
        </Button>

        <Button rightIcon={mdiMenuDown} emphasis="low" theme={theme}>
            Dropdown
        </Button>

        <IconButton label="Add" emphasis="low" icon={mdiPlus} theme={theme} />
    </>
);

// packages/site-demo/content/product/components/button/vue/demo4.vue
<template>
    <Button emphasis="low" :theme="theme">Default</Button>
    <Button :disabled="true" emphasis="low" :theme="theme">Disabled</Button>
    <Button :left-icon="mdiPencil" emphasis="low" :theme="theme">With Icon</Button>
    <Button :right-icon="mdiMenuDown" emphasis="low" :theme="theme">Dropdown</Button>
    <IconButton label="Add" emphasis="low" :icon="mdiPlus" :theme="theme" />
</template>

<script setup lang="ts">
import { mdiMenuDown, mdiPencil, mdiPlus } from '@lumx/icons';
import { Button, IconButton, type Theme } from '@lumx/vue';
defineProps<{ theme?: Theme }>();
</script>
