// packages/lumx-vue/src/components/heading/Heading.vue
<template>
    <Text v-bind="uiProps">
        <slot />
    </Text>
</template>

<script setup lang="ts">
import { computed, useAttrs } from 'vue';

import { HeadingProps, getHeadingProps } from '@lumx/core/js/components/Heading';

import { Text } from '../text';
import { useTheme } from '../../composables/useTheme';
import { useHeadingLevel } from './useHeadingLevel';

defineOptions({
    inheritAttrs: false,
});

const props = defineProps<HeadingProps>();
const attrs = useAttrs();
const defaultTheme = useTheme();
const context = useHeadingLevel();

const uiProps = computed(() => {
    const { className, ...headingProps } = getHeadingProps(
        {
            ...attrs,
            ...props,
            className: attrs.class as string,
        },
        context.headingElement,
    );

    return {
        ...headingProps,
        class: className,
        theme: props.theme || attrs.theme || defaultTheme,
    };
});
</script>

// packages/lumx-react/src/components/heading/Heading.tsx
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import {
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
    HeadingProps as UIProps,
    getHeadingProps,
} from '@lumx/core/js/components/Heading';
import { GenericProps } from '@lumx/core/js/types';

import { Text } from '../text';
import { useHeadingLevel } from './useHeadingLevel';

export interface HeadingProps extends GenericProps, UIProps {}

/**
 * Renders a heading component.
 * Extends the `Text` Component with the heading level automatically computed based on
 * the current level provided by the context.
 */
export const Heading = forwardRef<HeadingProps>((props, ref) => {
    const { children, ...otherProps } = props;
    const { headingElement } = useHeadingLevel();
    const headingProps = getHeadingProps(otherProps, headingElement);

    return (
        <Text ref={ref} {...headingProps}>
            {children}
        </Text>
    );
});

Heading.displayName = COMPONENT_NAME;
Heading.className = CLASSNAME;
Heading.defaultProps = DEFAULT_PROPS;
