// packages/lumx-vue/src/components/heading/HeadingLevelProvider.vue
<template>
    <slot />
</template>

<script setup lang="ts">
import { computed, provide, reactive, toRefs } from 'vue';
import { HeadingElement } from '@lumx/core/js/types';
import { HeadingLevelContext } from '@lumx/core/js/components/Heading/constants';
import { computeHeadingLevel } from '@lumx/core/js/components/Heading/utils';
import { HeadingLevelContextKey } from './context';
import { useHeadingLevel } from './useHeadingLevel';

defineOptions({
    name: 'HeadingLevelProvider',
});

const props = defineProps<{
    /** The heading level to start at. If left undefined, the parent context will be used, if any. */
    level?: number;
}>();

const { level: propLevel } = toRefs(props);
const parentContext = useHeadingLevel();

const nextLevel = computed(() => {
    return computeHeadingLevel(propLevel?.value, parentContext.level);
});

const headingElement = computed(() => `h${nextLevel.value}` as HeadingElement);

const context = reactive({
    level: nextLevel,
    headingElement,
});

provide(HeadingLevelContextKey, context as HeadingLevelContext);
</script>

// packages/lumx-react/src/components/heading/HeadingLevelProvider.tsx
import { ReactNode } from 'react';

import { HeadingElement } from '@lumx/react/utils/type';

import { computeHeadingLevel } from '@lumx/core/js/components/Heading/utils';

import { HeadingLevelContext } from './context';
import { useHeadingLevel } from './useHeadingLevel';

export interface HeadingLevelProviderProps {
    /** The heading level to start at. If left undefined, the parent context will be used, if any. */
    level?: number;
    /** The children to display */
    children: ReactNode;
}

/**
 * Provide a new heading level context.
 */
export const HeadingLevelProvider: React.FC<HeadingLevelProviderProps> = ({ children, level }) => {
    const { level: contextLevel } = useHeadingLevel();

    const nextLevel = computeHeadingLevel(level, contextLevel);
    const headingElement = `h${nextLevel}` as HeadingElement;

    return (
        <HeadingLevelContext.Provider value={{ level: nextLevel, headingElement }}>
            {children}
        </HeadingLevelContext.Provider>
    );
};
