// packages/site-demo/content/product/components/select-button/vue/multiple-selection.vue
<template>
    <SelectButton
        selection-type="multiple"
        label="Select fruits"
        :options="FRUITS"
        get-option-id="id"
        get-option-name="name"
        :value="value"
        @change="(newValue) => (value = newValue ?? [])"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { SelectButton } from '@lumx/vue';

const FRUITS = [
    { id: 'apple', name: 'Apple' },
    { id: 'banana', name: 'Banana' },
    { id: 'cherry', name: 'Cherry' },
    { id: 'grape', name: 'Grape' },
    { id: 'orange', name: 'Orange' },
    { id: 'peach', name: 'Peach' },
    { id: 'strawberry', name: 'Strawberry' },
];

const value = ref([FRUITS[0], FRUITS[2]]);
</script>

// packages/site-demo/content/product/components/select-button/react/multiple-selection.tsx
import { useState } from 'react';
import { SelectButton } from '@lumx/react';

const FRUITS = [
    { id: 'apple', name: 'Apple' },
    { id: 'banana', name: 'Banana' },
    { id: 'cherry', name: 'Cherry' },
    { id: 'grape', name: 'Grape' },
    { id: 'orange', name: 'Orange' },
    { id: 'peach', name: 'Peach' },
    { id: 'strawberry', name: 'Strawberry' },
];

export default () => {
    const [value, onChange] = useState([FRUITS[0], FRUITS[2]]);
    return (
        <SelectButton
            selectionType="multiple"
            label="Select fruits"
            options={FRUITS}
            getOptionId="id"
            getOptionName="name"
            value={value}
            onChange={(newValue = []) => onChange(newValue)}
        />
    );
};
