// packages/lumx-vue/.storybook/story-block/StoryBlock.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { classNames } from '@lumx/core/src/js/utils';
import isChromatic from 'chromatic/isChromatic';
import { toggleMaterialTheme } from './toggleMaterialTheme';
import '@lumx/core/scss/lumx.scss';
import './index.scss';
import 'focus-visible';

const props = defineProps<{
  context: any;
}>();

const appliedTheme = computed(() => {
    const { theme } = props.context.globals;
    return props.context.args.theme || theme;
});

// Hard code today date for stable chromatic stories snapshots.
if (props.context.parameters) {
    props.context.parameters.today = isChromatic() ? new Date('May 25 2021 01:00') : new Date();
}

const isChromaticEnv = isChromatic();

watch(() => props.context.globals.materialTheme, (newVal) => {
    toggleMaterialTheme(newVal !== 'true');
}, { immediate: true });

const classes = computed(() => classNames.join(
    'story-block',
    props.context.parameters.hasGreyBackground && 'story-block--has-grey-background',
    `story-block--theme-${appliedTheme.value}`
));
</script>

<template>
  <slot v-if="isChromaticEnv" />
  <div v-else :class="classes">
    <slot />
  </div>
</template>

// packages/lumx-react/storybook/story-block/StoryBlock.tsx
import React, { ElementType } from 'react';
import classNames from 'classnames';
import isChromatic from 'chromatic/isChromatic';
import { toggleMaterialTheme } from '@lumx/react/utils/MaterialThemeSwitcher';

import '@lumx/core/scss/lumx.scss';
import './index.scss';

import 'focus-visible';

interface StoryBlockProps {
    Story: ElementType;
    context: any;
}

const CLASSNAME = 'story-block';

export const StoryBlock: React.FC<StoryBlockProps> = (props) => {
    const { Story, context } = props;
    const { theme, materialTheme } = context.globals;
    const args = {...context.args, theme};

    // Hard code today date for stable chromatic stories snapshots.
    context.parameters.today = isChromatic() ? new Date('May 25 2021 01:00') : new Date();

    if (isChromatic()) return <Story />;

    React.useEffect(() => {
        toggleMaterialTheme(materialTheme !== 'true')
    }, [materialTheme])

    return (
        <div className={classNames(CLASSNAME, context.parameters.hasGreyBackground && `${CLASSNAME}--has-grey-background`, `${CLASSNAME}--theme-${theme}`)}>
            <Story />
        </div>
    );
};
