// packages/site-demo/content/product/components/time-picker-field/vue/locale.vue
<template>
    <TimePickerField
        label="Heure"
        locale="fr-FR"
        :value="value"
        :translations="TRANSLATIONS"
        @change="value = $event"
    />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { TimePickerField } from '@lumx/vue';

const TRANSLATIONS = {
    clearLabel: 'Effacer',
    showSuggestionsLabel: 'Afficher les suggestions',
};

const at = (hour: number, minute = 0) => {
    const d = new Date();
    d.setHours(hour, minute, 0, 0);
    return d;
};

const value = ref<Date | undefined>(at(14, 30));
</script>

// packages/site-demo/content/product/components/time-picker-field/react/locale.tsx
import { useState } from 'react';
import { TimePickerField } from '@lumx/react';

const TRANSLATIONS = {
    clearLabel: 'Effacer',
    showSuggestionsLabel: 'Afficher les suggestions',
};

const at = (hour: number, minute: number) => {
    const d = new Date();
    d.setHours(hour, minute, 0, 0);
    return d;
};

export default () => {
    const [value, onChange] = useState<Date | undefined>(at(14, 30));
    return (
        <TimePickerField label="Heure" locale="fr-FR" value={value} onChange={onChange} translations={TRANSLATIONS} />
    );
};
