// packages/lumx-vue/src/components/select-text-field/Stories/CustomRender.vue
<template>
    <SelectTextField
        selection-type="multiple"
        label="Select fruits"
        placeholder="Search fruits..."
        :options="FRUITS"
        filter="auto"
        get-option-id="id"
        get-option-name="name"
        get-section-id="category"
        :value="value"
        :translations="MULTI_TRANSLATIONS"
        @change="value = $event ?? []"
    >
        <template #chip="{ option }">
            <Chip>
                <template #before>
                    <Icon :icon="option.icon" size="xs" />
                </template>
                {{ option.name }}
            </Chip>
        </template>

        <template #sectionTitle="{ sectionId, options }">
            <Icon :icon="options[0].categoryIcon" size="xs" />
            {{ sectionId }}
        </template>

        <template #option="{ option }">
            <Combobox.Option :value="option.id">
                <template #before>
                    <Icon :icon="option.icon" size="xs" />
                </template>
                {{ option.name }}
            </Combobox.Option>
        </template>
    </SelectTextField>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { FRUITS, type Fruit } from '@lumx/core/js/components/SelectTextField/Stories';
import { MULTI_TRANSLATIONS } from '@lumx/core/js/components/SelectTextField/Tests';
import { Chip, Combobox, Icon, SelectTextField } from '@lumx/vue';

const value = ref<Fruit[]>([FRUITS[0], FRUITS[3]]);
</script>

// packages/site-demo/content/product/components/select-text-field/react/custom-render.tsx
import { useCallback, useState } from 'react';
import { Chip, Combobox, Icon, SelectTextField } from '@lumx/react';
import {
    mdiFoodApple,
    mdiFoodForkDrink,
    mdiFruitCitrus,
    mdiFruitGrapes,
    mdiFruitPineapple,
    mdiSprout,
} from '@lumx/icons';

interface Fruit {
    id: string;
    name: string;
    icon: string;
    category: string;
    categoryIcon: string;
}

const INITIAL_FRUITS: Fruit[] = [
    { id: 'apple', name: 'Apple', icon: mdiFoodApple, category: 'Pome', categoryIcon: mdiFoodApple },
    { id: 'banana', name: 'Banana', icon: mdiSprout, category: 'Tropical', categoryIcon: mdiFruitPineapple },
    {
        id: 'pineapple',
        name: 'Pineapple',
        icon: mdiFruitPineapple,
        category: 'Tropical',
        categoryIcon: mdiFruitPineapple,
    },
    { id: 'grape', name: 'Grape', icon: mdiFruitGrapes, category: 'Berry', categoryIcon: mdiFruitGrapes },
    { id: 'lemon', name: 'Lemon', icon: mdiFruitCitrus, category: 'Citrus', categoryIcon: mdiFruitCitrus },
    { id: 'orange', name: 'Orange', icon: mdiFruitCitrus, category: 'Citrus', categoryIcon: mdiFruitCitrus },
];

const TRANSLATIONS = {
    showSuggestionsLabel: 'Show suggestions',
    chipGroupLabel: 'Selected fruits',
    chipRemoveLabel: 'Remove',
};

export default () => {
    const [value, onChange] = useState<Fruit[]>([INITIAL_FRUITS[1], INITIAL_FRUITS[3]]);
    const [search, setSearch] = useState('');
    const [fruits, setFruits] = useState(INITIAL_FRUITS);

    const handleCreate = useCallback(() => {
        const newFruit: Fruit = {
            id: search.toLowerCase(),
            name: search,
            icon: mdiFoodForkDrink,
            category: 'Custom',
            categoryIcon: mdiFoodForkDrink,
        };
        setFruits((prev) => [...prev, newFruit]);
        onChange((prev) => [...prev, newFruit]);
        setSearch('');
    }, [search]);

    const canCreate = search && !fruits.some((f) => f.name.toLowerCase() === search.toLowerCase());

    return (
        <SelectTextField<Fruit>
            selectionType="multiple"
            label="Select fruits"
            placeholder="Search fruits..."
            options={fruits}
            filter="auto"
            getOptionId="id"
            getOptionName="name"
            getSectionId="category"
            value={value}
            onChange={(v) => onChange(v ?? [])}
            onSearch={setSearch}
            searchInputValue={search}
            translations={TRANSLATIONS}
            renderChip={(fruit) => <Chip before={<Icon icon={fruit.icon} size="xs" />}>{fruit.name}</Chip>}
            beforeOptions={
                canCreate ? (
                    <SelectTextField.Section>
                        <SelectTextField.Option value={`__create__${search}`} onClick={handleCreate}>
                            {`Create "${search}"`}
                        </SelectTextField.Option>
                    </SelectTextField.Section>
                ) : undefined
            }
            renderOption={(fruit) => (
                <Combobox.Option before={<Icon icon={fruit.icon} size="xs" />}>{fruit.name}</Combobox.Option>
            )}
            renderSectionTitle={(sectionId, options) => (
                <>
                    <Icon icon={options[0].categoryIcon} size="xs" />
                    {sectionId}
                </>
            )}
        />
    );
};
