// packages/site-demo/content/product/components/message/vue/demo4.vue
<template>
    <Message kind="success" has-background>
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
</template>

<script setup lang="ts">
import { Message } from '@lumx/vue';
</script>

// packages/site-demo/content/product/components/message/react/demo4.tsx
import { Message } from '@lumx/react';

export default () => (
    <Message kind="success" hasBackground>
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
);
