// packages/site-demo/content/product/components/message/vue/demo6.vue
<template>
    <Message
        v-if="isMessageDisplayed"
        kind="info"
        has-background
        :close-button-props="{ label: 'Close', onClick: () => (isMessageDisplayed = false) }"
    >
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
    <Button v-else @click="isMessageDisplayed = true">Reset message display</Button>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { Button, Message } from '@lumx/vue';
const isMessageDisplayed = ref(true);
</script>

// packages/site-demo/content/product/components/message/react/demo6.tsx
import React from 'react';
import { Button, Message } from '@lumx/react';

export default () => {
    const [isMessageDisplayed, setMessageDisplay] = React.useState(true);

    return isMessageDisplayed ? (
        <Message
            kind="info"
            hasBackground
            closeButtonProps={{ label: 'Close', onClick: () => setMessageDisplay(false) }}
        >
            <p>
                Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet,
                dui sapien tempus felis, sed cursus diam ante.
            </p>
        </Message>
    ) : (
        <Button onClick={() => setMessageDisplay(true)}>Reset message display</Button>
    );
};
