// packages/site-demo/content/product/components/message/vue/success.vue
<template>
    <Message kind="success" :has-background="true">
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
</template>

<script setup lang="ts">
import { Message } from '@lumx/vue';
</script>

// packages/site-demo/content/product/components/message/react/success.tsx
import { Message, Kind } from '@lumx/react';

export const App = () => (
    <Message kind={Kind.success} hasBackground>
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
);
