// packages/lumx-vue/src/components/progress/ProgressLinear.tsx
import { defineComponent, useAttrs } from 'vue';
import {
    ProgressLinear as ProgressLinearUI,
    type ProgressLinearProps as UIProps,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/ProgressLinear';
import { useTheme } from '../../composables/useTheme';
import { keysOf, type VueToJSXProps } from '../../utils/VueToJSX';

export type ProgressLinearProps = VueToJSXProps<UIProps, 'ref'>;

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

const ProgressLinear = defineComponent(
    (props: ProgressLinearProps) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        return () => {
            return (
                <ProgressLinearUI
                    {...props}
                    {...attrs}
                    className={props.class}
                    theme={props.theme || defaultTheme.value}
                />
            );
        };
    },
    {
        name: 'LumxProgressLinear',
        inheritAttrs: false,
        props: keysOf<ProgressLinearProps>()('class', 'theme'),
    },
);

export default ProgressLinear;

// packages/lumx-react/src/components/progress/ProgressLinear.tsx
import classNames from 'classnames';

import { Theme } from '@lumx/react';
import { GenericProps, HasTheme } from '@lumx/react/utils/type';
import { getRootClassName, handleBasicClasses } from '@lumx/core/js/utils/className';
import { useTheme } from '@lumx/react/utils/theme/ThemeContext';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

export interface ProgressLinearProps extends GenericProps, HasTheme {}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'ProgressLinear';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = getRootClassName(COMPONENT_NAME);

/**
 * Component default props.
 */
const DEFAULT_PROPS: Partial<ProgressLinearProps> = {};

/**
 * ProgressLinear component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const ProgressLinear = forwardRef<ProgressLinearProps, HTMLDivElement>((props, ref) => {
    const defaultTheme = useTheme() || Theme.light;
    const { className, theme = defaultTheme, ...forwardedProps } = props;

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames(className, handleBasicClasses({ prefix: CLASSNAME, theme }))}
        >
            <div className="lumx-progress-linear__line1" />
            <div className="lumx-progress-linear__line2" />
        </div>
    );
});
ProgressLinear.displayName = COMPONENT_NAME;
ProgressLinear.className = CLASSNAME;
ProgressLinear.defaultProps = DEFAULT_PROPS;
