// packages/site-demo/content/product/components/badge/vue/label.vue
<template>
    <Badge color="red">
        <span>4</span>
    </Badge>

    <Avatar image="https://i.pravatar.cc/128?img=32" alt="Avatar with label" size="m">
        <template #badge>
            <Badge color="red">
                <span>4</span>
            </Badge>
        </template>
    </Avatar>
</template>

<script setup lang="ts">
import { Avatar, Badge } from '@lumx/vue';
</script>

// packages/site-demo/content/product/components/badge/react/label.tsx
import { Avatar, Badge, ColorPalette, Size } from '@lumx/react';

export const App = () => (
    <>
        <Badge color={ColorPalette.red}>
            <span>4</span>
        </Badge>

        <Avatar
            image="/demo-assets/persona.png"
            alt="Avatar with label"
            size={Size.m}
            badge={
                <Badge color={ColorPalette.red}>
                    <span>4</span>
                </Badge>
            }
        />
    </>
);
