// packages/lumx-react/src/components/combobox/ComboboxOptionSkeleton.tsx
import { ReactNode, useEffect } from 'react';

import { GenericProps } from '@lumx/core/js/types';
import {
    ComboboxOptionSkeleton as UI,
    ComboboxOptionSkeletonProps as UIProps,
    ComboboxOptionSkeletonPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxOptionSkeleton';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { useComboboxContext } from './context/ComboboxContext';

/**
 * Props for Combobox.OptionSkeleton component.
 */
export interface ComboboxOptionSkeletonProps
    extends GenericProps,
        ReactToJSX<UIProps, ComboboxOptionSkeletonPropsToOverride> {
    /** Content rendered before the skeleton text (e.g. SkeletonCircle for avatar placeholders). */
    before?: ReactNode;
    /** Content rendered after the skeleton text. */
    after?: ReactNode;
    /** Override the default SkeletonTypography content entirely. */
    children?: ReactNode;
}

/**
 * Combobox.OptionSkeleton component — renders skeleton placeholder(s) inside a combobox list.
 *
 * Registers once with the combobox handle on mount (regardless of `count`). The handle
 * fires `loadingChange` / `loadingAnnouncement` events, so consumers don't need an
 * explicit `isLoading` prop on `Combobox.List`.
 *
 * Width variation across skeletons is handled by SCSS `:nth-child` rules automatically.
 *
 * @example
 * ```tsx
 * // Basic — 3 plain skeletons
 * <Combobox.List aria-label="Users">
 *     {users.map(u => <Combobox.Option key={u.id} value={u.id}>{u.name}</Combobox.Option>)}
 *     {isLoading && <Combobox.OptionSkeleton count={3} />}
 * </Combobox.List>
 *
 * // With avatar placeholder
 * {isLoading && <Combobox.OptionSkeleton count={3} before={<SkeletonCircle size="s" />} />}
 * ```
 *
 * @param props Component props.
 * @return React element(s).
 */
export const ComboboxOptionSkeleton = (props: ComboboxOptionSkeletonProps) => {
    const { handle } = useComboboxContext();
    useEffect(() => handle?.registerSkeleton(), [handle]);

    return <UI {...props} />;
};

ComboboxOptionSkeleton.displayName = COMPONENT_NAME;
ComboboxOptionSkeleton.className = CLASSNAME;

// packages/lumx-vue/src/components/combobox/ComboboxOptionSkeleton.tsx
import { defineComponent } from 'vue';

import {
    ComboboxOptionSkeleton as UI,
    type ComboboxOptionSkeletonProps as UIProps,
    type ComboboxOptionSkeletonPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxOptionSkeleton';
import type { JSXElement } from '@lumx/core/js/types';

import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useClassName } from '../../composables/useClassName';
import { useWatchDisposable } from '../../composables/useWatchDisposable';
import { useComboboxContext } from './context/ComboboxContext';

export type ComboboxOptionSkeletonProps = VueToJSXProps<UIProps, ComboboxOptionSkeletonPropsToOverride>;

/**
 * Combobox.OptionSkeleton component — renders skeleton placeholder(s) inside a combobox list.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxOptionSkeleton = defineComponent(
    (props: ComboboxOptionSkeletonProps, { slots, attrs }) => {
        const className = useClassName(() => props.class);
        const { handle } = useComboboxContext();

        // Register once with the combobox handle on mount
        useWatchDisposable(handle, (h) => h?.registerSkeleton());

        return () => {
            const before = attrs.before as JSXElement;
            const after = attrs.after as JSXElement;
            const children = slots.default?.() as JSXElement;

            return UI({
                ...attrs,
                className: className.value,
                count: props.count,
                before,
                after,
                children,
            } as any);
        };
    },
    {
        name: 'LumxComboboxOptionSkeleton',
        inheritAttrs: false,
        props: keysOf<ComboboxOptionSkeletonProps>()('hasDescription', 'count', 'class'),
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxOptionSkeleton;
