// packages/lumx-core/src/js/components/Combobox/ComboboxInput.tsx
import { mdiChevronUp, mdiChevronDown } from '@lumx/icons';
import type { CommonRef, HasClassName, HasTheme, LumxClassName } from '../../types';
import { getDisabledState } from '../../utils/disabledState';

/**
 * Defines the props for the core ComboboxInput template.
 */
export interface ComboboxInputProps extends HasClassName, HasTheme {
    /** The ID of the listbox element (for aria-controls). */
    listboxId?: string;
    /** Whether the combobox is open. */
    isOpen?: boolean;
    /** ref to the root element. */
    ref?: CommonRef;
    /** Reference to the input element. */
    inputRef?: CommonRef;
    /** Reference to the text field wrapper element. */
    textFieldRef?: CommonRef;
    /** Props for the toggle button (when provided, a chevron button is rendered). */
    toggleButtonProps?: Record<string, any>;
    /** Toggle callback for the chevron button. */
    handleToggle?(): void;
    /**
     * Controls how the combobox filters options as the user types.
     * When `'off'`, the input is rendered as `readOnly`.
     */
    filter?: 'auto' | 'manual' | 'off';
}

/**
 * Injected framework-specific components for ComboboxInput rendering.
 */
export interface ComboboxInputComponents {
    /** TextField component (framework-specific, e.g. React TextField with controlled input). */
    TextField: any;
    /** IconButton component (framework-specific, e.g. React IconButton with theme/disabled). */
    IconButton: any;
}

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'ComboboxInput';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-combobox-input';

/**
 * ComboboxInput core template.
 * Renders a TextField with combobox ARIA attributes and an optional toggle button.
 *
 * Framework-specific components (TextField, IconButton) are passed as a second argument
 * by the React/Vue wrappers.
 *
 * @param props      Component props.
 * @param components Injected framework-specific components.
 * @return JSX element.
 */
export const ComboboxInput = (props: ComboboxInputProps, { TextField, IconButton }: ComboboxInputComponents) => {
    const {
        listboxId,
        isOpen,
        ref,
        inputRef,
        textFieldRef,
        toggleButtonProps,
        handleToggle,
        filter,
        theme,
        ...forwardedProps
    } = props;

    // Compute whether the combobox is disabled (native or aria-disabled).
    const disabledState = getDisabledState(undefined, props);
    const isAnyDisabled = disabledState.disabled || disabledState['aria-disabled'] || undefined;

    return (
        <TextField
            autoComplete="off"
            readOnly={filter === 'off' || undefined}
            {...forwardedProps}
            ref={ref}
            role="combobox"
            aria-autocomplete="list"
            aria-controls={listboxId}
            aria-expanded={isOpen}
            inputRef={inputRef}
            textFieldRef={textFieldRef}
            theme={theme}
            afterElement={
                toggleButtonProps ? (
                    <IconButton
                        {...toggleButtonProps}
                        theme={theme}
                        isDisabled={isAnyDisabled}
                        emphasis="low"
                        size="s"
                        icon={isOpen ? mdiChevronUp : mdiChevronDown}
                        tabIndex={-1}
                        aria-controls={listboxId}
                        aria-expanded={isOpen}
                        onClick={handleToggle}
                    />
                ) : undefined
            }
        />
    );
};

// packages/lumx-vue/src/components/combobox/ComboboxInput.tsx
import { defineComponent, onMounted, onUnmounted, ref, watch } from 'vue';

import { ComboboxInput as UI, COMPONENT_NAME, CLASSNAME } from '@lumx/core/js/components/Combobox/ComboboxInput';
import { setupComboboxInput } from '@lumx/core/js/components/Combobox/setupComboboxInput';

import { useClassName } from '../../composables/useClassName';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import type { TextFieldProps } from '../text-field/TextField';
import { TextField } from '../text-field';
import { IconButton } from '../button';
import type { IconButtonProps } from '../button/IconButton';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxEvent } from './context/useComboboxEvent';
import { useComboboxOpen } from './context/useComboboxOpen';

/**
 * Props for Combobox.Input component.
 * Note: role, aria-autocomplete, aria-controls, aria-expanded are set internally and cannot be overridden.
 */
export type ComboboxInputProps = VueToJSXProps<TextFieldProps, 'inputRef' | 'textFieldRef'> & {
    /**
     * Props for the toggle button.
     * When provided, a chevron button will be rendered in the text field's afterElement
     * to toggle the listbox visibility.
     */
    toggleButtonProps?: Pick<IconButtonProps, 'label'> & Partial<Omit<IconButtonProps, 'label'>>;
    /** Called when an option is selected. */
    onSelect?: (option: { value: string }) => void;
    /**
     * Controls how the combobox filters options as the user types.
     *
     * - `'auto'` (default) — Options are automatically filtered client-side.
     * - `'manual'` — Filtering is the consumer's responsibility.
     * - `'off'` — Like `'manual'`, but the input is rendered as `readOnly`
     *   and `openOnFocus` defaults to `true`.
     */
    filter?: 'auto' | 'manual' | 'off';
    /**
     * When true, the combobox opens automatically when the input receives focus.
     * When false (default, unless `filter` is `'off'`), the combobox only opens
     * on click, typing, or keyboard navigation.
     *
     * @default false (true when filter is 'off')
     */
    openOnFocus?: boolean;
};

/**
 * Combobox.Input component - wraps TextField with combobox ARIA attributes.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxInput = defineComponent(
    (props: ComboboxInputProps, { emit, attrs }) => {
        const className = useClassName(() => props.class);
        const { listboxId, anchorRef, setHandle, handle } = useComboboxContext();
        const { isOpen, setIsOpen } = useComboboxOpen();

        const inputEl = ref<HTMLInputElement | null>(null);
        const textFieldEl = ref<HTMLElement | null>(null);

        // Sync the anchor ref when the text field element is set (via the adapter ref callback).
        watch(
            textFieldEl,
            (el) => {
                anchorRef.value = el;
            },
            { flush: 'sync' },
        );

        // Get the input element from the TextField component after mount
        onMounted(() => {
            const input = inputEl.value;
            if (!input) return;

            setHandle(
                setupComboboxInput(input, {
                    onSelect(option) {
                        // Update controlled value through Vue's emit flow.
                        emit('change', option.value);
                        props.onSelect?.(option);
                        emit('select', option);
                    },
                    filter: props.filter,
                    openOnFocus: props.openOnFocus,
                }),
            );
        });

        onUnmounted(() => {
            handle.value?.destroy();
            setHandle(null);
        });

        // Track whether the option list is empty to disable the toggle button.
        const optionsState = useComboboxEvent('optionsChange', undefined);

        const handleToggle = () => {
            if (optionsState.value?.optionsLength === 0) return;
            setIsOpen(!isOpen.value);
            inputEl.value?.focus();
        };

        return () => {
            const {
                toggleButtonProps,
                onSelect: _onSelect,
                filter,
                openOnFocus: _oof,
                class: _class,
                ...forwardedProps
            } = props;

            // Event handlers are framework-specific and forwarded through the core template's
            // spread to the TextField adapter. They are not in the core ComboboxInputProps type.
            const eventHandlers = {
                onChange: (value: string, name?: string, event?: Event) => emit('change', value, name, event),
                onInput: (value: string) => emit('change', value),
                onFocus: (event?: FocusEvent) => emit('focus', event),
                onBlur: (event?: FocusEvent) => emit('blur', event),
                onClear: (event?: MouseEvent) => emit('clear', event),
            };

            // Vue normalizes 'aria-disabled' prop to camelCase 'ariaDisabled'.
            // Re-map it to kebab-case for the core template which expects 'aria-disabled'.
            const { ariaDisabled: fwdAriaDisabled, ...restForwardedProps } = forwardedProps as any;

            return UI(
                {
                    ...attrs,
                    ...restForwardedProps,
                    'aria-disabled': fwdAriaDisabled ?? (attrs as any).ariaDisabled,
                    ...eventHandlers,
                    listboxId,
                    isOpen: isOpen.value,
                    filter,
                    textFieldRef: (el: HTMLElement | null) => {
                        textFieldEl.value = el;
                    },
                    inputRef: (el: HTMLInputElement | null) => {
                        inputEl.value = el;
                    },
                    toggleButtonProps,
                    handleToggle,
                    className: className.value,
                },
                { TextField, IconButton },
            );
        };
    },
    {
        name: 'LumxComboboxInput',
        inheritAttrs: false,
        props: keysOf<ComboboxInputProps>()(
            'class',
            'theme',
            'value',
            'error',
            'forceFocusStyle',
            'hasError',
            'afterElement',
            'helper',
            'icon',
            'isRequired',
            'isValid',
            'label',
            'labelProps',
            'maxLength',
            'isDisabled',
            'disabled',
            'aria-disabled',
            'multiline',
            'placeholder',
            'id',
            'clearButtonProps',
            'name',
            'type',
            'minimumRows',
            'toggleButtonProps',
            'onSelect',
            'filter',
            'openOnFocus',
        ),
        emits: {
            select: (option: { value: string }) => !!option,
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            change: (value: string, _name?: string, _event?: Event) => typeof value === 'string',
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            focus: (_event?: FocusEvent) => true,
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            blur: (_event?: FocusEvent) => true,
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            clear: (_event?: MouseEvent) => true,
        },
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxInput;
