// packages/lumx-core/src/js/components/Combobox/ComboboxButton.tsx
import type { CommonRef, HasClassName, JSXElement, LumxClassName } from '../../types';
import { classNames } from '../../utils';

/**
 * Label display mode for the ComboboxButton.
 * - `'show-selection'`: Show the selected value if available, otherwise the label.
 * - `'show-label'`: Always show the label.
 * - `'show-tooltip'`: Show nothing in the button; label appears only in tooltip.
 */
export type ComboboxButtonLabelDisplayMode = 'show-selection' | 'show-label' | 'show-tooltip';

/**
 * Defines the props for the core ComboboxButton template.
 */
export interface ComboboxButtonProps extends HasClassName {
    /** The label for the button (used for ARIA and tooltip). */
    label: string;
    /** The currently selected value to display. */
    value?: string;
    /** Controls how the label/value is displayed. */
    labelDisplayMode?: ComboboxButtonLabelDisplayMode;
    /** The ID of the listbox element (for aria-controls). */
    listboxId?: string;
    /** Whether the combobox is open. */
    isOpen?: boolean;
    /** ref to the root button element. */
    ref?: CommonRef;
}

/**
 * Injected framework-specific components for ComboboxButton rendering.
 */
export interface ComboboxButtonComponents {
    /** Button component (framework-specific, e.g. React Button with theme/disabled handling). */
    Button: any;
    /** Tooltip wrapper component. */
    Tooltip: any;
}

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'ComboboxButton';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-combobox-button';

/**
 * ComboboxButton core template.
 * Renders a Button with combobox ARIA attributes, wrapped in a Tooltip.
 *
 * Framework-specific components (Tooltip) are passed as a second argument
 * by the React/Vue wrappers.
 *
 * @param props      Component props.
 * @param components Injected framework-specific components.
 * @return JSX element.
 */
export const ComboboxButton = (props: ComboboxButtonProps, { Button, Tooltip }: ComboboxButtonComponents) => {
    const {
        className,
        label,
        value,
        labelDisplayMode = 'show-selection',
        listboxId,
        isOpen,
        ref,
        ...forwardedProps
    } = props;

    // Determine what content to display
    const showSelection = labelDisplayMode === 'show-selection';
    const tooltipOnly = labelDisplayMode === 'show-tooltip';

    const selectionLabel = showSelection && value ? value : null;
    const content: JSXElement = tooltipOnly ? null : selectionLabel || label;

    // Hide tooltip if the displayed content equals the label or when open
    const hideTooltip = label === content || isOpen;

    return (
        <Tooltip
            className={hideTooltip ? classNames.visuallyHidden() : undefined}
            label={label}
            closeMode="hide"
            ariaLinkMode="aria-labelledby"
        >
            <Button
                ref={ref}
                {...forwardedProps}
                className={classNames.join(className, CLASSNAME)}
                role="combobox"
                aria-controls={listboxId}
                aria-haspopup="listbox"
                aria-expanded={isOpen}
                aria-activedescendant=""
            >
                {content}
            </Button>
        </Tooltip>
    );
};

// packages/lumx-vue/src/components/combobox/ComboboxButton.tsx
import { defineComponent, onUnmounted, ref, useAttrs, watch } from 'vue';

import {
    ComboboxButton as UI,
    type ComboboxButtonProps as UIProps,
    type ComboboxButtonLabelDisplayMode,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxButton';
import { setupComboboxButton } from '@lumx/core/js/components/Combobox/setupComboboxButton';

import { useClassName } from '../../composables/useClassName';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Button } from '../button';
import { Tooltip } from '../tooltip';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxOpen } from './context/useComboboxOpen';

export type ComboboxButtonProps = VueToJSXProps<UIProps, 'label'> & {
    /** The label for the button (used for ARIA and tooltip). */
    label: string;
    /** The currently selected value to display. */
    value?: string;
    /** Controls how the label/value is displayed. @default 'show-selection' */
    labelDisplayMode?: ComboboxButtonLabelDisplayMode;
    /** Called when an option is selected. */
    onSelect?: (option: { value: string }) => void;
};

/**
 * Combobox.Button component - Button trigger for select-only combobox mode.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxButton = defineComponent(
    (props: ComboboxButtonProps, { emit }) => {
        const attrs = useAttrs();
        const className = useClassName(() => props.class);
        const { listboxId, anchorRef, setHandle, handle } = useComboboxContext();
        const { isOpen } = useComboboxOpen();

        const buttonRef = ref<HTMLElement | null>(null);

        // Create the combobox handle with button-mode controller on mount
        watch(
            buttonRef,
            (button) => {
                if (!button) return;
                setHandle(
                    setupComboboxButton(button as HTMLButtonElement, {
                        onSelect(option) {
                            props.onSelect?.(option);
                            emit('select', option);
                        },
                    }),
                );
                // Set anchor ref to the button element
                anchorRef.value = button;
            },
            { immediate: false },
        );

        onUnmounted(() => {
            handle.value?.destroy();
            setHandle(null);
        });

        return () => {
            const { label, value, labelDisplayMode = 'show-selection', class: _class, ...forwardedProps } = props;
            return UI(
                {
                    ...attrs,
                    ...forwardedProps,
                    label,
                    value,
                    labelDisplayMode,
                    listboxId,
                    isOpen: isOpen.value,
                    ref: (el: any) => {
                        // Handle both component instances and raw elements
                        buttonRef.value = el?.$el ?? el;
                        anchorRef.value = buttonRef.value;
                    },
                    className: className.value,
                },
                { Button, Tooltip },
            );
        };
    },
    {
        name: 'LumxComboboxButton',
        inheritAttrs: false,
        props: keysOf<ComboboxButtonProps>()(
            'class',
            'label',
            'value',
            'labelDisplayMode',
            'listboxId',
            'isOpen',
            'onSelect',
        ),
        emits: {
            select: (option: { value: string }) => !!option,
        },
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxButton;
