// packages/lumx-react/src/components/combobox/ComboboxState.tsx
import { ReactNode, useEffect, useState } from 'react';

import {
    ComboboxState as UI,
    ComboboxStateProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxState';
import { subscribeComboboxState } from '@lumx/core/js/components/Combobox/subscribeComboboxState';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { GenericBlock } from '../generic-block';
import { Text } from '../text';
import { useComboboxEvent } from './context/useComboboxEvent';
import { useComboboxContext } from './context/ComboboxContext';

/**
 * Props for Combobox.State component.
 */
export interface ComboboxStateProps extends ReactToJSX<UIProps, 'state'> {
    /** Additional content rendered after the state message. */
    children?: ReactNode;
}

/**
 * Combobox.State component - displays empty and error states for the combobox list.
 *
 * Place this component as a sibling to `Combobox.List` inside a `Combobox.Popover`:
 *
 * ```tsx
 * <Combobox.Popover>
 *   <Combobox.List aria-label="Options">{options}</Combobox.List>
 *   <Combobox.State
 *     emptyMessage="No results"
 *     errorMessage={isError ? 'Service unavailable' : undefined}
 *     errorTryReloadMessage="Please try again"
 *   />
 * </Combobox.Popover>
 * ```
 *
 * Activation rules (in priority order):
 * - **Error state**: active when `errorMessage` is provided (presence-based).
 *   Takes priority over all other states.
 * - **Loading state**: active when `loadingMessage` is provided and skeletons have been
 *   mounted for at least 500ms. Suppresses the empty state while loading.
 * - **Empty state**: active when `emptyMessage` is provided and the list has no visible options
 *   and is not loading.
 *
 * @param props Component props.
 * @return React element.
 */
export const ComboboxState = (props: ComboboxStateProps) => {
    const { handle } = useComboboxContext();
    const emptyState = useComboboxEvent('emptyChange', undefined);

    const [isLoading, setIsLoading] = useState(false);
    const [shouldAnnounce, setShouldAnnounce] = useState(false);
    const [isOpen, setIsOpen] = useState(false);

    useEffect(() => {
        if (!handle) return undefined;
        return subscribeComboboxState(handle, { setIsLoading, setShouldAnnounce, setIsOpen });
    }, [handle]);

    const state = { ...emptyState, isLoading, isOpen };

    // Only pass loadingMessage to core after the 500ms debounce threshold
    const loadingMessage = shouldAnnounce ? props.loadingMessage : undefined;

    return UI({ ...props, loadingMessage, state }, { GenericBlock, Text });
};

ComboboxState.displayName = COMPONENT_NAME;
ComboboxState.className = CLASSNAME;

// packages/lumx-vue/src/components/combobox/ComboboxState.tsx
import { defineComponent, ref } from 'vue';

import {
    ComboboxState as UI,
    type ComboboxStateProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxState';
import { subscribeComboboxState } from '@lumx/core/js/components/Combobox/subscribeComboboxState';

import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useWatchDisposable } from '../../composables/useWatchDisposable';
import { GenericBlock } from '../generic-block';
import { Text } from '../text';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxEvent } from './context/useComboboxEvent';

export type ComboboxStateProps = VueToJSXProps<UIProps, 'state'>;

/**
 * Combobox.State component - displays empty and error states for the combobox list.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxState = defineComponent(
    (props: ComboboxStateProps) => {
        const { handle } = useComboboxContext();
        const emptyState = useComboboxEvent('emptyChange', undefined);
        const isLoading = ref(false);
        const shouldAnnounce = ref(false);
        const isOpen = ref(false);

        useWatchDisposable(handle, (h) => {
            if (h) {
                return subscribeComboboxState(h, {
                    setIsLoading: (v) => {
                        isLoading.value = v;
                    },
                    setShouldAnnounce: (v) => {
                        shouldAnnounce.value = v;
                    },
                    setIsOpen: (v) => {
                        isOpen.value = v;
                    },
                });
            }
        });

        return () => {
            const state = { ...emptyState.value, isLoading: isLoading.value, isOpen: isOpen.value };
            // Only pass loadingMessage to core after the 500ms debounce threshold
            const loadingMessage = shouldAnnounce.value ? props.loadingMessage : undefined;

            return UI(
                {
                    emptyMessage: props.emptyMessage,
                    errorMessage: props.errorMessage,
                    errorTryReloadMessage: props.errorTryReloadMessage,
                    loadingMessage,
                    state,
                },
                { GenericBlock, Text: Text as any },
            );
        };
    },
    {
        name: 'LumxComboboxState',
        inheritAttrs: false,
        props: keysOf<ComboboxStateProps>()(
            'emptyMessage',
            'errorMessage',
            'errorTryReloadMessage',
            'loadingMessage',
            'class',
        ),
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxState;
