// packages/lumx-core/src/js/components/Listbox/ListboxOptionMoreInfo.tsx
import { mdiInformationOutline } from '@lumx/icons';

import type { CommonRef, HasClassName, JSXElement, LumxClassName } from '../../types';
import { classNames } from '../../utils';

/**
 * Defines the props for the core ListboxOptionMoreInfo template.
 */
export interface ListboxOptionMoreInfoProps extends HasClassName {
    /** Popover content (additional details about the option). */
    children?: JSXElement;
    /** Whether the popover is open. */
    isOpen?: boolean;
    /** ID for the popover element (used for aria-describedby on the parent option). */
    popoverId: string;
    /** Ref for the anchor element (icon button). */
    ref?: CommonRef;
    /** Mouse enter callback. */
    onMouseEnter?(): void;
    /** Mouse leave callback. */
    onMouseLeave?(): void;
    /** Props forwarded to the IconButton. */
    buttonProps?: Record<string, any>;
}

/**
 * Props that React/Vue wrappers need to re-declare with framework-specific types.
 */
export type ListboxOptionMoreInfoPropsToOverride = 'children' | 'popoverId' | 'isOpen';

/**
 * Injected framework-specific components for ListboxOptionMoreInfo rendering.
 */
export interface ListboxOptionMoreInfoComponents {
    /** IconButton component (framework-specific). */
    IconButton: any;
    /** Popover component (framework-specific). */
    Popover: any;
}

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'ComboboxOptionMoreInfo';

/**
 * Component default class name and class prefix.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-combobox-option-more-info';
const { block, element } = classNames.bem(CLASSNAME);

/**
 * ListboxOptionMoreInfo core template.
 * Renders an info icon button with a popover that shows additional details about a combobox option.
 * The popover opens on mouse hover or when the parent option is keyboard-highlighted.
 *
 * Framework-specific components (IconButton, Popover) are passed as a second argument
 * by the React/Vue wrappers.
 *
 * @param props      Component props.
 * @param components Injected framework-specific components.
 * @return JSX element.
 */
export const ListboxOptionMoreInfo = (
    props: ListboxOptionMoreInfoProps,
    { IconButton, Popover }: ListboxOptionMoreInfoComponents,
) => {
    const { children, className, isOpen, popoverId, ref, onMouseEnter, onMouseLeave, buttonProps } = props;

    return (
        <>
            <IconButton
                ref={ref}
                icon={mdiInformationOutline}
                size="s"
                {...buttonProps}
                className={block([className, buttonProps?.className])}
                emphasis="low"
                onMouseEnter={onMouseEnter}
                onMouseLeave={onMouseLeave}
                // Button plays no interactive role — only serves as a hover target and popover anchor.
                // Keyboard accessibility is handled via combobox keyboard highlighting.
                aria-hidden
                label=""
            />
            <Popover
                id={popoverId}
                className={element('popover')}
                anchorRef={ref}
                isOpen={isOpen}
                closeMode="unmount"
                closeOnEscape
                closeOnClickAway
                placement="bottom-end"
                hasArrow
            >
                {children}
            </Popover>
        </>
    );
};

// packages/lumx-vue/src/components/listbox/ListboxOptionMoreInfo.tsx
import { computed, defineComponent, ref } from 'vue';

import { useClassName } from '../../composables/useClassName';

import {
    ListboxOptionMoreInfo as UI,
    type ListboxOptionMoreInfoProps as UIProps,
    type ListboxOptionMoreInfoPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Listbox/ListboxOptionMoreInfo';
import type { JSXElement } from '@lumx/core/js/types';

import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { IconButton } from '../button';
import { Popover } from '../popover';
import { useListboxOptionContext } from './context/ListboxOptionContext';
import { useListboxContext } from './context/ListboxContext';
import { useListboxEvent } from './context/useListboxEvent';

export type ListboxOptionMoreInfoProps = VueToJSXProps<
    UIProps,
    ListboxOptionMoreInfoPropsToOverride | 'onMouseEnter' | 'onMouseLeave' | 'buttonProps'
> & {
    /** Callback when the popover opens or closes. */
    onToggle?: (isOpen: boolean) => void;
};

/**
 * Combobox.OptionMoreInfo component.
 *
 * Displays an info icon button on a combobox option that shows a popover with additional details.
 * The popover opens on mouse hover over the icon or when the parent option is keyboard-highlighted.
 *
 * Must be placed in the `after` slot of a `Combobox.Option`.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ListboxOptionMoreInfo = defineComponent(
    (props: ListboxOptionMoreInfoProps, { slots }) => {
        const mergedClassName = useClassName(() => props.class);

        // Ref to the IconButton component instance.
        const iconButtonRef = ref<any>(null);

        // Resolved DOM element (<button>) used as the popover anchor.
        const anchorEl = computed<HTMLElement | undefined>(() => iconButtonRef.value?.$el ?? undefined);

        const isHovered = ref(false);

        // Get the parent option ID from the option context
        const { optionId } = useListboxOptionContext();

        // Subscribe to active descendant changes for keyboard highlight detection
        const { list } = useListboxContext();
        const activeDescendantId = useListboxEvent(list, 'activeDescendantChange', null);

        const popoverId = `${optionId}-more-info`;

        /**
         * IconButton adapter (closure) that maps core `onMouseEnter`/`onMouseLeave`
         * → Vue `onMouseenter`/`onMouseleave`
         */
        function IconButtonAdapter(coreProps: any) {
            const { onMouseEnter, onMouseLeave, ...rest } = coreProps;
            return (
                <IconButton
                    ref={iconButtonRef}
                    {...{ onMouseenter: onMouseEnter, onMouseleave: onMouseLeave }}
                    {...rest}
                />
            );
        }
        /**
         * Adapter for Popover (closure): `anchorRef` with the resolved DOM element
         */
        const PopoverAdapter = (coreProps: any, { slots: popoverSlots }: any) => {
            const { anchorRef: _coreAnchorRef, ...rest } = coreProps;
            return (
                <Popover anchorRef={anchorEl} {...rest}>
                    {popoverSlots}
                </Popover>
            );
        };

        return () => {
            const isKeyboardHighlighted = activeDescendantId.value === optionId;
            const isOpen = isHovered.value || isKeyboardHighlighted;
            const children = slots.default?.() as JSXElement;

            return UI(
                {
                    // Pass `undefined` for the core template's `ref` prop. The core template
                    // passes `ref` to `<IconButton ref={ref}>`, but if we pass `iconButtonRef`
                    // here, Vue would bind the outer functional component's VNode ref to
                    // the same target, resolving to a Text node (due to Tooltip fragments)
                    // and overriding the adapter's inner `ref={iconButtonRef}` binding.
                    // By passing `undefined`, the outer VNode has no ref and only the adapter's
                    // inner ref binding takes effect.
                    ref: undefined,
                    className: mergedClassName.value,
                    isOpen,
                    popoverId,
                    children,
                    onMouseEnter: () => {
                        isHovered.value = true;
                    },
                    onMouseLeave: () => {
                        isHovered.value = false;
                    },
                },
                { IconButton: IconButtonAdapter, Popover: PopoverAdapter },
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<ListboxOptionMoreInfoProps>()('class', 'onToggle'),
        emits: {
            toggle: (isOpen: boolean) => typeof isOpen === 'boolean',
        },
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ListboxOptionMoreInfo;
