// packages/lumx-react/src/components/listbox/ListboxOptionAction.tsx
import { ElementType, ReactNode, SyntheticEvent, useEffect } from 'react';

import { ComponentRef, HasClassName, HasPolymorphicAs, HasRequiredLinkHref } from '@lumx/react/utils/type';
import {
    ListboxOptionAction as UI,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Listbox/ListboxOptionAction';
import { forwardRefPolymorphic } from '@lumx/react/utils/react/forwardRefPolymorphic';
import { useId } from '@lumx/react/hooks/useId';
import { useDisableStateProps } from '@lumx/react/utils/disabled/useDisableStateProps';
import { useListboxContext } from './context/ListboxContext';

/**
 * Combobox.OptionAction props.
 *
 * Polymorphic component — use `as` to render as a different element or component
 * (e.g., `as={IconButton}`, `as={Button}`). Defaults to `'button'`.
 */
export type ListboxOptionActionProps<E extends ElementType = 'button'> = HasPolymorphicAs<E> &
    HasClassName &
    HasRequiredLinkHref<E> & {
        /** Content of the action (icon, label, etc.). Optional when using a polymorphic `as` that provides its own content (e.g., IconButton). */
        children?: ReactNode;
        /** Whether the action is disabled. */
        isDisabled?: boolean;
        /** On click callback. */
        onClick?(evt: SyntheticEvent): void;
    };

/**
 * Combobox.OptionAction sub-component.
 *
 * Renders a secondary action button within a combobox option row (grid mode).
 * Each action renders as a `role="gridcell"` element, enabling 2D keyboard
 * navigation (ArrowLeft/Right to move between the option and its actions).
 *
 * Renders nothing outside grid mode (`type="grid"` on the parent list): without the grid
 * navigation, an action would not be reachable by keyboard and would break the listbox pattern.
 *
 * Uses the same polymorphic pattern as ListItem.Action (forwardRefPolymorphic + RawClickable).
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const ListboxOptionAction = Object.assign(
    forwardRefPolymorphic(
        <E extends ElementType = 'button'>(props: ListboxOptionActionProps<E>, ref: ComponentRef<E>) => {
            const { disabledStateProps, otherProps } = useDisableStateProps(props as any);
            const { children, className, as: Element = 'button', onClick, ...forwardedProps } = otherProps as any;
            const actionId = useId();
            const { type } = useListboxContext();
            const isGrid = type === 'grid';

            useEffect(() => {
                if (!isGrid) {
                    console.warn(
                        `[@lumx/react/${COMPONENT_NAME}] Option actions are only supported in grid mode (set type="grid" on the parent list); the action is not rendered.`,
                    );
                }
            }, [isGrid]);

            if (!isGrid) return null;

            return UI({
                as: Element as any,
                ...forwardedProps,
                ...disabledStateProps,
                id: actionId,
                className,
                handleClick: onClick,
                ref,
                children,
            });
        },
    ),
    { displayName: COMPONENT_NAME, className: CLASSNAME },
);

// packages/lumx-vue/src/components/listbox/ListboxOptionAction.tsx
import { defineComponent } from 'vue';

import {
    ListboxOptionAction as UI,
    type ListboxOptionActionProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Listbox/ListboxOptionAction';
import type { JSXElement } from '@lumx/core/js/types';

import { useId } from '../../composables/useId';
import { useClassName } from '../../composables/useClassName';
import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useListboxContext } from './context/ListboxContext';

export type ListboxOptionActionProps = Pick<VueToJSXProps<UIProps>, 'isDisabled' | 'class'> & {
    /** On click callback. */
    onClick?: (evt: MouseEvent) => void;
};

/**
 * Combobox.OptionAction sub-component.
 *
 * Renders a secondary action button within a combobox option row (grid mode).
 *
 * Renders nothing outside grid mode (`type="grid"` on the parent list): without the grid
 * navigation, an action would not be reachable by keyboard and would break the listbox pattern.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ListboxOptionAction = defineComponent(
    (props: ListboxOptionActionProps, { slots, attrs }) => {
        const actionId = useId();
        const className = useClassName(() => props.class);
        const { disabledStateProps, otherProps } = useDisableStateProps(props as any);
        const listboxContext = useListboxContext();
        let warned = false;

        return () => {
            if (listboxContext.type !== 'grid') {
                if (!warned) {
                    warned = true;
                    console.warn(
                        `[@lumx/vue/${COMPONENT_NAME}] Option actions are only supported in grid mode (set type="grid" on the parent list); the action is not rendered.`,
                    );
                }
                return null;
            }
            const children = slots.default?.() as JSXElement;
            const { onClick, class: _class, ...forwardedProps } = otherProps.value as any;
            return UI({
                as: 'button' as any,
                ...forwardedProps,
                ...attrs,
                ...disabledStateProps.value,
                id: actionId,
                className: className.value,
                handleClick: onClick,
                children,
            });
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<ListboxOptionActionProps>()('isDisabled', 'onClick', 'class'),
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ListboxOptionAction;
