// packages/site-demo/content/product/components/select-button/react/custom-trigger.tsx
import { useState } from 'react';
import { Chip, Icon, IconButton, Link, SelectButton } from '@lumx/react';
import { mdiFoodApple, mdiMenuDown } from '@lumx/icons';

const FRUITS = ['Apple', 'Banana', 'Cherry', 'Grape', 'Orange'];

export default () => {
    const [defaultValue, setDefaultValue] = useState<string>();
    const [iconValue, setIconValue] = useState<string>();
    const [chipValue, setChipValue] = useState<string>();
    const [linkValue, setLinkValue] = useState<string>();

    return (
        <>
            <SelectButton
                label="Select a fruit"
                options={FRUITS}
                getOptionId={String}
                value={defaultValue}
                onChange={setDefaultValue}
                size="s"
                emphasis="low"
                color="red"
            />

            <SelectButton
                as={IconButton}
                label="Select a fruit"
                labelDisplayMode="show-tooltip"
                options={FRUITS}
                getOptionId={String}
                value={iconValue}
                onChange={setIconValue}
                emphasis="medium"
                icon={mdiFoodApple}
                isSelected={!!iconValue}
            />

            <SelectButton
                as={Chip}
                label="Select a fruit"
                options={FRUITS}
                getOptionId={String}
                value={chipValue}
                onChange={setChipValue}
                isClickable
                isSelected={!!chipValue}
                after={<Icon icon={mdiMenuDown} />}
                renderOption={(fruit) => (
                    <SelectButton.Option value={fruit}>
                        <strong>{fruit}</strong>
                    </SelectButton.Option>
                )}
            />

            <SelectButton
                as={Link}
                label="Select a fruit"
                options={FRUITS}
                getOptionId={String}
                value={linkValue}
                onChange={setLinkValue}
                rightIcon={mdiMenuDown}
            />
        </>
    );
};

// packages/site-demo/content/product/components/select-button/vue/custom-trigger.vue
<template>
    <!-- Default select button (customized with the basic Button props) -->
    <SelectButton
        label="Select a fruit"
        :options="FRUITS"
        :get-option-id="String"
        :value="defaultValue"
        @change="(newValue) => (defaultValue = newValue)"
        size="s"
        emphasis="low"
        color="red"
    />

    <!-- IconButton select button -->
    <SelectButton
        label="Select a fruit"
        label-display-mode="show-tooltip"
        :options="FRUITS"
        :get-option-id="String"
        :value="iconValue"
        @change="(newValue) => (iconValue = newValue)"
    >
        <template #button="{ buttonProps, label }">
            <IconButton
                v-bind="buttonProps"
                emphasis="medium"
                :icon="mdiFoodApple"
                :label="label"
                :is-selected="!!iconValue"
            />
        </template>
    </SelectButton>

    <!-- Chip select button -->
    <SelectButton
        label="Select a fruit"
        :options="FRUITS"
        :get-option-id="String"
        :value="chipValue"
        @change="(newValue) => (chipValue = newValue)"
    >
        <template #button="{ buttonProps, children }">
            <Chip v-bind="buttonProps" :is-clickable="true" :is-selected="!!chipValue">
                {{ children }}
                <template #after>
                    <Icon :icon="mdiMenuDown" />
                </template>
            </Chip>
        </template>
        <template #option="{ option }">
            <SelectButtonOption :value="option">
                <strong>{{ option }}</strong>
            </SelectButtonOption>
        </template>
    </SelectButton>

    <!-- Link select button (visually a link but functionally a button) -->
    <SelectButton
        label="Select a fruit"
        :options="FRUITS"
        :get-option-id="String"
        :value="linkValue"
        @change="(newValue) => (linkValue = newValue)"
    >
        <template #button="{ buttonProps, children }">
            <Link v-bind="buttonProps">{{ children }} <Icon :icon="mdiMenuDown" /></Link>
        </template>
    </SelectButton>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { Chip, Icon, IconButton, Link, SelectButton, SelectButtonOption } from '@lumx/vue';
import { mdiFoodApple, mdiMenuDown } from '@lumx/icons';

const FRUITS = ['Apple', 'Banana', 'Cherry', 'Grape', 'Orange'];

const defaultValue = ref<string>();
const iconValue = ref<string>();
const chipValue = ref<string>();
const linkValue = ref<string>();
</script>
