// packages/site-demo/content/product/components/menu-button/react/menu-items.tsx
import { MenuButton, MenuItem, MenuDivider } from '@lumx/react';
import { mdiDelete, mdiFileDocumentOutline, mdiOpenInNew, mdiPencil } from '@lumx/icons';

export default () => (
    <MenuButton label="Item options">
        <MenuItem icon={mdiPencil} onClick={() => alert('Edit')}>
            Edit
        </MenuItem>
        <MenuItem icon={mdiDelete} color="red" onClick={() => alert('Delete')}>
            Delete
        </MenuItem>
        <MenuDivider />
        <MenuItem
            icon={mdiFileDocumentOutline}
            afterIcon={mdiOpenInNew}
            actionProps={{ as: 'a', href: 'https://example.com/docs', target: '_blank' }}
        >
            Documentation
        </MenuItem>
    </MenuButton>
);

// packages/site-demo/content/product/components/menu-button/vue/menu-items.vue
<template>
    <MenuButton label="Item options">
        <MenuItem :icon="mdiPencil" @click="() => alert('Edit')">Edit</MenuItem>
        <MenuItem :icon="mdiDelete" color="red" @click="() => alert('Delete')">Delete</MenuItem>
        <MenuDivider />
        <MenuItem :icon="mdiFileDocumentOutline" :after-icon="mdiOpenInNew">
            <template #action="{ actionProps }">
                <a v-bind="actionProps" href="https://example.com/docs" target="_blank">Documentation</a>
            </template>
        </MenuItem>
    </MenuButton>
</template>

<script setup lang="ts">
import { MenuButton, MenuItem, MenuDivider } from '@lumx/vue';
import {
    mdiBookOpenOutline,
    mdiContentCopy,
    mdiDelete,
    mdiFileDocumentOutline,
    mdiOpenInNew,
    mdiPencil,
} from '@lumx/icons';

const alert = window.alert;
</script>
