// packages/lumx-react/src/components/link/Link.tsx
import { Icon } from '@lumx/react';
import { GenericProps } from '@lumx/react/utils/type';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { wrapChildrenIconWithSpaces } from '@lumx/react/utils/react/wrapChildrenIconWithSpaces';
import { useDisableStateProps } from '@lumx/react/utils/disabled';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { classNames } from '@lumx/core/js/utils';
import { Link as UI, LinkProps as UIProps, CLASSNAME, COMPONENT_NAME } from '@lumx/core/js/components/Link';

const { element } = classNames.bem(CLASSNAME);

/**
 * Defines the props of the component.
 */
export interface LinkProps extends GenericProps, ReactToJSX<UIProps> {
    /**
     * Left icon (SVG path).
     * @deprecated Instead, simply nest `<Icon />` in the children
     */
    leftIcon?: string;
    /** Click handler. */
    onClick?: (event: React.MouseEvent) => void;
    /**
     * Right icon (SVG path).
     * @deprecated Instead, simply nest `<Icon />` in the children
     */
    rightIcon?: string;
    /** Children */
    children?: React.ReactNode;
}

/**
 * Link component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Link = forwardRef<LinkProps, HTMLAnchorElement | HTMLButtonElement>((props, ref) => {
    const { disabledStateProps, otherProps } = useDisableStateProps(props);
    const { children, leftIcon, rightIcon, linkAs, onClick, ...forwardedProps } = otherProps;

    return UI({
        ref,
        ...disabledStateProps,
        ...forwardedProps,
        linkAs,
        handleClick: onClick,
        children: wrapChildrenIconWithSpaces(
            <>
                {leftIcon && <Icon icon={leftIcon} className={element('left-icon')} />}
                {children && <span className={element('content')}>{children}</span>}
                {rightIcon && <Icon icon={rightIcon} className={element('right-icon')} />}
            </>,
        ),
    });
});

Link.displayName = COMPONENT_NAME;
Link.className = CLASSNAME;

// packages/lumx-vue/src/components/link/Link.tsx
import { computed, defineComponent, toRaw, useAttrs, useSlots } from 'vue';

import { Link as LinkUI, type LinkProps as UIProps, CLASSNAME, COMPONENT_NAME } from '@lumx/core/js/components/Link';

import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { useClassName } from '../../composables/useClassName';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { JSXElement } from '@lumx/core/js/types';
import { classNames } from '@lumx/core/js/utils';

export type LinkProps = VueToJSXProps<UIProps>;

export const emitSchema = {
    click: (event: MouseEvent) => event instanceof MouseEvent,
};

const { element } = classNames.bem(CLASSNAME);

/**
 * Link component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const Link = defineComponent(
    (props: LinkProps, { emit }) => {
        const slots = useSlots();
        const attrs = useAttrs();
        const className = useClassName(() => props.class);

        const { isAnyDisabled, disabledStateProps, otherProps } = useDisableStateProps(
            computed(() => ({ ...props, ...attrs })),
        );

        const handleClick = (event: MouseEvent) => {
            if (isAnyDisabled.value) {
                return;
            }

            emit('click', event);
        };

        return () => {
            const { linkAs, ...rest } = otherProps.value;
            return (
                <LinkUI
                    {...rest}
                    linkAs={toRaw(linkAs)}
                    {...disabledStateProps.value}
                    className={className.value}
                    handleClick={handleClick as any}
                    children={(<span className={element('content')}>{slots.default?.()}</span>) as JSXElement}
                />
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<LinkProps>()(
            'color',
            'colorVariant',
            'href',
            'isDisabled',
            'disabled',
            'linkAs',
            'target',
            'typography',
            'class',
            'aria-disabled',
        ),
        emits: emitSchema,
    },
);

export default Link;
