// packages/site-demo/content/product/components/list/vue/clickable.vue
<template>
    <List>
        <ListItem size="tiny" :link-props="{ href: '#' }"> Clickable list item </ListItem>
        <ListItem size="tiny" :link-props="{ href: '#' }" :is-disabled="true"> Disabled clickable list item </ListItem>
        <ListItem size="tiny" :link-props="{ href: '#' }" :is-highlighted="true">
            Highlighted clickable list item
        </ListItem>
        <ListItem size="tiny" :link-props="{ href: '#' }" :is-selected="true"> Selected clickable list item </ListItem>
    </List>
</template>

<script setup lang="ts">
import { List, ListItem } from '@lumx/vue';
</script>

// packages/site-demo/content/product/components/list/react/clickable.tsx
import { List, ListItem } from '@lumx/react';

export default () => (
    <List>
        <ListItem size="tiny" linkProps={{ href: '#' }}>
            Clickable list item
        </ListItem>
        <ListItem size="tiny" linkProps={{ href: '#' }} isDisabled>
            Disabled clickable list item
        </ListItem>
        <ListItem size="tiny" linkProps={{ href: '#' }} isHighlighted>
            Highlighted clickable list item
        </ListItem>
        <ListItem size="tiny" linkProps={{ href: '#' }} isSelected>
            Selected clickable list item
        </ListItem>
    </List>
);
