// packages/lumx-react/.storybook/story-block/StoryBlock.tsx
import React, { ReactElement, useState } from 'react';
import classNames from 'classnames';
import isChromatic from 'chromatic/isChromatic';
import { Alignment, Switch, Theme } from '@lumx/react';
import { MaterialThemeSwitcher } from '@lumx/react/utils/MaterialThemeSwitcher';

import '@lumx/core/scss/lumx.scss';
import './index.scss';

import 'focus-visible';

interface StoryBlockProps {
    children(p: { theme: Theme, today?: Date }): ReactElement;
}

const CLASSNAME = 'story-block';

export const StoryBlock: React.FC<StoryBlockProps> = (props) => {
    const { children } = props;

    const [theme, setTheme] = useState<Theme>(Theme.light);
    const toggleTheme = () => setTheme(theme === Theme.light ? Theme.dark : Theme.light);

    if (isChromatic()) {
        // Hard code today date for chromatic.
        return children({ theme, today: new Date('May 25 2021 01:00') });
    }

    return (
        <div className={classNames(CLASSNAME, `${CLASSNAME}--theme-${theme}`)}>
            <div className={`${CLASSNAME}__toolbar`}>
                <Switch
                    className="dark-theme-switcher"
                    isChecked={theme === Theme.dark}
                    onChange={toggleTheme}
                    position={Alignment.right}
                    theme={theme}
                >
                    Dark Background
                </Switch>
                <MaterialThemeSwitcher theme={theme} />
            </div>

            {children({ theme })}
        </div>
    );
};

// packages/lumx-vue/.storybook/story-block/StoryBlock.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { classNames } from '@lumx/core/src/js/utils';
import isChromatic from 'chromatic/isChromatic';
import { toggleMaterialTheme } from './toggleMaterialTheme';
import '@lumx/core/scss/lumx.scss';
import './index.scss';
import 'focus-visible';

const props = defineProps<{
  context: any;
}>();

const appliedTheme = computed(() => {
    const { theme } = props.context.globals;
    return props.context.args.theme || theme;
});

// Hard code today date for stable chromatic stories snapshots.
if (props.context.parameters) {
    props.context.parameters.today = isChromatic() ? new Date('May 25 2021 01:00') : new Date();
}

const isChromaticEnv = isChromatic();

watch(() => props.context.globals.materialTheme, (newVal) => {
    toggleMaterialTheme(newVal !== 'true');
}, { immediate: true });

const classes = computed(() => classNames.join(
    'story-block',
    props.context.parameters.hasGreyBackground && 'story-block--has-grey-background',
    `story-block--theme-${appliedTheme.value}`
));
</script>

<template>
  <slot v-if="isChromaticEnv" />
  <div v-else :class="classes">
    <slot />
  </div>
</template>
