// packages/site-demo/content/product/components/popover/react/demo5.tsx
import { useRef } from 'react';
import { Chip, FlexBox, Popover, Theme } from '@lumx/react';

export default ({ theme }: { theme?: Theme }) => {
    const topStartAnchorRef = useRef(null);
    const topEndAnchorRef = useRef(null);
    return (
        <>
            <FlexBox style={{ marginTop: 80, gap: 128 }} orientation="vertical">
                <Chip ref={topStartAnchorRef} theme={theme} size="s" style={{ placeSelf: 'flex-start' }}>
                    TOP_START
                </Chip>
                <Popover
                    isOpen
                    className="lumx-spacing-padding-huge"
                    theme={theme}
                    anchorRef={topStartAnchorRef}
                    placement="top-start"
                >
                    Popover aligned on start of the top side
                </Popover>
                <Chip ref={topEndAnchorRef} theme={theme} size="s" style={{ placeSelf: 'flex-end' }}>
                    TOP_END
                </Chip>
            </FlexBox>
            <Popover
                isOpen
                className="lumx-spacing-padding-huge"
                theme={theme}
                anchorRef={topEndAnchorRef}
                placement="top-end"
            >
                Popover aligned on start of the top side
            </Popover>
        </>
    );
};

// packages/site-demo/content/product/components/popover/vue/demo5.vue
<template>
    <FlexBox :style="{ marginTop: '80px', gap: '128px' }" orientation="vertical">
        <Button ref="topStartAnchorRef" size="s" emphasis="medium" :style="{ placeSelf: 'flex-start' }"> TOP_START </Button>
        <Popover
            :is-open="true"
            class="lumx-spacing-padding-huge"
            :anchor-ref="topStartAnchorElRef"
            placement="top-start"
        >
            Popover aligned on start of the top side
        </Popover>
        <Button ref="topEndAnchorRef" size="s" emphasis="medium" :style="{ placeSelf: 'flex-end' }"> TOP_END </Button>
    </FlexBox>
    <Popover :is-open="true" class="lumx-spacing-padding-huge" :anchor-ref="topEndAnchorElRef" placement="top-end">
        Popover aligned on start of the top side
    </Popover>
</template>

<script setup lang="ts">
import { computed, useTemplateRef } from 'vue';
import { Button, FlexBox, Popover } from '@lumx/vue';

const topStartAnchorRef = useTemplateRef<InstanceType<typeof Button>>('topStartAnchorRef');
const topStartAnchorElRef = computed(() => topStartAnchorRef.value?.$el as HTMLElement | undefined);

const topEndAnchorRef = useTemplateRef<InstanceType<typeof Button>>('topEndAnchorRef');
const topEndAnchorElRef = computed(() => topEndAnchorRef.value?.$el as HTMLElement | undefined);
</script>
