// packages/lumx-vue/src/utils/InfiniteScroll/InfiniteScroll.tsx
import { defineComponent, ref, watchEffect } from 'vue';
import {
    InfiniteScroll as UI,
    type InfiniteScrollProps,
    setupInfiniteScrollObserver,
} from '@lumx/core/js/utils/InfiniteScroll';
import { keysOf } from '../VueToJSX';

export type { InfiniteScrollProps };

/**
 * Handles basic callback pattern by using intersection observers.
 */
export const InfiniteScroll = defineComponent(
    (props: InfiniteScrollProps) => {
        const elementRef = ref<HTMLDivElement | null>(null);

        watchEffect((onCleanup) => {
            const element = elementRef.value;
            if (!element) return;

            const cleanup = setupInfiniteScrollObserver(element, props.callback, props.options);
            onCleanup(cleanup);
        });

        return () => UI({ ref: elementRef });
    },
    {
        name: 'LumxInfiniteScroll',
        inheritAttrs: false,
        props: keysOf<InfiniteScrollProps>()('callback', 'options'),
    },
);

export default InfiniteScroll;

// packages/lumx-react/src/utils/InfiniteScroll/InfiniteScroll.tsx
import React, { useEffect } from 'react';
import {
    InfiniteScroll as UI,
    type InfiniteScrollProps,
    setupInfiniteScrollObserver,
} from '@lumx/core/js/utils/InfiniteScroll';

export type { InfiniteScrollProps };

/**
 * Handles basic callback pattern by using intersection observers.
 */
export const InfiniteScroll: React.FC<InfiniteScrollProps> = ({ callback, options }) => {
    const elementRef = React.useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        const { current: element } = elementRef;
        if (!element) {
            return undefined;
        }

        return setupInfiniteScrollObserver(element, callback, options);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [elementRef.current, callback]);

    return UI({ ref: elementRef });
};
