// packages/lumx-vue/src/components/select-text-field/SelectTextField.tsx
import { computed, defineComponent, ref, watch } from 'vue';

import { getWithSelector } from '@lumx/core/js/utils/selectors';
import { type RenderOptionContext, type BaseSelectTextFieldWrapperProps } from '@lumx/core/js/utils/select/types';
import { getOptionDisplayName } from '@lumx/core/js/utils/select/getOptionDisplayName';
import { SelectTextField as UI } from '@lumx/core/js/components/SelectTextField';
import type { JSXElement } from '@lumx/core/js/types';

import { keysOf } from '../../utils/VueToJSX';
import { Combobox } from '../combobox';
import ComboboxOption from '../combobox/ComboboxOption';
import SelectionChipGroup from '../chip/SelectionChipGroup';
import { InfiniteScroll } from '@lumx/vue/utils/InfiniteScroll';
import { useHasEventListener } from '../../composables/useHasEventListener';

/** Props shared across single and multiple selection modes. */
interface BaseSelectTextFieldProps<O = any> extends BaseSelectTextFieldWrapperProps<O> {
    /** Content to render before the options list. */
    beforeOptions?: any;
    /** CSS class. */
    class?: string;
}

/** Props specific to single selection mode. */
export interface SingleSelectTextFieldProps<O = any> extends BaseSelectTextFieldProps<O> {
    /** Selection type. */
    selectionType: 'single';
    /** Selected option object. */
    value?: O;
}

/** Props specific to multiple selection mode. */
export interface MultipleSelectTextFieldProps<O = any> extends BaseSelectTextFieldProps<O> {
    /** Selection type. */
    selectionType: 'multiple';
    /** Selected option objects. */
    value?: O[];
}

/**
 * SelectTextField props — supports both single and multiple selection.
 * Discriminated on `selectionType`: when `'multiple'`, `value` is `O[]`.
 */
export type SelectTextFieldProps<O = any> = SingleSelectTextFieldProps<O> | MultipleSelectTextFieldProps<O>;

/**
 * Internal flattened type for `keysOf` — Vue's runtime prop system needs all keys
 * enumerated in a single interface (it cannot narrow on discriminated unions).
 */
type AllSelectTextFieldPropsKeys = BaseSelectTextFieldProps & {
    selectionType: 'single' | 'multiple';
    value?: any;
};

export const emitSchema = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    change: (_newValue?: any) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    search: (_searchText: string) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    'load-more': () => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    blur: (_event?: FocusEvent) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    focus: (_event?: FocusEvent) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    keydown: (_event?: KeyboardEvent) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    clear: (_event?: MouseEvent) => true,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    open: (_isOpen: boolean) => true,
};

/**
 * A text field with a select dropdown to choose between a list of options.
 * Supports search/filter, single selection, and multiple selection with chips.
 *
 * Scoped slots:
 * - `option({ option, index })` — custom option rendering inside a `<Combobox.Option>`.
 * - `sectionTitle({ sectionId, options })` — custom section header rendering.
 * - `chip({ option, index })` — custom chip rendering (multiple selection only).
 */
const SelectTextField = defineComponent(
    (props: SelectTextFieldProps, { emit, slots, attrs }) => {
        const isMultiple = computed(() => props.selectionType === 'multiple');

        // Resolve aria-disabled from props or attrs.
        // Vue normalizes kebab-case props to camelCase, so check both forms.
        const ariaDisabled = computed(
            () =>
                props['aria-disabled'] ??
                (props as any).ariaDisabled ??
                (attrs as any).ariaDisabled ??
                (attrs as any)['aria-disabled'],
        );

        // Compute whether the component is disabled (native or aria-disabled).
        const isAnyDisabled = computed(() => {
            return !!props.isDisabled || ariaDisabled.value === true || ariaDisabled.value === 'true';
        });

        // Track whether the user is actively typing a search.
        const isSearching = ref(Boolean(props.searchInputValue));
        const searchText = ref(props.searchInputValue ?? '');

        const listElement = ref<HTMLElement | null>(null);

        // Sync external controlled search value into internal state.
        watch(
            () => props.searchInputValue,
            (newVal) => {
                if (newVal !== undefined) {
                    searchText.value = newVal;
                    isSearching.value = Boolean(newVal);
                }
            },
        );

        // The display value shown in the input.
        const displayValue = computed(() => {
            if (isMultiple.value || isSearching.value) {
                return searchText.value;
            }
            return getOptionDisplayName(props.value as any, props.getOptionName, props.getOptionId);
        });

        // Map option id selection to option object selection.
        const handleSelect = (selectedOption: { value: string }) => {
            const selectedValue = selectedOption.value;
            const newOption =
                selectedValue &&
                props.options?.find((option) => getWithSelector(props.getOptionId, option) === selectedValue);

            if (!isMultiple.value) {
                emit('change', newOption);
            } else {
                const currentValue = (props.value as any[]) || [];
                const existingIndex = currentValue.findIndex(
                    (item) => getWithSelector(props.getOptionId, item) === selectedValue,
                );

                if (existingIndex === -1) {
                    // Skip if no matching option found (e.g. beforeOptions custom actions).
                    if (newOption) {
                        emit('change', [...currentValue, newOption]);
                    }
                } else {
                    // Remove option (toggle off)
                    const updated = [...currentValue];
                    updated.splice(existingIndex, 1);
                    emit('change', updated);
                }
            }

            // Reset search state after selection.
            isSearching.value = false;
            searchText.value = '';
            emit('search', '');
        };

        // Handle text input changes (search).
        const handleInputChange = (inputValue: string) => {
            isSearching.value = true;
            searchText.value = inputValue;
            emit('search', inputValue);

            // When the user clears the input (single mode only), clear the selection too.
            if (!isMultiple.value && inputValue === '' && props.value !== undefined && props.value !== null) {
                emit('change', undefined);
            }
        };

        // Handle clear button click (single mode only).
        const handleClear = (event?: MouseEvent) => {
            emit('change', undefined);
            isSearching.value = false;
            searchText.value = '';
            emit('search', '');
            emit('clear', event);
        };

        // Handle blur: reset input to selected value name, then emit blur and search events.
        const handleBlur = (event?: FocusEvent) => {
            isSearching.value = false;
            searchText.value = '';
            emit('search', '');
            emit('blur', event);
        };

        // Wrap the consumer's renderOption slot.
        // The scoped slot receives `{ option, index }` and should return
        // content to display inside a <Combobox.Option>.
        const wrappedRenderOption = computed(() => {
            const renderOptionSlot = slots.option;
            if (!renderOptionSlot) return undefined;

            return (option: any, { index, value: optionValue, isSelected, description }: RenderOptionContext) => {
                // TODO: override props and not just content
                const slotContent = renderOptionSlot({ option, index });

                // The slot content is wrapped in a Combobox.Option with
                // core-computed props (value, isSelected, description, key)
                return (
                    <ComboboxOption
                        key={optionValue}
                        value={optionValue}
                        isSelected={isSelected}
                        description={description ?? undefined}
                    >
                        {slotContent}
                    </ComboboxOption>
                ) as any;
            };
        });

        // Wrap the consumer's renderSectionTitle slot.
        // The scoped slot receives `{ sectionId, options }` and should return
        // custom JSX to display as the section title.
        const wrappedRenderSectionTitle = computed(() => {
            const renderSectionTitleSlot = slots.sectionTitle;
            if (!renderSectionTitleSlot) return undefined;

            return (sectionId: string, options: any[]) => {
                return renderSectionTitleSlot({ sectionId, options }) as any;
            };
        });

        // Check if a 'load-more' listener is registered on this component.
        // Uses vnode.props instead of $attrs because Vue 3 removes declared emits from $attrs.
        const hasLoadMoreListener = useHasEventListener('onLoad-more') || useHasEventListener('onLoadMore');

        const onLoadMore = () => emit('load-more');

        return () => {
            const showClear =
                !isMultiple.value &&
                !isAnyDisabled.value &&
                (props.hasClearButton ?? true) &&
                props.value !== undefined &&
                props.value !== null;

            const chips = isMultiple.value ? (
                <SelectionChipGroup
                    value={props.value as any[] | undefined}
                    theme={props.theme}
                    getOptionId={props.getOptionId}
                    getOptionName={props.getOptionName}
                    onChange={(newValue: any) => emit('change', newValue)}
                    isDisabled={isAnyDisabled.value}
                    label={props.translations.chipGroupLabel ?? props.label}
                    chipRemoveLabel={props.translations.chipRemoveLabel}
                >
                    {{ chip: slots.chip || undefined }}
                </SelectionChipGroup>
            ) : undefined;

            const listStatus = props.listStatus ?? 'idle';

            const beforeOptionsSlot = (props.beforeOptions ?? slots.beforeOptions?.()) as JSXElement | undefined;

            // Selector<O> is not assignable to Selector<any> due to function parameter contravariance.
            // The core template is not generic, so we cast selectors when forwarding to UI().
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            return UI(
                {
                    options: props.options,
                    getOptionId: props.getOptionId as any,
                    getOptionName: props.getOptionName as any,
                    getOptionDescription: props.getOptionDescription as any,
                    renderOption: wrappedRenderOption.value as any,
                    getSectionId: props.getSectionId as any,
                    renderSectionTitle: wrappedRenderSectionTitle.value as any,
                    selected: props.value,
                    label: props.label,
                    isMultiselectable: isMultiple.value,
                    listStatus,
                    onOpen: (isOpen: boolean) => emit('open', isOpen),
                    loadingMessage: props.translations.loadingMessage,
                    emptyMessage: props.translations.emptyMessage,
                    nbOptionMessage: props.translations.nbOptionMessage,
                    errorMessage: props.translations.errorMessage,
                    errorTryReloadMessage: props.translations.errorTryReloadMessage,
                    inputProps: {
                        ...props.inputProps,
                        placeholder: props.placeholder,
                        icon: props.icon,
                        value: displayValue.value,
                        onChange: handleInputChange,
                        onSelect: handleSelect,
                        onBlur: handleBlur,
                        onFocus: (event?: FocusEvent) => emit('focus', event),
                        onKeyDown: (event?: KeyboardEvent) => emit('keydown', event),
                        isDisabled: props.isDisabled,
                        'aria-disabled': ariaDisabled.value,
                        isRequired: props.isRequired,
                        hasError: props.hasError,
                        error: props.error,
                        helper: props.helper,
                        id: props.id,
                        name: props.name,
                        isValid: props.isValid,
                        maxLength: props.maxLength,
                        'aria-label': props.ariaLabel,
                        clearButtonProps: showClear ? { label: props.translations.clearLabel } : undefined,
                        onClear: handleClear,
                        toggleButtonProps: props.translations.showSuggestionsLabel
                            ? { label: props.translations.showSuggestionsLabel }
                            : undefined,
                        filter: props.filter,
                        openOnFocus: props.openOnFocus,
                        className: props.class,
                        theme: props.theme,
                    },
                    popoverProps: props.popoverProps,
                    listProps: {
                        ref: (el: any) => {
                            listElement.value = el?.$el || el;
                        },
                    },
                    chips: chips as any,
                    beforeOptions: beforeOptionsSlot as any,
                    onLoadMore: hasLoadMoreListener ? onLoadMore : undefined,
                    infiniteScrollOptions: { root: listElement.value, rootMargin: '100px' },
                },
                { Combobox, InfiniteScroll },
            );
        };
    },
    {
        name: 'LumxSelectTextField',
        inheritAttrs: false,
        props: keysOf<AllSelectTextFieldPropsKeys>()(
            'options',
            'getOptionId',
            'getOptionName',
            'getOptionDescription',
            'getSectionId',
            'selectionType',
            'value',
            'filter',
            'searchInputValue',
            'hasClearButton',
            'listStatus',
            'label',
            'placeholder',
            'icon',
            'isDisabled',
            'aria-disabled',
            'isRequired',
            'hasError',
            'error',
            'helper',
            'id',
            'name',
            'isValid',
            'maxLength',
            'ariaLabel',
            'inputProps',
            'popoverProps',
            'translations',
            'beforeOptions',
            'openOnFocus',
            'class',
            'className',
            'theme',
        ),
        emits: emitSchema,
    },
);

export default SelectTextField;

// packages/lumx-react/src/components/select-text-field/SelectTextField.tsx
import React, { SyntheticEvent, useCallback, useEffect, useRef, useState } from 'react';

import type { ChipProps } from '@lumx/core/js/components/Chip';
import { getWithSelector } from '@lumx/core/js/utils/selectors';
import { type RenderOptionContext, type BaseSelectTextFieldWrapperProps } from '@lumx/core/js/utils/select/types';
import { getOptionDisplayName } from '@lumx/core/js/utils/select/getOptionDisplayName';
import { SelectTextField as UI } from '@lumx/core/js/components/SelectTextField';
import { isComponentType } from '@lumx/react/utils/type';
import { Combobox, type ComboboxPopoverProps } from '../combobox';
import { InfiniteScroll } from '../../utils/InfiniteScroll';
import { useMergeRefs } from '../../utils/react/mergeRefs';
import { SelectionChipGroup } from '../chip/SelectionChipGroup';

interface BaseSelectTextFieldProps<O = any> extends BaseSelectTextFieldWrapperProps<O> {
    /**
     * Custom option render function. Must return a `<Combobox.Option>` element with custom
     * children/props. Core-computed props (`value`, `isSelected`, `description`, `key`) are
     * merged in automatically — the consumer does not need to forward them.
     */
    renderOption?: (option: O, index: number) => React.ReactNode;
    /**
     * Custom section title render function. Receives the section id and the options
     * in that section. Returns custom JSX to display as the section header.
     * When not provided, the section id is used as a plain text label.
     */
    renderSectionTitle?: (sectionId: string, options: O[]) => React.ReactNode;
    /**
     * Callback fired when the search input text changes.
     * Independent of `filter`: both can be used together (e.g. client-side
     * filtering + tracking search text for a "create" action).
     */
    onSearch?: (searchText: string) => void;
    /** Ref to the underlying input element. */
    inputRef?: React.Ref<HTMLInputElement>;
    /** Callback to load more items (infinite scroll). */
    onLoadMore?: () => void;
    /** Content to render before the options list. */
    beforeOptions?: React.ReactNode;
    /** Props forwarded to the Combobox.List popover. */
    popoverProps?: ComboboxPopoverProps;
    /** On blur callback. */
    onBlur?: (event: React.FocusEvent) => void;
    /** On focus callback. */
    onFocus?: (event: React.FocusEvent) => void;
    /** On key down callback. */
    onKeyDown?: (event: React.KeyboardEvent) => void;
    /** On clear callback (fired when the clear button is clicked). */
    onClear?: (event?: SyntheticEvent) => void;
    /** Callback fired when the dropdown open state changes. */
    onOpen?: (isOpen: boolean) => void;
}

/** Single selection props **/
export interface SingleSelectTextFieldProps<O = any> extends BaseSelectTextFieldProps<O> {
    /** Selection type. */
    selectionType: 'single';
    /** Selected option object. */
    value?: O;
    /** Callback on option selected (or cleared). */
    onChange?: (newValue?: O) => void;
    /** Not available in single selection. */
    renderChip?: never;
}

/** Multiple selection props **/
export interface MultipleSelectTextFieldProps<O = any> extends BaseSelectTextFieldProps<O> {
    /** Selection type. */
    selectionType: 'multiple';
    /** Selected option objects. */
    value?: O[];
    /** Callback on option array changed. */
    onChange?: (newValue?: O[]) => void;
    /** Custom chip render function. */
    renderChip?: (option: O) => React.ReactNode;
    /** Customize chip props per selected option. */
    getChipProps?: (option: O) => Partial<ChipProps>;
}

/**
 * SelectTextField props — supports both single and multiple selection.
 */
export type SelectTextFieldProps<O = any> = SingleSelectTextFieldProps<O> | MultipleSelectTextFieldProps<O>;

/**
 * A text field with a select dropdown to choose between a list of options.
 * Supports search/filter, single selection, and multiple selection with chips.
 */
export const SelectTextField = <O,>(props: SelectTextFieldProps<O>) => {
    const {
        // Options
        options,
        getOptionId,
        getOptionName,
        getOptionDescription,
        renderOption,
        getSectionId,
        renderSectionTitle,
        // Selection
        selectionType,
        value,
        onChange,
        // Search / filter
        filter,
        openOnFocus,
        onSearch,
        searchInputValue: externalSearchValue,
        // Clear
        hasClearButton = true,
        // Status
        listStatus = 'idle',
        // Text field
        className,
        label,
        placeholder,
        icon,
        isDisabled,
        'aria-disabled': ariaDisabled,
        isRequired,
        hasError,
        error,
        helper,
        id,
        name,
        isValid,
        maxLength,
        ariaLabel,
        inputRef: externalInputRef,
        // Event callbacks
        onBlur: externalOnBlur,
        onFocus,
        onKeyDown,
        onClear: externalOnClear,
        onOpen,
        // Forwarding
        inputProps: consumerInputProps,
        // Load more
        onLoadMore,
        beforeOptions,
        // Popover
        popoverProps,
        // Theme
        theme,
        // Translations
        translations,
    } = props;

    const isAnyDisabled = !!isDisabled || ariaDisabled === true || ariaDisabled === 'true';
    const isMultiple = selectionType === 'multiple';
    const renderChip = isMultiple ? (props as MultipleSelectTextFieldProps<O>).renderChip : undefined;
    const getChipProps = isMultiple ? (props as MultipleSelectTextFieldProps<O>).getChipProps : undefined;

    /* Wrap the consumer's renderOption to inject core-computed props.
     * The consumer returns a <Combobox.Option> with custom children/props.
     * This wrapper validates the element type, extracts the consumer's props, and
     * re-renders a <Combobox.Option> merging them with core-computed value/isSelected/description/key. */
    const wrappedRenderOption = renderOption
        ? (option: O, { index, value: optionValue, isSelected, description }: RenderOptionContext) => {
              const node = renderOption(option, index);
              if (!isComponentType(Combobox.Option)(node)) return null;
              const { children, ...customProps } = (node as React.ReactElement).props;
              return (
                  <Combobox.Option
                      key={optionValue}
                      {...customProps}
                      value={optionValue}
                      isSelected={isSelected}
                      description={description}
                  >
                      {children}
                  </Combobox.Option>
              );
          }
        : undefined;

    const [listElement, setListElement] = useState<HTMLElement | null>(null);
    const localInputRef = useRef<HTMLInputElement>(null);
    const mergedInputRef = useMergeRefs(localInputRef, externalInputRef);

    // Track whether the user is actively typing a search.
    const [isSearching, setIsSearching] = useState(() => Boolean(externalSearchValue));
    const [searchText, setSearchText] = useState(() => externalSearchValue ?? '');

    /* Sync external controlled search value into internal state when it changes.
     * This allows the parent to seed or reset the visible search text
     * (e.g., setting searchInputValue='' after creating an entry from beforeOptions). */
    useEffect(() => {
        if (externalSearchValue !== undefined) {
            setSearchText(externalSearchValue);
            setIsSearching(Boolean(externalSearchValue));
        }
    }, [externalSearchValue]);

    // The displayed value shown in the input
    let displayValue;
    if (isMultiple || isSearching) {
        displayValue = searchText;
    } else if (!isMultiple) {
        displayValue = getOptionDisplayName(value as O | undefined, getOptionName, getOptionId);
    }

    // Map option id selection to option object selection.
    const handleSelect = useCallback(
        (selectedOption: { value: string }) => {
            const selectedValue = selectedOption.value;
            const newOption =
                selectedValue && options?.find((option) => getWithSelector(getOptionId, option) === selectedValue);

            if (!isMultiple) {
                onChange?.(newOption as any);
            } else {
                const currentValue = (value as any[]) || [];
                const existingIndex = currentValue.findIndex(
                    (item) => getWithSelector(getOptionId, item) === selectedValue,
                );

                if (existingIndex === -1) {
                    // Skip if no matching option found (e.g. beforeOptions custom actions).
                    if (newOption) {
                        onChange?.([...currentValue, newOption] as any);
                    }
                } else {
                    // Remove option (toggle off)
                    const updated = [...currentValue];
                    updated.splice(existingIndex, 1);
                    onChange?.(updated as any);
                }
            }

            // Reset search state after selection.
            setIsSearching(false);
            setSearchText('');
            onSearch?.('');
        },
        [getOptionId, isMultiple, onChange, onSearch, options, value],
    );

    // Handle text input changes (search).
    const handleInputChange = useCallback(
        (inputValue: string) => {
            setIsSearching(true);
            setSearchText(inputValue);
            onSearch?.(inputValue);

            // When the user clears the input (single mode only), clear the selection too.
            if (!isMultiple && inputValue === '' && value !== undefined && value !== null) {
                (onChange as ((newValue?: O) => void) | undefined)?.(undefined);
            }
        },
        [isMultiple, onChange, onSearch, value],
    );

    // Handle clear button click (single mode only).
    const handleClear = useCallback(
        (event?: SyntheticEvent) => {
            // Prevent the clear event from being handled as a regular input change.
            event?.stopPropagation();
            (onChange as ((newValue?: O) => void) | undefined)?.(undefined);
            setIsSearching(false);
            setSearchText('');
            onSearch?.('');
            externalOnClear?.(event);
        },
        [onChange, onSearch, externalOnClear],
    );

    // Handle blur: reset input to selected value name, then call consumer's onBlur.
    const handleBlur = useCallback(
        (event?: React.FocusEvent) => {
            setIsSearching(false);
            setSearchText('');
            onSearch?.('');
            externalOnBlur?.(event as React.FocusEvent);
        },
        [externalOnBlur, onSearch],
    );

    const showClear = !isMultiple && !isAnyDisabled && hasClearButton && value !== undefined && value !== null;

    const chips = isMultiple ? (
        <SelectionChipGroup
            value={value as O[] | undefined}
            theme={theme}
            getOptionId={getOptionId}
            getOptionName={getOptionName}
            onChange={onChange as ((newValue?: O[]) => void) | undefined}
            inputRef={localInputRef as React.RefObject<HTMLInputElement>}
            isDisabled={isAnyDisabled}
            label={translations.chipGroupLabel ?? label}
            chipRemoveLabel={translations.chipRemoveLabel}
            renderChip={renderChip}
            getChipProps={getChipProps}
        />
    ) : undefined;

    // The core template is not generic, so we cast selectors when forwarding to UI().
    return UI(
        {
            options,
            getOptionId: getOptionId as any,
            getOptionName: getOptionName as any,
            getOptionDescription: getOptionDescription as any,
            renderOption: wrappedRenderOption,
            getSectionId: getSectionId as any,
            renderSectionTitle: renderSectionTitle as any,
            selected: value,
            label,
            isMultiselectable: isMultiple,
            listStatus,
            onOpen,
            loadingMessage: translations.loadingMessage,
            emptyMessage: translations.emptyMessage,
            nbOptionMessage: translations.nbOptionMessage,
            errorMessage: translations.errorMessage,
            errorTryReloadMessage: translations.errorTryReloadMessage,
            inputProps: {
                ...consumerInputProps,
                placeholder,
                icon,
                value: displayValue,
                onChange: handleInputChange,
                onSelect: handleSelect,
                onBlur: handleBlur,
                onFocus,
                onKeyDown,
                inputRef: mergedInputRef,
                isDisabled,
                'aria-disabled': ariaDisabled,
                isRequired,
                hasError,
                error,
                helper,
                id,
                name,
                isValid,
                maxLength,
                'aria-label': ariaLabel,
                clearButtonProps: showClear ? { label: translations.clearLabel } : undefined,
                onClear: handleClear,
                toggleButtonProps: translations.showSuggestionsLabel
                    ? { label: translations.showSuggestionsLabel }
                    : undefined,
                filter,
                openOnFocus,
                className,
                theme,
            },
            popoverProps,
            listProps: { ref: setListElement },
            chips,
            beforeOptions,
            onLoadMore,
            infiniteScrollOptions: { root: listElement, rootMargin: '100px' },
        },
        { Combobox, InfiniteScroll },
    );
};

SelectTextField.displayName = 'SelectTextField';
