// packages/site-demo/content/product/components/avatar/vue/actions.vue
<template>
    <Avatar :theme="theme" image="https://i.pravatar.cc/128?img=32" alt="Avatar with actions" size="xl">
        <template #actions>
            <FlexBox orientation="horizontal" verticalAlign="center" gap="regular">
                <IconButton label="Edit" color="dark" emphasis="low" :has-background="true" :icon="mdiPencil" size="s" />
                <IconButton label="See" color="dark" emphasis="low" :has-background="true" :icon="mdiEye" size="s" />
                <IconButton label="Delete" color="dark" emphasis="low" :has-background="true" :icon="mdiDelete" size="s" />
            </FlexBox>
        </template>
    </Avatar>
</template>

<script setup lang="ts">
import { mdiDelete, mdiEye, mdiPencil } from '@lumx/icons';
import { Avatar, FlexBox, IconButton, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();
</script>

// packages/site-demo/content/product/components/avatar/react/actions.tsx
import { mdiDelete, mdiEye, mdiPencil } from '@lumx/icons';
import { Alignment, Avatar, Emphasis, FlexBox, IconButton, Orientation, Size } from '@lumx/react';
import React from 'react';

export const App = ({ theme }: any) => (
    <Avatar
        theme={theme}
        image="/demo-assets/persona.png"
        alt="Avatar with actions"
        size={Size.xl}
        actions={
            <FlexBox orientation={Orientation.horizontal} vAlign={Alignment.center} gap={Size.regular}>
                <IconButton
                    label="Edit"
                    color="dark"
                    emphasis={Emphasis.low}
                    hasBackground
                    icon={mdiPencil}
                    size={Size.s}
                />
                <IconButton
                    label="See"
                    color="dark"
                    emphasis={Emphasis.low}
                    hasBackground
                    icon={mdiEye}
                    size={Size.s}
                />
                <IconButton
                    label="Delete"
                    color="dark"
                    emphasis={Emphasis.low}
                    hasBackground
                    icon={mdiDelete}
                    size={Size.s}
                />
            </FlexBox>
        }
    />
);
