// packages/lumx-vue/src/components/tabs/Tab.tsx
import { computed, defineComponent, useAttrs } from 'vue';

import {
    Tab as TabUI,
    type TabProps as UIProps,
    type TabPropsToOverride,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Tabs/Tab';

import { useDisableStateProps } from '../../composables/useDisableStateProps';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Icon } from '../icon';
import { Text } from '../text';
import { useTabProviderContext } from './state';

export type TabProps = VueToJSXProps<UIProps, TabPropsToOverride>;

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * Tab component.
 *
 * Implements WAI-ARIA `tab` role.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const Tab = defineComponent(
    (props: TabProps) => {
        const attrs = useAttrs();
        const { isAnyDisabled } = useDisableStateProps(computed(() => ({ ...props, ...attrs })));
        const tabState = useTabProviderContext('tab', props.id as string | undefined);
        const isActive = computed(() => props.isActive || tabState.value?.isActive);

        return () => {
            const { onFocus, onKeypress, onKeyPress, ...restAttrs } = attrs as any;
            return (
                <TabUI
                    {...restAttrs}
                    id={props.id}
                    className={props.class}
                    icon={props.icon}
                    iconProps={props.iconProps}
                    label={props.label}
                    isActive={isActive.value}
                    isAnyDisabled={isAnyDisabled.value}
                    isDisabled={props.isDisabled}
                    shouldActivateOnFocus={tabState.value?.shouldActivateOnFocus}
                    changeToTab={tabState.value?.changeToTab}
                    tabId={tabState.value?.tabId}
                    tabPanelId={tabState.value?.tabPanelId}
                    handleFocus={(event: FocusEvent) => (onFocus as any)?.(event)}
                    handleKeyPress={(event: KeyboardEvent) => ((onKeypress || onKeyPress) as any)?.(event)}
                    keyPressProp="onKeypress"
                    tabIndexProp="tabindex"
                    Icon={Icon}
                    Text={Text}
                />
            );
        };
    },
    {
        name: 'LumxTab',
        inheritAttrs: false,
        props: keysOf<TabProps>()('icon', 'iconProps', 'id', 'isActive', 'isDisabled', 'label', 'class'),
    },
);

export default Tab;

// packages/lumx-react/src/components/tabs/Tab.tsx
import React, { FocusEventHandler, KeyboardEventHandler, ReactNode, useCallback } from 'react';

import classNames from 'classnames';

import { Icon, IconProps, Size, Text } from '@lumx/react';
import { CSS_PREFIX } from '@lumx/react/constants';
import { GenericProps } from '@lumx/react/utils/type';
import { handleBasicClasses } from '@lumx/core/js/utils/className';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';

import { useDisableStateProps } from '@lumx/react/utils/disabled/useDisableStateProps';
import { useTabProviderContext } from './state';

/**
 * Defines the props of the component.
 */
export interface TabProps extends GenericProps {
    /** Children are not supported. */
    children?: never;
    /** Icon (SVG path). */
    icon?: IconProps['icon'];
    /** Icon component properties. */
    iconProps?: Omit<IconProps, 'icon'>;
    /** Native id property. */
    id?: string;
    /** Whether the tab is active or not. */
    isActive?: boolean;
    /** Whether the component is disabled or not. */
    isDisabled?: boolean;
    /** Label content. */
    label: string | ReactNode;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'Tab';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME = `${CSS_PREFIX}-tabs__link`;

/**
 * Component default props.
 */
const DEFAULT_PROPS: Partial<TabProps> = {};

/**
 * Tab component.
 *
 * Implements WAI-ARIA `tab` role {@see https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html#rps_label}
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const Tab = forwardRef<TabProps, HTMLButtonElement>((props, ref) => {
    const { isAnyDisabled, otherProps } = useDisableStateProps(props);
    const {
        className,
        icon,
        iconProps = {},
        id,
        isActive: propIsActive,
        label,
        onFocus,
        onKeyPress,
        tabIndex = -1,
        ...forwardedProps
    } = otherProps;
    const state = useTabProviderContext('tab', id);
    const isActive = propIsActive || state?.isActive;

    const changeToCurrentTab = useCallback(() => {
        if (isAnyDisabled) {
            return;
        }
        state?.changeToTab();
    }, [isAnyDisabled, state]);

    const handleFocus: FocusEventHandler = useCallback(
        (event) => {
            onFocus?.(event);
            if (state?.shouldActivateOnFocus) {
                changeToCurrentTab();
            }
        },
        [changeToCurrentTab, onFocus, state?.shouldActivateOnFocus],
    );

    const handleKeyPress: KeyboardEventHandler = useCallback(
        (event) => {
            onKeyPress?.(event);
            if (event.key !== 'Enter' || isAnyDisabled) {
                return;
            }
            changeToCurrentTab();
        },
        [changeToCurrentTab, isAnyDisabled, onKeyPress],
    );

    return (
        <button
            ref={ref}
            {...forwardedProps}
            type="button"
            id={state?.tabId}
            className={classNames(
                className,
                handleBasicClasses({ prefix: CLASSNAME, isActive, isDisabled: isAnyDisabled }),
            )}
            onClick={changeToCurrentTab}
            onKeyPress={handleKeyPress}
            onFocus={handleFocus}
            role="tab"
            tabIndex={isActive ? 0 : tabIndex}
            aria-disabled={isAnyDisabled}
            aria-selected={isActive}
            aria-controls={state?.tabPanelId}
        >
            {icon && <Icon icon={icon} size={Size.xs} {...iconProps} />}
            {label && (
                <Text as="span" truncate>
                    {label}
                </Text>
            )}
        </button>
    );
});
Tab.displayName = COMPONENT_NAME;
Tab.className = CLASSNAME;
Tab.defaultProps = DEFAULT_PROPS;
