// packages/lumx-react/src/components/menu/MenuTrigger.tsx
import { ElementType, useEffect, useRef } from 'react';

import {
    MenuTrigger as UI,
    MenuTriggerProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Menu/MenuTrigger';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { forwardRefPolymorphic } from '@lumx/react/utils/react/forwardRefPolymorphic';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { ComponentRef, HasPolymorphicAs, HasRequiredLinkHref } from '@lumx/react/utils/type';

import { Button } from '../button';
import { useMenuContext } from './context/MenuContext';
import { useMenuOpen } from './context/useMenuOpen';

/** MenuTrigger props. Polymorphic */
export type MenuTriggerProps<E extends ElementType = typeof Button> = Omit<
    HasPolymorphicAs<E>,
    'aria-haspopup' | 'aria-controls' | 'aria-expanded'
> &
    HasRequiredLinkHref<E> &
    ReactToJSX<UIProps, 'isOpen' | 'menuId'>;

/**
 * MenuTrigger component.
 *
 * @param  props Component props.
 * @return React element.
 */
export const MenuTrigger = Object.assign(
    forwardRefPolymorphic(<E extends ElementType = typeof Button>(props: MenuTriggerProps<E>, ref: ComponentRef<E>) => {
        const { menuId, triggerId, anchorRef, handle } = useMenuContext();
        const [isOpen] = useMenuOpen();
        const { as, children, ...triggerProps } = props as any;
        const TriggerComp = as ?? Button;

        const internalRef = useRef<HTMLElement>(null);
        const mergedRef = useMergeRefs(ref as any, internalRef, anchorRef);

        // Register trigger with the handle on mount; clean up on unmount.
        useEffect(() => {
            const triggerEl = internalRef.current;
            if (!triggerEl) return undefined;
            return handle.registerTrigger(triggerEl);
        }, [handle]);

        return UI(
            {
                ...triggerProps,
                id: triggerProps.id ?? triggerId,
                menuId,
                isOpen,
                ref: mergedRef,
                children,
            },
            { Trigger: TriggerComp },
        );
    }),
    { displayName: COMPONENT_NAME, className: CLASSNAME },
);

// packages/lumx-vue/src/components/menu-button/MenuTrigger.tsx
import { defineComponent, ref, watchEffect } from 'vue';

import type { JSXElement } from '@lumx/core/js/types';

import {
    MenuTrigger as UI,
    MenuTriggerProps as UIProps,
    CLASSNAME,
    COMPONENT_NAME,
} from '@lumx/core/js/components/Menu/MenuTrigger';

import { useClassName } from '../../composables/useClassName';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Button } from '../button';

import { useMenuContext } from './context';
import { useMenuOpen } from './useMenuOpen';

/** MenuTrigger props. */
export type MenuTriggerProps = VueToJSXProps<UIProps, 'menuId' | 'isOpen'>;

/**
 * MenuTrigger component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const MenuTrigger = defineComponent(
    (props: MenuTriggerProps, { slots, attrs }) => {
        const { menuId, triggerId, anchorRef, handle } = useMenuContext();
        const [isOpen] = useMenuOpen();
        const className = useClassName(() => props.class);
        const internalRef = ref<any>(null);

        watchEffect((onCleanup) => {
            const domEl = internalRef.value?.$el ?? internalRef.value;
            if (!domEl) return;
            // Set menu popover anchor on the trigger
            (anchorRef as any).value = domEl;
            // Register the menu trigger element in core logic
            const cleanup = handle.registerTrigger(domEl);
            // Cleanup
            onCleanup(() => cleanup());
        });

        return () => {
            const { as, ...restAttrs } = attrs as Record<string, any>;

            let Trigger: any = Button;
            if (slots.trigger) {
                // Custom trigger via scoped slot
                Trigger = (slotProps: Record<string, any>) =>
                    slots.trigger!({ triggerProps: { ...slotProps, ref: internalRef } });
            } else if (as) {
                // Use `as` prop, attr fallback, or default to Button
                Trigger = as;
            }

            return UI(
                {
                    ...restAttrs,
                    id: triggerId,
                    ref: slots.trigger ? undefined : internalRef,
                    className: className.value,
                    menuId,
                    isOpen: isOpen.value,
                    children: slots.default?.() as JSXElement,
                },
                { Trigger },
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<MenuTriggerProps>()('class', 'id'),
    },
);

export { CLASSNAME, COMPONENT_NAME };
export default MenuTrigger;
