// packages/lumx-core/src/js/components/Menu/MenuPopover.tsx
import type { HasClassName, JSXElement, LumxClassName } from '../../types';
import type { Placement } from '../Popover/constants';
import { classNames } from '../../utils';
import { PopoverProps } from '../Popover';

/** MenuPopover props. */
export interface MenuPopoverProps
    extends HasClassName,
        Pick<PopoverProps, 'placement' | 'anchorRef' | 'isOpen' | 'handleClose'> {
    /** Popover content (a `Menu`). */
    children?: JSXElement;
}

/** Framework components injected by wrappers. */
export interface MenuPopoverComponents {
    /** Popover component (framework-specific). */
    Popover: any;
    /** FlexBox component (framework-specific). */
    FlexBox: any;
}

export const COMPONENT_NAME = 'MenuPopover';

export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-menu-popover';
const { block, element } = classNames.bem(CLASSNAME);

/** MenuPopover core template. Renders a `Popover` with menu-friendly defaults. */
export const MenuPopover = (props: MenuPopoverProps, { Popover, FlexBox }: MenuPopoverComponents) => {
    const {
        children,
        className,
        isOpen,
        placement = 'bottom-start' as Placement,
        anchorRef,
        handleClose,
        ...forwardedProps
    } = props;

    return (
        <Popover
            {...forwardedProps}
            placement={placement}
            anchorRef={anchorRef}
            isOpen={isOpen}
            onClose={handleClose}
            closeOnClickAway
            closeOnEscape
            usePortal={false}
            focusAnchorOnClose
            withFocusTrap={false}
            closeMode="hide"
            fitToAnchorWidth={false}
            className={block([className])}
        >
            <FlexBox orientation="vertical" className={element('scroll')}>
                {children}
            </FlexBox>
        </Popover>
    );
};

// packages/lumx-vue/src/components/menu-button/MenuPopover.tsx
import { defineComponent, useSlots } from 'vue';
import type { JSXElement } from '@lumx/core/js/types';

import {
    MenuPopover as UI,
    MenuPopoverProps as UIProps,
    CLASSNAME as MENU_POPOVER_CLASSNAME,
    COMPONENT_NAME as MENU_POPOVER_COMPONENT_NAME,
} from '@lumx/core/js/components/Menu/MenuPopover';

import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { FlexBox } from '../flex-box';
import { Popover } from '../popover';

import { useMenuContext } from './context';
import { useMenuOpen } from './useMenuOpen';

/** MenusPopover props. */
export type MenuPopoverProps = VueToJSXProps<UIProps, 'anchorRef' | 'isOpen' | 'handleClose'>;

/**
 * MenuPopover component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const MenuPopover = defineComponent(
    (props: MenuPopoverProps) => {
        const slots = useSlots();
        const { anchorRef } = useMenuContext();
        const [isOpen, setIsOpen] = useMenuOpen();

        return () =>
            UI(
                {
                    ...props,
                    children: slots.default?.() as JSXElement,
                    isOpen: isOpen.value,
                    anchorRef,
                    handleClose: () => setIsOpen(false),
                },
                { Popover, FlexBox },
            );
    },
    {
        name: getName(MENU_POPOVER_COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<MenuPopoverProps>()('placement', 'fitToAnchorWidth', 'class'),
    },
);

export { MENU_POPOVER_CLASSNAME as CLASSNAME, MENU_POPOVER_COMPONENT_NAME as COMPONENT_NAME };
export default MenuPopover;
