// packages/lumx-core/src/js/components/Menu/MenuButton.tsx
import { mdiDotsVertical } from '@lumx/icons';
import type { JSXElement, LumxClassName } from '../../types';

export type MenuButtonVariant = 'button' | 'icon-button' | 'chip' | 'link';

export const DEFAULT_PROPS = {
    variant: 'button',
} satisfies Partial<MenuButtonProps>;

/** ARIA keys set by MenuButton on the trigger — omitted from variant component props. */
type MenuButtonAriaKeys = 'aria-haspopup' | 'aria-controls' | 'aria-expanded';

/** Per-variant keys internally managed by MenuButton — omitted from variant component props. */
type MenuButtonVariantsInternalKeys = {
    button: MenuButtonAriaKeys;
    'icon-button': MenuButtonAriaKeys;
    chip: MenuButtonAriaKeys | 'isClickable';
    link: MenuButtonAriaKeys | 'href' | 'linkAs';
};

/** Discriminated union of MenuButton props across all trigger variants. */
export type MenuButtonVariantsProps<TBase, TVariantProps extends Record<MenuButtonVariant, any>> = {
    [V in MenuButtonVariant]: TBase &
        (V extends 'button' ? { variant?: V } : { variant: V }) &
        Omit<TVariantProps[V], MenuButtonVariantsInternalKeys[V] | keyof TBase>;
}[MenuButtonVariant];

export interface MenuButtonProps {
    variant?: MenuButtonVariant;
    label?: JSXElement;
    children?: JSXElement;
    triggerProps?: Record<string, any>;
    popoverProps?: Record<string, any>;
    onOpen?: (isOpen: boolean) => void;
}

export interface MenuButtonComponents {
    MenuProvider: any;
    MenuTrigger: any;
    MenuPopover: any;
    MenuList: any;
}

export const COMPONENT_NAME = 'MenuButton';
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-menu-button';

/** Menu button core template (composition of menu provider, trigger, popover and list) */
export const MenuButton = (
    props: MenuButtonProps,
    { MenuProvider, MenuTrigger, MenuPopover, MenuList }: MenuButtonComponents,
) => {
    const { label, children, triggerProps, popoverProps, onOpen, variant } = props;

    const extraTriggerProps: Record<string, any> = {};
    if (variant === 'chip') {
        // Chip render as clickable (since the component cannot detect this automatically)
        extraTriggerProps.isClickable = true;
    }

    let triggerChildren;
    if (variant === 'icon-button') {
        // Label as prop (renders as tooltip label)
        extraTriggerProps.label = label;
        // Default icon
        if (!triggerProps?.icon) {
            extraTriggerProps.icon = mdiDotsVertical;
        }
    } else {
        // Only set the label as children when we are not displaying an icon-button
        triggerChildren = label;
    }

    return (
        <MenuProvider onOpen={onOpen}>
            <MenuTrigger {...triggerProps} {...extraTriggerProps}>
                {triggerChildren}
            </MenuTrigger>
            <MenuPopover {...popoverProps}>
                <MenuList>{children}</MenuList>
            </MenuPopover>
        </MenuProvider>
    );
};

// packages/lumx-vue/src/components/menu-button/MenuButton.tsx
import { defineComponent } from 'vue';

import type { JSXElement } from '@lumx/core/js/types';

import {
    DEFAULT_PROPS,
    MenuButton as UI,
    COMPONENT_NAME,
    MenuButtonProps as UIProps,
    type MenuButtonVariant,
    type MenuButtonVariantsProps,
} from '@lumx/core/js/components/Menu/MenuButton';

import { useClassName } from '../../composables/useClassName';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

import Button, { type ButtonProps } from '../button/Button';
import IconButton, { type IconButtonProps } from '../button/IconButton';
import Chip, { type ChipProps } from '../chip/Chip';
import Link, { type LinkProps } from '../link/Link';

import MenuProvider from './MenuProvider';
import MenuTrigger from './MenuTrigger';
import MenuPopover, { MenuPopoverProps } from './MenuPopover';
import MenuList from './MenuList';

/** Props that MenuButton explicitly declares */
type MenuButtonBaseProps = VueToJSXProps<UIProps, 'children' | 'triggerProps' | 'onOpen'> & {
    /** Menu button label */
    label: string;
    /** Trigger variant */
    variant?: MenuButtonVariant;
    /** Menu popover props */
    popoverProps?: MenuPopoverProps;
};

/** MenuButton props — discriminated union over the variant to inherit the target component's props. */
export type MenuButtonProps = MenuButtonVariantsProps<
    MenuButtonBaseProps,
    {
        button: ButtonProps;
        'icon-button': IconButtonProps;
        chip: ChipProps;
        link: LinkProps;
    }
>;

/** Menu trigger button component by variant */
const TRIGGER_COMPONENTS = {
    button: Button,
    'icon-button': IconButton,
    chip: Chip,
    link: Link,
} satisfies Record<MenuButtonVariant, unknown>;

/**
 * MenuButton component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const MenuButton = defineComponent(
    (props: MenuButtonBaseProps, { emit, slots, attrs }) => {
        const className = useClassName(() => props.class);
        const onOpen = (isOpen: boolean) => emit('open', isOpen);

        return () => {
            const { variant = DEFAULT_PROPS.variant as MenuButtonVariant, label, popoverProps } = props;

            return UI(
                {
                    label,
                    children: slots.default?.() as JSXElement,
                    popoverProps,
                    onOpen,
                    variant,
                    triggerProps: { ...attrs, as: TRIGGER_COMPONENTS[variant], class: className.value },
                },
                { MenuProvider, MenuTrigger, MenuPopover, MenuList },
            );
        };
    },
    {
        name: 'LumxMenuButton',
        inheritAttrs: false,
        props: keysOf<MenuButtonBaseProps>()('label', 'popoverProps', 'class', 'variant'),
        emits: ['open'],
    },
);

/**
 * MenuButton component constructor.
 */
export interface MenuButtonConstructor {
    new (props: MenuButtonProps): {
        $props: MenuButtonProps;
    };
}

// Re-type the component to handle discriminated union in prop types
export default MenuButton as unknown as MenuButtonConstructor & typeof MenuButton;
export { COMPONENT_NAME };
