// packages/lumx-vue/src/utils/Portal/Portal.tsx
import { defineComponent, inject, onBeforeUnmount, Teleport, ref, watch } from 'vue';
import { PORTAL_KEY, defaultPortalInit } from './PortalProvider';

export type { PortalProps } from '@lumx/core/js/utils/Portal';
import type { PortalProps } from '@lumx/core/js/utils/Portal';

/**
 * Render children in a portal outside the current DOM position
 * (defaults to `document.body` but can be customized with the PortalProvider)
 */
export const Portal = defineComponent(
    (props: PortalProps, { slots }) => {
        const portalInit = inject(PORTAL_KEY, defaultPortalInit);
        const context = ref<ReturnType<typeof portalInit> | null>(null);

        // Initialize portal context when enabled
        const initializePortal = () => {
            if (props.enabled) {
                context.value = portalInit();
            } else {
                context.value = null;
            }
        };

        // Initialize on mount and when enabled changes
        initializePortal();
        watch(() => props.enabled, initializePortal);

        // Register teardown on unmount
        onBeforeUnmount(() => {
            context.value?.teardown?.();
        });

        return () => {
            const content = slots.default?.();
            const container = context.value?.container;

            // If disabled or no container, render inline
            if (!props.enabled || !container) {
                return content;
            }

            // Render in portal using Teleport
            return <Teleport to={container}>{content}</Teleport>;
        };
    },
    {
        name: 'LumxPortal',
        props: {
            enabled: {
                type: Boolean,
                default: true,
            },
        },
    },
);

// packages/lumx-react/src/utils/Portal/Portal.tsx
import React from 'react';
import { createPortal } from 'react-dom';
import { PortalContext } from './PortalProvider';

export type { PortalProps } from '@lumx/core/js/utils/Portal';

export interface ReactPortalProps {
    enabled?: boolean;
    children: React.ReactNode;
}

/**
 * Render children in a portal outside the current DOM position
 * (defaults to `document.body` but can be customized with the PortalContextProvider)
 */
export const Portal: React.FC<ReactPortalProps> = ({ children, enabled = true }) => {
    const init = React.useContext(PortalContext);
    const context = React.useMemo(
        () => {
            return enabled ? init() : null;
        },
        // Only update on 'enabled'
        // eslint-disable-next-line react-hooks/exhaustive-deps
        [enabled],
    );

    React.useLayoutEffect(() => {
        return context?.teardown;
    }, [context?.teardown, enabled]);

    const { container } = context ?? {};
    if (!container || typeof container === 'string') {
        return <>{children}</>;
    }
    return createPortal(children, container);
};
