// packages/site-demo/content/product/components/menu-button/vue/variants.vue
<template>
    <!-- Default trigger, medium emphasis, small size -->
    <MenuButton label="Actions" emphasis="medium" size="s">
        <MenuItem @click="() => alert('Edit')">Edit</MenuItem>
        <MenuItem @click="() => alert('Duplicate')">Duplicate</MenuItem>
        <MenuDivider />
        <MenuItem @click="() => alert('Delete')">Delete</MenuItem>
    </MenuButton>

    <!-- Icon button trigger -->
    <MenuButton label="Actions" variant="icon-button" emphasis="low">
        <MenuItem @click="() => alert('Edit')">Edit</MenuItem>
        <MenuItem @click="() => alert('Duplicate')">Duplicate</MenuItem>
        <MenuDivider />
        <MenuItem @click="() => alert('Delete')">Delete</MenuItem>
    </MenuButton>

    <!-- Chip trigger -->
    <MenuButton label="Actions" variant="chip">
        <MenuItem @click="() => alert('Edit')">Edit</MenuItem>
        <MenuItem @click="() => alert('Duplicate')">Duplicate</MenuItem>
        <MenuDivider />
        <MenuItem @click="() => alert('Delete')">Delete</MenuItem>
    </MenuButton>

    <!-- Link trigger -->
    <MenuButton label="Actions" variant="link">
        <MenuItem @click="() => alert('Edit')">Edit</MenuItem>
        <MenuItem @click="() => alert('Duplicate')">Duplicate</MenuItem>
        <MenuDivider />
        <MenuItem @click="() => alert('Delete')">Delete</MenuItem>
    </MenuButton>
</template>

<script setup lang="ts">
import { MenuButton, MenuItem, MenuDivider } from '@lumx/vue';

const alert = window.alert;
</script>

// packages/site-demo/content/product/components/menu-button/react/variants.tsx
import { MenuButton, MenuItem, MenuDivider } from '@lumx/react';

export default () => (
    <>
        <MenuButton label="Actions" emphasis="medium" size="s">
            <MenuItem onClick={() => alert('Edit')}>Edit</MenuItem>
            <MenuItem onClick={() => alert('Duplicate')}>Duplicate</MenuItem>
            <MenuDivider />
            <MenuItem onClick={() => alert('Delete')}>Delete</MenuItem>
        </MenuButton>

        <MenuButton variant="icon-button" emphasis="low" label="Actions">
            <MenuItem onClick={() => alert('Edit')}>Edit</MenuItem>
            <MenuItem onClick={() => alert('Duplicate')}>Duplicate</MenuItem>
            <MenuDivider />
            <MenuItem onClick={() => alert('Delete')}>Delete</MenuItem>
        </MenuButton>

        <MenuButton variant="chip" label="Actions">
            <MenuItem onClick={() => alert('Edit')}>Edit</MenuItem>
            <MenuItem onClick={() => alert('Duplicate')}>Duplicate</MenuItem>
            <MenuDivider />
            <MenuItem onClick={() => alert('Delete')}>Delete</MenuItem>
        </MenuButton>

        <MenuButton variant="link" label="Actions">
            <MenuItem onClick={() => alert('Edit')}>Edit</MenuItem>
            <MenuItem onClick={() => alert('Duplicate')}>Duplicate</MenuItem>
            <MenuDivider />
            <MenuItem onClick={() => alert('Delete')}>Delete</MenuItem>
        </MenuButton>
    </>
);
