// packages/lumx-vue/src/components/combobox/ComboboxPopover.tsx
import { computed, defineComponent } from 'vue';

import {
    ComboboxPopover as UI,
    type ComboboxPopoverProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxPopover';
import type { JSXElement } from '@lumx/core/js/types';

import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Popover } from '../popover';
import type { PopoverProps } from '../popover/Popover';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxOpen } from './context/useComboboxOpen';
import { FlexBox } from '../flex-box';

/**
 * Adapter: maps core's `className` prop to Vue's `class` prop for Popover.
 * Also maps `anchorRef` (passed as CommonRef from core) to a Vue-compatible ref.
 * Children are received as Vue slots and forwarded to the Popover component.
 */
const PopoverAdapter = (p: any, { slots }: any) => {
    const { className, onClose, anchorRef, ...rest } = p;
    return (
        <Popover class={className} anchorRef={anchorRef} onClose={onClose} {...rest}>
            {{ default: slots.default }}
        </Popover>
    );
};

/**
 * Props type extends the core ComboboxPopover props (via VueToJSXProps) with additional
 * Popover passthrough props. The core type only declares props it explicitly uses;
 * extra Popover props flow through the core template's `...forwardedProps` spread.
 */
export type ComboboxPopoverProps = VueToJSXProps<UIProps, 'isOpen' | 'anchorRef'> &
    Partial<Omit<PopoverProps, 'isOpen' | 'anchorRef' | 'onClose' | 'class'>>;

/**
 * Combobox.Popover component - renders a Popover connected to the combobox context.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxPopover = defineComponent(
    (props: ComboboxPopoverProps, { slots }) => {
        const { anchorRef } = useComboboxContext();
        const { isOpen, setIsOpen } = useComboboxOpen();

        // Adapt anchorRef: Popover expects Ref<HTMLElement | undefined> | HTMLElement
        const popoverAnchorRef = computed(() => anchorRef.value ?? undefined);

        return () => {
            const { class: className, ...popoverProps } = props;

            return UI(
                {
                    ...popoverProps,
                    children: slots.default?.() as JSXElement,
                    className,
                    isOpen: isOpen.value,
                    anchorRef: popoverAnchorRef as any,
                    handleClose: () => setIsOpen(false),
                },
                { Popover: PopoverAdapter, FlexBox },
            );
        };
    },
    {
        name: 'LumxComboboxPopover',
        inheritAttrs: false,
        props: keysOf<ComboboxPopoverProps>()(
            'as',
            'boundaryRef',
            'class',
            'closeMode',
            'closeOnClickAway',
            'closeOnEscape',
            'elevation',
            'fitToAnchorWidth',
            'fitWithinViewportHeight',
            'focusAnchorOnClose',
            'focusElement',
            'focusTrapZoneElement',
            'hasArrow',
            'offset',
            'parentElement',
            'placement',
            'theme',
            'usePortal',
            'withFocusTrap',
            'zIndex',
        ),
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxPopover;

// packages/lumx-core/src/js/components/Combobox/ComboboxPopover.tsx
import type { HasClassName, JSXElement, LumxClassName } from '../../types';
import type { PopoverProps } from '../Popover';
import type { PopoverSizes } from '../Popover/types';
import { classNames } from '../../utils';
import { DEFAULT_COMBOBOX_POPOVER_MAX_HEIGHT } from './constants';

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'ComboboxPopover';

/**
 * Component default class name.
 */
export const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-combobox-popover';
const { block, element } = classNames.bem(CLASSNAME);

type InheritedPopoverProps = Pick<
    PopoverProps,
    'closeOnClickAway' | 'closeOnEscape' | 'fitToAnchorWidth' | 'isOpen' | 'anchorRef' | 'placement' | 'handleClose'
> &
    PopoverSizes;

/**
 * Defines the props for the core ComboboxPopover template.
 */
export interface ComboboxPopoverProps extends HasClassName, InheritedPopoverProps {
    /** Content (should contain a ComboboxList). */
    children?: JSXElement;
}

/**
 * Injected framework-specific components for ComboboxPopover rendering.
 */
export interface ComboboxPopoverComponents {
    /** Popover component (framework-specific). */
    Popover: any;
    /** FlexBox component (framework-specific). */
    FlexBox: any;
}

/**
 * ComboboxPopover core template.
 * Renders a Popover with combobox-specific defaults (className, closeMode, closeOnClickAway, closeOnEscape).
 *
 * Framework-specific components (Popover) are passed as a second argument
 * by the React/Vue wrappers.
 *
 * @param props      Component props.
 * @param components Injected framework-specific components.
 * @return JSX element.
 */
export const ComboboxPopover = (props: ComboboxPopoverProps, { Popover, FlexBox }: ComboboxPopoverComponents) => {
    const {
        children,
        className,
        closeOnClickAway = true,
        closeOnEscape = false,
        fitToAnchorWidth = true,
        isOpen,
        maxHeight = DEFAULT_COMBOBOX_POPOVER_MAX_HEIGHT,
        placement = 'bottom-start',
        anchorRef,
        handleClose,
        ...forwardedProps
    } = props;

    return (
        <Popover
            {...forwardedProps}
            placement={placement}
            fitToAnchorWidth={fitToAnchorWidth}
            maxHeight={maxHeight}
            className={block([className])}
            anchorRef={anchorRef}
            isOpen={isOpen}
            onClose={handleClose}
            closeOnClickAway={closeOnClickAway}
            closeOnEscape={closeOnEscape}
            closeMode="hide"
        >
            <FlexBox orientation="vertical" className={element('scroll')}>
                {children}
            </FlexBox>
        </Popover>
    );
};
