// packages/site-demo/content/product/components/dialog/react/processing-state.tsx
import { useCallback, useRef, useState } from 'react';
import { mdiPlay } from '@lumx/icons';
import { Button, Dialog, DialogHeading, Toolbar, type Theme } from '@lumx/react';
import { classNames } from '@lumx/core/js/utils';

export default ({ theme }: { theme?: Theme }) => {
    const [isOpen, setOpen] = useState(false);
    const close = useCallback(() => setOpen(false), []);
    const toggle = useCallback(() => setOpen(!isOpen), [isOpen]);
    const buttonRef = useRef(null);
    return (
        <>
            <Button leftIcon={mdiPlay} ref={buttonRef} onClick={toggle} theme={theme}>
                Open processing dialog
            </Button>

            <Dialog isOpen={isOpen} isLoading parentElement={buttonRef} onClose={close}>
                <header>
                    <Toolbar label={<DialogHeading>Default dialog</DialogHeading>} />
                </header>

                <p className={classNames.padding('horizontal', 'huge')}>
                    Nihil hic munitissimus habendi senatus locus, nihil horum? At nos hinc posthac, sitientis piros
                    Afros. Magna pars studiorum, prodita quaerimus. Integer legentibus erat a ante historiarum dapibus.
                    Praeterea iter est quasdam res quas ex communi. Ullamco laboris nisi ut aliquid ex ea commodi
                    consequat. Inmensae subtilitatis, obscuris et malesuada fames. Me non paenitet nullum festiviorem
                    excogitasse ad hoc. Cum ceteris in veneratione tui montes, nascetur mus. Etiam habebis sem dicantur
                    magna mollis euismod. Quis aute iure reprehenderit in voluptate velit esse. Phasellus laoreet lorem
                    vel dolor tempus vehicula. Ambitioni dedisse scripsisse iudicaretur. Paullum deliquit, ponderibus
                    modulisque suis ratio utitur. Ab illo tempore, ab est sed immemorabili. Nec dubitamus multa iter
                    quae et nos invenerat. Tu quoque, Brute, fili mi, nihil timor populi, nihil! Morbi fringilla
                    convallis sapien, id pulvinar odio volutpat. Cras mattis iudicium purus sit amet fermentum. Vivamus
                    sagittis lacus vel augue laoreet rutrum faucibus. Quisque ut dolor gravida, placerat libero vel,
                    euismod.
                </p>

                <footer>
                    <Toolbar
                        after={
                            <>
                                <Button emphasis="medium" onClick={close}>
                                    Cancel
                                </Button>
                                <Button className={classNames.margin('left', 'regular')} onClick={close}>
                                    Save
                                </Button>
                            </>
                        }
                    />
                </footer>
            </Dialog>
        </>
    );
};

// packages/site-demo/content/product/components/dialog/vue/processing-state.vue
<template>
    <Button :left-icon="mdiPlay" ref="buttonRef" @click="toggle" :theme="theme">Open processing dialog</Button>

    <Dialog :is-open="isOpen" :is-loading="true" :parent-element="buttonRef?.$el" @close="close">
        <template #header>
            <Toolbar>
                <DialogHeading>Default dialog</DialogHeading>
            </Toolbar>
        </template>

        <p class="lumx-spacing-padding-horizontal-huge">
            Nihil hic munitissimus habendi senatus locus, nihil horum? At nos hinc posthac, sitientis piros Afros. Magna
            pars studiorum, prodita quaerimus. Integer legentibus erat a ante historiarum dapibus. Praeterea iter est
            quasdam res quas ex communi. Ullamco laboris nisi ut aliquid ex ea commodi consequat. Inmensae subtilitatis,
            obscuris et malesuada fames. Me non paenitet nullum festiviorem excogitasse ad hoc. Cum ceteris in
            veneratione tui montes, nascetur mus. Etiam habebis sem dicantur magna mollis euismod. Quis aute iure
            reprehenderit in voluptate velit esse. Phasellus laoreet lorem vel dolor tempus vehicula.
        </p>

        <template #footer>
            <Toolbar>
                <template #after>
                    <Button emphasis="medium" @click="close">Cancel</Button>
                    <Button class="lumx-spacing-margin-left-regular" @click="close">Save</Button>
                </template>
            </Toolbar>
        </template>
    </Dialog>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { mdiPlay } from '@lumx/icons';
import { Button, Dialog, DialogHeading, Toolbar, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();

const buttonRef = ref<InstanceType<typeof Button>>();
const isOpen = ref(false);
const close = () => { isOpen.value = false; };
const toggle = () => { isOpen.value = !isOpen.value; };
</script>
