// packages/site-demo/content/product/components/thumbnail/react/sizes.tsx
import { Thumbnail } from '@lumx/react';

export default () => (
    <>
        <Thumbnail image="https://picsum.photos/id/511/300/300" alt="xxs" size="xxs" />
        <Thumbnail image="https://picsum.photos/id/511/300/300" alt="xs" size="xs" />
        <Thumbnail image="https://picsum.photos/id/511/300/300" alt="s" size="s" />
        <Thumbnail image="https://picsum.photos/id/511/300/300" alt="m" size="m" />
        <Thumbnail image="https://picsum.photos/id/511/300/300" alt="l" size="l" />
        <Thumbnail image="https://picsum.photos/id/511/300/300" alt="xl" size="xl" />
        <div style={{ width: 300 }}>
            <Thumbnail image="https://picsum.photos/id/511/300/300" alt="free" />
        </div>
    </>
);

// packages/site-demo/content/product/components/avatar/vue/sizes.vue
<template>
    <Avatar :theme="theme" image="https://i.pravatar.cc/128?img=32" alt="XS" size="xs" />
    <Avatar :theme="theme" image="https://i.pravatar.cc/128?img=32" alt="S" size="s" />
    <Avatar :theme="theme" image="https://i.pravatar.cc/128?img=32" alt="M" size="m" />
    <Avatar :theme="theme" image="https://i.pravatar.cc/128?img=32" alt="L" size="l" />
    <Avatar :theme="theme" image="https://i.pravatar.cc/128?img=32" alt="XL" size="xl" />
</template>

<script setup lang="ts">
import { Avatar, type Theme } from '@lumx/vue';

defineProps<{ theme?: Theme }>();
</script>
