// packages/lumx-react/src/components/radio-button/RadioGroup.tsx
import { ReactNode } from 'react';

import { GenericProps } from '@lumx/react/utils/type';
import type { LumxClassName } from '@lumx/core/js/types';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useClassnames } from '@lumx/react/utils';

/**
 * Defines the props of the component.
 */
export interface RadioGroupProps extends GenericProps {
    /** RadioButton elements */
    children: ReactNode;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'RadioGroup';

/**
 * Component default class name and class prefix.
 */
const CLASSNAME: LumxClassName<typeof COMPONENT_NAME> = 'lumx-radio-group';

/**
 * RadioGroup component.
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const RadioGroup = forwardRef<RadioGroupProps, HTMLDivElement>((props, ref) => {
    const { children, className, ...forwardedProps } = props;
    const { block } = useClassnames(CLASSNAME);

    return (
        <div ref={ref} {...forwardedProps} className={block([className])}>
            {children}
        </div>
    );
});
RadioGroup.displayName = COMPONENT_NAME;
RadioGroup.className = CLASSNAME;

// packages/lumx-vue/src/components/radio-button/RadioGroup.tsx
import { defineComponent, useAttrs } from 'vue';

import { RadioGroup as RadioGroupUI, CLASSNAME, COMPONENT_NAME } from '@lumx/core/js/components/RadioGroup';
import type { JSXElement } from '@lumx/core/js/types';

import { keysOf } from '../../utils/VueToJSX';

export interface RadioGroupProps {
    /** CSS class name */
    class?: string;
}

export { CLASSNAME, COMPONENT_NAME };

/**
 * RadioGroup component.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const RadioGroup = defineComponent(
    (props: RadioGroupProps, { slots }) => {
        const attrs = useAttrs();

        return () => (
            <RadioGroupUI {...props} {...attrs} className={props.class} children={slots.default?.() as JSXElement} />
        );
    },
    {
        name: 'RadioGroup',
        inheritAttrs: false,
        props: keysOf<RadioGroupProps>()('class'),
    },
);

export default RadioGroup;
