// packages/site-demo/content/product/components/message/react/demo5.tsx
import { Message } from '@lumx/react';

export default () => (
    <Message kind="info">
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
);

// packages/site-demo/content/product/components/message/vue/demo5.vue
<template>
    <Message kind="info">
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
</template>

<script setup lang="ts">
import { Message } from '@lumx/vue';
</script>
