// packages/site-demo/content/product/components/message/react/warning.tsx
import { Message, Kind } from '@lumx/react';
import React from 'react';

export const App = () => (
    <Message kind={Kind.warning} hasBackground>
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
);

// packages/site-demo/content/product/components/message/vue/warning.vue
<template>
    <Message kind="warning" :has-background="true">
        <p>
            Message text quisque tincidunt lobortis dui non auctor. Donec porta, ligula volutpat vehicula aliquet, dui
            sapien tempus felis, sed cursus diam ante.
        </p>
    </Message>
</template>

<script setup lang="ts">
import { Message } from '@lumx/vue';
</script>
