// packages/lumx-vue/src/components/text-field/RawInputText.tsx
import { defineComponent, useAttrs } from 'vue';

import {
    RawInputText as RawInputTextUI,
    type RawInputTextProps as UIProps,
} from '@lumx/core/js/components/TextField/RawInputText';

import { useTheme } from '../../composables/useTheme';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

export type RawInputTextProps = VueToJSXProps<UIProps>;

export const emitSchema = {
    change: (value: string, name?: string, event?: Event) => typeof value === 'string',
};

/**
 * Raw input text component.
 * (input element without any decoration)
 *
 * @param  props Component props.
 * @return Vue element.
 */
const RawInputText = defineComponent(
    (props: RawInputTextProps, { emit }) => {
        const attrs = useAttrs();
        const defaultTheme = useTheme();

        const handleChange = (value: string, name?: string, event?: any) => {
            event?.stopImmediatePropagation();
            emit('change', value, name, event);
        };

        return () => {
            return (
                <RawInputTextUI
                    {...(attrs as UIProps)}
                    value={props.value}
                    type={props.type}
                    name={props.name}
                    className={props.class}
                    theme={props.theme || defaultTheme.value}
                    handleChange={handleChange}
                />
            );
        };
    },
    {
        name: 'LumxRawInputText',
        inheritAttrs: false,
        props: keysOf<RawInputTextProps>()('class', 'theme', 'value', 'type', 'name'),
        emits: emitSchema,
    },
);

export default RawInputText;

// packages/lumx-react/src/components/text-field/RawInputText.tsx
import { SyntheticEvent } from 'react';

import { Theme, useTheme } from '@lumx/react';

import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import {
    RawInputText as UI,
    RawInputTextProps as UIProps,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/TextField/RawInputText';

import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';

/**
 * Defines the props of the component.
 */
export interface RawInputTextProps extends ReactToJSX<UIProps> {
    onChange?: (value: string, name?: string, event?: SyntheticEvent) => void;
}
/**
 * Component default props.
 */
export { DEFAULT_PROPS };

/**
 * Raw input text component
 * (input element without any decoration)
 */
export const RawInputText = forwardRef<RawInputTextProps, HTMLInputElement>((props, ref) => {
    const defaultTheme = useTheme() || Theme.light;
    const { theme = defaultTheme, onChange, ...restOfProps } = props;

    return UI({
        ...restOfProps,
        ref,
        theme,
        handleChange: onChange,
    });
});
