// packages/lumx-core/src/js/components/Tabs/TabList.tsx
import { Alignment } from '../../constants';
import { CommonRef, HasClassName, HasTheme, JSXElement } from '../../types';
import { classNames } from '../../utils';

import { TABS_CLASSNAME as CLASSNAME } from './constants';

const { block, element } = classNames.bem(CLASSNAME);

export enum TabListLayout {
    clustered = 'clustered',
    fixed = 'fixed',
}

/**
 * Defines the props of the component.
 */
export interface TabListProps extends HasClassName, HasTheme {
    /** ARIA label (purpose of the set of tabs). */
    ['aria-label']: string;
    /** Tab list. */
    children: JSXElement;
    /** Layout of the tabs in the list. */
    layout?: TabListLayout;
    /** Position of the tabs in the list (requires 'clustered' layout). */
    position?: Alignment;
    /** ref to the wrapper element */
    ref?: CommonRef;
}

/**
 * Component display name.
 */
export const COMPONENT_NAME = 'TabList';

/**
 * Component default props.
 */
export const DEFAULT_PROPS: Partial<TabListProps> = {
    layout: TabListLayout.fixed,
    position: Alignment.left,
};

/**
 * TabList component.
 *
 * Implements WAI-ARIA `tablist` role {@see https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html#rps_label}
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const TabList = (props: TabListProps) => {
    const {
        'aria-label': ariaLabel,
        children,
        className,
        layout = DEFAULT_PROPS.layout,
        position = DEFAULT_PROPS.position,
        theme,
        ref,
        ...forwardedProps
    } = props;

    return (
        <div
            ref={ref}
            {...forwardedProps}
            className={classNames.join(
                className,
                block({
                    [`layout-${layout}`]: Boolean(layout),
                    [`position-${position}`]: Boolean(position),
                    [`theme-${theme}`]: Boolean(theme),
                }),
            )}
        >
            <div className={element('links')} role="tablist" aria-label={ariaLabel}>
                {children}
            </div>
        </div>
    );
};

// packages/lumx-vue/src/components/tabs/TabList.tsx
import { defineComponent, ref, useAttrs, useSlots } from 'vue';

import {
    TabList as TabListUI,
    type TabListProps as UIProps,
    TabListLayout,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Tabs/TabList';
import { TABS_CLASSNAME as CLASSNAME } from '@lumx/core/js/components/Tabs/constants';
import { type JSXElement } from '@lumx/core/js/types';

import { useTheme } from '../../composables/useTheme';
import { useRovingTabIndexContainer } from '../../composables/useRovingTabIndexContainer';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

// aria-label is excluded from declared Vue props — Vue treats aria-* as attrs,
// so it flows through the {..attrs} spread to the core component.
type InternalProps = VueToJSXProps<UIProps, 'aria-label'>;

/** Public props type (includes aria-label for TypeScript consumers). */
export type TabListProps = InternalProps & { 'aria-label': string };

export { TabListLayout, CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * TabList component.
 *
 * Implements WAI-ARIA `tablist` role.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const TabList = defineComponent(
    (props: InternalProps) => {
        const attrs = useAttrs();
        const slots = useSlots();
        const defaultTheme = useTheme();
        const containerRef = ref<HTMLElement | null>(null);

        useRovingTabIndexContainer({
            containerRef,
            itemSelector: '[role="tab"]',
        });

        return () => (
            <TabListUI
                {...attrs}
                ref={containerRef}
                aria-label={attrs['aria-label'] as string}
                className={props.class}
                theme={props.theme || defaultTheme.value}
                layout={props.layout}
                position={props.position}
                children={slots.default?.() as JSXElement}
            />
        );
    },
    {
        name: 'LumxTabList',
        inheritAttrs: false,
        props: keysOf<InternalProps>()('layout', 'position', 'theme', 'class'),
    },
);

export default TabList;
