// packages/lumx-react/src/components/tabs/TabList.tsx
import React, { ReactNode } from 'react';

import classNames from 'classnames';

import { Alignment, Theme } from '@lumx/react';
import { GenericProps, HasTheme } from '@lumx/react/utils/type';
import { handleBasicClasses } from '@lumx/core/js/utils/className';
import { mergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useTheme } from '@lumx/react/utils/theme/ThemeContext';

import { useRovingTabIndex } from '../../hooks/useRovingTabIndex';
import { TABS_CLASSNAME as CLASSNAME } from './constants';

export enum TabListLayout {
    clustered = 'clustered',
    fixed = 'fixed',
}

/**
 * Defines the props of the component.
 */
export interface TabListProps extends GenericProps, HasTheme {
    /** ARIA label (purpose of the set of tabs). */
    ['aria-label']: string;
    /** Tab list. */
    children: ReactNode;
    /** Layout of the tabs in the list. */
    layout?: TabListLayout;
    /** Position of the tabs in the list (requires 'clustered' layout). */
    position?: Alignment;
}

/**
 * Component display name.
 */
const COMPONENT_NAME = 'TabList';

/**
 * Component default props.
 */
const DEFAULT_PROPS: Partial<TabListProps> = {
    layout: TabListLayout.fixed,
    position: Alignment.left,
};

/**
 * TabList component.
 *
 * Implements WAI-ARIA `tablist` role {@see https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html#rps_label}
 *
 * @param  props Component props.
 * @param  ref   Component ref.
 * @return React element.
 */
export const TabList = forwardRef<TabListProps, HTMLDivElement>((props, ref) => {
    const defaultTheme = useTheme() || Theme.light;
    const {
        'aria-label': ariaLabel,
        children,
        className,
        layout = DEFAULT_PROPS.layout,
        position = DEFAULT_PROPS.position,
        theme = defaultTheme,
        ...forwardedProps
    } = props;
    const tabListRef = React.useRef(null);
    useRovingTabIndex({
        parentRef: tabListRef,
        elementSelector: '[role="tab"]',
        keepTabIndex: false,
        extraDependencies: [children],
    });

    return (
        <div
            ref={mergeRefs(ref, tabListRef)}
            {...forwardedProps}
            className={classNames(className, handleBasicClasses({ prefix: CLASSNAME, layout, position, theme }))}
        >
            <div className={`${CLASSNAME}__links`} role="tablist" aria-label={ariaLabel}>
                {children}
            </div>
        </div>
    );
});
TabList.displayName = COMPONENT_NAME;
TabList.className = CLASSNAME;
TabList.defaultProps = DEFAULT_PROPS;

// packages/lumx-vue/src/components/tabs/TabList.tsx
import { defineComponent, ref, useAttrs, useSlots } from 'vue';

import {
    TabList as TabListUI,
    type TabListProps as UIProps,
    TabListLayout,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Tabs/TabList';
import { TABS_CLASSNAME as CLASSNAME } from '@lumx/core/js/components/Tabs/constants';
import { type JSXElement } from '@lumx/core/js/types';

import { useTheme } from '../../composables/useTheme';
import { useRovingTabIndexContainer } from '../../composables/useRovingTabIndexContainer';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';

// aria-label is excluded from declared Vue props — Vue treats aria-* as attrs,
// so it flows through the {..attrs} spread to the core component.
type InternalProps = VueToJSXProps<UIProps, 'aria-label'>;

/** Public props type (includes aria-label for TypeScript consumers). */
export type TabListProps = InternalProps & { 'aria-label': string };

export { TabListLayout, CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * TabList component.
 *
 * Implements WAI-ARIA `tablist` role.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const TabList = defineComponent(
    (props: InternalProps) => {
        const attrs = useAttrs();
        const slots = useSlots();
        const defaultTheme = useTheme();
        const containerRef = ref<HTMLElement | null>(null);

        useRovingTabIndexContainer({
            containerRef,
            itemSelector: '[role="tab"]',
        });

        return () => (
            <TabListUI
                {...attrs}
                ref={containerRef}
                aria-label={attrs['aria-label'] as string}
                className={props.class}
                theme={props.theme || defaultTheme.value}
                layout={props.layout}
                position={props.position}
                children={slots.default?.() as JSXElement}
            />
        );
    },
    {
        name: 'LumxTabList',
        inheritAttrs: false,
        props: keysOf<InternalProps>()('layout', 'position', 'theme', 'class'),
    },
);

export default TabList;
