// packages/lumx-react/src/components/tabs/TabPanel.tsx
import { useTabProviderContext } from '@lumx/react/components/tabs/state';
import { COMPONENT_PREFIX, CSS_PREFIX } from '@lumx/react/constants';
import { Comp, GenericProps, handleBasicClasses } from '@lumx/react/utils';

import classNames from 'classnames';
import React from 'react';

/**
 * Defines the props of the component.
 */
export interface TabPanelProps extends GenericProps {
    /** The tab panel HTML id. */
    id?: string;
    /** Whether the tab is active or not. */
    isActive?: boolean;
}

/**
 * The display name of the component.
 */
const COMPONENT_NAME = `${COMPONENT_PREFIX}TabPanel`;

/**
 * The default class name and classes prefix for this component.
 */
const CLASSNAME = `${CSS_PREFIX}-tab-panel`;

/**
 * The default value of props.
 */
const DEFAULT_PROPS: Partial<TabPanelProps> = {};

/**
 * TabPanel component.
 *
 * Implements WAI-ARIA `tabpanel` role {@see https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html#rps_label}
 *
 * @param  props Component props.
 * @return React element.
 */
export const TabPanel: Comp<TabPanelProps> = (props) => {
    const { children, id, className, isActive: propIsActive, ...forwardedProps } = props;

    const state = useTabProviderContext('tabPanel', id);
    const isActive = propIsActive || state?.isActive;

    return (
        <div
            {...forwardedProps}
            id={state?.tabPanelId}
            className={classNames(className, handleBasicClasses({ prefix: CLASSNAME, isActive }))}
            role="tabpanel"
            tabIndex={0}
            aria-labelledby={state?.tabId}
        >
            {(!state?.isLazy || isActive) && children}
        </div>
    );
};
TabPanel.displayName = COMPONENT_NAME;
TabPanel.className = CLASSNAME;
TabPanel.defaultProps = DEFAULT_PROPS;

// packages/lumx-vue/src/components/tabs/TabPanel.tsx
import { computed, defineComponent, useAttrs, useSlots } from 'vue';

import {
    TabPanel as TabPanelUI,
    type TabPanelProps as UIProps,
    type TabPanelPropsToOverride,
    CLASSNAME,
    COMPONENT_NAME,
    DEFAULT_PROPS,
} from '@lumx/core/js/components/Tabs/TabPanel';
import { type JSXElement } from '@lumx/core/js/types';

import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useTabProviderContext } from './state';

export type TabPanelProps = VueToJSXProps<UIProps, TabPanelPropsToOverride>;

export { CLASSNAME, COMPONENT_NAME, DEFAULT_PROPS };

/**
 * TabPanel component.
 *
 * Implements WAI-ARIA `tabpanel` role.
 *
 * @param  props Component props.
 * @return Vue element.
 */
const TabPanel = defineComponent(
    (props: TabPanelProps) => {
        const attrs = useAttrs();
        const slots = useSlots();
        const tabState = useTabProviderContext('tabPanel', props.id as string | undefined);
        const isActive = computed(() => props.isActive || tabState.value?.isActive);

        return () => (
            <TabPanelUI
                {...attrs}
                className={props.class}
                isActive={isActive.value}
                id={tabState.value?.tabPanelId}
                isLazy={tabState.value?.isLazy}
                tabId={tabState.value?.tabId}
                tabIndexProp="tabindex"
                children={slots.default?.() as JSXElement}
            />
        );
    },
    {
        name: 'LumxTabPanel',
        inheritAttrs: false,
        props: keysOf<TabPanelProps>()('isActive', 'id', 'class'),
    },
);

export default TabPanel;
