// packages/lumx-vue/src/components/combobox/ComboboxList.tsx
import { defineComponent, ref, useAttrs, watch } from 'vue';

import {
    ComboboxList as UI,
    type ComboboxListProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxList';
import type { JSXElement } from '@lumx/core/js/types';

import { useClassName } from '../../composables/useClassName';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { useWatchDisposable } from '../../composables/useWatchDisposable';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxEvent } from './context/useComboboxEvent';
import { provideComboboxListContext } from './context/ComboboxListContext';

export type ComboboxListProps = VueToJSXProps<UIProps, 'aria-label' | 'aria-busy' | 'aria-multiselectable' | 'id'>;

/**
 * Combobox.List component - wraps List with listbox ARIA attributes.
 * Registers itself as the combobox listbox on mount.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxList = defineComponent(
    (props: ComboboxListProps, { slots }) => {
        const attrs = useAttrs();
        const className = useClassName(() => props.class);
        const { listboxId, handle } = useComboboxContext();
        const listRef = ref<HTMLElement | null>(null);

        provideComboboxListContext({
            // Getters: keep the provided values reactive (read again on each consumer render).
            get type() {
                return props.type || 'listbox';
            },
            get selectionType() {
                const multiselectable = attrs['aria-multiselectable'];
                return multiselectable === true || multiselectable === 'true' ? 'multiple' : 'single';
            },
        });

        // Register the list as the listbox when both handle and list element are available
        useWatchDisposable([handle, listRef], ([handleValue, list]) => {
            if (!handleValue || !list) return;
            return handleValue.registerListbox(list);
        });

        // Tracking states
        const isLoading = useComboboxEvent('loadingChange', false);
        const isOpen = useComboboxEvent('open', false);
        const options = useComboboxEvent('optionsChange', undefined);

        // Flush pending navigation (that could not run when closed)
        watch(
            [isOpen, () => options.value?.optionsLength],
            () => {
                if (isOpen.value) handle.value?.flushPendingNavigation();
            },
            { flush: 'post' },
        );

        return () => {
            const children = isOpen.value ? (slots.default?.() as JSXElement) : null;
            // Get aria-label and aria-multiselectable from attrs (Vue normalizes hyphenated prop
            // names to camelCase in props, so we read from attrs to get the original values)
            const ariaLabel = (attrs['aria-label'] ?? '') as string;
            const ariaMultiselectable = attrs['aria-multiselectable'] as boolean | undefined;
            return UI({
                'aria-label': ariaLabel,
                'aria-multiselectable': ariaMultiselectable || undefined,
                'aria-busy': isLoading.value || undefined,
                className: className.value,
                ref: listRef as any,
                id: listboxId,
                type: props.type || 'listbox',
                children,
            } as any);
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        // Note: 'aria-label' is intentionally NOT declared as a prop because Vue normalizes
        // hyphenated prop names to camelCase (ariaLabel) internally, making it inaccessible
        // via props['aria-label']. Instead, we read it from attrs where Vue keeps the original name.
        props: keysOf<ComboboxListProps>()('type', 'class'),
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxList;

// packages/lumx-react/src/components/combobox/ComboboxList.tsx
import { useEffect, useMemo, useRef, useState } from 'react';

import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import {
    ComboboxList as UI,
    ComboboxListProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxList';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { useComboboxContext } from './context/ComboboxContext';
import { ComboboxListContext } from './context/ComboboxListContext';
import { useComboboxOpen } from './context/useComboboxOpen';
import { useComboboxEvent } from './context/useComboboxEvent';

/** Props for Combobox.List component. */
export interface ComboboxListProps extends ReactToJSX<UIProps, 'aria-busy'> {}

/**
 * Combobox.List component - wraps List with listbox ARIA attributes.
 * Registers itself as the combobox listbox on mount.
 *
 * To render the list inside a popover, wrap it with Combobox.Popover.
 *
 * @param props Component props.
 * @param ref   Component ref.
 * @return React element.
 */
export const ComboboxList = forwardRef<ComboboxListProps, HTMLUListElement>((props, ref) => {
    const { listboxId, handle } = useComboboxContext();
    const { 'aria-label': ariaLabel, type = 'listbox', className, children, ...forwardedProps } = props;
    const internalRef = useRef<HTMLUListElement>(null);
    const mergedRef = useMergeRefs(ref, internalRef);
    const selectionType = String(forwardedProps['aria-multiselectable']) === 'true' ? 'multiple' : 'single';
    const listContextValue = useMemo(() => ({ type, selectionType }) as const, [type, selectionType]);
    const [isOpen] = useComboboxOpen();
    const options = useComboboxEvent('optionsChange', undefined);
    const visibleCount = options?.optionsLength ?? 0;

    // Register list as listbox when handle is available.
    useEffect(() => {
        const list = internalRef.current;
        if (!list) return undefined;
        return handle?.registerListbox(list);
    }, [handle]);

    // Track loading state for aria-busy
    const [isLoading, setIsLoading] = useState(false);
    useEffect(() => {
        if (!handle) return undefined;
        // Read current state synchronously (catches registrations before subscription).
        setIsLoading(handle.isLoading);
        return handle.subscribe('loadingChange', setIsLoading);
    }, [handle]);

    // Flush pending keyboard navigation after options commit on open.
    useEffect(() => {
        if (isOpen) handle?.flushPendingNavigation();
    }, [isOpen, visibleCount, handle]);

    return (
        <ComboboxListContext.Provider value={listContextValue}>
            {UI({
                ...forwardedProps,
                'aria-label': ariaLabel,
                'aria-busy': isLoading || undefined,
                className,
                ref: mergedRef,
                id: listboxId,
                type,
                children: isOpen ? children : null,
            })}
        </ComboboxListContext.Provider>
    );
});

ComboboxList.displayName = COMPONENT_NAME;
ComboboxList.className = CLASSNAME;
