// packages/lumx-vue/src/components/combobox/ComboboxInput.tsx
import { defineComponent, onMounted, onUnmounted, ref, watch } from 'vue';

import { ComboboxInput as UI, COMPONENT_NAME, CLASSNAME } from '@lumx/core/js/components/Combobox/ComboboxInput';
import { setupComboboxInput } from '@lumx/core/js/components/Combobox/setupComboboxInput';

import { useClassName } from '../../composables/useClassName';
import { keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import type { TextFieldProps } from '../text-field/TextField';
import { TextField } from '../text-field';
import { IconButton } from '../button';
import type { IconButtonProps } from '../button/IconButton';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxOpen } from './context/useComboboxOpen';

/**
 * Props for Combobox.Input component.
 * Note: role, aria-autocomplete, aria-controls, aria-expanded are set internally and cannot be overridden.
 */
export type ComboboxInputProps = VueToJSXProps<TextFieldProps, 'inputRef' | 'textFieldRef'> & {
    /**
     * Props for the toggle button.
     * When provided, a chevron button will be rendered in the text field's afterElement
     * to toggle the listbox visibility.
     */
    toggleButtonProps?: Pick<IconButtonProps, 'label'> & Partial<Omit<IconButtonProps, 'label'>>;
    /** Called when an option is selected. */
    onSelect?: (option: { value: string }) => void;
    /**
     * Controls how the combobox filters options as the user types.
     *
     * - `'auto'` (default) — Options are automatically filtered client-side.
     * - `'manual'` — Filtering is the consumer's responsibility.
     * - `'off'` — Like `'manual'`, but the input is rendered as `readOnly`
     *   and `openOnFocus` defaults to `true`.
     */
    filter?: 'auto' | 'manual' | 'off';
    /**
     * When true, the combobox opens automatically when the input receives focus.
     * When false (default, unless `filter` is `'off'`), the combobox only opens
     * on click, typing, or keyboard navigation.
     *
     * @default false (true when filter is 'off')
     */
    openOnFocus?: boolean;
};

/**
 * Combobox.Input component - wraps TextField with combobox ARIA attributes.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxInput = defineComponent(
    (props: ComboboxInputProps, { emit, attrs }) => {
        const className = useClassName(() => props.class);
        const { listboxId, anchorRef, setHandle, handle } = useComboboxContext();
        const { isOpen, setIsOpen } = useComboboxOpen();

        const inputEl = ref<HTMLInputElement | null>(null);
        const textFieldEl = ref<HTMLElement | null>(null);

        // Sync the anchor ref when the text field element is set (via the adapter ref callback).
        watch(
            textFieldEl,
            (el) => {
                anchorRef.value = el;
            },
            { flush: 'sync' },
        );

        // Get the input element from the TextField component after mount
        onMounted(() => {
            const input = inputEl.value;
            if (!input) return;

            setHandle(
                setupComboboxInput(input, {
                    onSelect(option) {
                        // Update controlled value through Vue's emit flow.
                        emit('change', option.value);
                        props.onSelect?.(option);
                        emit('select', option);
                    },
                    filter: props.filter,
                    openOnFocus: props.openOnFocus,
                }),
            );
        });

        onUnmounted(() => {
            handle.value?.destroy();
            setHandle(null);
        });

        const handleToggle = () => {
            setIsOpen(!isOpen.value);
            inputEl.value?.focus();
        };

        return () => {
            const {
                toggleButtonProps,
                onSelect: _onSelect,
                filter,
                openOnFocus: _oof,
                class: _class,
                ...forwardedProps
            } = props;

            // Event handlers are framework-specific and forwarded through the core template's
            // spread to the TextField adapter. They are not in the core ComboboxInputProps type.
            const eventHandlers = {
                onChange: (value: string, name?: string, event?: Event) => emit('change', value, name, event),
                onInput: (value: string) => emit('change', value),
                onFocus: (event?: FocusEvent) => emit('focus', event),
                onBlur: (event?: FocusEvent) => emit('blur', event),
                onClear: (event?: MouseEvent) => emit('clear', event),
            };

            // Vue normalizes 'aria-disabled' prop to camelCase 'ariaDisabled'.
            // Re-map it to kebab-case for the core template which expects 'aria-disabled'.
            const { ariaDisabled: fwdAriaDisabled, ...restForwardedProps } = forwardedProps as any;

            return UI(
                {
                    ...attrs,
                    ...restForwardedProps,
                    'aria-disabled': fwdAriaDisabled ?? (attrs as any).ariaDisabled,
                    ...eventHandlers,
                    listboxId,
                    isOpen: isOpen.value,
                    filter,
                    textFieldRef: (el: HTMLElement | null) => {
                        textFieldEl.value = el;
                    },
                    inputRef: (el: HTMLInputElement | null) => {
                        inputEl.value = el;
                    },
                    toggleButtonProps,
                    handleToggle,
                    className: className.value,
                },
                { TextField, IconButton },
            );
        };
    },
    {
        name: 'LumxComboboxInput',
        inheritAttrs: false,
        props: keysOf<ComboboxInputProps>()(
            'class',
            'theme',
            'value',
            'error',
            'forceFocusStyle',
            'hasError',
            'afterElement',
            'helper',
            'icon',
            'isRequired',
            'isValid',
            'label',
            'labelProps',
            'maxLength',
            'isDisabled',
            'disabled',
            'aria-disabled',
            'multiline',
            'placeholder',
            'id',
            'clearButtonProps',
            'name',
            'type',
            'minimumRows',
            'toggleButtonProps',
            'onSelect',
            'filter',
            'openOnFocus',
        ),
        emits: {
            select: (option: { value: string }) => !!option,
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            change: (value: string, _name?: string, _event?: Event) => typeof value === 'string',
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            focus: (_event?: FocusEvent) => true,
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            blur: (_event?: FocusEvent) => true,
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            clear: (_event?: MouseEvent) => true,
        },
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxInput;

// packages/lumx-react/src/components/combobox/ComboboxInput.tsx
import { type Ref, useCallback, useEffect, useRef } from 'react';

import { setupComboboxInput } from '@lumx/core/js/components/Combobox/setupComboboxInput';
import { ComboboxInput as UI, COMPONENT_NAME, CLASSNAME } from '@lumx/core/js/components/Combobox/ComboboxInput';
import { forwardRef } from '@lumx/react/utils/react/forwardRef';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { IconButton, IconButtonProps } from '../button';
import { TextField, TextFieldProps } from '../text-field';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxOpen } from './context/useComboboxOpen';

/**
 * Props for Combobox.Input component.
 * Note: role, aria-autocomplete, aria-controls, aria-expanded are set internally and cannot be overridden.
 */
export interface ComboboxInputProps extends TextFieldProps {
    /** Reference to the input element. */
    inputRef?: Ref<HTMLInputElement>;
    /**
     * Props for the toggle button.
     * When provided, a chevron button will be rendered in the text field's afterElement
     * to toggle the listbox visibility.
     */
    toggleButtonProps?: Pick<IconButtonProps, 'label'> & Partial<Omit<IconButtonProps, 'label'>>;
    /** Called when an option is selected. */
    onSelect?: (option: { value: string }) => void;
    /**
     * Controls how the combobox filters options as the user types.
     *
     * - `'auto'` (default) — Options are automatically filtered client-side.
     * - `'manual'` — Filtering is the consumer's responsibility.
     * - `'off'` — Like `'manual'`, but the input is rendered as `readOnly`
     *   and `openOnFocus` defaults to `true`.
     */
    filter?: 'auto' | 'manual' | 'off';
    /**
     * When true, the combobox opens automatically when the input receives focus.
     * When false (default, unless `filter` is `'off'`), the combobox only opens
     * on click, typing, or keyboard navigation.
     *
     * @default false (true when filter is 'off')
     */
    openOnFocus?: boolean;
}

/**
 * Combobox.Input component - wraps TextField with combobox ARIA attributes
 * and optionally includes a toggle button.
 *
 * @param props Component props.
 * @param ref   Component ref (will be forwarded to the anchor ref for popover positioning).
 * @return React element.
 */
export const ComboboxInput = forwardRef<ComboboxInputProps, HTMLDivElement>((props, ref) => {
    const { listboxId, anchorRef, setHandle } = useComboboxContext();
    const [isOpen, setIsOpen] = useComboboxOpen();
    const { inputRef: externalInputRef, toggleButtonProps, onSelect, filter, openOnFocus, ...otherProps } = props;
    const internalInputRef = useRef<HTMLInputElement>(null);
    const mergedInputRef = useMergeRefs(externalInputRef, internalInputRef);

    // Keep callbacks in refs to avoid re-creating the handle on every render
    const onSelectRef = useRef(onSelect);
    onSelectRef.current = onSelect;
    const onChangeRef = useRef(otherProps.onChange);
    onChangeRef.current = otherProps.onChange;

    // Create the combobox handle with input-mode controller on mount
    useEffect(() => {
        const input = internalInputRef.current;
        if (!input) return undefined;
        const handle = setupComboboxInput(input, {
            onSelect(option) {
                // Update controlled value through React's normal onChange flow.
                onChangeRef.current?.(option.value);
                onSelectRef.current?.(option);
            },
            filter,
            openOnFocus,
        });
        setHandle(handle);
        return () => {
            handle.destroy();
            setHandle(null);
        };
    }, [filter, openOnFocus, setHandle]);

    const handleToggle = useCallback(() => {
        setIsOpen(!isOpen);
        internalInputRef.current?.focus();
    }, [internalInputRef, isOpen, setIsOpen]);

    return UI(
        {
            ...otherProps,
            ref,
            listboxId,
            isOpen,
            filter,
            inputRef: mergedInputRef,
            textFieldRef: anchorRef as Ref<HTMLDivElement>,
            toggleButtonProps,
            handleToggle,
        },
        { TextField, IconButton },
    );
});

ComboboxInput.displayName = COMPONENT_NAME;
ComboboxInput.className = CLASSNAME;
