// packages/lumx-vue/src/components/combobox/ComboboxButton.tsx
import { defineComponent, onUnmounted, ref, useAttrs, watch } from 'vue';

import {
    ComboboxButton as UI,
    type ComboboxButtonProps as UIProps,
    type ComboboxButtonLabelDisplayMode,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxButton';
import { setupComboboxButton } from '@lumx/core/js/components/Combobox/setupComboboxButton';

import { useClassName } from '../../composables/useClassName';
import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { Button } from '../button';
import { Tooltip } from '../tooltip';
import { useComboboxContext } from './context/ComboboxContext';
import { useListboxEvent } from '../listbox/context/useListboxEvent';
import { useListboxContext } from '../listbox/context/ListboxContext';
import { useComboboxOpen } from './context/useComboboxOpen';

export type ComboboxButtonProps = VueToJSXProps<UIProps, 'label' | 'renderButton'> & {
    /** The label for the button (used for ARIA and tooltip). */
    label: string;
    /** The currently selected value to display. */
    value?: string;
    /** Controls how the label/value is displayed. @default 'show-selection' */
    labelDisplayMode?: ComboboxButtonLabelDisplayMode;
    /** Called when an option is selected. */
    onSelect?: (option: { value: string }) => void;
    /** Custom render function replacing the default `<Button>`. See `ComboboxButtonProps.renderButton` in core. */
    renderButton?: UIProps['renderButton'];
};

/**
 * Combobox.Button component - Button trigger for select-only combobox mode.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxButton = defineComponent(
    (props: ComboboxButtonProps, { emit }) => {
        const attrs = useAttrs();
        const className = useClassName(() => props.class);
        const { listboxId, anchorRef, setHandle, handle } = useComboboxContext();
        const { isOpen } = useComboboxOpen();
        const { list } = useListboxContext();
        const optionsState = useListboxEvent(list, 'optionsChange', { optionsLength: 0 });
        const isLoading = useListboxEvent(list, 'loadingChange', false);

        const buttonRef = ref<HTMLElement | null>(null);

        // Create the combobox handle with button-mode controller on mount
        watch(
            buttonRef,
            (button) => {
                if (!button) return;
                setHandle(
                    setupComboboxButton(button as HTMLButtonElement, {
                        onSelect(option) {
                            emit('select', option);
                        },
                    }),
                );
                // Set anchor ref to the button element
                anchorRef.value = button;
            },
            { immediate: false },
        );

        onUnmounted(() => {
            handle.value?.destroy();
            setHandle(null);
        });

        return () => {
            const {
                label,
                value,
                labelDisplayMode = 'show-selection',
                renderButton,
                class: _class,
                ...forwardedProps
            } = props;
            return UI(
                {
                    ...attrs,
                    ...forwardedProps,
                    label,
                    value,
                    labelDisplayMode,
                    renderButton,
                    listboxId,
                    isOpen: isOpen.value && (!!optionsState.value?.optionsLength || isLoading.value),
                    ref: (el: any) => {
                        // Handle both component instances and raw elements
                        buttonRef.value = el?.$el ?? el;
                        anchorRef.value = buttonRef.value;
                    },
                    className: className.value,
                },
                { Button, Tooltip },
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<ComboboxButtonProps>()(
            'class',
            'label',
            'value',
            'labelDisplayMode',
            'renderButton',
            'listboxId',
            'isOpen',
            'onSelect',
        ),
        emits: {
            select: (option: { value: string }) => !!option,
        },
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxButton;

// packages/lumx-react/src/components/combobox/ComboboxButton.tsx
import { ElementType, useEffect, useRef, useState } from 'react';

import { setupComboboxButton } from '@lumx/core/js/components/Combobox/setupComboboxButton';
import {
    ComboboxButton as UI,
    ComboboxButtonProps as UIProps,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxButton';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { forwardRefPolymorphic } from '@lumx/react/utils/react/forwardRefPolymorphic';
import { useMergeRefs } from '@lumx/react/utils/react/mergeRefs';
import { ComponentRef, HasPolymorphicAs, HasRequiredLinkHref } from '@lumx/react/utils/type';
import { Tooltip } from '../tooltip';
import { Button } from '../button';
import { useListboxEvent } from '../listbox/context/useListboxEvent';
import { useListboxContext } from '../listbox/context/ListboxContext';
import { useComboboxContext } from './context/ComboboxContext';
import { useComboboxOpen } from './context/useComboboxOpen';

/**
 * Props for Combobox.Button component.
 *
 * Polymorphic component — use `as` to render the trigger as a different element or component
 * (e.g., `as="a"`, `as={RouterLink}`). Defaults to the LumX `Button` component.
 */
export type ComboboxButtonProps<E extends ElementType = typeof Button> = Omit<
    HasPolymorphicAs<E>,
    'children' | 'role' | 'aria-controls' | 'aria-haspopup' | 'aria-expanded' | 'aria-activedescendant'
> &
    HasRequiredLinkHref<E> &
    ReactToJSX<UIProps>;

/**
 * Combobox.Button component - Button trigger for select-only combobox mode.
 *
 * Renders a button with proper ARIA attributes. Registers itself as the
 * combobox trigger on mount for keyboard navigation and typeahead.
 * Polymorphic — use `as` to change the rendered element or component.
 *
 * @param props Component props.
 * @param ref   Component ref.
 * @return React element.
 */
export const ComboboxButton = Object.assign(
    forwardRefPolymorphic(
        <E extends ElementType = typeof Button>(props: ComboboxButtonProps<E>, ref: ComponentRef<E>) => {
            const { listboxId, anchorRef, setHandle } = useComboboxContext();
            const [isOpen] = useComboboxOpen();
            const { list } = useListboxContext();
            const state = useListboxEvent(list, 'optionsChange', { optionsLength: 0 });
            const isLoading = useListboxEvent(list, 'loadingChange', false);
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const { as, label, value, labelDisplayMode = 'show-selection', onSelect, ...buttonProps } = props as any;

            // If `as` is provided, use it directly; otherwise use the LumX Button (full theme/disabled behavior).
            const ButtonComp = as ?? Button;

            // Track the button DOM element via state (instead of useRef) so it re-triggers the useEffect
            const [buttonElement, setButtonElement] = useState<HTMLButtonElement | null>(null);
            const mergedRef = useMergeRefs(ref as any, setButtonElement, anchorRef as any);

            // Keep onSelect in a ref to avoid re-creating the handle on every render
            const onSelectRef = useRef(onSelect);
            onSelectRef.current = onSelect;

            // Create the combobox handle with button-mode controller on mount
            useEffect(() => {
                if (!buttonElement) return undefined;
                const handle = setupComboboxButton(buttonElement, {
                    onSelect(option) {
                        onSelectRef.current?.(option);
                    },
                });
                setHandle(handle);
                return () => {
                    handle.destroy();
                    setHandle(null);
                };
            }, [buttonElement, setHandle]);

            return UI(
                {
                    ...buttonProps,
                    label,
                    value,
                    labelDisplayMode,
                    listboxId,
                    isOpen: isOpen && (!!state?.optionsLength || isLoading),
                    ref: mergedRef,
                },
                { Button: ButtonComp, Tooltip },
            );
        },
    ),
    { displayName: COMPONENT_NAME, className: CLASSNAME },
);
