// packages/lumx-vue/src/components/combobox/ComboboxOptionMoreInfo.tsx
import { computed, defineComponent, ref } from 'vue';

import { useClassName } from '../../composables/useClassName';

import {
    ComboboxOptionMoreInfo as UI,
    type ComboboxOptionMoreInfoProps as UIProps,
    type ComboboxOptionMoreInfoPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxOptionMoreInfo';
import type { JSXElement } from '@lumx/core/js/types';

import { getName, keysOf, VueToJSXProps } from '../../utils/VueToJSX';
import { IconButton } from '../button';
import { Popover } from '../popover';
import { useComboboxOptionContext } from './context/ComboboxOptionContext';
import { useComboboxEvent } from './context/useComboboxEvent';

export type ComboboxOptionMoreInfoProps = VueToJSXProps<
    UIProps,
    ComboboxOptionMoreInfoPropsToOverride | 'onMouseEnter' | 'onMouseLeave' | 'buttonProps'
> & {
    /** Callback when the popover opens or closes. */
    onToggle?: (isOpen: boolean) => void;
};

/**
 * Combobox.OptionMoreInfo component.
 *
 * Displays an info icon button on a combobox option that shows a popover with additional details.
 * The popover opens on mouse hover over the icon or when the parent option is keyboard-highlighted.
 *
 * Must be placed in the `after` slot of a `Combobox.Option`.
 *
 * @param props Component props.
 * @return Vue element.
 */
const ComboboxOptionMoreInfo = defineComponent(
    (props: ComboboxOptionMoreInfoProps, { slots }) => {
        const mergedClassName = useClassName(() => props.class);

        // Ref to the IconButton component instance.
        const iconButtonRef = ref<any>(null);

        // Resolved DOM element (<button>) used as the popover anchor.
        const anchorEl = computed<HTMLElement | undefined>(() => iconButtonRef.value?.$el ?? undefined);

        const isHovered = ref(false);

        // Get the parent option ID from the option context
        const { optionId } = useComboboxOptionContext();

        // Subscribe to active descendant changes for keyboard highlight detection
        const activeDescendantId = useComboboxEvent('activeDescendantChange', null);

        const popoverId = `${optionId}-more-info`;

        /**
         * IconButton adapter (closure) that maps core `onMouseEnter`/`onMouseLeave`
         * → Vue `onMouseenter`/`onMouseleave`
         */
        function IconButtonAdapter(coreProps: any) {
            const { onMouseEnter, onMouseLeave, ...rest } = coreProps;
            return (
                <IconButton
                    ref={iconButtonRef}
                    {...{ onMouseenter: onMouseEnter, onMouseleave: onMouseLeave }}
                    {...rest}
                />
            );
        }
        /**
         * Adapter for Popover (closure): `anchorRef` with the resolved DOM element
         */
        const PopoverAdapter = (coreProps: any, { slots: popoverSlots }: any) => {
            const { anchorRef: _coreAnchorRef, ...rest } = coreProps;
            return (
                <Popover anchorRef={anchorEl} {...rest}>
                    {popoverSlots}
                </Popover>
            );
        };

        return () => {
            const isKeyboardHighlighted = activeDescendantId.value === optionId;
            const isOpen = isHovered.value || isKeyboardHighlighted;
            const children = slots.default?.() as JSXElement;

            return UI(
                {
                    // Pass `undefined` for the core template's `ref` prop. The core template
                    // passes `ref` to `<IconButton ref={ref}>`, but if we pass `iconButtonRef`
                    // here, Vue would bind the outer functional component's VNode ref to
                    // the same target, resolving to a Text node (due to Tooltip fragments)
                    // and overriding the adapter's inner `ref={iconButtonRef}` binding.
                    // By passing `undefined`, the outer VNode has no ref and only the adapter's
                    // inner ref binding takes effect.
                    ref: undefined,
                    className: mergedClassName.value,
                    isOpen,
                    popoverId,
                    children,
                    onMouseEnter: () => {
                        isHovered.value = true;
                    },
                    onMouseLeave: () => {
                        isHovered.value = false;
                    },
                },
                { IconButton: IconButtonAdapter, Popover: PopoverAdapter },
            );
        };
    },
    {
        name: getName(COMPONENT_NAME),
        inheritAttrs: false,
        props: keysOf<ComboboxOptionMoreInfoProps>()('class', 'onToggle'),
        emits: {
            toggle: (isOpen: boolean) => typeof isOpen === 'boolean',
        },
    },
);

export { COMPONENT_NAME, CLASSNAME };
export default ComboboxOptionMoreInfo;

// packages/lumx-react/src/components/combobox/ComboboxOptionMoreInfo.tsx
import { ReactNode, useEffect, useRef, useState } from 'react';

import {
    ComboboxOptionMoreInfo as UI,
    ComboboxOptionMoreInfoProps as UIProps,
    ComboboxOptionMoreInfoPropsToOverride,
    COMPONENT_NAME,
    CLASSNAME,
} from '@lumx/core/js/components/Combobox/ComboboxOptionMoreInfo';
import { ReactToJSX } from '@lumx/react/utils/type/ReactToJSX';
import { IconButton, IconButtonProps } from '@lumx/react/components/button';
import { Popover } from '@lumx/react/components/popover';
import { useComboboxOptionContext } from './context/ComboboxOptionContext';
import { useComboboxEvent } from './context/useComboboxEvent';

/**
 * Props for Combobox.OptionMoreInfo component.
 */
export interface ComboboxOptionMoreInfoProps extends ReactToJSX<UIProps, ComboboxOptionMoreInfoPropsToOverride> {
    /** Content of the popover (additional details about the option). */
    children?: ReactNode;
    /** Callback when the popover opens or closes. */
    onToggle?(isOpen: boolean): void;
    /** Props forwarded to the IconButton. */
    buttonProps?: Partial<IconButtonProps>;
}

/**
 * Combobox.OptionMoreInfo component.
 *
 * Displays an info icon button on a combobox option that shows a popover with additional details.
 * The popover opens on mouse hover over the icon or when the parent option is keyboard-highlighted.
 *
 * Must be placed in the `after` slot of a `Combobox.Option`.
 *
 * Please consider using a simpler option `description` prop instead for better UX and a11y.
 *
 * @param props Component props.
 * @return React element.
 */
export const ComboboxOptionMoreInfo = (props: ComboboxOptionMoreInfoProps) => {
    const { children, onToggle, buttonProps, ...forwardedProps } = props;
    const ref = useRef<HTMLButtonElement>(null);
    const [isHovered, setIsHovered] = useState(false);

    // Get the parent option ID from the option context (provided by Combobox.Option).
    const { optionId } = useComboboxOptionContext();

    // Subscribe to active descendant changes to detect keyboard highlight.
    const activeDescendantId = useComboboxEvent('activeDescendantChange', null);
    const isKeyboardHighlighted = activeDescendantId === optionId;

    // Open on mouse hover or keyboard highlight.
    const isOpen = isHovered || isKeyboardHighlighted;

    useEffect(() => {
        onToggle?.(isOpen);
    }, [isOpen, onToggle]);

    // Predictable ID convention: the parent ComboboxOption sets aria-describedby="${optionId}-more-info"
    // on the role="option" element. The Popover uses closeMode="hide" to keep content in the DOM
    // so that screen readers can resolve the aria-describedby reference even when the popover is closed.
    const popoverId = `${optionId}-more-info`;

    return UI(
        {
            ...forwardedProps,
            ref,
            isOpen,
            popoverId,
            children,
            buttonProps,
            onMouseEnter: () => setIsHovered(true),
            onMouseLeave: () => setIsHovered(false),
        },
        { IconButton, Popover },
    );
};

ComboboxOptionMoreInfo.displayName = COMPONENT_NAME;
ComboboxOptionMoreInfo.className = CLASSNAME;
